### ISSUE TITLE
[MailServer] Implement RequestHistoricMessages() in request-response fashion

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1006]
# Problem

Currently, the `RequestHistoricMessages()` just sends a request to MailServer using special `p2pRequestCode` message code. This method exits immediately and it's not possible to know when all messages from MailServer get received.

This method does not support pagination either and does not allow limiting returned messages from MailServer by the number of envelopes. This does not need to be implemented here but the solution should be flexible so that the pagination is possible.

# Implementation

TBD: waiting for a more detailed implementation plan. Figure out how pagination can be supported.

More or less, it should look like this:
1. `RequestHistoricMessages()` sends a request to MailServer and blocks until all messages are received (it may timeout earlier),
2. MailServer, after sending all messages matching the request, sends a special message code `p2pRequestResponseCode` informing about that fact,
3. `RequestHistoricMessages()` returns.

# Acceptance Criteria

1. `RequestHistoricMessages()` should return after all messages have been received or timeout.

# Notes

- remember that `RequestHistoricMessages()` should work with and without a callback,
- a timeout should be passed in `RequestHistoricMessages()` arguments

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by gravityblast** [comment]
@adambabik  can we implement pagination in a different issue so that we only focus on the `p2pRequestReplyCode` message?

I thought something like this could work:

* Client (`status-react`) calls `shhext_requestMessages`
* Client (`shhext/api`) calls `RequestHistoricMessages` with an envelope that contains the request + a unique ID
* Client waits for `p2pRequestReplyCode` message with that ID
* Mailserver receives p2pRequestCode with unique ID
* Mailserver sends all the messages to the peer
* Mailserver sends `p2pRequestReplyCode`
* Client recevives `p2pRequestReplyCode` and notify `status-react`

Can `p2pRequestReplyCode` arrive before the last message sent by the mailserver?

**Comment by adambabik** [comment]
> can we implement pagination in a different issue so that we only focus on the p2pRequestReplyCode message?

Yeah, totally. It's in the issue description: `This does not need to be implemented here but the solution should be flexible so that the pagination is possible.`. 

I just mentioned it in order not to lock ourselves with a solution that does not take it into account

---

The plan sounds good!

> Can p2pRequestReplyCode arrive before the last message sent by the mailserver?

As far as I know, the p2p connection is a TCP connection and both messages and message codes are sent one after another directly to the recipient (it's not Whisper broadcast) so `p2pRequestReplyCode` should arrive after the last message. 

Having said that, there may be some implementation details with Whisper filters which are async or use buffered channels. So, even if `p2pRequestReplyCode` arrives after the last message, we should make sure that the fact of receiving all messages is communicated to the client after watchers (filters) are notified (https://github.com/ethereum/go-ethereum/blob/a76e46e3d7cb77bfcbc95d92df9f4b6ccdd742f2/whisper/whisperv6/whisper.go#L857-L858). 

Unless, it's not an issue and we don't need to bother with that. We can store the last message hash in `p2pRequestReplyCode` so that the client can figure out this race condition on their end if it's necessary. I think it's a tradeoff we can make.

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>
