### ISSUE TITLE
Flaky builds due to occasional huge offset relative to NTP servers

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#1015]
# Problem

Every now and then the e2e tests fail on Travis because of a huge clock difference with NTP servers. This causes flaky tests and a good amount of dev productivity lost due to context switching and tending to builds. Here are a couple of logs:

https://travis-ci.org/status-im/status-go/jobs/387822155, log excerpt:
```
INFO [06-05|11:05:56] Difference with ntp servers              offset=-50723h28m10.403016684s
ERROR[06-05|11:05:57] bad envelope received, peer will be disconnected peer=2eeb00e24f4b9f23 err="very old message"
```

[log from https://travis-ci.org/status-im/status-go/jobs/389231302](https://github.com/status-im/status-go/files/2080584/log2.txt)

[log from https://travis-ci.org/status-im/status-go/jobs/389231294](https://github.com/status-im/status-go/files/2080685/log3.txt)

# Acceptance Criteria

Builds pass consistently without huge unjustified offsets from NTP servers.

**Comment by adambabik** [comment]
Does it relate or duplicate https://github.com/status-im/status-go/issues/1022?

**Comment by pedropombeiro** [comment]
@adambabik yup, #1022 will completely disable NTP usage in tests, so this will be a non-issue after that is merged.

**Comment by dshulyak** [comment]
@PombeirP did you ever noticed that error after https://github.com/status-im/status-go/pull/1016 was merrged?

**Comment by pedropombeiro** [comment]
@dshulyak yes, I think it still happened.
