### ISSUE TITLE
Replace gometalinter with golangci-lint

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#1017]
# Problem

gometalinter is very slow compared to [golangci-lint](https://github.com/golangci/golangci-lint). In order to speed up CI builds, we should migrate to the faster tool.

Context: https://status-im.slack.com/archives/C8QP8S5UH/p1527617461000018

```
time make lint
lint

real    1m4.286s
user    3m21.009s
sys     0m20.387s
```

# Implementation

- Update Makefile to install and run golangci-lint.
- Compare time take to install and run lint tool, before and after upgrade.

# Acceptance Criteria

The new tool runs in a functionally equivalent way to gometalinter.
The new tool is faster than the existing solution.

**Comment by pedropombeiro** [comment]
Took a preliminary look at golangci-lint and found the following differences compared to gometalinter:
- 4.5x faster
- Speed is blazing fast compared to gometalinter and would be great having this soon on our CI to relieve pressure
- Doesn't support customizing `gas` linter
- Doesn't support `misspell` linter

```
real    0m14.062s
user    0m43.052s
sys     0m4.261s
```

On the other hand, it seems to produce more useful results than gometalinter. An example:
![image](https://user-images.githubusercontent.com/138074/41303524-c8c4131c-6e6d-11e8-971f-3df054a08b74.png)

@divan @adambabik do you have any suggestions regarding the above limitations? E.g. should we run the `misspell` linter separately in the `make lint` target? `gasv2` linter is just `gas -fmt=csv`, is this required?

**Comment by adambabik** [comment]
In my opinion, `gas` is still too experimental and I would get rid of it. We can run `misspell` individually, not a problem. As long as it will be encapsulated in `make lint` target.
