### ISSUE TITLE
allow to disable status-go ntp sync

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1022]
Notify status-react that time is out of sync, so that user can turn on time sync on device and turn off our own

we need to add an option to config and disable ntp time source usage based on this option

second part of the change is to send signal that offset is noticeable (some research required to define exact number, for instance whisper will tolerate small time skews but i don't remember exact number)

**Comment by pedropombeiro** [comment]
On test code, we should turn off NTP sync when setting up nodes so that we don't incur on rate limiting from servers (seen in https://github.com/status-im/status-go/pull/1016)

**Comment by adriacidre** [comment]
@dshulyak current code does not stop status-go from ntp syncing it only reduces how often it gets synced. 

If I understood well, there is the need from status-react to predefine (through the node config) a timeout for the ntp sync process so they can continue this process on its side, right?

Basically this issue is about introducing that config timeout, manage the timeout on `timesource/timesource.go` and sending back a signal to status-react once the timeout is reached. Am I correct?

**Comment by dshulyak** [comment]
> If I understood well, there is the need from status-react to predefine (through the node config) a timeout for the ntp sync process so they can continue this process on its side, right?

why timeout?

i was thinking about including an explicit option that will allow disabling ntp sync in status-go.
we can start an app with ntp sync turned on, then notify a user that we run such sync, and it has such diff. if he wants he can disable our ntp sync on status-react config tab, and enable global sync on mobile device

**Comment by pedropombeiro** [comment]
Do we need a UI option in that case though? If the user decides to enable global sync, the only thing that happens is that the offset will become much smaller, so everything is fine. What do we gain from adding a user option? Are we concerned about e.g. CPU and battery usage? 

To be clear, it's fine having the code option, just not sure that we need to expose it in the UI.

**Comment by adriacidre** [comment]
The worflow will look like:

```
1 - App is started with ntp sync turned on
2 - When the sync switches from `fast` to `slow` mode, status-go sends a signal to status-react
3 - Status-react offers an option to to disable the ntp sync on status-go side.
4.- Status-react updates config values to stop ntp sync
5.- Ntp sync is disabled on status-go
```

I think I'm a bit confused about step 2, as, in case it doesn't happen when the switch takes place. Why do status-go needs to send a notification to status-react if by default ntp sync will be started and status-react already knows about it?

**Comment by dshulyak** [comment]
my main concern is that mobile os time sync service is probably more reliable than what we have. so we can eliminate some bugs by having the option to turn off status-go ntp sync.

**Comment by pedropombeiro** [comment]
Yeah, that's a fair assumption. Regarding the exact approach though, I think that in order to avoid surprises later, we should involve Design/UXR teams to make sure they agree on the UX we'll want to offer. cc @andmironov @jpbowen

**Comment by dshulyak** [comment]
> Why do status-go needs to send a notification to status-react if by default ntp sync will be started and status-react already knows about it?

that makes sense. maybe instead status-react can set this option based on os info. can we check if os time service is enabled? is there an api for that?

**Comment by pedropombeiro** [comment]
As far as I know, in the case of Android, it only syncs with the network provider, and according to my experience, that's not been very precise (I've seen it consistently some seconds away from atomic clock). I've long used an app called ClockSync which will sync using NTP (if you're rooted): https://android.gadgethacks.com/how-to/set-your-android-atomic-time-for-perfectly-synced-clock-0170500/

<blockquote><img src="https://img.gadgethacks.com/img/29/31/63596755165539/0/set-your-android-atomic-time-for-perfectly-synced-clock.1280x600.jpg" width="48" align="right"><div><img src="https://img.gadgethacks.com/images/favicons/gadgethacks/favicon-16x16.png" height="14"> WonderHowTo</div><div><strong><a href="https://android.gadgethacks.com/how-to/set-your-android-atomic-time-for-perfectly-synced-clock-0170500/">How to Set Your Android to Atomic Time for a Perfectly Synced Clock</a></strong></div><div>For most Android phones, the system clock is set using a protocol called NITZ, which relies on a connection with your carrier to ensure that the time stays in sync. The trouble here is that this feature won't work when you're outside of cellular range, and a lot of times, the carriers themselves have technical difficulties that can result in your phone's clock being minutes or even hours out of sync. I've experienced this issue several times, personally, and it always makes me wish Android's clock would simply sync with official time-keeping services like NTP or NIST. Well thanks to a recent</div></blockquote>

**Comment by dshulyak** [comment]
closed by mistake

**Comment by adambabik** [comment]
It looks like it's done. @adriacidre?

**Comment by adriacidre** [comment]
hey @adambabik I think we still need some input from react team regarding this comment
> that makes sense. maybe instead status-react can set this option based on os info. can we check if os time service is enabled? is there an api for that?
