### ISSUE TITLE
Get rid of transactions queue

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1027]
# Problem

Because we don't have "sign later" functionality anymore, there is no reason to have transactions queue on go side.

# Implementation
-remove transactions queue functionality
-instead two `approve` methods implement one `sendTransaction`

![image](https://user-images.githubusercontent.com/11790366/41297804-a1967ba4-6e68-11e8-8e46-8a6b1f89e62c.png)

**Comment by mandrigin** [comment]
@flexsurfer but we still need to signal to react side that a DApp tries to send a transaction, right? or, how that would be implemented?

**Comment by mandrigin** [comment]
even if they just do any raw call...
but then we are moving all the protection on the level of web3.js that is hardly maintained

**Comment by flexsurfer** [comment]
@mandrigin so how it works now, we have stutusHTTPProvider, which has `send` and `sendAsync` https://github.com/status-im/status-react/blob/develop/resources/js/web3_init.js#L56, where we call status-go and wait signal, i suggest to do not call status-go, but show wallet UI, and then if user presses send, call status-go, so just remove queue and signals

**Comment by mandrigin** [comment]
ah, ok, so that would be a part of status-react now. makes sense.
same for `personal_sign` and the other stuff, I guess, right?

--
note to whoever will implement that, that we will still need to sign everything locally and use the local nonce and stuff, these things aren't for removal.

**Comment by flexsurfer** [comment]
right, thanks

**Comment by flexsurfer** [comment]
@sebastiandelgado any updates on this? what are our next steps?

**Comment by sebastiandelgado** [comment]
@flexsurfer Its almost done. Already approved and merged most of the changes into the branch `feature/remove-transactions-queue-1027`. I have a PR open for the last commit (https://github.com/status-im/status-go/pull/1117) that should make this feature branch ready to merge. You can check the new interface for calling signMessage and sendTransaction at the lib/library.go file.
