### ISSUE TITLE
Add pagination to mail server

### ISSUE THREAD

**Issue by gravityblast** [status-im/status-go#1036]
# Problem

`status-react` uses the mail server to ask for envelopes sent when the app was offline, usually requesting messages for the last 24 hours.
If the request contains a bloom filter that matches a public chat with a high number of messages sent in the last 24 hours, the client will end up receiving a lot of messages that can make the app slow or unusable. 

# Current implementation

Currently `status-react` send a request to the mail server with the following parameters:

* `From`
* `To`
* `BloomFilter` (derived from the Topic specified in the request from `status-react`)

The mail server receives the request and sends one p2p message for each envelope that matches the bloom in the time range between `From` and `To`. It uses a range iterator that moves forward from `From` to `To`. The keys in leveldb are sorted lexicographically. Each envelope is stored in leveldb with this key:

`timestamp_bytes + envelope_hash_bytes`

# Changes to be implemented

* [ ] change the query to leveldb to a range that moves backwards from `To` to `From`.
* [ ] add a third parameter to the request called `Limit`, to limit the number of messages sent back to the client
* [ ] the mail server should iterate through messages from `To` to `From` and stop if `Limit` is reached.
* [ ] add a fourth parameter to the request called `Cursor`
* [ ] update the mail server response message to include the cursor to use in the next page request (next message key in leveldb). Currently the response payload is `request_id_bytes`, it can be updated to be `request_id_bytes + last_envelope_key_bytes`. If there's no next page, the cursor is not sent.

# Acceptance Criteria

The mail server should be back backwards compatible, so clients should be able to specify or not the `Limit` parameter in the request.

`status-react` should receive a maximum number of messages specified in the `Limit` parameter.

`status-react` should receive a signal `mailserver.request.completed` that contains the request id and the key of the last envelope sent from the mail server. This key can be used as a value for the `To` parameter in successive requests.

**Comment by adambabik** [comment]
> add a third parameter to the request called Limit

We should note that Mail Server may have its own `Limit`.

> update the mail server response message to include the key of the last envelope sent. Currently the response payload is request_id_bytes, it can be updated to be request_id_bytes + last_envelope_key_bytes.

The client makes the first requests and receives a response. How can it figure out that all messages were transferred from the requested time window and if not, how can it request for the rest? `last_envelope_key_bytes` can be sent in the next request to help with that. Also, the client should be able to update the time window based on the received messages. So, we probably need to do:
1. Allow `LastEnvelopeHash` in the request body,
2. The response from the server should include information on whether or not all messages from the requested time span were sent.

**Comment by gravityblast** [comment]
we should also update the documentation here https://github.com/status-im/status-go/wiki/Additional-JSON-RPC-API

Is there any other place with docs about this? /cc @adambabik @PombeirP 

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by adambabik** [comment]
Oh and we also can change `Topic` to bloom filter in the request payload I guess. The client will be able to reduce the number of queries.

**Comment by gravityblast** [comment]
> The client makes the first requests and receives a response. How can it figure out that all messages were transferred from the requested time window and if not, how can it request for the rest? last_envelope_key_bytes can be sent in the next request to help with that

`last_envelope_key_bytes` is already `timestamp_bytes + last_envelope_hash_bytes`, so the flow I thought was:

we have 5 enveloped in the db with these keys:

1 - `1000000000hash1`
2 - `2000000000hash2`
3 - `2000000000hash3`
4- `3000000000hash4`
5- `3000000000hash4`

**First request**
Request:`From: 2000000000, To: 3000000000, Limit: 3`
Mailserver sends envelopes 5, 4, 3, and a `p2pRequestCompleteCode` message with `requestID` and the key of the next message: `2000000000hash2`

**second request**
Request:`From: 2000000000, To: 2000000000hash2, Limit: 3`
Mailserver sends envelopes 2 and a `p2pRequestCompleteCode` message with `requestID` 
and nothing else, because the range doesn't contain any other message.

Does it make sense? @adambabik @cammellos

**Comment by gravityblast** [comment]
>Oh and we also can change Topic to bloom filter in the request payload I guess. 

@adambabik `status-react` sends a request to the local node with `Topic`, but the local node sends the request to the mailserver with a bloom filter derived from that topic.

>The client will be able to reduce the number of queries.

Do you mean having a bloom filter from multiple topics? that would work, but pagination would make less sense maybe?

**Comment by cammellos** [comment]
We would not be querying multiple topics together in this case anymore, as would not work with pagination, also it would be more difficult to get a balanced load

**Comment by adambabik** [comment]
@pilu In this example, `last_envelope_hash_bytes` is a hash of a message that was not sent back. Is that correct? (`2000000000hash2` is the message with ID `2` while the mail server returns `5`, `4` and `3`).

`To` will be an integer or string. I would stick with one type and provide a new property for the sake of clarity.

Not sending the `last_envelope_hash_bytes` in such a case will make it impossible to sync filters and the mail server request response. Unless this feature is not important.

Another way would be to send:
- the last sent message hash (always present),
- the last sent message timestamp (or `0` in a case when all messages were passed to the client) (always present).

@cammellos hm, why it won't play well with pagination? It still gonna be possible to send N requests each with a bloom filter from a topic and have the same logic. The only different is that it will happen on the client side rather than in status-go.

**Comment by cammellos** [comment]
@adambabik  it would be the hash of the last message sent, next time we ask with that, the response will be non-inclusive ( greater than but not equal).

@adambabik yes, it would work in that way, we'd just probably won't use it that way (we'll likely always ask for a single topic at time).

**Comment by adambabik** [comment]
> it would be the hash of the last message sent, next time we ask with that, the response will be non-inclusive ( greater than but not equal).

I agree. That's also my intention.

> yes, it would work in that way, we'd just probably won't use it that way (we'll likely always ask for a single topic at time).

Ok, so in that case let's not complicate and leave the current way of doing that.

**Comment by gravityblast** [comment]
>@pilu In this example, last_envelope_hash_bytes is a hash of a message that was not sent back. Is that correct? (2000000000hash2 is the message with ID 2 while the mail server returns 5, 4 and 3).

@adambabik `2000000000hash2` is the key in the database, `2000000000` is the timestamp, `hash2` is the envelope hash.

>To will be an integer or string. I would stick with one type and provide a new property for the sake of clarity.

I agree with this. I think it should be `string`, because the query is using a range on the keys in the database. and the keys are bytes with `timestamp + hash`.

**Comment by adambabik** [comment]
The client should know nothing about the structure of keys in the mail server database. It must be agnostic in case we will change the underlying datastore it in the future.

**Comment by gravityblast** [comment]
> Not sending the last_envelope_hash_bytes in such a case will make it impossible to sync filters and the mail server request response. Unless this feature is not important.

what do you mean exactly?

In general what I propose is sending a partial key, which is what we do now sending only the time stamp, or a full key which is `timestamp + hash`. if the mail server reponse sends the next key (timestamp + hash), the client can ask for the second page starting exactly from that key instead of a timestamp (which can be the prefix of multiple keys)

**Comment by gravityblast** [comment]
> The client should know nothing about the structure of keys in the mail server database. It must be agnostic in case we will change the underlying datastore it in the future.

it makes sense. I thinking what we can do if we have 10 messages with the same timestamp, and the request limit is 5. we serve the last 5, but how can the client know there are other messages in the same timestamp? that's why I was thinking about using the full key, so that the next query can have same timestamp + `hash` of the 5th message

**Comment by cammellos** [comment]
If you want to keep it agnostic, you can have 3 parameters:
1 & 2 ) To & From, which works exactly as now, but return a `cursor` (timestamp+hash, but as far as the client is concerned is just a string, any string).
3) `cursor` which is whatever the servers sends, and it's used for pagination.

Flow would be:

1) Client asks for `/messages?to=blah&from=blah`
2) Server sends back cursor or nothing if no more messages are available
3) Provided more messages are available client can ask for `/messages?cursor=cursor&from=blah`
and repeat.

**Comment by gravityblast** [comment]
> Provided more messages are available client can ask for /messages?cursor=cursor&from=blah
and repeat.

my initial idea is exactly this one, except that the next request uses cursor as the value for the `To` parameter

**Comment by cammellos** [comment]
exactly, the advantage of keeping them separate is that it better
abstracted, in case you change structure of the database  ( say now the
id/cursor is an integer instead, it becomes a bit hairy to detect whether
is a timestamp or an id)

**Comment by gravityblast** [comment]
@cammellos  I like it!

**Comment by gravityblast** [comment]
I updated the description. I'll wait also for a new feedback from @adambabik

**Comment by adambabik** [comment]
@pilu 

>> Not sending the last_envelope_hash_bytes in such a case will make it impossible to sync filters and the mail server request response. Unless this feature is not important.

> what do you mean exactly?

When the client receives `requestResponse` code, it might happen that the last messages were not passed to the filters yet due to implementation details (another goroutine, buffered channels etc.). In such a case, the client may want to delay handling `requestResponse` signal until the last received messages are passed to the filters and handled by the client logic. Having the last message hash in `requestResponse` payload is needed for that. (By client here I mean the app). The thing is that it's a super nasty detail which may not be a problem for now. We can safely skip it when working on this issue.

The `cursor` idea is very nice and it is even more decoupled than the solution I proposed [here](https://github.com/status-im/status-go/issues/1036#issuecomment-397658984).

**Comment by gravityblast** [comment]
I see thank you @adambabik!
