### ISSUE TITLE
New debug_postconfirm rpc endpoint

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go#1041]
# Problem

We have the need to write some tests checking if a whisper message is sent to the network or is expired even before leaving the current node.

# Implementation

The proposed solution is to introduce a new blocking endpoint `shhext_postconfirm`. 
This endpoint will send a message same as `shhext_post` does, but, in addition will wait for an `EventEnvelopeSent` event and return success or error if timed out.

`debug_` endpoints should be disabled by default, and only available when activated through the config

# Acceptance Criteria

- A call to `debug_postconfirm` for a message expiring before leaving the node should return success.
- A call to `debug_postconfirm` for a message expiring after leaving the node should return an error.

# Notes

This issue is related with https://github.com/status-im/status-scale/issues/12 and some more tests are planned on top of it.

**Comment by gravityblast** [comment]
@adriacidre can't we just use the `envelopeFeed` in the test to wait for the envelope to be sent?

**Comment by gravityblast** [comment]
@adriacidre ah I see now the other issue, but I don't know about the test. can we wait for another client to receive it?

**Comment by adriacidre** [comment]
My initial though was to have two peers sending messages from one to the other, but then we wont be able to know if messages have expired before being sent or not.

Current test looks [like this](https://github.com/status-im/status-go/blob/develop/t/destructive/peers_test.go#L62) and this feature will allow us write the same tests from status-scale, which doesn't have access to the running node internals.
