### ISSUE TITLE
Figure out why Discovery V5 performs poorly with a high number of concurrent peers

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1049]
# Problem

We observed that Discovery V5  performs poorly with many concurrent peers. 

# Implementation

Try to dig deep into Discover V5 code and figure out what's the bottleneck. The current lead is a single threaded model and moving peers to unknown state after no response for 500ms for ping requests.

# Acceptance Criteria

1. The root cause is identified and confirmed with a fix. If the fix is complex, a naive confirmation is enough.

# Notes

Testing concurrent peers and Discovery V5: TBD

**Comment by dshulyak** [comment]
> The current lead is a single threaded model and moving peers to unknown state after no response for 500ms for ping requests.

it is not the case because then there will almost no traffic between peers

**Comment by dshulyak** [comment]
This test can be used to simulate discovery with lots of concurrent users and observe metrics
https://github.com/status-im/status-scale/blob/master/tests/metrics_test.go#L15
Change number of peers here https://github.com/status-im/status-scale/blob/master/tests/metrics_test.go#L20

Check readme for steps how to run those tests. There is couple of prerequisites

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-scale">status-im/status-scale</a></strong></div><div>Contribute to status-scale development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-scale">status-im/status-scale</a></strong></div><div>Contribute to status-scale development by creating an account on GitHub.</div></blockquote>
