### ISSUE TITLE
eth_uninstallFilter support

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1057]
see react-native issue https://github.com/status-im/status-react/issues/4873

**Comment by adriacidre** [comment]
hey @flexsurfer, could you provide more info on how/from `eth_uninstallFilter` is being requested?
We're already supporting this endpoint, so, we will need more info to debug where is the problem.

**Comment by flexsurfer** [comment]
@adriacidre  could you provide more info on how we can use this endpoint? so dapp calls `web3.eth.uninstallFilter` synchronously but we don't support sync calls, can we call it async?

**Comment by adriacidre** [comment]
Hey @flexsurfer [this is a test](https://github.com/status-im/status-go/blob/5bbfabde94676d517485757e2657aa13d6e28cf5/t/e2e/services/filters_latest_test.go#L66) with an example on how's called, something like:

```
`{"jsonrpc":"2.0","method":"eth_uninstallFilter","params":["%s"],"id":67}`
```

The problem may be the endpoint is available through the `HttpProvider` while dApp is trying to access it through `IpcProvider`. 

Anyway, we need more details to on how you debugged (or a simple example on how to reproduce it) and what's missing on `status-go` side.

**Comment by flexsurfer** [comment]
thanks @adriacidre let me check, maybe we don't need changes on go side

**Comment by flexsurfer** [comment]
fixed on react-native side
