### ISSUE TITLE
Geth 1.5.9 introduces HD wallets, consider switching to their implementation

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#108]
- https://github.com/ethereum/go-ethereum/releases/tag/v1.5.9
- we need to review their implementation, and probably sit out couple of releases, before attempting to switch to their wallet implementation (since account and account manager API changes a lot atm, we will chase the moving target otherwise)

**Comment by influx6** [comment]
@tiabc  @jarradh  At what point should we begin looking at this issue?

**Comment by sla-shi** [comment]
Closing per @jarradh suggestion.
