### ISSUE TITLE
Extend go-ethereums USB Ledger HD support with OTG

### ISSUE THREAD

**Issue by jarradh** [status-im/status-go#109]
https://en.wikipedia.org/wiki/USB_On-The-Go

**Comment by jarradh** [comment]
Take a look at geths hidapi wrapper Android exclude restraints here:
https://github.com/karalabe/hid

Failing this we can look at 
https://github.com/LedgerHQ/android-u2f-bridge/tree/master/app/src/main/java/com/ledger/android/u2f/bridge

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by tiabc** [comment]
Closing due to undefined scope.

**Comment by tiabc** [comment]
Closing due to undefined scope.
