### ISSUE TITLE
Allow to start node with different fleet

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1100]
# Problem

Currently, we have two fleets: `eth.beta` and `eth.staging`. However, it's not possible to easily start the status node with one or another.

# Implementation

Implement a way to select a fleet when starting node via CLI (`statusd`) or using a configuration JSON blob (status-react).

# Acceptance Criteria

1. It's possible to start the node with both fleets,
2. Cache layer is separated for fleets (peers cached for fleet A are not used when the node is started with fleet B).

**Comment by dshulyak** [comment]
cache uses location based on datadir https://github.com/status-im/status-go/blob/develop/cmd/statusd/main.go#L41 . just change that and cache will be isolated. any reason not to do so?

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by adambabik** [comment]
That's a great idea!

So the only thing that is left is to add `eth.staging` to `cluster.go`.

**Comment by jakubgs** [comment]
Would it not be possible for `status-react` to provide the full list of both `bootnodes`, static `whisper` and `mail` nodes to the `status-go` library? Having to change to different files in two different repos to update fleet info is a pretty wonky process.

Also, I've created the following related issue: https://github.com/status-im/status-react/issues/5213

**Comment by adambabik** [comment]
It is possible. Probably we need to make one tweak in status-go because I don't think it's possible to provide custom static nodes. Bootnodes can be provided by status-react for sure.

Bootnodes must be included in status-go as well as we use it in many places and assume bootnodes are available. Having said that, status-react as a client should have a possibility to override any nodes included in status-go.

**Comment by adambabik** [comment]
It was done in https://github.com/status-im/status-go/pull/1111.
