### ISSUE TITLE
Free C.CString memory

### ISSUE THREAD

**Issue by divan** [status-im/status-go#1116]
# Problem

We use CGo in a few places, where we need to interact with alien UI codebase (`lib` and `signal` packages). Historically, the code is uses calls like `send(C.CString(jsonData))`, which seems to be leaking memory (see 
https://github.com/status-im/status-go/issues/1067#issuecomment-407567649).

According to https://blog.golang.org/c-go-cgo:

> Conversion between Go and C strings is done with the C.CString, C.GoString, and C.GoStringN functions. These conversions make a copy of the string data.
> ...
> Memory allocations made by C code are not known to Go's memory manager. When you create a C string with C.CString (or any C memory allocation) you must remember to free the memory when you're done with it by calling C.free.

We need to properly free memory and test that it doesn't break anything with status-react and status-desktop.

# Implementation

One fix for `signal` package has been done here: https://github.com/status-im/status-go/pull/1114
But there are still `lib` package that uses C.Cstring heavily.

<blockquote><div><strong><a href="https://blog.golang.org/c-go-cgo">C? Go? Cgo! - The Go Blog</a></strong></div></blockquote>

**Comment by adambabik** [comment]
I was skimming through `library.go` and it looks like it only returns `C.CString`s. However, this still can cause memory leaks as I am not sure if ObjC or Java frees that memory.

**Comment by pedropombeiro** [comment]
Maybe we need to expose a method in `library.go` to allow callers to explicitly free up memory returned by methods such as `GenerateConfig` that return `*C.char`?

**Comment by kishansagathiya** [comment]
I was not able to find any usage of `GenerateConfig`(same for few other methods that return *C.char). Are these methods being consumed by some other status-im projects/services? If so, which?

**Comment by pedropombeiro** [comment]
Yes, they are consumed by https://github.com/status-im/status-react

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>
