### ISSUE TITLE
Refactor signals mechanism

### ISSUE THREAD

**Issue by divan** [status-im/status-go#1124]
# Problem

The current design of `signals` package is flawed, leads to unreliable tests, unneeded dependency on CGo and less readable codebase.

# Intro

A quick reminder of what `signals` package is responsible for: it implements a simple communication mechanism between "Go part" (`status-go`) and "UI part" (`status-react`). It allows Go code to send events like "Node crashed" so it can be handled properly.

A brief history of the package:
 - at the beginning, there were 5 signals implemented (see https://github.com/status-im/status-go/commit/349103de1a2a4caa81e837f5949c0b2a76ce7aa5#diff-defceddac2d1b71932eb45fe35163178)
    - EventNodeStarted = "node.started"
    - EventNodeReady = "node.ready"
    - EventNodeStopped = "node.stopped"
    - EventNodeCrashed = "node.crashed"
    - EventChainDataRemoved = "chaindata.removed"
 - next, we started to add more signals for various use cases (message sent notification to display `seen` indicator, discovery start/stop notifications etc)
 - signals creation code was scattered over packages, and then was moved into a single package under `signals` name

Essentially the signals implementation is a singleton, that resides in `signals` package and it worked well when we needed only one implementation, and the usage surface was small. However, we started to write more tests with signals involved, which made this "singleton" package approach less than optimal, leading to flaky tests.

Then we discovered a memory leak in CGo code of signals, and realized that it was running and depending on CGo in the server build, where no UI part involved, and thus no need to use signals at all.

That all led to a discussion on refactoring and proposal to change the architecture of this package.

# Implementation

First of all, we need to define an interface that describes methods that the signal handler should implement.
Then, implement a couple of cases – noop implementation (for the server), Cgo-based implementation for React-Native UI, and mock implementation for tests.

Important note, that implementation should be selected at compile time, as there are currently only three known use cases:
 - standalone server (no need for signals at all)
 - library for binding with React-Native UIs (CGo-based implementation)
 - mock for tests

# Acceptance criteria
 - signals mechanism work as earlier with `status-react` and `status-desktop`
 - server build (`cmd/statusd`) doesn't use CGo code and ideally no code related to signals at all
 - tests are still testing signals, with better readability of code simplified

**Comment by divan** [comment]
@MaxRis this refactor will break the current way how you use signals in status-desktop, I think. Can we discuss it here what will be the best way for you to receive signals from status-go in status-desktop?

**Comment by maxhora** [comment]
Hey @divan , will it be possible to implement status-desktop support in the similar way how it works currently? at the moment status-desktop via react-native's `Status` module sets C callback function pointer and status-go executes this callback when some event occurred. P.S. Additional complexity adds the fact that GoLang is not able to handle unsafe pointer to C callback directly in Go source code and to overcome this it was needed to call C callback from GoLang by keeping invocation code inside native C module which is internally added into statug-go.

Setting of callback: status-react desktop -> Status react-native native module -> call of callback setter method from status-go.h
Calling of callback on status-go side: event occurs -> imported C method invoked from Go source code -> stored callback invoked from native C code
