### ISSUE TITLE
Write a proxy between Ethereum and Status networks

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1129]
# Problem

**Ethereum network** -- the main network of peers where the Ethereum transactions are propagated and mined. Ethereum network nodes can run other protocols like swarm or Whisper.
**Status network** -- a subnetwork of the Ethereum network which nodes run additional protocols (rendezvous) or the same protocols but with particular settings (Whisper).

The definition of Status network is not a reality yet. Currently, the Status network is a separate network, not a subnetwork. We would like to change that and this is the first issue to address this problem.

The first thing that we'd like to achieve is to allow to discover Ethereum nodes from within Status network. In particular, we'd like to find LES peers and propagate them within the Status network.

# Implementation

*This implementation proposal is not verified yet.*

The proposal is to run separate proxy nodes similar to bootnodes. Such a node will run two peers discovery protocols: Discovery V5 and rendezvous. Discovery V5 will be connected to the Ethereum network. Rendezvous protocol which will be connected to the Status network. 

Any request sent to rendezvous matching the configuration will be proxied to Discovery V5. Similarly, any nodes found with Discovery V5 matching the configuration will be propagated within rendezvous.

# Acceptance Criteria

It's possible to find peers from the Ethereum network running Discovery V5 and propagate them within the Status network running rendezvous.

# Notes

1. Verify if running proxy nodes in a similar fashion to bootnodes provides enough functionality. Bootnodes are not regular peers and they are only useful by the peers discovery protocol which makes sense but might be not enough.

2. Another variant of this might be that Status network server nodes will run both Discovery V5 and rendezvous protocols. In such a case, a proxy node should proxy peers from the Ethereum network to both Status network protocols.

# Future Steps

The next step is to get rid of custom Discovery V5 version and make Status network a subset of the Ethereum network while still keep enough free slots to handle Status app instances.

**Comment by adambabik** [comment]
@dshulyak please check if everything makes sense :)

**Comment by dshulyak** [comment]
LGTM 👍

**Comment by adambabik** [comment]
This is done thanks to:
- https://github.com/status-im/rendezvous
- https://github.com/status-im/status-go/tree/develop/cmd/proxy

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/rendezvous">status-im/rendezvous</a></strong></div><div>Contribute to status-im/rendezvous development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>
