### ISSUE TITLE
Consider moving LES cluster to scaleway

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#115]
*Price comparison:*

- https://www.scaleway.com/pricing/
- https://www.digitalocean.com/pricing/

*Notes:*
- to run LES+SHH server comfortably (w/o out of memory faults, and processing decent amount of peers) we need 2GB node (so that we have at least 1GB solely for the Geth)
- DO's 2GB node is 20$, and Scaleways **ARM** servers are EUR 3 
- so if we can create a docker image for ARM, we effectively will be able to double number of servers, for 1/3 of cost

**Comment by jarradh** [comment]
amazing!

**Comment by farazdagi** [comment]
https://github.com/status-im/status-cluster/blob/master/README.md
