### ISSUE TITLE
Add labels to docker images to identify them better

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1157]
# Problem

Currently, we use tags like `deploy-staging` for docker images. When such an image is deployed, we have no information what version it is, who created it etc.

# Implementation

Add the following `LABEL`s to docker images:
1. `LABEL version={{ version }}`
2. `LABEL git_sha={{ git_sha }}` 
2. `LABEL author={{ author }}`

# Acceptance Criteria

1. It's easy to figure out which status-go version/commit is used to build this particular docker image.

**Comment by kishansagathiya** [comment]
@adambabik 
> LABEL author={{ author }}

Do you mean author of the latest commit or maintainer of the Dockerfile?

**Comment by adambabik** [comment]
I was thinking about an author of the particular build. Using git SHA, we can figure out author of the commit but it does not need to be a person who created and pushed the image.

We can also add `LABEL maintainer=` to some email alias within status.im org.

**Comment by jakubgs** [comment]
I was working on something like this but never finished:
https://github.com/status-im/status-go/commit/0db25ab1819d2bb98fdbbce60ae7839903fe50e9
