### ISSUE TITLE
Introduce and expose "shh_postRaw" method

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1216]
# Problem

It should be possible to prepare and encrypt messages outside this method and post them into whisper network using this method 

part of https://discuss.status.im/t/web3-js-whisperprovider-sign-with-status-everywhere/370 

<blockquote><img src="https://discuss.status.im/uploads/default/optimized/1X/7bbf16f6cc54605316f30b5a133947c4853e3ea7_1_690x425.png" width="48" align="right"><div><img src="/uploads/default/original/1X/8c298ce8e38884365c17cdf0afea1ae108e992f9.png" height="14"> Status.im</div><div><strong><a href="https://discuss.status.im/t/web3-js-whisperprovider-sign-with-status-everywhere/370">Web3.js WhisperProvider. Sign with Status everywhere!</a></strong></div><div>Overview  Currently, the only way to browse Decentralized web applications on the desktop is to use specific tools, browsers or extensions. What if it were possible to browse DApps and sign transactions on every web browser safely and even on someone else’s devices.  Proposal  First of all, it should be super simple to incorporate it in currently working DApps, literally one line of code. To interact with Ethereum blockchain DApps use Web3HttpProvider with the web3.js library, so we could introd...</div></blockquote>

**Comment by randomshinichi** [comment]
Hey there, I talked with Adam and I'd like to do this as a nice first issue

**Comment by flexsurfer** [comment]
hey @randomshinichi i believe @mandrigin did this

**Comment by dshulyak** [comment]
@mandrigin shared this branch some time ago https://github.com/status-im/whisper/tree/feature/post-raw.

it seems that implementation is complete.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/whisper">status-im/whisper</a></strong></div><div>Contribute to status-im/whisper development by creating an account on GitHub.</div></blockquote>
