### ISSUE TITLE
Swarm: service configuration

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#122]
Make sure that Swarm is configurable via Node Settings #116 

**Notes:**
- current swarm implementation on `go-ethereum` side is alpha (it works most of the time, but you can have panics, corrupt DB state etc)
- therefore while we need to proceed with adding Swarm support, we also need a way to turn to be able to fine tune it (or even turn off) via configuration
- attempt after #114 
- follows up #87

**Comment by rgeraldes** [comment]
Looking at this one @influx6 @tiabc.
Related to #87 (swarm service)
- Configuration support for enabling/disabling swarm service is already present.
Next steps: 
- Add swarm service support
- Extend configuration (swarm options)

**Comment by jarradh** [comment]
Running Swarm on mobile device is currently way too bandwidth intensive, we tried. 
We're currently working with the Swarm team to create light swarm clients, which requires an economic stake in the network. 

They can be found here.
https://gitter.im/ethereum/swarm

**Comment by rgeraldes** [comment]
You caught me watching a swarm video :)
https://www.youtube.com/watch?v=TJ968X-IFZY&t=433s

Thanks for the info.
Ricardo

**Comment by rgeraldes** [comment]
@jarradh Thanks for the info.

**Comment by dshulyak** [comment]
I would close this one and reopen later if needed

**Comment by adambabik** [comment]
I agree. This will be tracked as an idea. All depends on when Swarm Team will manage to provide an implementation of a light client that we can start integrating.
