### ISSUE TITLE
Allow to run status node as a bootnode

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1223]
# Problem

It should be possible to easily run Status Node as a bootnode without a separate binary. Currently, it's possible provided that two conditions are met:
1. Status Node is run with a known IP, for example: `"ListenAddr": "46.101.224.245:30303"`,
2. Discovery V5 does not time out (currently, it can be bypassed by registering a discovery topic).

# Implementation

Provide an additional setting that will prevent Discovery V5 from timeout while not registering any topics.

# Acceptance Criteria

Status Node can act as a bootnode.

# Notes

What about rendezvous? Should we also make it possible to run rendezvous server within Status Node? cc @dshulyak

**Comment by dshulyak** [comment]
> What about rendezvous? Should we also make it possible to run rendezvous server within Status Node?

there is not a lot of benefits doing it. unlike in discovery v5 records are not shared between different rendezvous instances.

**Comment by adambabik** [comment]
@dmitryn so if I want my node to be found using rendezvous, I must connect it to a rendezvous server and then others need to ask the same server?

**Comment by dshulyak** [comment]
yes. this is pretty much it.
rendezvous is useful only when it is widely known and peers can easily agree which rendezvous points are used.
they still can use many, but anyway rendezvous server must be widely known.
