### ISSUE TITLE
config: allow specifying virtual hosts and CORS

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1232]
# Problem

Currently, there is no way to specify virtual host names and CORS when using an HTTP JSON-RPC interface.

# Implementation

The `Config` struct should accept virtual host names and CORS settings. These needs to be compatible with:
- virtual hosts: https://github.com/ethereum/go-ethereum/blob/master/node/config.go#L109-L116
- CORS: https://github.com/ethereum/go-ethereum/blob/master/node/config.go#L104-L107

# Acceptance Criteria

- it's possible to specify virtual hosts and send an HTTP request with a different host than localhost,
- it's possible to specify CORS rules in a config JSON file.
- both settings have to work with a JSON config file.

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>Official Go implementation of the Ethereum protocol - ethereum/go-ethereum</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>Official Go implementation of the Ethereum protocol - ethereum/go-ethereum</div></blockquote>

**Comment by dshulyak** [comment]
is there a plan to expose statusd to the internet or what is the story behind this?

**Comment by adambabik** [comment]
It's for DappNode.io integration. As far as I understand (need to confirm), you can run DAppNode on a server and you can have a VPN connection with an internal domain that resolves to your server. Now, you may want to access your node securely and you would issue an HTTP request with that domain to communicate with the node. Currently, such a request will be rejected due to accepting only `localhost` as a `Host` header.
