### ISSUE TITLE
getting mailserver.request.expired signals too often

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1233]
# Problem

When watching for `mailserver.request.success` signals on status-react we encounter a lot  of `mailserver.request.expired`. More often that not it making the same request on this signal will end up in an infinite loop as it will expire again and again.
I also noticed that adding the mailserver as a peer also often take quite some time (more than 15 sec which is our timeout for retrying).

# Implementation

Handling of these signal can be tested in https://github.com/status-im/status-react/pull/6223

# Acceptance Criteria

Less expired requests, faster connection to mailserver

**Comment by adambabik** [comment]
@yenda is this solved after we switch to multiple topics per request?

**Comment by yenda** [comment]
Only partially because react supports a very long timeout. There is still the problem of requests being sent one by one

**Comment by adambabik** [comment]
Ok, thanks for the update. 

To make the requests sent one-by-one work fast, we need to add parallel processing in this place: https://github.com/status-im/whisper/blob/master/whisperv6/whisper.go#L905 (handling `p2pRequestCode` packet code).

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/whisper">status-im/whisper</a></strong></div><div>Contribute to status-im/whisper development by creating an account on GitHub.</div></blockquote>
