### ISSUE TITLE
LES crashes when syncing Ropsten

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#1247]
# Problem

I have a statusd built from the latest master (rev. `ba504e99c4a004d5fe025dd12f5e7bb66f1190dc`).

When I try to sync Ropsten in LES Client mode, it syncs something first and then crashes.

```
DEBUG[10-18|15:11:44.958] Done synchronising with peer             id=74a0fb8bd37536d3 conn=staticdial
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x47f32b8]

goroutine 124 [running]:
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).checkAnnouncedHeaders(0xc00026e5a0, 0xc000f10f80, 0xc0000cc950, 0x1, 0x1, 0xc000e67d48, 0x1, 0x1, 0x6be4f5fbed426f49)
	/Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:648 +0x1d8
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).newHeaders(0xc00026e5a0, 0xc0000cc950, 0x1, 0x1, 0xc000e67d48, 0x1, 0x1)
	/Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:602 +0x121
github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).syncLoop(0xc00026e5a0)
	/Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:220 +0x30c
created by github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.newLightFetcher
	/Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:132 +0x20d
```

It crashes after every restart too.

I'm attaching the config file I'm using to this issue: https://gist.github.com/mandrigin/1eb6916e4cbc84a2651d7c898bf2a3e2

Command-line: `build/bin/statusd -c ./light-conf.json -log DEBUG`

**Comment by mandrigin** [comment]
This crash is not 100% reproducible, sometimes I have to wait for it to crash before going into the crash loop.

**Comment by b00ris** [comment]
@mandrigin I wasn't able to reproduce it. It would be great if you share your datadir with me.

**Comment by mandrigin** [comment]
@b00ris sure, I will try to reproduce once more and will share the datadir or will close the issue

**Comment by JekaMas** [comment]
We should make a PR to go-ethereum upstream fixing validation in light client fetcher. At the moment it's possible to raise a panic on client side just sending to it an invalid block without `td`.
