### ISSUE TITLE
"No suitable peers available" when requesting the account balance in LES (when syncing)

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#1248]
# Problem

I have a statusd built from the latest master (rev. `ba504e99c4a004d5fe025dd12f5e7bb66f1190dc`).

It is running as a LES *client*.

It is connected to our own LES server:
`enode://00406d8b388ced326f644c64ffd1557741b96ccfbb4751a25104ad03e8d39c7bffc79780531cb80a709e767a7e9a08936edf1ef06e50e7991831d98c02498803@104.248.199.52:30303`

I'm waiting until the sync is visibly over (no log entries about `Inserted new header` or `Imported new block headers`, etc).

I'm checking balance of this account: https://ropsten.etherscan.io/address/0x762cc2bfdba9d54d7b5b3a077982dae898212957 (2 tx on Ropsten)

I'm sending this JSON-RPC to the LES client:
```
{
	"jsonrpc": "2.0",
	"id": 121212,
	"method": "eth_getBalance",
	"params": [
		"0x762CC2BFDbA9D54D7B5b3A077982DAE898212957",     
		"latest"
	]
}
```

I'm getting the unexpected JSON-RPC response:
```
{
	"jsonrpc": "2.0",
	"id": 121212,
	"error": {
		"code": -32000,
		"message": "no suitable peers available"
	}
}
```

In the logs I see:
```
DEBUG[10-18|15:29:29.503] Requesting trie proof                    id=00406d8b388ced32 conn=staticdial                            root=1ca9b8…2cf682 key="[112 176 168 35 83 111 65 198 52 251 52 42 139 166 163 162 10 207 55 243 9 61 36 154 66 187 130 247 207 112 222 251]"
DEBUG[10-18|15:29:29.503] Fetching batch of proofs                 id=00406d8b388ced32 conn=staticdial                            count=1
DEBUG[10-18|15:29:29.544] Validating trie proof                    root=1ca9b8…2cf682 key="[112 176 168 35 83 111 65 198 52 251 52 42 139 166 163 162 10 207 55 243 9 61 36 154 66 187 130 247 207 112 222 251]"
DEBUG[10-18|15:29:29.544] Light Ethereum message handling failed   id=00406d8b388ced32 conn=staticdial                            err="Invalid response - reqID = 7782328339939563196"
```

<blockquote><img src="/images/favicon2.ico" width="48" align="right"><div><strong><a href="https://ropsten.etherscan.io/address/0x762cc2bfdba9d54d7b5b3a077982dae898212957">Ropsten Accounts, Address And Contracts</a></strong></div><div>The Ethereum BlockChain Explorer, API and Analytics Platform</div></blockquote>

**Comment by JekaMas** [comment]
It looks like we were affected by Constantinople issue. We can close that issue and restart our cluster with full sync.

@mandrigin https://github.com/status-im/status-go/issues/1254

**Comment by mandrigin** [comment]
It works when synced, but not when syncing, even after cluster re-sync.

**Comment by b00ris** [comment]
@mandrigin @JekaMas 
```
DEBUG[10-25|00:32:35.421] Invalid header encountered               number=4230000 hash=250d0c…0deb75 err="invalid difficulty: have 14784344571, want 14784343547"
WARN [10-25|00:32:35.423] Rolled back headers                      count=112  header=4228735->4228735 fast=0->0 block=0->0
DEBUG[10-25|00:32:35.423] Transaction receipt download terminated  err="receipt download canceled (requested)"
DEBUG[10-25|00:32:35.423] Skeleton fill terminated                 err="block header download canceled (requested)"
DEBUG[10-25|00:32:35.423] Skeleton chain invalid                   peer=9ddb58cb90f8f00a err="block header download canceled (requested)"
``` 

it's constantinople problem. 
>Geth v1.8.17 is our regular maintenance release, which among numerous bugfixes also features the full Constantinople feature set and enables it on the Ropsten testnet at block #4230000.

After this block LES constantly drop server peers and we got "no suitable peers available" from odr.

**Comment by mandrigin** [comment]
@b00ris so, does it mean that we need to upgrade our LES server to 1.8.17 asap?

**Comment by jakubgs** [comment]
Clusters updated to `1.8.17`.

**Comment by mandrigin** [comment]
@b00ris ULC is affected too on the initial sync. 
statusd config is attached: [ulc-conf.json.zip](https://github.com/status-im/status-go/files/2518231/ulc-conf.json.zip)

**Comment by mandrigin** [comment]
@jakubgs @b00ris after upgrading the servers, I can't make neither LES nor ULC to sync: https://github.com/status-im/status-go/issues/1258
