### ISSUE TITLE
Support ULC params in statusd

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#1249]
# Problem

After merging the ULC patch, there is a new option available in the ethereum light client config (see https://github.com/status-im/status-go/blob/develop/node/node.go#L205-L224)

`ethConf.ULC.TrustedServers` needs to receive a list of enodes of trusted servers.

It should be possible to pass these trusted nodes list through statusd config.

Example of statusd config
```json
    "LightEthConfig": {
        "Enabled": true,
        "ULC": {
            "TrustedServers": [
                "enode://5ec02c12da79943968bd88b5d4a380fecd304a22bf7d9d43b3d77f5ba2c631815adb041de293ae9fef2ee6fc0460b55a3c6579cbde655d091254561664493153@178.62.217.111:30303", 
                "enode://830d27a87331e3706bd2fbc8931db2ffb2c5d92aec6ed62e595816e2a2859450680b8542f77f021218e8714297d714db3503f87915a2e5c879a4f06a9f471e89@178.62.222.51:30303", 
                "enode://194c8d5e6e27581c65f90be7a068b69361672798b3791033697985a9f47ff4cf364d7bc8d2657915ae9b5f84c7bafedbfed834b9e1cc762363db7ed56f43280f@178.62.240.13:30303"
            ]
        }
    },
```

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by mandrigin** [comment]
@b00ris any news on this issue?

**Comment by b00ris** [comment]
I'm going to make PR today

**Comment by b00ris** [comment]
Resolved https://github.com/status-im/status-go/pull/1255
