### ISSUE TITLE
Scope of libp2p integration

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1253]
1. implement p2p.MsgReadWriter wrapping libp2p's net.Stream

every devp2p protocol has a loop for handling single peer connection. for whisper it is whisper.HandlePeer which accepts p2p.Peer and p2p.MsgReadWriter. p2p.Peer ID is used in whisper, so p2p.Peer can be created using id from stream.Conn().RemotePeer and casted to a required type. IsFlaky() method of p2p.Peer used when messages are broadcasted (covered in point 3).

p2p.MsgReadWriter provides interface for reading/writing a single message. We can wrap net.Stream to encode/decode message. Encoding choice is up to us, but it makes sense to stick with rlp, as it sometimes used by protocol directly.

2. integrate libp2p.Host with status-go peer pool

peerpool manages discovery and sends found peers to p2p.Server. to integrate libp2p.Host with discovery we need a common interface between p2p.Server and libp2p.Host.

the same interface can be used for adding static peers.

3. implement libp2p ping protocol

we are relying on devp2p pings to verify how flaky is connection. this is done to have a signal when messages are actually leave the node. not perfect, but this is what we have right now to achieve at least some reliability.

protocol should be simple ping/pong and integrated with p2p.Peer to provide information about connection flakiness.

4. run same instance of whisper with peers from devp2p and libp2p networks

switching to libp2p completely will create a network which will be completely isolated from devp2p network. to prevent this we need to have instances that can run with connections to devp2p peers and libp2p peers. those peers will act like a proxy between old (devp2p) and new (libp2p) networks.

technically we need to ensure that HandlePeer works both with p2p.MsgReadWriter provided by devp2p server and new libp2p server. and peerpool/discovery can find libp2p and devp2p peers.

5. peer should indicate that it accepts libp2p connection

add a separate parameter to ENR to indicate this.

**Comment by adambabik** [comment]
> protocol should be simple ping/pong and integrated with p2p.Peer to provide information about connection flakiness.

Do we need ping/pong or heartbeat would be enough? Maybe we can create an issue in go-ethereum with a description of this protocol? I think it can be nicely generalized.

Great stuff! What are the next steps?

**Comment by dshulyak** [comment]
> Do we need ping/pong or heartbeat would be enough? Maybe we can create an issue in go-ethereum with a description of this protocol? I think it can be nicely generalized.

Could be heartbeats. I thought about ping/pong so that dialer can control frequency. There is already ping/pong protocol implemented in devp2p server. We need similar thing but for libp2p.

> Great stuff! What are the next steps?

I started looking at 1st item. Trying to understand how to properly handle deadlines with streams. In devp2p deadlines are handled per connection, so in case if some protocol is idle - connection will not timeout because of periodic pings. With deadline per protocol we can get unexpected disconnects whenever whisper will go idle.

**Comment by adambabik** [comment]
> Could be heartbeats. I thought about ping/pong so that dialer can control frequency. There is already ping/pong protocol implemented in devp2p server. We need similar thing but for libp2p.

Interesting. I took a look and it seems that ping/pong protocol in devp2p is super simple:
- it has no retry logic,
- it does not wait for pong (I did not notice any code for that, there is only one in examples).

Our flaky peer detection, on the other hand, works based on incoming messages.

> I started looking at 1st item. Trying to understand how to properly handle deadlines with streams. In devp2p deadlines are handled per connection, so in case if some protocol is idle - connection will not timeout because of periodic pings. With deadline per protocol we can get unexpected disconnects whenever whisper will go idle.

On the other hand, if any protocol returns an error, the connection is dropped for all protocols, right? It's interesting what's the best strategy... Maybe we can keep track of healthy protocols per connection and if there is none then the peer is disconnected?

**Comment by dshulyak** [comment]
> Our flaky peer detection, on the other hand, works based on incoming messages.

receiver responds with a pong. so in the end client controls frequency. and based on this detector renews timer each time when pong/ping or any other message was read.

> On the other hand, if any protocol returns an error, the connection is dropped for all protocols, right? It's interesting what's the best strategy... Maybe we can keep track of healthy protocols per connection and if there is none then the peer is disconnected?

yeah this is kinda similar to what i tried. by default if single stream timeouts it will not affect another stream. but we can leave whisper stream without deadlines for reads/writes. create separate ping/pong stream and add deadlines. if io timeouts we can close whole connection in that stream. libp2p interfaces gives access to it.
