### ISSUE TITLE
Restart and resync LES cluster

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#1254]
# Problem

Status LES cluster is in inconsistant state.

# Implementation

It should be restarted and resynced.

# Acceptance Criteria

All LES servers are in sync with the Network. Basic calls (account, transaction) works fine.

**Comment by divan** [comment]
Closing it, as it's not a status-go codebase issue.
I contacted @jakubgs in Status #status-core-infra channel, please do the same next time with similar issues.

**Comment by mandrigin** [comment]
@divan Status app is not a reliable history/decision documentation place though. Maybe you can suggest alternative github repo?

**Comment by divan** [comment]
@mandrigin do we need git repository for the things like asking right people to restart servers?

**Comment by mandrigin** [comment]
I want some place to track all LES-related issues, otherwise it looks like it isn’t any work, to investigate and fix server issues. 

I believe, that there should be some ticketing for ops tasks and that Status or Slack is pretty poor being this ticketing system.

**Comment by jakubgs** [comment]
I think the right place is where it's configured so:
https://github.com/status-im/infra-misc

<blockquote><div><strong><a href="https://github.com/status-im/infra-misc">Page not found · GitHub</a></strong></div></blockquote>

**Comment by divan** [comment]
@mandrigin agree. To me, `status-go` repo is definitely not a good ticketing system for Status infrastructure.
UPD: see answer above
