### ISSUE TITLE
Updated docs on hub.docker.com/r/statusteam/status-go/

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1256]
# Problem

We have multiple places with instructions how to run Status Node and they are not up-to-date. Fix https://hub.docker.com/r/statusteam/status-go/ readme to point to https://docs.status.im/docs/run_status_node.html.

# Acceptance Criteria

There is a single doc describing how to run Status Node and all places refer to it instead of duplicating the content.

<blockquote></blockquote>
<blockquote><div><strong><a href="https://docs.status.im/docs/run_status_node.html">Status, a Mobile Client for Ethereum 2.0</a></strong></div></blockquote>

**Comment by pablanopete** [comment]
I believe this link is outdated now since our web refresh.

**Comment by pablanopete** [comment]
On trying to generate a node key within docker I'm having this error. @adambabik 

`docker run --rm ethereum/client-go:alltools-latest -genkey=/var/run/status-go/nodekey`

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"-genkey=/var/run/status-go/nodekey\": stat -genkey=/var/run/status-go/nodekey: no such file or directory": unknown.`

any idea why it wouldn't be finding the dir after running docker and trying to generate a node key?

**Comment by adambabik** [comment]
@pablanopete the problem is a default `entrypoint` in that Docker image. Try add `--entrypoint=bootnode` after `--rm`.

**Comment by adambabik** [comment]
It's changed https://hub.docker.com/r/statusteam/status-go/.

<blockquote></blockquote>
