### ISSUE TITLE
[ULC/LES] Initial sync never finishes

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#1258]
# Problem

I can't make ULC to finish the initial sync properly. It ends up with these log entries repeating.

Syncing from scratch, the datadir/keydir are cleared before starting.

```
WARN [10-26|09:46:33.299] Rolled back headers                      count=112  header=4229887->4229887 fast=0->0 block=0->0
DEBUG[10-26|09:46:33.300] Transaction receipt download terminated  err="receipt download canceled (requested)"
DEBUG[10-26|09:46:33.300] Skeleton fill terminated                 err="block header download canceled (requested)"
DEBUG[10-26|09:46:33.300] Skeleton chain invalid                   peer=690c93ac2f6e6f71 err="block header download canceled (requested)"
DEBUG[10-26|09:46:33.300] Header download terminated               peer=690c93ac2f6e6f71
DEBUG[10-26|09:46:33.300] Block body download terminated           err="block body download canceled (requested)"
DEBUG[10-26|09:46:33.300] Synchronisation terminated               elapsed=384.666263ms
WARN [10-26|09:46:33.300] Synchronisation failed, dropping peer    peer=690c93ac2f6e6f71 err="retrieved hash chain is invalid"
DEBUG[10-26|09:46:33.300] Done synchronising with peer             id=690c93ac2f6e6f71 conn=staticdial
DEBUG[10-26|09:46:33.300] Unknown peer to check sync headers       id=690c93ac2f6e6f71 conn=staticdial
DEBUG[10-26|09:46:33.300] Light Ethereum message handling failed   id=690c93ac2f6e6f71 conn=staticdial err=EOF
DEBUG[10-26|09:46:33.300] Disconnected old entry                   enode=690c93ac2f6e6f71
DEBUG[10-26|09:46:33.300] Removing p2p peer                        id=690c93ac2f6e6f71 conn=staticdial duration=15.243s   peers=2 req=false err="useless peer"
```

At the same time, `eth_syncing` is showing that the sync is happening:
```
{
	"jsonrpc": "2.0",
	"id": 121212,
	"result": {
		"currentBlock": "0x408aff",
		"highestBlock": "0x41ab35",
		"knownStates": "0x0",
		"pulledStates": "0x0",
		"startingBlock": "0x3dffff"
	}
}
```
statusd, build from sources @ `bdbceba6eb3c1065c1aca235b13791f1e95fe739`

statusd config: [ulc-conf.json.zip](https://github.com/status-im/status-go/files/2518245/ulc-conf.json.zip)

@b00ris @JekaMas can you take a look?

**Comment by mandrigin** [comment]
okay, same thing on *the same block* in LES too: 

```
DEBUG[10-26|09:54:46.859] Received new announcement                id=bc827e035cf3a42c conn=staticdial number=4303702 hash=2c6a91…2a046a reorg=0
DEBUG[10-26|09:54:46.927] Waiting for head header timed out        peer=52018eb510f8d332 elapsed=6.000006s
DEBUG[10-26|09:54:46.927] Synchronisation terminated               elapsed=6.002242792s
WARN [10-26|09:54:46.927] Synchronisation failed, dropping peer    peer=52018eb510f8d332 err=timeout
DEBUG[10-26|09:54:46.927] Done synchronising with peer             id=52018eb510f8d332 conn=staticdial
DEBUG[10-26|09:54:46.927] Unknown peer to check sync headers       id=52018eb510f8d332 conn=staticdial
DEBUG[10-26|09:54:46.927] Light Ethereum message handling failed   id=52018eb510f8d332 conn=staticdial err=EOF
DEBUG[10-26|09:54:46.927] Disconnected old entry                   enode=52018eb510f8d332
DEBUG[10-26|09:54:46.927] Removing p2p peer                        id=52018eb510f8d332 conn=staticdial duration=11.973s   peers=1 req=false err="useless peer"
DEBUG[10-26|09:54:48.173] Recalculated downloader QoS values       rtt=2s           confidence=1.000 ttl=6.000006s
DEBUG[10-26|09:54:50.175] Recalculated downloader QoS values       rtt=2s           confidence=1.000 ttl=6.000006s
DEBUG[10-26|09:54:52.180] Recalculated downloader QoS values       rtt=2s           confidence=1.000 ttl=6.000006s
DEBUG[10-26|09:54:54.182] Recalculated downloader QoS values       rtt=2s           confidence=1.000 ttl=6.000006s
DEBUG[10-26|09:54:56.183] Recalculated downloader QoS values       rtt=2s           confidence=1.000 ttl=6.000006s
DEBUG[10-26|09:54:56.284] Dialing new peer
```

`eth_syncing`
```
{
	"jsonrpc": "2.0",
	"id": 121212,
	"result": {
		"currentBlock": "0x4087ff",
		"highestBlock": "0x41ab4a",
		"knownStates": "0x0",
		"pulledStates": "0x0",
		"startingBlock": "0x3dffff"
	}
}
```


Config: [light-conf.json.zip](https://github.com/status-im/status-go/files/2518276/light-conf.json.zip)

**Comment by mandrigin** [comment]
after a few starting/restarting managed to get it to the block `0x40897f` (LES), can't get pass that now

**Comment by jakubgs** [comment]
I researched this today since I saw `netdata` containers continuously fail on the `les-rops` hosts and I found this:
https://grafana.status.im/d/QCTZ8-Vmk/single-host?orgId=1&var-host=node-02.do-ams3.les-rops.misc&from=1541861824532&to=1541862045175

The host runs out of memory:
![les_mem_usage](https://user-images.githubusercontent.com/2212681/48311141-a7a37880-e59b-11e8-86c7-14a2249b0371.png)

And CPU usage in __percent__ reaches ~125 million... percent...:
![les_cpu_usage](https://user-images.githubusercontent.com/2212681/48311140-9fe3d400-e59b-11e8-90bf-6e19c1b0b3c1.png)

And this is what I found in the logs there:
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf8a0b3, 0x16)
#011/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc0dc000000, 0x4000000, 0x1e996f8)
#011/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x1e7fb40, 0x4000000, 0x7fc074ced398, 0x7fc07bf9b8a0)
#011/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x1e7fb40, 0x879, 0x0)
#011/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x1e7fb40, 0x879, 0x1e99708, 0x2800)
#011/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x1e7fb40, 0x879, 0x101, 0x7fc07ead6fff)
#011/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
#011/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x1e7fb40, 0x879, 0x27b000101, 0x42ae05)
#011/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x10f2000, 0xc04b070100, 0x472c66)
#011/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
#011/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x40)
#011/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
#011/usr/local/go/src/runtime/proc.go:1229
```
Now, this seems to be happening fairly quickly:
![container_mem_usage](https://user-images.githubusercontent.com/2212681/48311170-0bc63c80-e59c-11e8-97c0-34d5ff6c9a3d.png)

For example from 14:59 when the container is restarted to 15:22 when it reaches pretty much peak memory usage.

Either Geth has a memory leak, or this host needs more memory...

**Comment by jakubgs** [comment]
I have implemented and deployed a docker memory limit for LES nodes:
https://github.com/status-im/infra-misc/commit/ed99965073b6062a7fee2602f90f2b5cb82c68fa
Simply using the docker `--memory` option:
https://docs.docker.com/config/containers/resource_constraints/#memory
I've deployed it to the `les-rops.misc` fleet for now. Let's see how it changes it's behaviour.

<blockquote><img src="/favicons/docs@2x.ico" width="48" align="right"><div><img src="/favicons/docs@2x.ico" height="14"> Docker Documentation</div><div><strong><a href="https://docs.docker.com/config/containers/resource_constraints/">Limit a container's resources</a></strong></div><div>Limiting the system resources a container can use</div></blockquote>

**Comment by jakubgs** [comment]
Well, at lest now the container gets restarted around 2.7 GB instead of going to the full 3.6 GB and fucking up the host and other containers:
![better_mem](https://user-images.githubusercontent.com/2212681/48312558-f0b1f780-e5b0-11e8-9b47-4a74f0da86ab.png)
Not sure if this is an improvement for the syncing process.

**Comment by mandrigin** [comment]
Okay, it looks like it is because we still use the old go-ethereum that doesn't support Constantinople hard fork.
