### ISSUE TITLE
Implement eth_getFilterLogs 

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1262]

**Comment by dshulyak** [comment]
Some dapps are relying on this method? I didn't notice that it exists before. Thanks
Currently results will be returned with getFilterChanges, which works for any filter type. And this one will work only for logs (https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterlogs) . Right?

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/wiki">ethereum/wiki</a></strong></div><div>The Ethereum Wiki. Contribute to ethereum/wiki development by creating an account on GitHub.</div></blockquote>

**Comment by flexsurfer** [comment]
Yes some dapps are relying or even truffle framework is relying on this method. i don't know how exactly eth_getfilterlogs works if I understand correctly  eth_getfilterlogs returns all logs , but getFilterChanges returns only logs which occurred since last getFilterChanges call
