### ISSUE TITLE
Add support for arrays and slices to signTypedData

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1267]
# Problem

Both metamask and implementation linked to EIP do not support arrays.
I skipped them when typed data was implemented initially.

# Implementation

EIP 712 defines how array and slices should be encoded:

> The array values are encoded as the keccak256 hash of the concatenated encodeData of their contents (i.e. the encoding of SomeType[5] is identical to that of a struct containing five members of type SomeType).

# Acceptance Criteria

Arrays and slices, denoted as `type[3]` and `type[]` are supported and can be used in typed data request.

**Comment by randomshinichi** [comment]
I'd like to do this - is it still available?

**Comment by dshulyak** [comment]
@randomshinichi yes

**Comment by randomshinichi** [comment]
Cool. Forgive me for asking but I'm just starting out:
Is this api/backend.go (StatusBackend.SignTypedData) or lib/library.go (SignTypedData())?

What kind of data does it sign/when is this function used?

**Comment by dshulyak** [comment]
Library just wraps status backend to provide an interface for bindings that are used by mobile/desktop. You can find all the logic related to typed data in services/typeddata. Typed data is an implementation of the https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

UPD: sorry, i pasted corrupted link at first. fixed it

**Comment by divan** [comment]
@dshulyak just in case, there is a parallel implementation if EIP191/712 is in progress in geth: https://github.com/ethereum/go-ethereum/pull/17789
