### ISSUE TITLE
Contact codes may be generated incorrectly 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status-go#1268]
# Problem

Certain users can not edit their contact codes in the ENS usernames DApp. 

See this issue in ens-usernames: https://github.com/status-im/ens-usernames/issues/79

```
I think this contract code is not properly generated: 0x04beb846a66a820bf7c2ecee595ce9cf7850ac3449029639e93462815c7391868402e0998c5e3bd6cf35769d74a06400811c100404ae70ee3e2ca796b7949fd4de - when trying to extract the x,y coordinates the y coordinate is shorter than the x. As a result this address will not be able to register their contact code.
```

# Notes

It's possible this is an issue on the DApp side but requires status-go to confirm.

**Comment by oskarth** [comment]
@status-im/go ^ thoughts?

**Comment by dshulyak** [comment]
I tried to unmarshall given public key into x and y coordinates. here is a snippet:

```go
package main

import (
	"crypto/elliptic"
	"fmt"

	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/crypto"
)

const (
	val = "0x04beb846a66a820bf7c2ecee595ce9cf7850ac3449029639e93462815c7391868402e0998c5e3bd6cf35769d74a06400811c100404ae70ee3e2ca796b7949fd4de"
)

func main() {
	data, err := hexutil.Decode(val)
	if err != nil {
		panic(err)
	}
	x, y := elliptic.Unmarshal(crypto.S256(), data)
	fmt.Println(x, y)
}
```

both x and y are 32 bytes. first byte is set to 4, so that elliptic.Unmarshal knows that public key is in compressed form

**Comment by dshulyak** [comment]
So every public key will be 65 bytes array. With 0 byte set to 4, and then every coordinate appended.  This is the code that is used: https://golang.org/src/crypto/elliptic/elliptic.go?s=8232:8279#L295.

@bgits I tried to follow js code and it seems that that they just expect 64 bytes here https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/key.js

<blockquote><div><strong><a href="https://golang.org/src/crypto/elliptic/elliptic.go?s=8232:8279#L295">src/crypto/elliptic/elliptic.go - The Go Programming Language</a></strong></div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/238531?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/indutny/elliptic">indutny/elliptic</a></strong></div><div>Fast Elliptic Curve Cryptography in plain javascript - indutny/elliptic</div></blockquote>

**Comment by bgits** [comment]
I can confirm this is purely client-side. I opened a PR in ens-usernames to correct this.

**Comment by dshulyak** [comment]
Great, i will close issue then
