### ISSUE TITLE
Messages are "sent" but not delivered if network is flaky

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1276]
# Problem

If message is sent exactly when network connection disappears or changes it will be marked as "sent" but not delivered. To reproduce this issue writer must send messages at the high rate. In the test I am sending them every 50ms and in parallel introduce network conditions. Packet loss must result in the connection being dropped, so wait until connection will be terminated by read deadline (15s).

We enabled aggressive heartbeats between every client. But it doesn't provide strict guarantees, it only makes the window when such bug can occur smaller.

On the mobile device this issue can occur when client changes network connection from WIFI to 3g/4g or simply leaves the zone of coverage at the time of writing. The other sign of this issue might be received notification, but no actual message. I haven't try to reproduce it on mobile yet, but i've seen reports from users that share similar data.

Also, consider that whisper by itself doesn't provide any guarantees as well. So even if message was sent to a peer, it doesn't mean that this peer will deliver message anywhere at all. We can expect it from our peers because we control 100% of our network. But imagine what would happen if we won't.

# Implementation

We need to have mechanism that provides stricter delivery guarantees. Usually such guarantees can be achieved by acknowledging delivery by the receiver, and re-trying by the sender if ack's were not received in the expected window.

I will keep it open here if someone has ideas how to provide it on the level of whisper. Otherwise we need to reconsider ack's on the application protocol.

# Acceptance Criteria

Client should have a strict guarantee that message will be delivered. Or informed that it is impossible to do so.

cc @mandrigin @cammellos @adambabik

**Comment by dshulyak** [comment]
I can definitely reproduce this on mobile. Sent a message the exact moment i turned of wifi) marked as sent, but wasn't delivered to my desktop device or mailserver. And the same for desktop with enabled packet loss.

**Comment by dshulyak** [comment]
And I can reproduce the case with received notification without message. Once connection is restored notification will be sent, but message was already discarded. Not entirely sure why notification is sent, but it is probably done by client that we use for notifications.

**Comment by adambabik** [comment]
We talked about one idea during the hackathon. Let's assume we have N peers and select one peer randomly (`a^i`). Now, we send a message to N-1 peers and wait until it's received from peer `a^i`. If it's never received in T seconds, it's highly probable that the message did not leave the device and it should be retried.

Are there any concerns about privacy/darkness with regards to this approach?

**Comment by dshulyak** [comment]
> Are there any concerns about privacy/darkness with regards to this approach?

it might be easier to distinguish messages that originate on the device that sends them this way

but i am more concerned about general guarantees that this approach provides. there is no end-to-end guarantee. consider the case where message was sent to the network successfully. but recipients mail server went offline and this message wasn't stored. so it will be never delivered to user.

**Comment by dshulyak** [comment]
For instance, this bug with "sent" but not delivered can be reproduced in a different ways:
- server that received a message will go down before it transmits messages further
- mail server of the recipient will be unreachable when message is transferred
- servers that used by sender or recipient are partitioned into separate network, think part of our cluster in alibaba

Each case can be simulated with status-scale. The only solution, i can think of, to all of those cases is to use synchronization protocol with confirmations between sender and recipient in the chat. It is easy to imagine such protocol when peers are online. But will require heavy redesign of mail servers to make it work when they are not.

So do we accept that they can occur and ignore them, and wait for new protocol just to solve them? 
@oskarth maybe?

**Comment by adambabik** [comment]
> but recipients mail server went offline and this message wasn't stored. so it will be never delivered to user

In this case, you would need to check with every mail server if it properly stored your message. That's not really feasible. Also, even if the mail server stored a particular message, there is no guarantee that the message will stay there for sufficient amount of time.

> It is easy to imagine such protocol when peers are online. But will require heavy redesign of mail servers to make it work when they are not.

I agree that it is definitely possible to implement some checks/acks when two parties are online. They could exchange some info and confirm that all messages since the last check were exchanged. 

Regarding the mail server redesign, as we don't control these nodes, I don't think it will ever be possible to make some strong guarantees, especially when each party can use a different one. Negotiating a mail server used for a particular conversation might be helpful to improve these guarantees.

**Comment by dshulyak** [comment]
> In this case, you would need to check with every mail server if it properly stored your message. That's not really feasible. Also, even if the mail server stored a particular message, there is no guarantee that the message will stay there for sufficient amount of time.

so what i was thinking about is to use a concept of a delegated mail server. at the beginning of communication peers should exchange which mail server they are using. not the whole ip address, but just an identity. this identity will respond to messages when original recipient is not available. and the sender will use responses from this identity as a confirmation of delivery.

**Comment by mandrigin** [comment]
> But will require heavy redesign of mail servers to make it work when they are not.

What kind of redesign are you talking about exactly?

**Comment by dshulyak** [comment]
so to give an example: at the start you "pair" with some mail server. it can be you personal mail server, or one that found on the network. this mail server actually needs to know when it should send a confirmation. it can be done by sharing bloom filter, but it could be too broad. so once paired, you include id of this mail server in a contact exchange with me. when i am trying to communicate with you and you are offline, i will receive a confirmation that your mail server got a message and that's it.

**Comment by mandrigin** [comment]
So, if we start from ground up, we have a tad different message states than a normal centralized messenger has.

1. *Not Sent* — the message is still on our local node and wasn't sent anywhere
2. *In Transit* — the message has left the node, and propagated at least to one other node in the network.
3. *Delivered* — when the recipient node received the message.
4. *Timed Out* — when the message has left the node, but wasn't received by the recipient (or the ack wasn't delivered).

Note that there is no *Sent* state (which we currently have, but it is a lie), because sending it to a p2p network doesn't mean anything and doesn't guarantee delivery (network partitions, bad timing, etc).

For user, (1) and (2) are essentially the same, I think.

So, maybe we can avoid receiving acks from mailservers specifically and only care about acks from the recipient. Then it potentially can be done _on top of_ whisper as opposed to _in_ Whisper.

What do you think?

**Comment by cammellos** [comment]
we had acks at some point I believe in the chat high level protocol,
@rasom could you give us some insights of pro-cons/how they were working etc?

**Comment by mandrigin** [comment]
But that is of course is reasonable for 1:1 messages.
Public chats are way more tricky.
What does it even mean that the message was successfully delivered to a public chat?
Especially, when we don't control all the mailservers.

**Comment by cammellos** [comment]
public chat I don't think is feasible (bar checking mailserver etc), I think we should still at least make sure the message has left the node at the devp2p/whisper level, before sending a confirmation to the user, if that's easy enough and not too costly, it would cover at least the most obvious case of failure, still leaving us exposed to some scenarios of course.

**Comment by mandrigin** [comment]
So far, when all the mailservers are under our control, we need to be able to somehow ensure that they are in sync with each other and send acks when the public chat message is delivered to one (or, better, at least or two) of them.

**Comment by cammellos** [comment]
a mailserver could publish an ack of the whisper envelope hash (on some topic), and any client who cares could just listen for those acks, re-transmit otherwise

**Comment by mandrigin** [comment]
yeah, I agree, but then we also need to be sure that mailservers are in sync with each other as much as possible. Reinventing DB replication, but using Whisper :-P
One more thing, that I would maybe implement a special "mailserver ack" and wait for at least 2 (or N) of those to consider message "sent".

**Comment by mandrigin** [comment]
Alternatively, "~sent to~ received by a half of known mailservers" or something like that.

**Comment by cammellos** [comment]
yes, something like that, for replication we have the advantage of being append-only, but yes, at this point it  makes more sense to use an already working distributed database behind the scene, as re-implementing that is just not something we should do :), and they can synchronize each other outside whisper, as I don't think we would lose any darkness there but we need to think a bit carefully

**Comment by dshulyak** [comment]
> So, maybe we can avoid receiving acks from mailservers specifically and only care about acks from the recipient. Then it potentially can be done on top of whisper as opposed to in Whisper.

the concern is a following situation: you send me a message while i am offline, it got lost. i came back online, and what are my options? i cannot send any acks, and i must request state that i am missing from you. so without any 3rd parties that can help us to synchronize state this seems unreliable.

> a mailserver could publish an ack of the whisper envelope hash (on some topic), and any client who cares could just listen for those acks, re-transmit otherwise

it doesn't guarantee that **my** mail server received a message though

> yeah, I agree, but then we also need to be sure that mailservers are in sync with each other as much as possible. Reinventing DB replication, but using Whisper :-P

i am not sure that this should a goal. if i run my mail server i am much more interested in receiving my data, then storing potentially terabytes of random data.

**Comment by dshulyak** [comment]
> Public chats are way more tricky.

it is probably fine that public chats are best effort based. so receiving a confirmation from your mail server is enough

**Comment by cammellos** [comment]
> it doesn't guarantee that my mail server received a message though

 that's very true, so there seem to be some conflicting views, probably we should figure out, do we care about user-run mailservers for now or we should only consider our stack?

**Comment by mandrigin** [comment]
> it doesn't guarantee that my mail server received a message though

But you won't get 100% consistency guarantees in any distributed systems all the time, if you want system availability, the CAP theorem. That is why in a distributed DB there are options like "wait until written to a single node, to at least two nodes, to at least 1/2 of the nodes in the cluster". That is the best effort.

**Comment by cammellos** [comment]
uh, maybe I misunderstood, what do you mean by `my` mailserver? the one you run your own or the one you are connected to?

**Comment by mandrigin** [comment]
> the concern is a following situation: you send me a message while i am offline, it got lost. i came back online, and what are my options? i cannot send any acks, and i must request state that i am missing from you. so without any 3rd parties that can help us to synchronize state this seems unreliable.

That is why you show  "in transit" state to a sender, and not "sent". "In transit" doesn't provide guarantees that it won't timeout. So if the message is lost, at least the sender will know that after a timeout it didn't receive the Ack, so it can resend the message.

Marking message as "Sent" inquires that sooner or later the recipient will receive it when she'll be online. To me, wording matters, because it sets expectations.

**Comment by mandrigin** [comment]
With a system where messages have any kind of TTL, it is impossible to guarantee that the recipient will receive your message even if it is successfully propagated in the network (to all nodes and mailservers in our case). So we shouldn't pretend that we can guarantee it.

**Comment by mandrigin** [comment]
So, for real the states that we care about are:
Not Sent, 
Propagating (to mailservers, that is),
In Transit (when it propagated to the number of mailserver we want, but wasn't delivered to the recipient, "Sent" for public chats),
Delivered (only for 1:1),
Seen (only for 1:1),
Error

**Comment by dshulyak** [comment]
> that's very true, so there seem to be some conflicting views, probably we should figure out, do we care about user-run mailservers for now or we should only consider our stack?

i think the latter. if we care only about our stack, that we can just use http servers with a distributed database behind. no?

> But you won't get 100% consistency guarantees in any distributed systems all the time, if you want system availability, the CAP theorem. That is why in a distributed DB there are options like "wait until written to a single node, to at least two nodes, to at least 1/2 of the nodes in the cluster". That is the best effort.

but this is not what i care. in this case i care only about consistency between me and the recipient. thats why i am waiting for confirmation from recipient or mail server that is used by recipient. 

> uh, maybe I misunderstood, what do you mean by my mailserver? the one you run your own or the one you are connected to?

the one that i am using. it can be my own though

> That is why you show "in transit" state to a sender, and not "sent". "In transit" doesn't provide guarantees that it won't timeout. So if the message is lost, at least the sender will know that after a timeout it didn't receive the Ack, so it can resend the message.

it may work i am not against trying it or smth like that. the reason i like idea with personal mail server is that you are getting a confirmation that provides strict and probabilistic guarantee of delivery.

**Comment by rasom** [comment]
@cammellos 
> could you give us some insights of pro-cons/how they were working etc?

naïve implementation, some types of messages required acks and if you haven't received them during some period of time you retried sending (N times). Guys removed that code when mail servers were introduced, though it was discussed that users might want to not rely on mailservers at all because of security concerns and we still need to guaranty delivery in this case (to some extent).

**Comment by rasom** [comment]
> public chat I don't think is feasible (bar checking mailserver etc), I think we should still at least make sure the message has left the node at the devp2p/whisper level, before sending a confirmation to the user

that's what we expected from `envelope.sent` event

**Comment by mandrigin** [comment]
> but this is not what i care. in this case i care only about consistency between me and the recipient. thats why i am waiting for confirmation from recipient or mail server that is used by recipient.

okay, we need to branch 2 discussions from here, because there I was talking (mostly) about public chats mostly, but you are clearly answering about 1:1 chats :-)

though, I agree, for 1:1 chat, maybe a delegated mailserver could work. at least, we might try it out.

a few concerns there:
1) what if this mailserver becomes unavailable mid-chat
2) what if we have negotiated on the mailserver while we were both online, then I want to send a message when you are offline, but the mailserver is offline too?

I can summarize the ideas from this thread and we can work on different ones separately.

**Comment by dshulyak** [comment]
> okay, we need to branch 2 discussions from here, because there I was talking (mostly) about public chats mostly, but you are clearly answering about 1:1 chats :-)

definitely, i completely agree that those 2 cases should be separated. i personally fine with probabilistic guarantees for public chats. but for 1to1 and potentially group chats i want to have strict guarantee.

> what if this mailserver becomes unavailable mid-chat

sorry, i was thinking that any device can send an ack, but mail server acts as helper to synchronize the state of our conversation when we are not online simultaneously. 

> what if we have negotiated on the mailserver while we were both online, then I want to send a message when you are offline, but the mailserver is offline too?

i don't have an answer. but it should be definitely clear to a sender that message didn't reach the destination. 

> I can summarize the ideas from this thread and we can work on different ones separately.

i don't mean that we need refactor the way we are using mail server immediately. we can start fixing issues that are clear, like an absence of confirmations on devp2p or whisper level. but once we will start decentralizing out network, those issues will become less theoretical

**Comment by mandrigin** [comment]
@dshulyak yeah, it is obvious we need some kinds of acks.
Do you want to start working on implementing acks now? I can create a github issue then.

I'll try to coordinate the project in the meantime.

**Comment by dshulyak** [comment]
> @dshulyak yeah, it is obvious we need some kinds of acks.
Do you want to start working on implementing acks now? I can create a github issue then.

yes, i am looking how to introduce those on whisper level.

let me know if there are other ideas

**Comment by mandrigin** [comment]
@dshulyak I think that is a great starting point, I will make a separate github issue for that if you don't mind and let's keep this one for a "bigger picture".

**Comment by adambabik** [comment]
We can not rely only on our mail servers. Also, negotiating a mail server is not an option because one may go down in the middle of the conversation and then a new mail server must be negotiated but it's super complicated and still not perfect. Also, it means I need to trust the same mail server that my interlocutor which is not true.

I like the option with acks on Whisper level but please first write a draft how it will work and be implemented.

I think we can definitely implement checks when two parties are online. That should be fairly easy. Any checks in offline mode can be lost just like messages.

**Comment by mandrigin** [comment]
> I think we can definitely implement checks when two parties are online.

Which checks are you talking about here?

**Comment by dshulyak** [comment]
@adambabik 

> We can not rely only on our mail servers. Also, negotiating a mail server is not an option because one may go down in the middle of the conversation and then a new mail server must be negotiated but it's super complicated and still not perfect. Also, it means I need to trust the same mail server that my interlocutor which is not true

i feel like this is not what i was describing. and probably it is different from @mandrigin idea as well.
in my solution mail server was chosen by a user. but it is there only to speedup synchronization. so if we are communicating. you will send me an id that can sign a confirmation on your behalf. i will send you another id. it is true that they may go down, in such case message will be marked as not delivered until either that concrete mail server will be available again, or any of my devices will be available. how they will do it in briar?

what was proposed by @mandrigin is to wait for confirmations from any mail server in the network. it was described here https://github.com/status-im/status-go/issues/1278 .

**Comment by adambabik** [comment]
> so if we are communicating. you will send me an id that can sign a confirmation on your behalf. i will send you another id.

ID of what? Of mail server that will send confirmations that it stored my messages?

**Comment by dshulyak** [comment]
> ID of what? Of mail server that will send confirmations that it stored my messages?

by id i meant public key. doesn't have to be publicly known id of the mail server. you negotiate this id when you "pair" with mail server.

**Comment by adambabik** [comment]
> how they will do it in briar?

There was just a proposal for now but it looked like when I send a message and you are offline, my messages are sent to your second device. When you are back online, you sync with your second device first and then you should be able to continue conversation with the full history.

Is this flow the same what you propose?

**Comment by dshulyak** [comment]
> Is this flow the same what you propose?

exactly. but we do it over whisper, no direct communication. not sure if thats direct in briar, just mentioned that for clarity)

**Comment by adambabik** [comment]
Won't it introduce quite significant additional network load? Mail server will send an ack for every message? Can we make it work with https://github.com/status-im/status-go/issues/1276#issuecomment-439126115 with a difference that a mail server would need to be added as a peer for the whole period of time when one wants to send messages?

I don't know if briar uses anything other than direct p2p link.

**Comment by mandrigin** [comment]
@adambabik it depends how big the ACKs is, but since we have these special nodes to support offline messaging, only their ACKs make sense to track. No other node guarantees anything since the TTL that we use is so low.

**Comment by mandrigin** [comment]
and, again, to me reliable messaging > network load
If messaging doesn't work, I don't really care how much traffic is used by the chat application.

**Comment by dshulyak** [comment]
> Won't it introduce quite significant additional network load? Mail server will send an ack for every message? Can we make it work with #1276 (comment) with a difference that a mail server would need to be added as a peer for the whole period of time when one wants to send messages?

it won't increase it x10, but rather a x2-3, depends on the optimizations. i don't think that https://github.com/status-im/status-go/issues/1276#issuecomment-439126115 covers network partitioning, or provides any delivery guarantees to recipient. it only gives guarantee of a delivery to potentially closest peers, and we can do that using whisper acks.

> reliable messaging > network load

no doubt, but it cannot be growing uncontrollably

**Comment by adambabik** [comment]
@dshulyak hasn't this issue been solved after you introduced acknowledging?

**Comment by mandrigin** [comment]
there is one more bugfix we need to add to status-go (https://github.com/status-im/status-go/pull/1378) and then make a new release and update it in status-react. then we can close it.

**Comment by cammellos** [comment]
This has now been solved
