### ISSUE TITLE
Flaky TestGetFilterLogs

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1281]
# Problem
Test `TestGetFilterLogs` is flaky:

```
--- FAIL: TestGetFilterLogs (0.00s)
Error Trace: api_test.go:95
Error: "[map[fromBlock:0xa toBlock:latest address:[] topics:[]] map[fromBlock:0xa toBlock:latest address:[] topics:[]]]" should have 1 item(s), but has 2
```

# Acceptance Criteria

1. Race conditions and flakiness of `TestGetFilterLogs` is removed.

**Comment by dshulyak** [comment]
Yes, indeed it polls in the background. So it needs to be at least one
