### ISSUE TITLE
Provide information about selected mail servers to status-go

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1285]
# Problem

We need to have information about selected mail servers when [confirmation](https://github.com/status-im/status-go/issues/1278) is received.

Several alternatives:
- assume that we are always connected with a mail server from TrustedMailServers. This information already available in status-go configuration. But it doesn't include info about manually added mail servers. So we may get into inconsistent state, and never show a confirmation that message was delivered.
- implicitly use last mail server that was used for fetching history. it seems to provide consistent information, but may sound a bit hacky. one potential inconsistency would be if we send a message before sending a request for history
- explicitly get a selected list of mail servers from a user when application is started, or this list was changed

I would prefer the last one, but i've seen a couple of discussions how to handle mail servers connection better. This is definitely will have an impact on that so maybe we can have a discussion here.

# Implementation

Add a binding to status-go library: UseMailServers that accepts lists of enodes and returns error if one of those is not parseable.

The binding does 3 things:
- ensures that we are connected with one mail server from that list
- provides configuration for requesting history
- provides configuration to envelope tracker

History request will use any connected peer from that list, unless mailserverPeer argument is passed. if it is passed it will preserve current logic.

Envelope tracker will acknowledge an envelope if confirmation was received from any peer in the list.

# Acceptance Criteria

Each part should work correctly according to the logic described. And information about used mail servers should be consistent across different components.

cc @yenda @adambabik @mandrigin @cammellos @PombeirP

**Comment by dshulyak** [comment]
Trying to collected requirements for mail server connection management. Let me know if there is some conflicting work, so that i can adjust appropriately.

- App will provide client side load balancing. So that if one mail server is out of slots for new peers, or unreachable we swap it with another one. User should be able to select list of mail servers that he wants to use. If he haven't selected the list we assume that we can use all mail servers.
- App will try to maintain one connection all the time. Because of the reasons described in https://github.com/status-im/status-go/issues/1278.
- App will try to replace connected mail server if:
   - mail server is unreachable
   - disconnected our node
   - mail request expired
- App will stick with currently connected mail server across reboots
- App will provide next information to the user:
  - which mail server is connected
  - last reason of the disconnect for every mail server
  - when last query was made
  - request latency for every mail server
- App will recommend mail servers based on latency. For example by sorting them based on latency

**Comment by mandrigin** [comment]
No, I don't see any conflicting work there.
Btw, which parts will be implemented in what codebase?

**Comment by dshulyak** [comment]
@mandrigin i am thinking about adding all this logic to status-go, and status-react will only provide UI for this functions. what are your thoughts?

**Comment by mandrigin** [comment]
Make sense to me. Is that one a blocker to ACKs?

**Comment by dshulyak** [comment]
> Make sense to me. Is that one a blocker to ACKs?

definitely not, just a thing that would be nice to implement in future. technically nothing blocks ACKs, status-react already maintains connection with mail server. the main improvement here is a selection of many mail servers

**Comment by adambabik** [comment]
Do we already have some mechanisms to handle flaky/stale peers? We implemented flakiness detection but I don't remember if we actually do something with this knowledge. My point is that we could have some general flakiness detection logic (which is general for all types of peers) and some more specific one for mail servers.

I like this idea, it can definitely simplify the current situation when people changes mail servers manually because they suspect something is wrong.

While working on it, I think it would be beneficial to get rid of mailservers from status-react codebase.

**Comment by yenda** [comment]
> While working on it, I think it would be beneficial to get rid of mailservers from status-react codebase.

Totally the current situation of managing mailservers on status-react is far from ideal. It requires many round trips with status-go to get connected (addPeer, wait for peer summary update, markTrustedPeer, create sym-key),
Defining a simple API with connectMailserver(mailserverList) to connect to mailserver and a few signals mailserver.connected / mailserver.disconnected / mailserver.connecting would be more efficient.
