### ISSUE TITLE
Crash on logging in (fatal error: concurrent map writes)

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status-go#130]
### Summary
Status app was closed and almost immediately opened again. After Login app crashed. It happens from time to time but I can't provide specific steps that would always lead to the crash.

### Steps
- Open Status
- Add new contact with QR
- Open Discover tab
- Write some message to the unknown contact found in discover
- Close app
- Open app
- Login -> after typing a password and tap on Connect app crashed

OS: Android
Status version: 0.9.3-26-gb820e06+ 
http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-b820e0.apk

### Log
[crash on login 20172203152519-logcat.txt](https://github.com/status-im/status-go/files/861715/crash.on.login.20172203152519-logcat.txt)

**Comment by farazdagi** [comment]
- this issue occurs in Whisper ver.2 only
- so, this issue will be resolved when https://github.com/status-im/status-go/pull/129 is merged (that PR features transition to Whisper ver.5)
- regression test added (and Whisper ver.5 passes it w/o issues): https://github.com/status-im/status-go/pull/129/files#diff-ee4dca3ca47b80c97f2c95f1666ea273R12

**Comment by farazdagi** [comment]
- I've added regression test case, to make sure that issue is caught on Whisper/2, but not on Whisper/5
- Whisper/5 PR has been successfully merged, so it is safe to close this issue
- @annadanchenko should you spot this problem on Whisper/5 enabled app, please feel free to re-open the issue
