### ISSUE TITLE
Jail: integrate ottoext (event loop, timeout, fetch)

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#132]
- add support for `setTimeout()/setInterval()

**Notes:**
- particularly, we need this to be able to run [filter.watch()](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3shhfilter) inside the jail (which relies on `poll()`, which in turn uses `setTimeout()`)
- once updated, updates to `TestJailWhisper()` - all tests should run inside jailed environment (currently part of tests use Go directly)

**Implementation:**
- https://github.com/robertkrimen/natto/blob/master/natto.go
- also checkout `go-ethereum` JSRE (which is heavily based on natto code)
- we need to take into account that currently our jailed VMs are being cloned in https://github.com/status-im/status-go/blob/develop/geth/jail/jail.go#L127 (to be able to utilize global `message_id`), so event loop used for `setTimeout()` needs to be aware of possible VM cloning

**Comment by farazdagi** [comment]
**Jarrad:**
- another developer asking if they can do http requests
- https://github.com/deoxxa/ottoext

**Comment by jarradh** [comment]
Yup, Ideally we had persistent contexts and ability to do `fetch` and `setTimeout`

**Comment by ksjogo** [comment]
If I want to give that a whirl, `status-go/geth/jail/jail.go` is the right place? And `make test-jail` to execute tests?

**Comment by farazdagi** [comment]
- @ksjogo sounds great, please proceed (yep, `geth/jail` and `make test-jail` should get you started)
- however, allow me to wrap up major refactoring of the code https://github.com/status-im/status-go/pull/172 One of the purposes of this refactoring was to simplify and clean up the code, allowing for easier contribution.

This PR should be done today, I will ping you back immediately.

**Comment by ksjogo** [comment]
Ok, will wait for you ping.

**Comment by farazdagi** [comment]
@ksjogo The PR has been completed, once it is merged (normally it won't take long), you can start looking into `setTimeout()` (or you can base your work on top https://github.com/farazdagi/status-go/tree/feature/node-management-refactoring branch).

**Comment by ksjogo** [comment]
It's not great but a step: https://github.com/ksjogo/status-go/tree/feature/timeouts
Functions are available in the iOS simulator with a newly build framework but are not within the runloop yet. Eval context needs to be changed probably.

**Comment by farazdagi** [comment]
Thank you for starting on that. Later on today I will have an in-depth review of what you have so far.

**Comment by influx6** [comment]
Current question I have is what exactly is lacking in the provided `setTimeout/setInterval` provided by https://github.com/deoxxa/ottoext. Is there something special that ours must provide that defer from what ottotext provides.

@farazdagi Would appreciate the elaboration.
