### ISSUE TITLE
Makefile fails if GOPATH has multiple entries

### ISSUE THREAD

**Issue by 3ach** [status-im/status-go#1323]
# Problem
`make setup` fails if there are multiple entries in the GOPATH environment variable. 

# Implementation
Maybe the first entry in GOPATH should be used in the Makefile, this is the approach `go get` uses. 

# Acceptance Criteria
`status-go` can be built with multiple entries in the GOPATH

**Comment by adambabik** [comment]
@zachzundel how do such multiple entries look like? For example `GOPATH=/one/path:/second/path` etc?

**Comment by 3ach** [comment]
Yes

**Comment by adambabik** [comment]
Ok, all clear. Thanks for reporting this issue! I marked it with a label for people who would like to contribute to the project for better visibility.

**Comment by zeddee** [comment]
hey @zachzundel @adambabik,

I think I've fixed this in #1376 ? But just read CONTRIBUTE.md and closed it to comply with guidelines + goahead to work on this
