### ISSUE TITLE
Deploy docker image for status-go when doing a release

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1325]
# Problem

Currently, we have a Jenkins job that creates status-go releases but this job does not pushes a docker image to Docker Hub.

# Implementation

When doing a release of status-go using Jenkins, a docker image should be a part of the release.

# Acceptance Criteria

1. Releasing status-go creates and pushes a Docker image to [Docker Hub](https://hub.docker.com/r/statusteam/status-go). It should push it with a released version as a tag and update `deployed-tests` tag.

cc @jakubgs

**Comment by jakubgs** [comment]
Not stale, just forgot about it because it was not in the project.

**Comment by jakubgs** [comment]
I consider this done, the builds run here:
https://ci.status.im/job/status-go/job/platforms/job/docker/
