### ISSUE TITLE
whisper: historic messages

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#136]
- wnodes have been deployed on our cluster, so nothing stops us to request (using wnodes symmetric keys) archived messages
- start by reviewing commented out `RequestHistoricMessages()` in `whisper5/api.go`

**Comment by rgeraldes** [comment]
- RequestHistoricMessages method was obsoleted from whisper api (version > 1.59).
- from version > 1.59, shh.post supports direct p2p communication which allows us to request historic messages. (by adding a value to targetPeer)
- Necessary input for the message is a time range (lower value must be given by the notification) and topic of the messages that we should query from the mail server database.

**Comment by rgeraldes** [comment]
Part of #222

**Comment by rgeraldes** [comment]
As discussed, we will send the payload via push notification so this issue is no longer valid.
