### ISSUE TITLE
Different versions of nodes can not connect

### ISSUE THREAD

**Issue by edmundmiller** [status-im/status-go#1366]
fd949c5 broke our `status-go` node, and we were unable to connect until we upgraded to `.1`. 

Not sure if that's acceptable or not to the team, since you're in the middle of development, and updating the default mail servers yourselves, I just thought it might cause issues for community members in the future.

This is just an FYI in case you cared about backwards compatibility across recent versions.

**Comment by adambabik** [comment]
Hey @Emiller88. To clarify, you mean that it worked fine for `0.20.0-beta.0` and `0.20.0-beta.1` stopped working?

Also, when you say "connect" you mean connecting to one of our nodes in `eth.beta`?

**Comment by edmundmiller** [comment]
It still works on `.1` connecting to your group of nodes that are on `.1`. 

The `.0` version could not connect with the `.1` nodes/mailservers and retrieve messages.
