### ISSUE TITLE
Turn off Digital Ocean cluster

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#141]
- our bootstrap cluster (LES+SHH+Swarm, Faucet, Monitoring) has moved to Scaleway
- with 0.9.6 release it is safe to turn the previous cluster nodes off

**Comment by sla-shi** [comment]
@jarradh @carlbennetts @farazdagi please verify this has been turned off.

**Comment by tiabc** [comment]
Does somebody http://46.101.129.137:3001/faucet-info? It's still on DigitalOcean and will be inaccessible once we switch it off.

@rasom, what URLs from any status cluster does `status-react` use? I don't want to break anything.

**Comment by dshulyak** [comment]
@adambabik do you know any details about it?
