### ISSUE TITLE
Expose vanilla ECDSA signing

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1438]
# Problem

eth_sign signs a message constructed like this: `\x19Ethereum Signed Message:\n" + message.length + message`. Swarm feeds require to sign only the message. Since the private key is only known to status-go it needs to be done there and therefore exposed through IPC.

# Implementation

Expose call similar to `.signMessage` but with `message` only

# Acceptance Criteria

The signature produced is valid and allows to update swarm feeds.

# Notes

This will be used for tribute to talk

**Comment by adambabik** [comment]
To clarify, you need an option to construct a signature of `\x19Ethereum Signed Message:\n" + message`?

Is there already a swarm RPC method that allows that? If so, we can just overwrite it instead of creating a new one.

**Comment by yenda** [comment]
No that is what eth_sign does, here a simple ecdsa signature of `message` only is needed.
eth_sign is a rpc method, we also have `signMessage` exposed via IPC.

**Comment by yenda** [comment]
@adambabik there is a `Sign` function in `swarm/storage/sign.go` but is it simply calling the `crypto.Sign` method and it take a `GenericSigner`. `SignHash` from `accouts/keystore/keystore.go` seems like a better candidate to sign.

`Sign` from `api.go` does the following:

```golang
// Sign calculates an ECDSA signature for:
// keccack256("\x19Ethereum Signed Message:\n" + len(message) + message).
//
// Note, the produced signature conforms to the secp256k1 curve R, S and V values,
// where the V value will be 27 or 28 for legacy reasons.
//
// The account associated with addr must be unlocked.
//
// https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign
func (s *PublicTransactionPoolAPI) Sign(addr common.Address, data hexutil.Bytes) (hexutil.Bytes, error) {
	// Look up the wallet containing the requested signer
	account := accounts.Account{Address: addr}

	wallet, err := s.b.AccountManager().Find(account)
	if err != nil {
		return nil, err
	}
	// Sign the requested hash with the wallet
	signature, err := wallet.SignHash(account, signHash(data))
	if err == nil {
		signature[64] += 27 // Transform V from 0/1 to 27/28 according to the yellow paper
	}
	return signature, err
}
```

We need a function that doesn't call signHash on the data. This function would only be used internally for signing swarm updates. If that doesn't sound like a good idea then we could investigate a solution that would expose a `getSignedDigest` function that computes the digest for the swarm feed update and returns the signature of this digest directly. Currently I compute and hash the digest on react side.

**Comment by gravityblast** [comment]
remember that signMessage adds a prefix so that even if you pass the hash of a valid transaction, it doesn't produce a valid transaction signature. so for security reasons this function must not be exposed.

**Comment by yenda** [comment]
@gravityblast yes but that is for rpc exposed methods like `eth_sign` and `eth_personalSign`. In this case it would be only exposed through IPC and o ly used by the app internally to sign the digests of swarm feeds updates.

**Comment by yenda** [comment]
Otherwise I would propose a `signSwarmRequest` which would take a json of parameters to construct the digest, sign it and return the  signature, but I am confused by the go code to get the digest.

This is how a signature is computed: https://swarm-guide.readthedocs.io/en/latest/usage.html#computing-feed-signatures and this is the getDigest function https://github.com/ethereum/go-ethereum/blob/master/swarm/storage/feed/request.go#L138

**Comment by adambabik** [comment]
If you have already access to the request and data and can get the digest, we should only expose a binding to sign it. 

However, it would be great to describe the whole story. After looking at https://swarm-guide.readthedocs.io/en/latest/usage.html I assume you want to post to a feed and it requires a signature. How do you communicate with the swarm? Through some HTTP gateway? 

## Proposed solution

Expose a binding called `SignHash` which will take a hash (hex-encoded) and password and will output a signature hex-encoded.

**Comment by yenda** [comment]
@adambabik I am fine with this solution, however I would prefer if the password wasn't required, as in  `eth_sign` rpc method which doesn't require password if the account is already unlocked, to simplify user experience

**Comment by adambabik** [comment]
@yenda we do require password for other sign-related bindings. I think it's another security layer which would prevent someone from sending a transaction/signing a message if they get to your phone and it's unlocked. 

However, if what you want to do is more like a sending a message and passing a password each time is very inconvenient, we can remove this requirement. Also, should it be signed with a wallet key or chat key?

**Comment by yenda** [comment]
@adambabik in this case asking for a password will be inconvenient but security wise you wont be able to sign an arbitrary transaction because it will only be used to sign internally and won't be exposed to users or applications.

Right now the wallet key and chat key are the same afaik? But in the future it should be signed with the chat key, because the swarm feeds are linked to an ethereum address, and the ethereum address of a user is derived from his public key, even if in the future this ethereum address won't be the actual one used for the wallet.

**Comment by adambabik** [comment]
> but security wise you wont be able to sign an arbitrary transaction because it will only be used to sign internally and won't be exposed to users or applications.

Right so it's the same as with other sign-related binding. My point was that it does not protect when one gets access to the phone and the app which is unlocked. But as it is signing related to the chat, we don't need user's password.

Ok, so the chat key it is. They are the same but we already have the interface prepared to use wallet or chat key so we needed to clarify this before implementing. 

## Updated solution
Expose a binding called `SignHash` which will take a hash (hex-encoded) and will output a hex-encoded signature of this hash. It should be signed with the chat key.

**Comment by mandrigin** [comment]
@adambabik are you planning to work on it or should I take it over?

**Comment by mandrigin** [comment]
Okay, I will start working on that now then.

**Comment by mandrigin** [comment]
@yenda @gravityblast can you take a look at https://github.com/status-im/status-go/pull/1444? is that what you wanted there?

**Comment by yenda** [comment]
@mandrigin Thank you it looks like it!
