### ISSUE TITLE
multi-account support from main HD Wallet (GO)

### ISSUE THREAD

**Issue by gravityblast** [status-im/status-go#1479]
# Problem
We want to have multi-account support (multiple ethereum accounts for each user),
and custom derivation paths for HD Wallets (another issue willll be opened for imported accounts).

Each user has accounts derived from the main HD Wallet + imported accounts.
The main HD wallet is the one defined by the generated/imported mnemonic phrase.

From the main HD Wallet we can derive and save extended keys that we can use to derive other
accounts without the need to store the master key.

When users generate or import a HD Wallet, we want to store one or many root extended keys,
used to derive child keys.

## Example

* The user opens Status for the first time
* A master key is generated and kept in memory in status-go
* status-react requests a list of n addresses derived from the BIP44 parent key (m/44'/60'/0'/0), or any custom path.
* status-go returns a list of addresses so that status-react can show them to the user
* status-react tells status-go to save a list of keys:
  * the BIP44 parent key (m/44'/60'/0'/0)
  * the first BIP44 account (m/44'/60'/0'/0/0)
  * other BIP44 keys if needed
* status-go saves the requested keys and remove the master key from memory
* later status-react can call status-go to unlock the BIP44 parent key and derive other BIP44 accounts

# Definitions
**Extended key**: a private key together with its chain code. As described in the BIP32,
an extended key can be used to derive child keys (with their own chain code).

**Normal key**: a private key without a chain code. A normal key cannot derive BIP32 child keys.

# Implementation
The current implementation has 1 keystore json file for each user.
Each keystore file is encrypted with the user's password.
The standard json keystore file has only one normal key.
Our implementation extends that format to have two keys:

* the standard normal key (that we derive with m/44'/60'/0'/0/0)
 This key is currently used for wallet and chat.
* an extended key (that we currently derive with m/44'/60'/0'/0/1)
 The initial idea of this key was to use it to derive sub-accounts.

My proposal is to keep only one key for each keystore file.
We can still have the two "extended key" and "key" fields,
but they are basically the same key.
Key is the normal key of the keystore file.
ExtendedKey is the same key with its chain code, so it allows to derive child keys.
ExtendedKey can be empty if a user imports a normal key.

When a user creates the first account status-react can asks status-go to save 4 keystore files:

* m/44'/60'/0'/0/0
 The first wallet key.
* m/44'/60'/0'/0
 The BIP44 parent key. This key allows deriving other wallet accounts.
* m/43'/60'/1581'/0'/0'
 Whisper key
* m/43'/60'/1581'/0'
 Whisper parent key. This key allows deriving other chat keys

The master key is never saved. So other subtrees are not available for future use, unless the user regenerate the master key importing the mnemonic phrase.

When we create a new random account we generate a new extended master key,
so we can derive any key, and any extended child key can derive again other keys and so on.
The same thing applies if the user is recovering an account or importing one with the mnemonic phrase.

The same process can be used for custom derivation.
status-react will pass another root path instead of the standard BIP44 path.

Importing raw private keys or standard keystore json file will create only normal keys,
not extended keys, so it won't be possible to derive child keys from those accounts.

The 4 keystore files above will be encrypted with the same user's password.
In the future we could allow having different passwords for some accounts for the same user.
status-react can save a reference to the first account and try to unlock it
every time a password is needed. So that it can verify the password before storing/encrypting a new account.

status-react needs to keep a mapping of all the created accounts by address for each user. (maybe it’s already partially implemented like this).
Example (pseudo code and names just for reference):

```
{
user1 => {
address1 => {
origin: mainHDWallet, // it will be recovered with the mnemonic phrase
type: extendedKey,
path: "m/44'/60'/0'/0"
// BIP44 accounts parent. can be instantiated to derive other child keys
},
address2 => {
origin: mainHDWallet, // it will be recovered with the mnemonic phrase
type: extendedKey,
path: "m/44'/60'/0'/0/0"
// BIP44 accounts 0. can derive child keys
// but normally we don't want to derive child keys from BIP44 accounts.
// An advance user can anyway use it to derive child keys.
},
address3 => {
origin: mainHDWallet, // it will be recovered with the mnemonic phrase
type: extendedKey,
path: "m/1’/2’/3" // custom path. It can derive child keys
},
address4 => {
origin: imported, // from raw private key or keystore json file. it won't be recovered with the mnemonic phrase
type: normalKey,
path: unknown,
// it cannot be used to derive keys
},
user2 => {
...
},
...
}
```

Each one of the 4 keys has an address.
Every time status-react needs to use of the the keys it will refer to them by address and password to unlock them.

status-go will export 2 groups of functions

1 - Import Account (for normal keys):
 1a. import raw private key
 1b. import keystore json file

Both 1a and 1b will generate normal keys, it will not be possible to derive keys. It will only be possible to encrypt and store them.

2 - Create account from extended key:
 1a. New - it instantiates a new random extended master key (used for the first account)
 1b. From mnemonic - it instantiates an extended master key from the mnemonic phrase (used to recover and to add accounts from a different mnemonic).
 1c. From existing key already stored - it will unlock an existing keystore file (imported or created previously)
 and instantiates the extended key store inside.
 If the selected keystore contains only a normal key it will return an error.

These 3 steps will instantiate an ExtendedKey in memory.
It will be a master key for 1a and 1b, or another extended key for 1c.
At this point status-react can:

* ask for n addresses from a specific root path (relative to the instantiated key).
for example with n=3 and path=m/44'/60'/0'/0 it will return the addresses for these accounts:

```
m/44'/60'/0'/0/0
m/44'/60'/0'/0/1
m/44'/60'/0'/0/2
```

This allows status-react to show addresses to the user before storing the key.

* store 1 or multiple keys specifying a specific path. For example, if the master key is instantiated:
* Store(m/44'/60'/0'/0) - this will allow status-react to save a reference to
the BIP44 root to be able to instantiate it in the future to
derive other child keys
* Store(m/44'/60'/0'/0/i) - store the BIP44 account at index i, to be used as a normal wallet key.

**Comment by gravityblast** [comment]
@guylouis  @flexsurfer  @yenda 
I imported the description from the document we shared the other day and I added some more comments

**Comment by corpetty** [comment]
how much extra work is it to store in secure hardware of device, if available (like we do for the password, paging @mandrigin for this)?  If we're fiddling with this, putting in a more secure environment (when available) is optimal.  

As for implementation, first blush looks like this covers all the use cases of the miro diagram without changing any security of the app as it is now.  I will go a bit deeper tomorrow after morning calls to try and find any issues.

**Comment by guylouis** [comment]
@yenda suggested in status channels that status-go handles the list of accounts. Did you re-discuss that and came to a conclusion on what we should do ?

**Comment by gravityblast** [comment]
> @yenda suggested in status channels that status-go handles the list of accounts. Did you re-discuss that and came to a conclusion on what we should do ?

@guylouis when a user logs in, status-react sends username/password using address and the user's password. so status-react already knows about the address associated to the user, and it needs to know about it. with multi-account it needs to know all the addresses to give the user the ability to unlock any key to use it or to derive other keys. does it make sense? /cc @yenda  

Also because there's no db used here, status-go is just trying to unlock keys from a folder.

**Comment by gravityblast** [comment]
>how much extra work is it to store in secure hardware of device, if available (like we do for the password, paging @mandrigin for this)? If we're fiddling with this, putting in a more secure environment (when available) is optimal.

I'm not sure about it. I think access to specific phone's API is not available from status-go, so probably we would need to change a lot of things. @mandrigin do you know more about it maybe?

>As for implementation, first blush looks like this covers all the use cases of the miro diagram without changing any security of the app as it is now. I will go a bit deeper tomorrow after morning calls to try and find any issues.

The main change in security here is that in the current implementation, the master key is not kept in memory. It's generated, used to derive a key to store, and removed.
In this new implementation we need to keep it in memory until status-react asks for something, so it means we need to be sure it's removed in any possible case

**Comment by 0xc1c4da** [comment]
➤ Wrike Bot commented:

Eric DAndrea Franz All the necessary task dependencies have been completed, so you can start working on it right away.

**Comment by 0xc1c4da** [comment]
➤ Guy-Louis Grau commented:

now that we added effort estimation, and since this is a GO development I removed Eric+Andrey from owners, because the work will be done by Andrea
