### ISSUE TITLE
validate JSON configuration

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#149]
- expose JSON config validation method
- only basic validation at this time i.e. load the JSON into config (make sure it is loadable in principle), then some minor sanity checks (to see if config *looks like* it can be run on mainnet, ropsten, rinkeby)

**Comment by adambabik** [comment]
Hey @tiabc @rasom, I have a few questions:
1. `NodeConfig` has a few fields with other configs like `WhisperConfig`, `SwarmConfig` etc. Do we want to validate them as well or here we just focus on `NodeConfig`? 
2. Do you have a list of fields that definitely should be validated? If not I will walk through all fields and validate these that can be validated.

**Comment by tiabc** [comment]
1. Yes, all of them should be validated.
2. Please, look through every field.

The point here is that users can manually edit configuration and we should ensure that it looks like valid configuration.

**Comment by tiabc** [comment]
@rasom:
> so in overall, what we need from status-go side: we want to be sure that when user passes some configuration (arbitrary, imagine that user will have control over all parameters) that configuration will be validated before applying and the next problems should be detected:
> 1) absence of required parameters
> 2) wrong types (bool instead of string, etc)
> 3) wrong parameters (keys)
> 4) wrong parameters values (like we have some enum for NetworkId, and user passes wrong value or so)
> 5) whatever else that makes sense, like detecting of mutually exclusive parameters (if such exist)

**Comment by tiabc** [comment]
Thanks, @adambabik, clean execution!
