### ISSUE TITLE
Syncing mailservers needs some love

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1496]
# Problem

- [x] in the README.md there is no mention of `Limit` in the request
- [x] there is no error passing from mailserver (https://github.com/status-im/whisper/pull/29)
- [x] unknown behaviour if `Limit` is `0` (https://github.com/status-im/whisper/pull/29)
- [x] syncing envelopes does not follow cursor. We need an option which will follow the cursor. This is needed to sync long periods of time

cc @annadanchenko @jakubgs

**Comment by jakubgs** [comment]
Definitely true. I wasn't able to use the instructions because I as getting errors like:
```
The method shh_markTrustedPeer does not exist/is not available
```
Or
```
Could not find peer with ID: abc
```

**Comment by adambabik** [comment]
The first one is strange. I tested `mail-01.do-ams3.eth.test` and didn't have this problem even once.

The second one can be due to various reasons when a peer can not be added. Another node might have a max number of peers already or the one that tries to connect is blacklisted (this can happen if you request to sync too many messages so with no or very large limit).

What should work fine is when the limit is set to a safe number like `500` and the requests are sequential with the cursor value from the responses of syncing progress.
