### ISSUE TITLE
Peer marked with shh_markTrustedPeer does not appear as trusted

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#1513]
If I add a peer with `admin_addPeer`, and then I call `shh_markTrustedPeer` for it to mark it as trusted, and call `admin_peers` to check its status it does not appear as trusted:

```
$ curl -s localhost:8545/ -XPOST -H 'content-type:application/json' -d '{"jsonrpc":"2.0","method":"admin_peers","id":74}'
...

... {
"enode": "enode://531e252ec966b7e83f5538c19bf1cde7381cc7949026a6e499b6e998e695751aadf26d4c98d5a4eabfb7cefd31c3c88d600a775f14ed5781520a88ecd25da3c6@35.225.227.79:443",
"id": "4cf1de823dfbc51ed0deaf629e2b319f5908bb641d20d0083884115c65f68c82",
"name": "Statusd/v0.25.0-beta.0/linux-amd64/go1.10.8",
"caps": [
"shh/6"
],
"network": {
"localAddress": "172.18.0.2:37484",
"remoteAddress": "35.225.227.79:443",
"inbound": false,
"trusted": false,
"static": true
},
"protocols": {
"shh": "unknown"
}
},
```

My understanding is that the peers `trusted` status is different from a peers whisper `trusted` status, is that correct?

If so, can I look up peers whisper `trusted` status with some call?

**Comment by cammellos** [comment]
Closing for now, this should be working as we use it in the app, feel free to re-open if still an issue
