### ISSUE TITLE
Contacts service api

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1531]
# Problem

As part of the Essential for security scope of realm migrations, contacts need to be migrated to status-go

# Implementation

**table contact**

not sure which field is best to use as id, probably public-key but it is worth noting that in the future a contact might have multiple public-keys

- address          {:type :string :optional true} indexed
- name             {:type :string :optional true}
- photo-path       {:type :string :optional true}
- last-updated     {:type :int :default 0}
- public-key       :string indexed

These two are tricky as they need to be queried for instance for blocked users:

- tags             {:type "string[]"}
- system-tags      {:type "string[]"}

it could be achieved either using a tag table or using a text field but saving fields that need to be queried apart (like blocked as boolean)

**table contact-device-info**

There can be multiple contact device info per contact
- id :string
- timestamp :int
- fcm-token :string

**api**

- contacts_getContacts
return an array of contacts
should return tags and system tags as arrays of string
should return contact-device-info as array of maps in the "device-info" key

- contacts_saveContact
return an array of contacts
takes tags and system tags as arrays of string
takes contact-device-info as array of maps in the "device-info" key

**Comment by cammellos** [comment]
We are planning to add this to `status-protocol-go` which is currently being integrated https://github.com/status-im/status-protocol-go/issues/10 https://github.com/status-im/status-go/pull/1526 , so if you don't mind I would hold off for now. We could instead focus on `accounts` as that is not to be added to `status-protocol-go` but to `status-go`

**Comment by yenda** [comment]
@camellos Ok great
