### ISSUE TITLE
Remove onbarding code

### ISSUE THREAD

**Issue by gravityblast** [status-im/status-go#1538]
# Problem

After merging #1500 , `account/onboarding.go` and the onboarding references in lib/mobile and `api/backend.go` are not used anymore.
We can remove all that code.

**Comment by saratsista** [comment]
@gravityblast Can I take up this issue to work on it?

**Comment by saratsista** [comment]
> @gravityblast Can I take up this issue to work on it?

Sorry, just saw that you self-assigned this.
