### ISSUE TITLE
history-index is not returned by browser service

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1544]
# Problem

history-index key is not returned by browser service when calling `browsers_getBrowsers`

# Acceptance Criteria

history-index key is returned as well

**Comment by yenda** [comment]
My understanding is that `omitempty` considers 0 to be empty, so history-index is not returned when the index is 0. Taking this into consideration I made a fix on status-react side which considers history-index to be 0 if there is none, so this is very low priority.

**Comment by dshulyak** [comment]
@yenda yes. i realized that it will be omitted when you opened an issue. easy fix so i will push it
