### ISSUE TITLE
.recoverAccount returns same keys for root, chat and wallet accounts

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1549]
# Problem

.recoverAccount returns same keys for root, chat and wallet accounts

# Implementation

all keys should be different

**Comment by dshulyak** [comment]
@flexsurfer do you know why @gravityblast wanted to remove that function https://github.com/status-im/status-go/issues/1539 ? Maybe there is a replacement?

**Comment by flexsurfer** [comment]
@dshulyak maybe, couldxa

**Comment by flexsurfer** [comment]
@dshulyak where can i see all methods available for status-react ?

**Comment by flexsurfer** [comment]
found this https://github.com/status-im/status-go/pull/1542/files#diff-e7036f52b1c1b5c00044217cb550d29eR133 would be nice to have `MultiAccountImportMnemonicAndDerive` similar to `MultiAccountGenerateAndDeriveAddresses`

**Comment by dshulyak** [comment]
As far as i can tell all methods related to multiaccounts are in this file https://github.com/status-im/status-go/blob/develop/mobile/multiaccount.go

**Comment by flexsurfer** [comment]
i don't want to block you by my PR , let's merge it as is and implement `MultiAccountImportMnemonicAndDerive` in separate PR

**Comment by dshulyak** [comment]
@gravityblast can you take a look please?
