### ISSUE TITLE
Sub-cluster in Hong Kong

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#155]
- we need sub-cluster deployed in Hong Kong (it is harder to do so in mainland China)
- sub-cluster will have:
  - LES, SHH/5
  - Faucet

**Comment by farazdagi** [comment]
- Jarrad,  I need hosting provider login details where you want this sub-cluster deployed.
- AWS seem to have Beijing DC (acc. to https://aws.amazon.com/about-aws/global-infrastructure/)
- RackSpace has Hong Kong DC (https://www.rackspace.com/about/datacenters)

**Comment by jarradh** [comment]
i tested the node ips they don't seem to be blocked and I ran out of time to follow up on this, will confirm once in China
