### ISSUE TITLE
Upgrade Whisper when the fixed PoW is merged into our fork

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1556]
# Problem

In geth 1.9.0, calculation of the PoW algorithm was changed. More https://github.com/status-im/whisper/issues/30.

# Implementation

This issue is just about using a new version of our fork when ready.

# Acceptance Criteria

Old clients using the older status-go as well as these using the updated PoW version need to be able to communicate.

**Comment by oskarth** [comment]
> Old clients using the older status-go as well as these using the updated PoW version need to be able to communicate.

It's not a immediately obvious (not documented) how this would be received, more details would be useful. This is also seems to break from geth solution, as they broke compatibility (something we also have/had a chance to do for v1).

1. Old send -> Old receive OK
2. New send -> new receive OK

3. Old send -> New receive
4. New send -> old receive

This should be documented in specs as well

**Comment by adambabik** [comment]
We are on geth 1.9.5 and it was handled during the upgrade.
