### ISSUE TITLE
Expose messages API

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1560]
# Problem

We move messages storage from status-react to status-protocol-go in https://github.com/status-im/status-protocol-go/pull/42. After it's moved, we need an API to get into it from status-react.

# Implementation

Create a new API endpoints to manages messages in `shhext` namespace.

# Acceptance Criteria

* Expose all methods from `Messenger` from status-protocol-go here.

**Comment by cammellos** [comment]
this has now been merged, closing
