### ISSUE TITLE
Share the database with Messenger from status-protocol-go

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1562]
# Problem

We have at least three sqlite databases being opened when the app starts:
- db for browsers
- db for permissions
- db for wallet.

Each separate encrypted sqlite database file requires non-trivial amount of time to be opened. This slows down the startup of the application.

# Implementation

1. Open a single encrypted sqlite database file which will be shared between various services and libraries.
2. Collect migrations in one place similarly to https://github.com/status-im/status-protocol-go/blob/master/migrations.go and apply in one go before the app passes the initial setup. This is to detect any problems early.

Because there is no separation of database files between individual components, there is still a threat that two components define tables with the same names. This can be mitigated to some extent by always applying all migrations for unit and integration tests of the components or at least for an object managing the state of a component.

Another problem is a table storing the migrations metadata. By default, [`schema_migrations`](https://github.com/status-im/migrate/blob/master/database/sqlite3/sqlite3.go#L21) is used. However, when a single database is shared between different libraries, like in our case where a single database is shared between status-go and status-protocol-go, each library should use a different migrations table to avoid conflicts.

# Acceptance Criteria

* A single database instance and database file is shared between status-go services and status-protocol-go library.
* Migrations are properly applied in status-go services as well as in libraries using custom migrations tables to avoid conflicts.
* status-go individual components do not open a database. They receive a `*sql.DB` instance only.
* All unit and integrations tests relying on a database should use one with all migrations from a given library applied.

cc @dshulyak @cammellos

**Comment by dshulyak** [comment]
Well this is a duplicate. There is this issue https://github.com/status-im/status-go/issues/1536 which is closed by https://github.com/status-im/status-go/pull/1540. I am just waiting for Eric to merge integrate main part

**Comment by dshulyak** [comment]
Also wallet is not straightforward to merge with others. Cause there is network specific information. So this needs to be solved https://github.com/status-im/status-go/issues/1537

**Comment by adambabik** [comment]
@dshulyak I was not aware of that PR. It looks good but there are a few things missing described in this issue:
- no custom name for the migrations table,
- `Messenger` from status-protocol-go also needs to share this instance.

**Comment by dshulyak** [comment]
you are right those things are not in the pr

**Comment by adambabik** [comment]
That's cool, though. We can do it in a separate one, it makes more sense and provides better visibility.
