### ISSUE TITLE
Wallet should be tracking accounts created after login

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1566]
# Problem

Any account that is created after user logged in won't be tracked by a wallet service. Currently list of accounts is passed when user logs in and after that there is no way to add more accounts to a wallet service.

# Implementation

Once https://github.com/status-im/status-go/pull/1530 is merged we will have a service with an rpc method `accounts_saveAccounts`. When it is called we must notify wallet service. Wallet will check for any new accounts and restart wallet.Reactor with new list of accounts. Note that we don't watch every account separately so whole reactor needs to be restarted.

Adding new account to wallet service shouldn't block `accounts_saveAccounts` method. There should be a simple component in wallet service that manages reactor updates and provides a communication channel to other services. Accounts can be passed either using a channel to a service or triggering a channel after accounts stored in db.

# Acceptance Criteria

New accounts can be added to a wallet tracker after user logged in.

@flexsurfer does it sound fine to you if we will use accounts_saveAccounts to start listening for new addresses in the wallet?

**Comment by flexsurfer** [comment]
yes sounds fine for me, thanks!

**Comment by gravityblast** [comment]
we should also add the new accounts to the account `watchAddresses` so that they are valid addresses that can be used to sign transactions.

**Comment by flexsurfer** [comment]
we've discussed this with @dshulyak and decided we don't need `watchAddresses`, why do we need them @gravityblast ?

**Comment by dshulyak** [comment]
i think they were added before we had accounts database in status-go. now we can watch every address that is added to that accounts database. maybe we can pass a database to accounts manager now and it will use it for such information?

**Comment by gravityblast** [comment]
yes it's correct, it was needed before the new work on the database. yes we can pass the db to the manager.
