### ISSUE TITLE
Сan't send funds from added account

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1575]
see https://github.com/status-im/status-react/issues/8759

**Comment by flexsurfer** [comment]
maybe related to https://github.com/status-im/status-go/issues/1566

**Comment by dshulyak** [comment]
That's unlikely, sending transactions are not coupled with wallet service.

**Comment by flexsurfer** [comment]
@gravityblast why can't we sign transaction for address we have a saved key for?

**Comment by gravityblast** [comment]
@flexsurfer it comes from the old code for "single" accounts. You could only sign with your current key.
We can change it but it means you could be able to sign a tx with another user's account. 
But this requires you to know both the address and the password of the other user's account, so at that point you could just login as the other user. I think we can remove this check, what do you think @flexsurfer @dshulyak ?

**Comment by yenda** [comment]
@gravityblast @dshulyak can't you just change the check so that it verifies that the sender is one of the wallet accounts owned by the multiaccount

**Comment by gravityblast** [comment]
@yenda yes it makes sense, I think @dshulyak was already passing the db to the account manager to be able to do that right? I'm ooo so it might be good if we open an issue

**Comment by dshulyak** [comment]
this is where we do this check https://github.com/status-im/status-go/blob/develop/api/backend.go#L562-L579, right? if so we don't even need to pass database. just need to be sure that it was already opened at the time of the check

**Comment by gravityblast** [comment]
@dshulyak yes exactly!
