### ISSUE TITLE
LoginWithKeycard should start node

### ISSUE THREAD

**Issue by dmitryn** [status-im/status-go#1576]
# Problem

`LoginWithKeycard` now results in `{\"error\":\"there is no running node\"}`

# Implementation

Start the node like during `Login` call https://github.com/status-im/status-go/blob/be9c55bc16ca035ca9bfc0586b6c9298a91bdcd4/lib/library.go#L356

**Comment by dshulyak** [comment]
So instead of loading this data from database https://github.com/status-im/status-go/blob/develop/api/backend.go#L203-L215 we will start a node with accounts that are based on a key that is passed to LoginWithKeycard?

**Comment by dmitryn** [comment]
@dshulyak i think so, but i'm not the author of previous implementation. @gravityblast what do you think?

**Comment by gravityblast** [comment]
> So instead of loading this data from database https://github.com/status-im/status-go/blob/develop/api/backend.go#L203-L215 we will start a node with accounts that are based on a key that is passed to LoginWithKeycard?

@dshulyak yes it's correct, the whisper key is not stored in the phone but passed from the card. the wallet key stays on the card, but we could store the address so that we don't need to pass it all the time. then we have the other watch addresses as usual.

**Comment by dshulyak** [comment]
i am not totally sure how it suppose to work, application currently needs next information to login:
- multi-account
- password
- wallet address and watch addresses
- chat key

are you going to pass all of it to me? can i assume that wallet address and watch address can be derived from chat key?

also node configuration needs to be known in advance, how it will be passed?

**Comment by dmitryn** [comment]
>multi-account
password
wallet address and watch addresses
chat key

@dshulyak we can pass that information. Not sure about node configuration, how does it work in regular login? I suppose we can do the same.
