### ISSUE TITLE
Signal needed when login fails

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1583]
# Problem

When the user inputs the wrong password, status-go doesn't inform status-react and status-react hangs https://github.com/status-im/status-react/issues/8829

# Implementation

We need a signal from status-go that login failed

Currently I see this in the logs:
```
08-24 04:03:10.191 17362 17408 D StatusModule: clearStorageAPIs
08-24 04:03:10.209 17362 17408 D StatusModule: login
08-24 04:03:10.251 17362 17408 D StatusModule: Login result: {"error":""}
08-24 04:03:10.325 17362 17413 E GoLog   : ERROR[08-24|02:03:10.322] failed to start a node                   address=0xc91f5F264Ab6472cB88c79e533d278792Df61b19 error="file is encrypted or is not a database"
```

# Acceptance Criteria

I would propose that "node.login" signal is replaced by "login.success" and "login.failed" but I am open to suggestions

**Comment by rachelhamlin** [comment]
@yenda this a v1 blocker? anyone aware of it? @cammellos @dshulyak

**Comment by cammellos** [comment]
This looks like a v1 blocker, yes

**Comment by dshulyak** [comment]
@yenda does it matter if instead existing signal will be extended with error? e.g. node login will be sent always, but if failed - body will have field with non-empty error

**Comment by yenda** [comment]
no it doesn't matter but login should be completely aborted if it fails (no half started node)

**Comment by dshulyak** [comment]
@yenda i won't be able to finish this. i will try to merge my pending PRs today

**Comment by cammellos** [comment]
@yenda 

```
Signal event: {"type":"node.login","event":{"error":"file is not a database"}
```

I have added an error field to `node.login`, let me know if that works for you. 

Here's the PR for testing https://github.com/status-im/status-go/pull/1594
