### ISSUE TITLE
Revert temporary fix for gomobile 

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#1588]
# Problem

Revert https://github.com/status-im/status-go/pull/1585/commits/29e45b3615a85aafb01b4cf8108a1692836828a5 once a fix will merged to gomobile master branch

gomobile issue: https://github.com/golang/go/issues/33859

**Comment by adambabik** [comment]
This is done in https://github.com/status-im/status-go/commit/3dbcb6a19e0595c2640f53c5fc53b866cb28e620.
