### ISSUE TITLE
Faucet: deploy for Rinkeby

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#161]
- after https://github.com/status-im/status-go/issues/159
- basically, we need to deploy a node with systemd unit file which executes `statusd --bootcluster rinkeby.dev.json faucet` command

NB: in PR mention http://faucet.statusd.im

**Comment by influx6** [comment]
I have the initial systemd files for rinkey in commit b0dab806fadd4c396a7bae853837928503e1807b. But testing in a docker container is not possible, found out too late, will get a linux vm running on my mac to validate that they do work.

Am not sure we want `start` and `stop` option, so for now, it will simply boot up `statusd` as a solo command.

**Comment by tiabc** [comment]
Closing as the description has changed. See #383 for details.
