### ISSUE TITLE
Sync `lib/library.go` and `mobile/status.go`

### ISSUE THREAD

**Issue by vkjr** [status-im/status-go#1624]
# Problem

Interface in `lib/library.go` is inconsistent with `mobile/status.go`. `LoginWithKeycard` function has incorrect amount of arguments, `SaveAccountAndLoginWithKeycard` not implemented. 
That impacts desktop builds and doesn't allow to synchronize `react-native-status` for mobile and desktop platforms.

# Implementation
Fix `lib/library.go`

# Notes
This issue impacts https://github.com/status-im/status-react/pull/8630

**Comment by cammellos** [comment]
this has been done
