### ISSUE TITLE
Save (Multi?)Account call

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#1634]
# Problem

https://github.com/status-im/status-react/issues/8812

As a user I need to be able to change the username and profile picture in the multiaccounts db so that when I open the app, I see my ens name and profile picture in the list of multiaccounts if I have set them.

# Implementation

This means that status-react need to be able to save these fields in the multiaccounts db through a direct or rpc call. Currently these are set only once when account is created with `saveAccountAndLogin`

# Acceptance Criteria

saveAccount native call allows user to change the account values ONLY when he's logged in and ONLY name and picture.

**Comment by yenda** [comment]
To answer the question from @flexsurfer in the title, yes it is multiaccount but status-go did not update the naming policy as of yet (probably should at some point)

**Comment by cammellos** [comment]
@yenda what about `multiaccounts_updateAccount`? https://github.com/status-im/status-go/blob/019f124f6b0cbd40ecb58081105828fdf12f653c/services/accounts/multiaccounts.go#L25 
and 

https://github.com/status-im/status-go/blob/019f124f6b0cbd40ecb58081105828fdf12f653c/multiaccounts/database.go#L66

It takes and account with:

`name, photoPath, keycardPairing, keycardKeyUid and address` and updates them, checking `address` is the selected account.

Let me know if it will do.

**Comment by cammellos** [comment]
@yenda ping

**Comment by yenda** [comment]
@cammellos yes it should do it, the status-react issue is a bounty now, leaving it to @tbenr

**Comment by cammellos** [comment]
Thanks, will close this one then.
