### ISSUE TITLE
Geth 1.6.2 cannot decode Whispersv5 envelopes sent by status-go

### ISSUE THREAD

**Issue by nnicksize** [status-im/status-go#164]
**geth version**
```
Geth
Version: 1.6.2-unstable
Git Commit: 10cd54e92464ed8bb77b2e8e8dfb62fe91353ce9
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: windows
```

**status-go version**
2f0c93f (refactor: linters + recommendations applied, closes #146 )

**Problem 1**
The interface to call shh.post is different in status-go than in geth.
The next line works when geth is attached to a node running geth, but results in the below error when geth is attached to a node running status-go.
```
shh.post({type: 'sym', ttl: 20, topic: topic, powTarget: 2.5, powTime: 8, payload: payload, key: key});
Error: invalid argument 0: cannot unmarshal non-string as hex data
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at <anonymous>:1:1
```
The following works when geth is attached to a node running status-go.
```
shh.post({type: 'sym', ttl: "0x20", topic: topic, powTarget: "2.5", powTime: "0x8", payload: payload, key: key});
null
```

**Problem 2**
The geth node reports the following error when receiving the Whisperv5 message sent by status-go.
```
WARN [05-15|20:09:58] failed to decode envelope, peer will be disconnected peer=19f1f6e822ad0416 err="invalid message: (code 1) (size 835) rlp: expected input string or byte for []uint8, decoding into (whisperv5.Envelope)(whisperv5.rlpenv).Version"
```

**Comment by farazdagi** [comment]
Thanks for elaboration!

I will look into the issue within a session: will update our `go-ethereum` deps to 1.6.1, and revisit the https://github.com/status-im/status-go/pull/163

**Comment by adambabik** [comment]
I verified this with the newest `geth` (1.6.7 and 1.7.0-beta) and `status-go` "develop" branch and it works fine now.

```
> key
"0x045fae49c22e5d403980a6bf1db33e983d502ded1f17927ebaf5e7223fa6ca1f1f070b2e8717d14fc58b0d2e270670eb4efa70b0fe27a83c980732b4efff9260e6"
> shh.post({ ttl: 20, topic: '0x07678231', powTarget: 2.5, powTime: 8, payload: '0x68656c6c6f', pubKey: key});
true
```

BTW there is no `key` property in `shh.post()` anymore, but it's replaced with `pubKey`.
