### ISSUE TITLE
Launch nodes which support new PoW

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#1641]
# Problem

As a node runner, I want to be able to run with the EIP627 spec compliant and updated PoW calculation. Additionally, I want to disconnect nodes that don't satisfy my powRequirement.

Currently, due to mismatching PoW calculations, old pow calculations that seem to meet powRequirements actually don't (indeterministic).

What this means in practice is that _all_ Status nodes are sending what seems like bad envelopes from new/spec compliant nodes point of view.

Before v1, we don't want to break things for existing users. For v1, we want to switch over and use only new pow checks.

# Implementation

Deploy a separate fleet which has some nodes that do pow calculation using new fixed algorithm.

There might be some edge cases wrt mailservers and stickyness, but we don't need to expose this to status-react yet.

Also bump status-go version so it is visible what type of peer you are connected to.

# Acceptance Criteria

I can run a node with new pow calculation and not disconnect all nodes in the Status network.

# Notes

See conversation in #core-infra

# Future Steps

- Update specs
- Update status-react
- Figure out how to deal with mailservers gracefully

^ @adambabik

**Comment by adambabik** [comment]
I would suggest to upgrade mailservers and server nodes on `eth.staging` and test whether everything works as expected. If so, maybe we can just use `eth.staging` instead of creating a new fleet to develop V1.

That would mean broken message passing between pre-V1 and V1 versions but the same would happen with a new fleet.

**Comment by oskarth** [comment]
Sounds good to me!

**Comment by adambabik** [comment]
eth.staging fleet is updated. I tested it with status-console-client and messages are exchanged properly.

**Comment by adambabik** [comment]
I am gonna test mailservers because @jakubgs discovered some problems.

**Comment by adambabik** [comment]
`eth.staging` runs new PoW and it's confirmed the messages are exchanged properly between clients.
