### ISSUE TITLE
The 'make setup' command fails

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#1645]
# Problem
Our docs state that in order to build `status-go` you have to run `make setup`:
>The first thing to do to get started is to run make setup. That’ll ensure that all tools required to do a first build are installed and set up.
https://status.im/build_status/status_go.html

# Symptoms

```
...
go: finding github.com/vacp2p/mvds v0.0.18
go: github.com/vacp2p/mvds@v0.0.18: parsing go.mod: unexpected module path "github.com/status-im/mvds"
panic: error loading module requirements

goroutine 1 [running]:
cmd/go/internal/mvs.Downgrade.func2(0xc00038a480, 0x16, 0xc00045966a, 0x7)
        /usr/local/go/src/cmd/go/internal/mvs/mvs.go:317 +0x676
cmd/go/internal/mvs.Downgrade(0xc0000f33a0, 0x1e, 0x0, 0x0, 0x16c86c0, 0xc00014c460, 0xc00031d3a0, 0x1, 0x1, 0x0, ...)
        /usr/local/go/src/cmd/go/internal/mvs/mvs.go:349 +0x5c7
cmd/go/internal/modget.runGet(0x1a45ba0, 0xc0000cc070, 0x1, 0x1)
        /usr/local/go/src/cmd/go/internal/modget/get.go:446 +0x20d3
main.main()
        /usr/local/go/src/cmd/go/main.go:219 +0x7a4
make: *** [Makefile:211: gen-install] Error 2
```

# Question
It appears that `make statusgo` works just fine even without running `make setup` first. Do we even need to mention that target in the docs?

**Comment by adambabik** [comment]
> It appears that make statusgo works just fine even without running make setup first. Do we even need to mention that target in the docs?

We don't. We should separate building from contributing. To build, you only need `make statusgo`. To contribute, that is to send a PR, you should do `make setup` (I just checked and not all targets from `setup` are needed).

I will update docs.
