### ISSUE TITLE
Balance is not updated after sending / receiving transaction and sometimes no transaction is shown in transaction history

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1665]
# Problem

The balance on multi-account and individual account view is not updated after sending or receiving transaction until relogin.

Original issue https://github.com/status-im/status-react/issues/9361

Related issue https://github.com/status-im/status-react/issues/9280

**Comment by rachelhamlin** [comment]
Should this replace #9361? I'm unclear if there's a build on it.
