### ISSUE TITLE
Waku 0: integrate Waku node and Waku client

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1683]
# Problem

Statusd as well as status-go libraries should have Waku node/client service instantiated when it is enabled in the configuration.

# Implementation

Following the current strategy in status-go, add a `WakuConfig` to `params.NodeConfig`. If enabled, a Waku node/client service should be instantiated, similarly to Whisper service. 

Waku service should be visible as a separate subprotocol.

# Acceptance Criteria

1. Status-go library can communicate with Waku node using a separate subprotocol.
2. Statusd can run with Waku node subprotocol enabled and server Waku nodes.
3. Statusd has an additional command which is a CLI implementation of Waku client.

# Requirements

1. Waku service is implemented first -- this will be done in a separate repo similarly to Whisper.

**Comment by oskarth** [comment]
Thanks - one more thing to keep in mind is that there's a need for a WakuWhisper bridge, we are currently experimenting with this in the nim-eth code base

**Comment by oskarth** [comment]
@adambabik is this the most up to date master issue for status-go Waku client? Does it cover:

```
	- shhext (https://github.com/status-im/status-go/pull/1777)
	- topic interest (_)
	- mailserver topic interest (_)
	- bridging logic (_)
  	- full spec compliant (link to issue?)
  		- simulation would be useful for this
```
?

**Comment by adambabik** [comment]
I consider this done. We have all pieces, including bridging, in place and have started integration with status-react.
