### ISSUE TITLE
Create a Waku service as speced in Waku/0

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1700]
# Problem

Implement waku/0 protocol, a Status fork of Whisper with additional codes and changes.

All details can be found in [a waku meta issue](https://github.com/vacp2p/pm/issues/2).

# Implementation

* Create a separate submodule which will implement waku/0 subprotocol and will be based on the EIP-627 as well as [Status' fork of geth's Whisper implementation](https://github.com/status-im/whisper).

# Acceptance Criteria

1. It must be compatible with [the current specs](https://github.com/status-im/specs),
2. It must allow to implement https://github.com/status-im/status-go/issues/1683.

**Comment by oskarth** [comment]
@adambabik what's the state of this?

**Comment by oskarth** [comment]
Ping @adambabik

**Comment by adambabik** [comment]
It's almost finished. We need to close:
- https://github.com/status-im/specs/pull/74 (required)
- https://github.com/status-im/status-go/pull/1732 (required)
- https://github.com/vacp2p/specs/issues/71 (I can finish this without it because it is the same as https://github.com/status-im/specs/pull/72)
