### ISSUE TITLE
Logging: shared logs

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#171]
- ~~we need to keep it under 5MB~~
- ~~we need to make sure that intabug has permission to read the file (or `777`)~~
- allow configurable "hosted logging" backends, so that we can consolidate and analyze our logs w/o instabug as well

**Comment by farazdagi** [comment]
Note (to myself):
- As an obvious use case for logging, investigate why node might crash (@rasom experienced issue when syncing and trying to `StopNode()` on Android).
- One possible issue might be ethash *cache* generation (it happens on the first run), so the thing might disappear after cache is built

**Comment by tiabc** [comment]
Note some work done in https://github.com/status-im/status-go/pull/173 when getting back to this issue.

**Comment by tiabc** [comment]
Decreasing priority as it doesn't block anything.

**Comment by dshulyak** [comment]
@divan this seems outdated, right? 

https://github.com/status-im/status-go/pull/524

**Comment by adambabik** [comment]
This is something different. It's more about collecting logs into a single place and allowing to browse them using Logstash or something similar. It's not a particularly status-go issue but the cross-team effort.
