### ISSUE TITLE
Merge patches 0000, 0040, and 0044

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1772]
# Problem

We have two patches related to the `Key` and `KeyStore` in `github.com/ethereum/go-ethereum/accounts/keystore` package.

# Implementation

Go to https://github.com/status-im/go-ethereum/blob/patched/1.9/_assets/patches and merge 0000 and 0044 patches into one. Do the clean up of deprecated items.

# Acceptance Criteria

1. Merge all keystore-related patches into one,
2. Get rid of deprecated stuff after introducing multi-account.

# Notes

@gravityblast is the point of contact if there are any questions and should review the related PR.

**Comment by dzuqe** [comment]
Hey @Samyoul . i've submitted a PR in go-ethereum that should fix this issue https://github.com/status-im/go-ethereum/pull/90 . There's a more detailed description there.
