### ISSUE TITLE
Clean up whisper-related patches

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1773]
# Problem

status-go uses its own fork of Whisper, thus, we don't need any patches in https://github.com/status-im/go-ethereum.

# Acceptance Criteria

1. Make sure all whisper-related patches are incorporated in https://github.com/status-im/status-go/tree/develop/whisper.
1. Remove all whisper-related patches from https://github.com/status-im/go-ethereum/tree/patched/1.9/_assets/patches.

**Comment by dzuqe** [comment]
hey @adambabik i've submitted a PR in go-ethereum that fixes this issue https://github.com/status-im/go-ethereum/pull/89

**Comment by flexsurfer** [comment]
@Samyoul
