### ISSUE TITLE
Geth 1.6.7 rebase

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#178]
- https://github.com/ethereum/go-ethereum/releases/tag/v1.6.7

**Comment by tiabc** [comment]
@adambabik:
> Yeah, maybe we can do some CI to do it automatically
> with making it automated we could have a PR every time a new release of go-ethereum is released and hopefully we would resolve conflicts only with major changes

**Comment by adambabik** [comment]
List of commits: https://github.com/status-im/go-ethereum/wiki/%5BWIP%5D-Rebase-Geth-1.6.7-stable

**Comment by tiabc** [comment]
@adambabik, thank, very fast execution. There may be bugs. If so, we'll fix them directly in the original branch.
