### ISSUE TITLE
Implement requesting messages per topics in Waku/0

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1798]
# Problem

We want to remove false positives and allow requesting messages not only by a bloom filter but also a list of topics. 

This will reveal to mailserver a list of topics a given peer is interested in.

# Implementation

Extend mailsever request object with `Topic` field which stores a list of topics.

# Acceptance Criteria

1. It is possible to request historic messages per topic,
2. Mailserver understands this request and replies properly.

**Comment by oskarth** [comment]
Can we make it explicit that this issue is about supporting v0.2 as specified here? https://specs.vac.dev/waku/mailserver.html

**Comment by adambabik** [comment]
Done in https://github.com/status-im/status-go/pull/1805
