### ISSUE TITLE
waku.MessagesRequesthad has no field Topics

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#1822]
When trying to build `status-go` at `v0.41.0` I'm getting:
```
../../go/src/github.com/status-im/status-go/mailserver/mailserver.go:382:14:
    req.Topics undefined (type waku.MessagesRequest has no field or method Topics)
```
It appears that it's not part of the `waku.MessagesRequesthad` struct but is used in `Deliver()`:
https://github.com/status-im/status-go/blob/98758d299d8b89e8b7d28da770ac9a01cbe9d985/mailserver/mailserver.go#L377-L387
Not sure if it should be there. But removing it temporarily solved that issue.

**Comment by adambabik** [comment]
It has been fixed.
