### ISSUE TITLE
CreatePublicChat requires timesource, but Messenger doesn't export it

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#1823]
I tried using `CreatePublicChat()` but it now requires `timesource ClockValueTimesource`:
https://github.com/status-im/status-go/blob/98758d299d8b89e8b7d28da770ac9a01cbe9d985/protocol/chat.go#L227
I found out that `protocol/messenger.go` has an unexported `getTimesource()` that it uses:
https://github.com/status-im/status-go/blob/98758d299d8b89e8b7d28da770ac9a01cbe9d985/protocol/messenger.go#L632
So I made it exported by renaming it `GetTimesource()` and that fixed my build, but I'm not sure if it should be exported, or if I used it right.

**Comment by adambabik** [comment]
Closed by #1837.
