### ISSUE TITLE
Erring startNodeWithAccount() method puts node into a corrupted state

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1836]
Description from Discuss:

> could you look into `startNodeWithAccount`? In case of error it calls `stopNode`, but it seems like it puts the app into a state where it can't login into any account after that. It doesn't happen with wrong password because the node isn't even started at that point, but with an invalid public key in a chat, `startNode` fails when calling `injectAccountIntoServices`, and I suspect that either `stopNode` isn't working properly, or we need something more like Logout which does a bunch of stuff and that we call before stopNode when doing a logout

**Comment by yenda** [comment]
We should probably make sure that startNode undo what it did instead of just returning an error when it fails at any point?

**Comment by adambabik** [comment]
That's correct. The cleanup process should kick in and leave the node in a state where it can be restarted successfully.
