### ISSUE TITLE
jail: sendAsync

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#184]
- right now `send()` and `sendAsync` rely on the very same function
- we need to make sure that `sendAsync` is really executed in async manner i.e.:
  - the request itself will run within goroutine
  - function will return immediately with `Otto.UndefinedValue()`
  - once request is finished w/i the goroutine, callback method (if present is called)
- we should have this covered with as many tests as possible, as we are opening the pandora box of race conditions, and concurrent access to VM - which shouldn't be treated lightly

**Comment by tiabc** [comment]
@influx6 thanks for starting and working on the issue for a while, your feedback was extremely valuable!
