### ISSUE TITLE
Implement code 22 for exchanging options

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#1853]
Implement code 22 for exchanging options

# Problem
Currently we have no way to exchange topic-interest, and we need a way to exchange that information among peers.

# Solution

The proposed solution is to have a new code `22`, which exchange an `ALIST` through `RLP`, which may contain any option that is currently exchanged in the handshake (therefore including topic-interest).

All the options are optional, and we assume that the field has not changed if not present.

For a description of how topic-interest and bloom filters are handled refer to https://notes.status.im/bloom-filter-topic-interest-waku?view .

The handshake will also be changed to allow for the absence of any field, which otherwise will be defaulted as follow:

- for PoW, 0
- light node off
- full bloom filter
- no topic-interest

**Comment by oskarth** [comment]
Will this supersede code 21?

**Comment by cammellos** [comment]
I would think so, as we never actually used it,  same could go for `2`, `3` and `20` , unless we need to maintain compatibility @adambabik @kdeme

**Comment by adambabik** [comment]
I understand waku/0 is a clean sheet so I would go with the lowest unused packet code possible so `2` (`1` is for messages).

**Comment by kdeme** [comment]
I'm fine with dropping those packet types as they become redundant.
One small item though, perhaps we should also add something in the spec in the lines of:
_The `StatusOptions` parameter in the `StatusUpdate` packet SHOULD only set options that require updating._ ? To avoid e.g. unnecessary transfers of big topic lists.

Another more important item that I just realized is that by allowing this new packet type which passes `StatusOptions`, we implicitly now also allow for changing `light-mode` setting and `confirmations-enabled` setting "on the go", as before there were no packet types to change those settings.
I don't see a big problem with this, but it will require some extra logic to implement in the clients.

**Comment by adambabik** [comment]
Very good point @kdeme  👍
