### ISSUE TITLE
JSON-RPC Server Delegation in Network Configuration

### ISSUE THREAD

**Issue by jarradh** [status-im/status-go#190]
While we're adding a network switching, we should also enable the mode to define a JSON-RPC server, when run in this mode the client does no Blockchain synchronisation at all. With this we can address sluggish/slow/hot phones with high battery consumption. 

In this mode Whisper is still functional but `eth_` rpc calls (either via IPC or HTTP) are proxied to the JSON-RPC server, `sendTransaction` must still be intercepted as signing of transaction must still be done on client using our transaction signing queue. From `status-react`'s perspective, nothing should change.

The user should be able to define a JSON-RPC proxy in the network configuration parameters passed here to [StartNode](https://github.com/status-im/status-go/blob/develop/cmd/statusd/library.go#L29 ). Should be a new Param in [NodeConfig](https://github.com/status-im/status-go/blob/bc3ea62ecad96ddab3eed683bba81a239560b645/geth/params/config.go#L132-L132) 

`status-react` should provide default configs, which will use  (ignore IPFS for now)
```
Main Ethereum Network
https://mainnet.infura.io/nKmXgiFgc2KqtoQ8BCGJ

Test Ethereum Network (Ropsten)
https://ropsten.infura.io/nKmXgiFgc2KqtoQ8BCGJ

IPFS Gateway
https://ipfs.infura.io

IPFS RPC
https://ipfs.infura.io:5001
```

**Comment by jarradh** [comment]
We had done a similar scheme 2 years ago in Java, obviouslt out of date but may help illustrate it.  You can see under `light` in https://github.com/status-im/ethereumj-personal/tree/187a6b49c3933d19fe02c7270ebdf927a8beb93d/ethereumj-core-android/src/main/java/org/ethereum/android/jsonrpc

**Comment by influx6** [comment]
@jarradhope From my understanding after looking over at things, what we want is a basic jsonrpc that proxies all requests to the underline address given in the issue 
https://status-im.slack.com/archives/G2B3U1AKE/p1499073510578589.

## Questions:
1. Is there currently an underline JSON-RPC server being used or is a new one needed to be coded up.
2. Are the given resource links the available rpc servers for infura to proxy to for certain requests ?
3. We filter out rpc request to the appropriate handler where `eth_` related calls still go to the current rpc server and others to our local version.
4. Does our local version speak directly to whisper or the given links.

Anymore information would be highly appreciated.

**Comment by rasom** [comment]
1. Currently we are running local node with JSON-RPC server
2. Can't answer
3. We definitely need to intercept all `shh_` calls, and some `eth_` calls. For instance no need to intercept [eth_getBlockNumber](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethblocknumber) call, but we have to intercept `eth_sendTransaction`, etc.
4. Directly, we will run local node with enabled Whisper protocol

**Comment by influx6** [comment]
@rasom Most grateful for the help.

**Comment by jarradh** [comment]
Could you please clarify what you mean by 'basic jsonrpc' ? I feel there may be some miscommunication here, as our definition for this changes frequently in discussion. As we should be intercepting API requests _at a lower level_ than the running HTTP JSON-RPC server. So that IPC requests can also be relayed to a HTTP JSON-RPC server.

1. We are currently running a HTTP based JSON-RPC sever but **we _shouldn't be_** see Issue #177, now assigned to you @influx6 
2. I'm not sure I understood the question, but yes. You can also run a RPC server locally.
3. Please clarify the  meaning by `filter out`, `current rpc server`,  `local version` and `intercept all ssh_ calls` ? I'm not sure I can agree here.
4. Whisper subprotocol and API calls runs normally and is not affected.

**Comment by influx6** [comment]
Thanks for the response @jarradh and clarifications, as to your desired questions.

1. As to `filter out`, I referred to the function of processing calls which does not fall under the `eth` prefix commands, since those would be proxied to whisper.
2. As to `current RPC Server`, referred to the fact an existing rpc server is currently being runned by `NodeManager` and I envisioned a second one would be started which would allow by pass of ethereum blockchain synchronization processes.
3. As to `local version` that simply referred to my thought at the moment that the current rpcserver/http server is remote and all rpc calls where sent directly to it.

**Comment by jarradh** [comment]
Perfect that sounds fine to me.

**Comment by influx6** [comment]
Let's do a reset on the explanations, I feel this following below properly explains my current confusion with this issue. @jarradh @tiabc 

Hello, am wondering if I could have your view to help me better understand what needs to be done, on this issue https://github.com/status-im/status-go/issues/190
 
Currently the target is to:
1. Provide a rpc proxy to handle all requests internal and deliver to another rpc endpoint as needed.
2. Ensure ethereum blockchain is not called when the on mobile.

Now the issue am facing is:

1. `node.Node` from the `ethereum/node` package, provides the rpc server to manage API request coming to a `Node.

2. Faraz worked on a piece that allows executing RPC calls directly by retrieving a node's internal RPC server inhttps://github.com/status-im/status-go/issues/177 , written in https://github.com/status-im/status-go/blob/develop/geth/node/rpc.go

Related to  Issue #177

The sample java project given show case a rpc proxy that internal handles and delivers request to another endpoint as needed and proxies when necessary.

My main issue point is:
1. Do they need me to write such a strucuture similarly in go?
2. How does this fit in with the current architecture, has `Node` create comes from the `ethereum` package and the approach RPCServer coming from that is internal created.
3. How does this new PRC Server proxy sit into the current architecture and receive request, has from my code review, everything related goes directly to the node, are we looking to replace that as well?

Atleast if I can understand this series of points then I know what to do, but right now am to be honest confused.

P.S: I know @farazdagi is unfortunately sick and has left, but it would really be helpful if I can get is insight on this.

**Comment by influx6** [comment]
I do believe I can resolve the issue, but I need to properly understand what is required and what the current problem is, the current explanation is good but since am new to the code base, certain facts and architectural details are lacking, which would have properly allowed me to understand and see the requirement more clearly.

**Comment by tiabc** [comment]
Let me try to make a brief general answer, I'll answer with more details some later.

The point is that devices running Ethereum node quickly run out of battery and DAG is also a problem. This makes the application too heavy for such small devices as smartphones.

The current decision is to proxy all possible request to "public Ethereum nodes", i.e. infura. That said, we still need to run super-light nodes with no blockchain synchronization at all only for whisper messages which still needs to function to properly distribute the load and avoid centralization.

`eth_sendTransaction` also needs to be intercepted as transactions needs to be signed with the local queue.

Other calls can be proxied to infura avoiding the need to synchronize the whole blockchain locally.

This is basically the task to be done.

@jarradh, please, correct me if I'm wrong anywhere.

**Comment by influx6** [comment]
So basically in code terms. We need the ethereum.Node to be initialized only with the whisper service and then a custom RPC seevee, whicj handles all request internally.  

Which piece of the API handles signing for `eth_` requests?

**Comment by tiabc** [comment]
Not for all `eth_` but only for `eth_sendTransaction`. You can find all such places by searching by the `SendTransactionRequest` constant: https://github.com/status-im/status-go/blob/develop/geth/jail/requests.go#L16

The actual sending is processed here: https://github.com/status-im/status-go/blob/develop/geth/jail/requests.go#L56

The whisper service and shh service are the same thing, by the way :)

About architecture, I've [drafted a small sketch](https://ibb.co/iXAccv) with what it should look like in the end. As you can see, wherever the request comes from, it should eventually be routed to either the local node (if it's `shh_*` or `eth_sendTransaction` with some more logic in the latter case) or to the specified upstream node and a new separate component should handle this routing. What to the more detailed architecture, I'd work on propose-discuss basis: you face the problem, propose solutions and we discuss what best fits us.

Also, please, note that this task is about the new mode of operation which can be either turned on or turned off. So the parameter in `NodeConfig` (say, `UpstreamEthRPC`) should control it.

In your shoes, I'd start from intercepting requests from all places and passing them through that router and then did some exceptions.

This task is not absolutely easy and straightforward, indeed. Let me know if something is still left unclear.

**Comment by tiabc** [comment]
@influx6, by the way, if you're unfamiliar with transactions' sending flow, look here: https://github.com/status-im/status-go/wiki/Notes-on-Bindings#6-sending-transactions

**Comment by influx6** [comment]
Greatly appreciate the explanations, will take the time to study them and
come up with a approach, which will be describe here for review.

On 8 Jul 2017 07:20, "Ivan Tomilov" <notifications@github.com> wrote:

@influx6 <https://github.com/influx6>, by the way, if you're unfamiliar
with transactions' sending flow, look here: https://github.com/status-im/
status-go/wiki/Notes-on-Bindings#6-sending-transactions

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/status-im/status-go/issues/190#issuecomment-313837521>,
or mute the thread

**Comment by influx6** [comment]
Hello @jarradh, @tiabc and @rasom 

Although am slowly grasping the core pieces of this codebase and what this issue entails, thanks to the explanations provided, though there are still spots needing clarification, but for now, my current plan is to do following:

- Implement a partial router which maps out needed calls as appropriately
Currently we know we are making calls when related to rpc using the `RPCClient` (see https://github.com/status-im/status-go/blob/develop/geth/common/types.go#L86) and `Jail` instances (see https://github.com/status-im/status-go/blob/develop/geth/jail/jail.go#L182-L240). 

My initial plan falls into two goals:

1. To abstract out all necessary calls into a central `RPCRouter` structure, where we can atleast control how specific RPC requests such has `eth_sendTransaction` and other related calls appropriately.
2. To return a `RPCClient` specific to the necessary upstream endpoint desired as relating to the dealing with unwanted synchronization of ethereum block chains. 

This solution is absolutely not complete,but is intended to allow us map out areas which have points of RPC calls and request processing, where a more complete solution can be created from.

My next goal is to check out `github.com/ethereum/go-ethereum/rpc` and understand what is specific about this implementation, if it's possible to direct a new `rpc.Client` instance to a different upstream endpoint.
 
_Please feel free to review and bash the approach as much as possible_.

**Comment by tiabc** [comment]
Sounds good if I understand everything correctly. Don't forget about IPC, requests can also come from there.

The only hurdle I'm thinking about is that `eth_sendTransaction` requires correct `nonce` which is continuously incremented every time a transaction is sent. So a local node needs to synchronize the blockchain to be able to sign and send a valid transaction. In this case we'll have to additionally request `eth_getTransactionCount` from the upstream node, create and sign a raw transaction and sent it. Let's delay `eth_sendTransaction` implementation until all the rest is solid.

**Comment by influx6** [comment]
@tiabc  Yes, that is something am worried about, currently I have not scoped the IPC code base yet, if you have source links of areas where the request for ipc get's resolved then please do share.

Currently, `eth_sendTransaction`, logic seemed to be handled in the `jail instance` piece of the `geth/jail` package, unless have misunderstood things, I refactored that piece and it's other areas to direct calls to the `RPCNodeManager` provided which exposes a `Execute` (in https://github.com/status-im/status-go/blob/979aa6245efdedc2795e9cb12fe5769f52f6a6a3/geth/common/types.go#L44-L47) method to handle such calls which allows us direct as needed, such RPC requests to use the expected `NodeManager` which will return a `rpc.Client` directly from ethereum's core to process the request (as in https://github.com/status-im/status-go/blob/979aa6245efdedc2795e9cb12fe5769f52f6a6a3/geth/proxy/transactions/sendtransaction.go#L20-L62).

Other `RPC` calls from the Jail instance will be processed by another (as in https://github.com/status-im/status-go/blob/979aa6245efdedc2795e9cb12fe5769f52f6a6a3/geth/proxy/transactions/sendtransaction.go#L68-L135).

Since most parts of the code as related to IPC and also whisper related actions use the `rpc.Client()` from the `NodeManager` then we can also depending on the flag in the `NodeConfig` return an appropriate `rpc.Client` suited to talk directly to the upstream.

_Would appreciate pointers to the IPC related hot spots._

**Comment by influx6** [comment]
Seems like IPC calls might have become obsolute as stated in https://github.com/status-im/status-go/issues/134. 

Please review when possible @tiabc.

**Comment by tiabc** [comment]
Oh, yes, you seem right, `status-react` must already be using the `CallRPC` signal instead of requesting rpc or ipc endpoints.

Please, regard my answers with some degree of criticism as I'm pretty new to the project as well.

Regarding other thoughts, I'll review them later today or tomorrow.

**Comment by influx6** [comment]
Ah, sure, no problem. We both are new indeed, all the answer all help to formulate an initial plan. Thanks for the help.

**Comment by influx6** [comment]
@tiabc @jarradh @rasom 

The latest commit #d0a02bd adds the necessary pieces to return a `rcp.Client` depending on the values of the `UpstreamConfig` params in `params.NodeConfig` and will dictate which client to return. But one more piece is missing for this initial setup which is finding the specific area which initiates the blockchain synchronization.

Initially I assumed the call to synchronize ethereum locally is done here (https://github.com/status-im/status-go/blob/issue/190/geth/node/node.go#L94), but unfortunately am not a 100% sure, has to if any other piece of the code such has the call to `Whisper` start up may depend on it as well (here https://github.com/status-im/status-go/blob/issue/190/geth/node/node.go#L99) might depend on it.

Please @jarradh and @rasom your pointers would be greatly appreciated.

Last obstacle I see to the initial run of this code, is to figure out how to properly test whether we are actually connected to the external infura node or still using the internal instance.
See https://github.com/status-im/status-go/blob/d0a02bdf1a81813fe5fb74e39e2c9e2577b79b25/geth/proxy/rpc_test.go#L32.

Any ideas?

Cheers.

**Comment by rasom** [comment]
@influx6 can you please open a new PR with existing progress for this issue?

**Comment by tiabc** [comment]
Well, it seems ethereum synchronization is started there indeed. If you dive into it, you'll find `les.New` where all that initialization happens. Anyway, if you're unsure, you can comment out those lines, run the program and ensure there is no blockchain synchronization (and, hopefully, no errors). At least, `eth` and `shh` services are registered there and then start on `geth/node/manager.go:82`. The underlying ethereum libraries traverse through the provided constructors and calls them.

Whisper start doesn't seem to depend on eth as I can see. It's worth checking though.

As to the last question, I think architecturally there should be no way to distinguish between executors from the client side. Moreover, this is correct - consumers doesn't need to have any idea of which implementation they're interacting with. In this case, testing should be accomplished with mock objects. You mock different executors which return a pre-specified response to the call and then check the result.

**Comment by tiabc** [comment]
After all work has been done, I've realised that the associated pull request has a semantic bug: in case of a configured upstream rpc server transactions are sent immediately without waiting for `CompleteTransaction` or `DiscardTransaction`.

However, the pull request has become too big and been lasting too long to last anymore and my decision here would be to merge this pull request after release, test what we already have and implement waiting for those signals in a separate issue #245 under the next milestone.

@rasom, @annadanchenko, thumbs up if agree. Comment if not.

**Comment by tiabc** [comment]
Phew. Thanks, @influx6, that was really hard one.
