### ISSUE TITLE
Implement signMessageWithChatKey(string) string method

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1907]
# Problem

We want to sign messages without user action, so we have chat key in status go, so we want to sign messages with this key in status react

# Implementation

Implement `signMessageWithChatKey(string) string` method

# Acceptance Criteria

It's possible to sign message without password

**Comment by flexsurfer** [comment]
@Ferossgp fyi

**Comment by cammellos** [comment]
You can use this branch for now https://github.com/status-im/status-go/tree/feature/sign-message
You have a `SignMessageWithChatKey` method, that returns the hex encoded string of the signature, or error.
