### ISSUE TITLE
Fix issues with syncing mailservers

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#1924]
# Problem

In relation to recent [postmortem](https://github.com/status-im/infra-docs/blob/master/postmortems/20200327_mailserver_db_issues.md) of DB issues we found that syncing mailservers using the [available instructions](https://github.com/status-im/status-go/blob/develop/mailserver/README.md) doesn't work properly.

# Notes

I've made [a script](https://github.com/status-im/infra-utils/blob/master/status-go/mail_sync.py) for syncing mailservers by calling the 3 methods described in the instructions:

* `admin_addPeer` - Which returns `result: true` but is lying
* `shh_markTrustedPeer` - Which fails due to peer not being added
* `shhext_syncMessages` - Which will fail if peer is not marked as trusted

# Issues

The `shh_markTrustedPeer` call fails with:
```log
Could not find peer with ID: 2721ca3e5c87d73ce892bd0710f9a78eef4c800f92aeaa7feec8b9b86b62c131
```
If peer has not been added already. And apparently `admin_addPeer` is an async call.

For that reason I [implemented a loop](https://github.com/status-im/infra-utils/blob/1a9e7350317bb3194b779b61908bc92cdc67bbe8/status-go/mail_sync.py#L83-L92) that calls `admin_addPeer` and `admin_peers` in order to catch the moment when peer is added before trying to mark it as trusted. The issue with that is that it never worked:
```
Failed to addPeer, sleeping...
Failed to addPeer, sleeping...
Failed to addPeer, sleeping...
Failed to addPeer, sleeping...
```

**Comment by jakubgs** [comment]
Still relevant.

**Comment by jakubgs** [comment]
Still broken, but okay.

**Comment by cammellos** [comment]
Closing because we will be working exclusively on waku-v2 store nodes, but yes, still broken, we should eventually remove the code
