### ISSUE TITLE
Messengers acquires a lock in some methods for very long time

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#1936]
# Problem

There are a few methods in `Messenger` in `protocol` package, for example `VerifyENSNames`, which acquire a lock for very long time.

# Implementation

Fix this by guarding only these operations that really need a lock to be acquired.

# Acceptance Criteria

1. There is no locks that are acquired during waiting for the internet request to be finished.

**Comment by Samyoul** [comment]
Resolved with https://github.com/status-im/status-go/pull/2199, which includes code from https://github.com/status-im/status-go/pull/2181 that explicitly deals with this issue.
