### ISSUE TITLE
Function passed to setInterval inside the jail is never called 

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#196]
js code:
```js
var hiCnt = 0;

function sayHi () {
    status.sendMessage("Hi " + hiCnt);
    hiCnt++;
}

status.addListener("init", function () {
    sayHi();
    setInterval(sayHi, 1000);
    status.sendMessage("after first \"Hi\"");
});
```
In result a new message should be sent to chat every second, but this doesn't happen.

<img width="364" alt="screen shot 2017-07-18 at 16 23 00" src="https://user-images.githubusercontent.com/2364994/28321160-2cb9d910-6bdb-11e7-9f50-9503fdedf3a8.png">

`setInterval` is defined because there are no errors in output and the second message is sent successfully.

`develop` branch was used

**Comment by influx6** [comment]
This is an odd situation, has I have the loop working properly in a test case with Jail which can be found in commit #9f52be21. I will investigate further, properly due to the way the loop is registered,  but I can not say for sure for the main time.

**Comment by tiabc** [comment]
Thanks, @influx6, nice work!
