### ISSUE TITLE
Create a separate application for Mail Server and Push Notifications

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#197]
Jarrad:
> If we're doing push notifications and a mailserver, maybe it's best to have a program alongside the node which handles this

So it's a good idea to separate concerns and, probably, deploy the new application separately.

Do not start this task, it's currently more about investigation.

TODO: This issue should be revisited and all parts of our application should be separated.

**Comment by adambabik** [comment]
This is currently being worked on https://github.com/status-im/ideas/issues/1.
