### ISSUE TITLE
Remove vendored Whisper and any remain usages

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#1970]
# Problem

[vendor/github.com/status-im/status-go/whisper/](https://github.com/status-im/status-go/tree/develop/vendor/github.com/status-im/status-go/whisper/v6) exists and so does [whisper](https://github.com/status-im/status-go/tree/develop/whisper) .

If we have a dedicated package in the repo we don't need whisper to also be vendored.

# Implementation

Remove the vendor code for Whisper. Remove any remaining usages or references to the vendored package in favour of the repo package.

# Acceptance Criteria

Implement the above implementation without introducing any breaking changes.

# Future Steps

We probably will want to review all of the vendored packages at some point, but there is a mega load, so may not rank highly in terms of priorities.

**Comment by felixboehm** [comment]
whisper is not in vendor anymore. close?

There is one remaining self referencing vendor module for extkeys.

**Comment by jonathanalvares9009** [comment]
Hi @Samyoul can I take up this issue? I'm interested in the status.im project

**Comment by Azanul** [comment]
It looks like it has already been resolved
