### ISSUE TITLE
Push notifications node

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#1988]
# Problem

To implement push notifications for ios we have to use Apple push server and user's device token, but we would want to use it not directly from users's devices but via "push notifications" waku node, here are more details https://discuss.status.im/t/decentralized-push-notifications-for-ios/1718

# Implementation

1) implement and run waku node which will be listening for two commands
 a) register device token 
 b) send PN
2) implement and run database in which user's tokens will be stored
3) implement communication with  Apple push server directly or using https://github.com/appleboy/gorush 

# Acceptance Criteria

User A should be able to register his device's token by sending a message to push notification waku node contact
User B should be able to send PN to user B by sending a message to push notification waku node contact

**Comment by flexsurfer** [comment]
regarding device token registration we also need deregistering, 
and we need some confirmation from pn node when a user has been registered or deregistered

**Comment by flexsurfer** [comment]
also to be able to send PN from pn node we need next credentials
```
token: {
    key: '<key_file_name>.p8'),
    keyId: apnKeyId
    teamId: apnTeamId
  }
```

**Comment by flexsurfer** [comment]
with gorush https://github.com/appleboy/gorush#send-ios-notification
``` 
gorush -ios -m "your message" -i "your certificate path" \
  -t "device token" --topic "apns topic"
```

-i, --key <file>                 certificate key file path
-P, --password <password>        certificate key password

**Comment by flexsurfer** [comment]
@andremedeiros could you assists with getting certificate?

**Comment by cammellos** [comment]
this has been implemented,closing
