### ISSUE TITLE
Using status-go in an Android React Native app

### ISSUE THREAD

**Issue by Annorstades** [status-im/status-go#199]
Hi!

I've been trying to get geth working in my React Native (Android) app without success. I've been following [this guide](https://github.com/ethereum/go-ethereum/wiki/Mobile:-Introduction). I can't wrap my head around how it's being done in Status.

That being said, my ClojureScript skills are well below standard. How would I go about using web3 in standard Javascript without relying on, say, Infura? I know it's an amateurish question, but hey – how else are we going to get the ethereum revolution on the road if half-wits like me can't ask stupid questions? ;)

**Comment by tiabc** [comment]
Hi! Great that you want to play around with Status. As this is not a concrete issue and rather a discussion topic, I'd recommend you to visit our slack channel: status-im.slack.com and ask your questions in #dev-status

Generally, `status-go` is the application `react-native` interacts with, it's not an ordinary geth node (though it's embedded in `status-go`).

Good luck and looking forward to seeing you on our channel!

**Comment by Annorstades** [comment]
Thanks, I'll do that! Apologies for cluttering up the issues page.
