### ISSUE TITLE
Make CI build versions for every platform and upload it into some storage

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#201]
Every release there should be a binary for every platform.

**Comment by MarinX** [comment]
Which platforms ?
Which storage ? 
Please provide more insights about this task.

**Comment by tiabc** [comment]
It's essential to build only 2 binaries:
- Android.
- iOS.

We also need binaries for development but they can be built ourselves. The important thing is to build them for the Clojure team.

Not sure which storage to suggest. My options are currently restrained to some Travis storage in case there's one or our scaleway cluster. @roma, @jarradh, you already tried to put binaries to some artifacts storage, as I know. Which one you tried?

**Comment by MarinX** [comment]
@roma said that we are using  [artifactory](https://www.jfrog.com/) for storing.

Artifactory has an API for uploading. Idea is to create a script that will upload binaries. Then, connect script on travis for every build.

**Comment by MarinX** [comment]
@jarradh I need rights to modify jenkins and artifactory to finish the task.
Explained here:
[Jenkins->Artifactory](https://www.jfrog.com/confluence/display/RTF/Jenkins+Artifactory+Plug-in)

**Comment by oskarth** [comment]
Here's the current flow as outlined by @rasom https://github.com/status-im/status-go/wiki/status-go-deployment

**Comment by adambabik** [comment]
First, let's decide what we mean by "every release" @tiabc. Can we assume that every marge to master is a release?

Next, the flow (for the sake of clarity, let's assume a merge to master is a release):
1. Merge to master triggers Travis CI build,
2. Travis runs tests and make binaries,
3. If all is good, binaries are uploaded to Artifactory via API.

If Travis won't be able to build binaries, we can switch to Jenkins, but the flow will remain the same.

Anything else would be helpful to status-react team? @rasom

**Comment by adambabik** [comment]
Update: It's possible to use Travis CI to build and upload artefacts. It has a few downsides though:
1. It's slow as it needs to download a docker image. We can use `docker save/import` to cache it probably,
2. It can't (or will be hard) to make it a part of a complete CI/CD pipeline that involves also status-react and automated tests.

Having said that, I'd like to also explore building it in Jenkins as it has more potential.

**Comment by tiabc** [comment]
Sometimes, we run into problems when asking the Clojure team to use some our branch of the latest `develop`. In this light every push to any branch is a release. The Clojure team should be able to use any our binary at any time without any additional efforts.

I don't have access to Jenkins. I think you should contact @annadanchenko for that.

**Comment by adambabik** [comment]
Branch builds were added to Jenkins.
