### ISSUE TITLE
whisper: mocha tests

### ISSUE THREAD

**Issue by rgeraldes** [status-im/status-go#206]
- Current tests (static/tests/whisper.js) were done for geth 1.5.9 and api changed drastically according to Victor

**Comment by rgeraldes** [comment]
- Current mocha tests represent a test of a flow proposed some months ago for push notifications
As soon as we discuss the solution next week (14/Aug), we can start doing them taking into account the new web3.js being used in order to test the flow without the need of a front end.

**Comment by sla-shi** [comment]
Per @tiabc This highly depends on the new workflow for push notifications and should probably go to the 3rd milestone.

**Comment by JekaMas** [comment]
This task is highly related to whisper mailbox (we cant add new feature without tests) so we are going to make it as a part of mailboxing.

**Comment by dshulyak** [comment]
@JekaMas can we close this issue?

**Comment by adambabik** [comment]
We have both Go and mocha tests for the mailbox. The case is that they are not run in CI now and we don't know in what shape they are. It also could be interesting to compare pros and cons for e2e written as mocha tests vs Go tests.
