### ISSUE TITLE
Add support for signTypedData_v4

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#2062]
# Problem

It's not possible to sign typed data with the latest spec (signTypedData_v4)

# Implementation

https://docs.metamask.io/guide/signing-data.html#sign-typed-data-v4

**Comment by cammellos** [comment]
I looked a bit into this, and I am a bit confused, I believe metamask implementation might not be according to specs.
We have our own implementation of signed type data, but we can use geth's.
That should be fairly easy, but not sure exactly now if I am right in saying that metamask is not according to specs.

https://github.com/MetaMask/eth-sig-util/pull/107

**Comment by flexsurfer** [comment]
https://github.com/status-im/status-go/pull/2182
