### ISSUE TITLE
Mailserver requests are still using bloom filters

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#2068]
# Problem

After investigating  https://github.com/status-im/status-react/issues/11351 
we noticed that mailservers requests are still using bloom filters, regardless of whether waku is using bloom filter mode.

Mailservers don't support querying by topic at the moment. https://github.com/status-im/status-go/blob/3f63b0c23cbe32c2331cb6201ee5cb5255ce9353/mailserver/mailserver.go#L1002 

and topics is never passed to mailserver:

https://github.com/status-im/status-go/blob/3f63b0c23cbe32c2331cb6201ee5cb5255ce9353/services/ext/api.go#L599

My understanding from previous conversations was that it was implemented, but it's not the case.

We should understand performance of querying by topics when a large amount of topics is passed in (500/1000 etc), to make sure the query is performant.

**Comment by churik** [comment]
Reproduced during testing release 17/11/2020

Logs from Jarrad device: [Status-debug-logs.zip](https://github.com/status-im/status-go/files/5553613/Status-debug-logs.zip)
