### ISSUE TITLE
Contact Discovery

### ISSUE THREAD

**Issue by fabius** [status-im/status-go#2159]
# Problem

When trying to add a contact using their [adjective, adjective, animal] username, I figured that this procedure is not supported. So I am asking for some clarification on this end:

- did I just mess something up or is this in fact not supported?
- is there some kind of contact discovery implementation available / being worked on / in the pipeline?

# Notes

I sincerely hope this is not a case of RTFM.

**Comment by cammellos** [comment]
Hi @fabius
That's correct, adding a contact using the 3 random words is not supported and it won't be, as the mapping between pk -> 3 random words is a one-way function (i.e you can't derive the pk from the 3 random words username)

> is there some kind of contact discovery implementation available / being worked on / in the pipeline?

Currently no, as we progress with the communities initiative that's something we might start look into, but currently is too early to say.
Thanks for the questions, will close the issue for now, but feel free to re-open!
