### ISSUE TITLE
Investigate possible optimisation for setInterval

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#216]
Currently, every Call with javascript containing setInterval a new goroutine with ottoext.Loop.Run() is created. With many calls with setInterval this could lead to unrestrained goroutine leakage, memory consumption and thus worse performance and user experience.

Ideally, we should have a single `loop.Run` per jail cell which accepts calls and run javascript inside. Under this issue you should investigate if this is possible and if so, implement it.

**Comment by divan** [comment]
I believe this issue was a part of https://github.com/status-im/status-go/pull/283#issue-254384600 and can be closed.
