### ISSUE TITLE
Swarm Support (status-go)

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-go#217]

**Comment by divan** [comment]
Just to note, swarm patches are not included in our Geth 1.7.0 rebase: https://github.com/status-im/go-ethereum/wiki/Rebase-Geth-1.7.0

**Comment by tiabc** [comment]
Note some work has been done in PR https://github.com/status-im/status-go/pull/117

**Comment by dshulyak** [comment]
It is not actionable without any description, no reason to have it open

**Comment by 0xc1c4da** [comment]
This shouldn't be closed, Swarm Light Clients are on the way, will follow up on this

**Comment by themue** [comment]
Especially discussed this morning an alternative to the broadcast behaviour of whisper and probably swarm could help here for a kind of virtual mailboxes and channels while whisper only is used for notification.  Very rough thought now, has to be enlarged upon.

**Comment by dshulyak** [comment]
It seems that all epics are at first described at status-im/ideas, with higher levels goals and at least general design. This is why I wanted to close this one.

And secondly, adding light swarm client to status-go and using pss for a chat should be at least two separate issues in my opinion.

**Comment by themue** [comment]
Yes, correct. So label should be better "should be closed after both ideas have been added". Should have made this more clear.

**Comment by mandrigin** [comment]
We are investigating it as a part of https://github.com/status-im/ideas/issues/84
So closing this issue.
