### ISSUE TITLE
Optimization of status-go

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-go#218]
Victor Notes:
1. there are issues reported with iPhone4 (constant crashes)
2. additionally, when provided CHT block gets older - we start seeing syncing problem
3. we need to improve memory footprint of the exposed statusd node (tweaking cache is your first stop, obviously)

**Comment by dshulyak** [comment]
I would close it and track epics in status-im/ideas

**Comment by adambabik** [comment]
As far as I know, all points are covered in other epics.
