### ISSUE TITLE
Fix and refactor tests

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#220]
@adambabik:
> no clear distinction between unit, integration and e2e tests. E.g. unit tests calls the network and it should not happen, lots of geth logs when running unit tests which make them hard to debug.

Moreover, our tests fail due to several reasons:
1. Peers availability at the moment of running a function: `no suitable peers available`.
2. Lack of time to synchronise the whole blockchain: `nonce too low`, `insufficient funds ...`.
3. Race conditions from #176: `leveldb: closed`.

All of that is unreliable and we should make tests reliable and reproducible.

We'll have to work on scopes of different test types and refactor tests so that:
1. Types of tests are clearly defined.
2. Unit tests are fast to run and doesn't call any external dependencies.
3. There's a clear way to run unit and integration tests separately.
4. The outputs after running tests is clear to read and helps you understand where the error is (probably, there should be a way to define the verboseness of them as a cli argument).
5. Each test is comprehensive. Currently, every test is really loong and set up differently. We need to change it: every tests should be set up easily, it must be short and it's logic must be easily followed.
6. Tests run on CI should be more verbose than those run locally (locally you either run your own new tests, or can increase verbosity on demand).

Some concrete ideas for refactoring:
1. Separate e2e tests on a public testnet from our unittesting which had better be done on our private net.
2. Refactor tests from `./cmd/statusd`: move them from `utils.go` to normal tests. The idea is to have application Facade tested separately from go bindings. The latter should be tester with either mocked StatusAPI or just with e2e tests.
~~3. Save a local version of https://gist.githubusercontent.com/tiabc/83ed515fbb0c0e9d39700a6279072b6a/raw/a8c7b08488fab3c1d9139b18af33da3df823e3ff/cht.json?u=1501859652 to avoid failing tests due to bad connection behavior.~~ (resolved in #270).
4. I believe logic for failing after a certain timeout shouldn't clutter tests and must be handled with the `-timeout` flag rather than with timeout handling in every possible test.
5. E2e tests that require some prerequisites, like specific amount of ETH or fully synced blockchain, should report if those prerequisites are met before executing.
6. Having the following pipeline is a good idea:
- unit tests;
- integration tests on private chain;
- integration tests on public test chain (or on every existing).

See testing notes: https://gist.github.com/jeluard/4564c04f118b1cfa828ffe741811b0aa

TODO: This issue looks like an epic for reliable testing. Worth making it epic?

**Comment by adambabik** [comment]
Is it possible to create a small private ethereum network? E.g. run a bunch of processes and test against that network? It would be reliable and deterministic because each tests run would start with the same block id. Of course, in the next step (e.g. if a PR merges to master), the CI system should run the tests against the public testnet.

**Comment by tiabc** [comment]
@adambabik, yes, it's possible and this is stated in idea for refactoring 1 :)
I also sometimes saw that in one test blockchain synchronisation was completed and in the other test it was started over again either from scratch, or from the known CHT root, not sure which.

Yeah, agree about public net. We can also run them on push, not necessarily on pr and run tests again the private net locally. Currently we have plenty of time on ci so nothing to worry about.

**Comment by tiabc** [comment]
This should be removed from milestone 1 as this issue has grown into a giant requiring tremendous amount of work and none of its parts is quickly resolvable.

**Comment by tiabc** [comment]
Closing as it's already been implemented in other issues and already in `develop`.
