### ISSUE TITLE
Refactor logging

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#221]
@adambabik:
> Logs from status-go and geth are mixed

We should make logs easy to read and distinguish which of them are Geth's and which are Status's. Internally there should probably be a separate logger for Status.

**Comment by MarinX** [comment]
Just a note.
This `status-go` packages uses `go-ethereum` log and should be replaced by using new logger.

- geth/params/config.go
- geth/api/backend_test.go
- geth/api/backend_jail_test.go
- geth/api/api_test.go
- geth/api/backend_txqueue_test.go
- geth/api/backend.go
- geth/node/node.go
- geth/node/signals.go
- geth/node/rpc_test.go
- geth/node/manager.go
- geth/node/manager_test.go
- geth/node/rpc.go
- geth/node/utils.go
- geth/common/logger.go
- geth/common/logger_test.go
- geth/common/utils.go
- geth/jail/jail.go

**Comment by MarinX** [comment]
#235
