### ISSUE TITLE
Opt-in metrics should not store metrics until consent is given

### ISSUE THREAD

**Issue by arnetheduck** [status-im/status-go#2227]
# Problem

https://github.com/status-im/status-go/blob/91620b9982e930c55e29b2e3a3df574032991f33/_docs/app-metrics.md#opt-in-system

The documentation states that metrics will be collected and stored before the user has opted in to do so - this creates a problematic situation where the metrics may leak information prior to consent should the phone be lost or malware gets access to the storage.

It also wastes phone resources unnecessarily.

A more safe solution would be to keep the entire metrics subsystem completely disabled until opt-in has happened - this would also make sure that bugs in the collection or distribution don't affect "normal" usage.

**Comment by shivekkhurana** [comment]
This option was kept to capture critical onboarding data. The metrics in question are only stored in-memory, until the user opts-in. And the opt-in banner is visible as soon as the user logs in. 

In case the user does't opt-in, the metrics will be deleted. If the user closes the app before logging in, the metrics will be deleted.
