### ISSUE TITLE
Add peer connection status support for Wakuv2

### ISSUE THREAD

**Issue by vitvly** [status-im/status-go#2280]
# Problem

Since Wakuv2 support has been merged into status-go, we don't have peer information available. Hence mobile client has to temporarily include a hardcoded conditional, whereby we always assume we're connected to some peers if using Wakuv2.

# Implementation

Now that go-waku has some support for peer management merged (https://github.com/status-im/go-waku/pull/30), it is necessary to make it available to status-go.

Also, as the Waku spec for peer management is now available (https://rfc.vac.dev/spec/27), some changes might be needed in go-waku to reflect the spec.

**Comment by oskarth** [comment]
It is worth noting that the 27/WAKU2-PEERS spec is a set of recommendations, and not strict requirements per se. They are up to each node and client, and e.g. go-libp2p might have more help when it comes to things like robust connection management, etc.

From what I recall, the main two requirements mentioned from Core in the past are to know (i) if you are connected to a relay node (ii) if you are connected to a store node. It might be a good idea to prioritize which of the recommendations in the spec make sense for Core, especially in light of enabling dogfooding and testing. Additionally, if there are more requirements that aren't already captured these can feed back into the spec.

**Comment by vitvly** [comment]
@oskarth thanks, this is good to know! As suggested by @cammellos earlier, i've added `IsOnline`/`HasHistory` boolean flags to go-waku. This seems to be most important for the client now.
