### ISSUE TITLE
Log rotate

### ISSUE THREAD

**Issue by MarinX** [status-im/status-go#229]
Currently, `go-ethereum` log package does not support log rotating which can be issue on mobile devices.

The `go-ethereum` logger depends on the package [log15](github.com/inconshreveable/log15)

**Comment by tiabc** [comment]
@rasom do we allow status-go log output on mobile devices at all?

**Comment by pedropombeiro** [comment]
Regarding log15 and log rotation, this might be useful: https://github.com/inconshreveable/log15/issues/133

@tiabc I wouldn't mind picking this up, but am wondering why this has been open for such a long time.

**Comment by pedropombeiro** [comment]
I'm almost finished with this GHI, just in case. It seems that geth log output is disabled by default by status-react: https://github.com/status-im/status-react/blob/develop/modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java#L180. I've asked [a question](https://github.com/status-im/status-react/pull/2803#issuecomment-353984101) related to another PR of mine, in case we want to enable geth logging by default, now that the level can be controlled independently by a feature flag.
