### ISSUE TITLE
Extend documentation about go-ethereum changes

### ISSUE THREAD

**Issue by themue** [status-im/status-go#233]
Add more information about _where_ and _why_ `go-ethereum` has been changed by status.

Document is in according wiki at https://github.com/status-im/go-ethereum/wiki/%5BWIP%5D-Rebase-Geth-1.6.7-stable.

**Comment by adambabik** [comment]
More details can be found here: https://github.com/status-im/go-ethereum/wiki/Rebase-Geth-1.7.0

The way we apply patches will change in https://github.com/status-im/status-go/pull/492 with [a Readme included](https://github.com/status-im/status-go/blob/adf7895549037bea5cc287636acb2e1236c56b44/geth-patches/README.md)
