### ISSUE TITLE
reorderCommunityChat doesn't seem to update positions correctly when chat is moved to different category

### ISSUE THREAD

**Issue by 0x-r4bbit** [status-im/status-go#2376]
# Problem

When a chat item is moved from one category into a different one at the **same** position as it was in the previous category, new positions for all chat items in the new category aren't recalculated correctly.

Here's an example. Assuming a chat structure like this:

```
- category1
  - chat1 (p0) // position 0
  - chat2 (p1)
  - chat3 (p2)
- category2
  - chat1 (p0)
  - chat2 (p1)
  - chat3 (p2)
```

Now imagine, the user moves `chat3` of `category2` which is at `p2` to `category1` at `p2`. This will eventually call `insertAndSort` (https://github.com/status-im/status-go/blob/89251e841655082076ef304791b9ee3145f337c2/protocol/communities/community_categories.go#L260).

The resulting signal contains the community with a list that looks like this:

```
- category1
  - chat1 (p0) // position 0
  - chat2 (p1)
  - chat3 (p2) // position 2
  - chat3 (p2) // also position 2
- category2
  - chat1 (p0)
  - chat2 (p1)
```

We can "fix" this by performing a `reorderCommunityChat` within **the same** category, causing a simple sort. In that case, the resulting signal will have a list with chats where each `position` is unique again.

I assume that there's a bug in `inserAndSort()` which is supposed to insert the chat to the new category and then perform the sorting. It should probably take into account that the new chat can have the same `position` as the new `position` it wants to be put in.

Also **this is not happening** when the position was different in the first place. For example, instead of moving `chat3 (p3)` to `category1` at `p3`, to `category1` at `p2`, the resulting positions are correct.

**Comment by richard-ramos** [comment]
https://github.com/status-im/status-go/pull/2448 probably fixed this issue!

**Comment by 0x-r4bbit** [comment]
NICE!!

**Comment by Parveshdhull** [comment]
> #2448 probably fixed this issue!

Yup, this fixed the issue. Tested in https://github.com/status-im/status-react/pull/12854. Thanks
