### ISSUE TITLE
Outline actual cross-projects architecture

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#238]
Overall architecture is necessary to ensure we're all on the same page and where different integration problems may arise. This is also the first step to facilitate QA test `status-go`.

Infrastructure documentation would also be nice: how the project is built, how it communicates with `status-react` (and development workflow of that) and what our scaleway cluster is used for.

**Comment by tiabc** [comment]
In slack:
> So high-level design is the following. `status-go` is cross-compiled for every platform using xgo. `status-react` calls it through JNI using signals defined in `library.go`. Those signals invoke `StatusAPI` which is our application Facade.
> 
> Under the hood, it contains different structures moved from `go-ethereum` and modified for our needs. We also have our customised version of `go-ethereum`:  https://github.com/status-im/go-ethereum/commits/status/1.6.7-stable and an issue to figure out which changes are still required and get rid of the rest: https://github.com/status-im/status-go/issues/238
> 
> As to your question about regression tests, we're only starting to let test team in our project and have an issue about that: https://github.com/status-im/status-go/issues/239
> 
> One important concept is our js jail. It's an isolated environment for JS code execution based on Otto VM. Jail consists of multiple jail cells - each refers to a particular chat in `status-react`. `status-react` (or dapp, user or user bot) can execute arbitrary JS in chat. All that calls are executed in our jail cells.
> Details on bindings `status-react` uses can be found here: https://github.com/status-im/status-go/wiki/Notes-on-Bindings
> 
> This is what I find most important things. You may glance through the ongoing issues on the zenhub board (once you have github access) and have a feeling what's currently going on. Meanwhile, you can familiarise yourself with pull requests.
> 
> Questions are welcome. By asking them you'll help to document the existing architecture from a newcomer's point of view.

**Comment by divan** [comment]
Some initial design drawing is here: https://docs.google.com/drawings/d/1D2wukqYWockdMe3zQK4Y600nAIxp9weV5AdWCuCtzgI/edit

**Comment by gruberb** [comment]
@divan Are those drawings available without having to have a  Google account?

**Comment by divan** [comment]
@gruberb I’m afraid not. They’re also aren’t complete yet. I should probably review it and prepare for usage with wiki.

**Comment by pedropombeiro** [comment]
@divan what should we do with this issue? It's been open for months now, should it be closed?

**Comment by skyf0cker** [comment]
> Some initial design drawing is here (WIP): https://docs.google.com/drawings/d/1D2wukqYWockdMe3zQK4Y600nAIxp9weV5AdWCuCtzgI/edit

The link is broken now, can you give a new link? @divan
