### ISSUE TITLE
Implement Java transport to call status-go bindings for QA

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#239]
# Problem

The QA team needs to test status-go functionality and has no way of doing that.

They need:
1. A simple interface to call status-go functions.
2. Automate their acceptance tests based on some scenarios.

# Implementation

Implement (or steal from status-react) a Java application which is capable of invoking status-go bindings with a JSON RPC interface.

# Acceptance Criteria

1. The QA team can invoke arbitrary status-go bindings.
2. They're able to write automated tests (say, with Python) against status-go bindings.
3. status-go bindings are invoked the very same way as in production (through JNI).
4. There's written documentation on how to use the Java application to call status-go bindings and how to update the Java app if status-go bindings added, changed or removed.

**Comment by adambabik** [comment]
I image that this interactive console could have a similar interface to `geth attach/console` so that exposed bindings could be called like this:

```
$ statusd console
> StartNode(configJSON)
{"status": true}
> CallRPC(input)
...
```

Also, to clarify, this issue is not about interacting with `status-go` running on a device/simulator but rather running it as a process on a host machine?

**Comment by tiabc** [comment]
The point here is not to over-complicate things. `geth attach` is fine if it's done faster than some cli-based tool or an RPC server.

I think the first step is definitely to just run it on a host machine. @annadanchenko, please, consult here how you see that.

**Comment by annadanchenko** [comment]
@adambabik @tiabc I'm fine with running status-go on host machine.

**Comment by adambabik** [comment]
I wonder if this should be really the Test Team responsibility at all. In my opinion, a more effective would be adding a contract testing between status-go and status-react. It would work this way:
1. Clojure Team creates a contract file which describes their requirements,
2. status-react is run against the contract to make sure it's still valid (or to generate one),
3. status-go is run against the contract file and gets validated.

If we move this responsibility to the Test Team, we will make the teams more dependent on each other instead of relaxing the dependency. It will require quite a lot of syncs to make those scenarios close to reality.

**Comment by tiabc** [comment]
Sorry, what shouldn't be the test team's responsibility? They need that interface to run their acceptance tests and test things manually.

I really like what you're suggesting but you're solving other problem, not the one stated in the description, as I understand. I totally agree that we need to test a contract between our applications but this is not what the test team will be testing, this is what we should provide and what should work by default.

**Comment by adambabik** [comment]
I guess I don't fully understand what those scenarios will be and how they will be different from status-go e2e tests. The only difference I see is that we run e2e tests directly using the API and the Test Team will use bindings. Will those scenarios be more complex versions of our e2e tests? What kind of bugs do we want to eliminate with those scenarios?

**Comment by tiabc** [comment]
Yes, that's the first difference. I'm not sure about concrete scenarios but the test team need to test status-go somehow, this is why they need it. @annadanchenko may advise on concrete scenarios, I think.

What kind of bugs? As I understand, any bugs mostly related to business logic and some subtleties of operation. I also think they're going to test our contract and ensure we haven't changed anything critical. In the end, they can run some manual tests which we'll either include into our e2e tests or they'll include them into their acceptance tests.

Generally, as they're responsible for quality, they should have a possibility to ensure the functionality we provide complies to their quality requirements. Finally, I wouldn't say we cover many cases in our tests.

**Comment by tiabc** [comment]
It's important but not so important, decreasing priority.

**Comment by pedropombeiro** [comment]
@tiabc, @annadanchenko if the goal is to be able to test as close as possible to the production setup, is there a reason why something like https://github.com/kivy/pyjnius couldn't be used to access the bindings from Python by leveraging the Android package generated by xgo? It's not something I have experience with, but which I came across while investigating this issue, and I was able to create a `Statusgo` class instance from Python by taking the `statusgo-android-16.aar` package and extracting `classes.jar` from it:

![image](https://user-images.githubusercontent.com/138074/34297261-66a30cf2-e717-11e7-9dc8-6302d6c12088.png)

If this is enough for QA's needs, it looks like it would be the most flexible option with the lowest investment.

**Comment by dshulyak** [comment]
I completely don't understand this issue. Why java bindings are required to write tests in python?)
I would assume that for e2e tests I will need to start statusd (that exposes jsonrpc api) and use https://github.com/ethereum/web3.py if I want to write tests in python.

What am I missing?

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/web3.py">ethereum/web3.py</a></strong></div><div>web3.py - A python interface for interacting with the Ethereum blockchain and ecosystem.</div></blockquote>

**Comment by pedropombeiro** [comment]
I think the idea is to actually exercise our `Statusgo` bridge, not just the code behind it.

**Comment by mandrigin** [comment]
But if we call Java methods, isn't ObjC part still uncovered?

**Comment by dshulyak** [comment]
@PombeirP thanks, makes sense

**Comment by adambabik** [comment]
It's not about Java or Objective-C glue code but only C bindings like `StartNode()` in status-go. However, I am not sure who came up with this idea and if it ever was considered as something really useful for anyone.

I think we can close it and create a new issue when someone will describe requirements and objectives.
