### ISSUE TITLE
Tests refactoring: reliable blockchain synchronisation

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#246]
Ensure blockchain synchronisation is reliably finished before tests are run.

Acceptance criteria:
1. All tests requiring synchronised blockchain are only run after blockchain has been fully synchronised.
2. Blockchain synchronisation indication is done reliably, i.e. using polling to `eth.syncing` and `eth.isSyncing` instead of `time.Sleep()`.
3. Blockchain is only synchronised for the first test (not for every one) and cached for the others.
4. Some tests reset `chaindata`. For such tests it's required to copy the chaindata in a separate directory and run that test there.

TODO: Pick the next step for tests reliability from #220.

**Comment by tiabc** [comment]
@oleg-raev (side contributor) is looking into that.

**Comment by influx6** [comment]
@tiabc Can I get code points/lines where the test/code resets the synchronized blockchain data?

**Comment by influx6** [comment]
After testing abit, the current approach in my mind as an initial resolution of sync status is to query `eth_syncing` method over the ethereum JSON API. We will need a periodic check atleast till sync is done for now, Polling basically. (see https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_syncing).

The `eth.isSyncing` is good but am not sure how well we can lock a callback has this might need us to utilize jail, though according to documentation, it simply adds a callback to listening to sync progress during starts/stops. (see https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethissyncing)

**Comment by tiabc** [comment]
@influx6 don't forget that it should work for both cases:
1. When sync hasn't yet started.
2. When it started but not finished.

**Comment by influx6** [comment]
@tiabc Yes, true. When syncing indeed has begun we will receive objects has response for `eth_syncing`, currently it we can know using the poll method when it's already started and syncing, since we get continuous feedback as to current sync state.

We will naturally have to hook up into the part that registers for synchronization to account for when the synchronization is expected to start, if local ethereum node is enable. 

I suspect the area that sets for synchronization is here: https://github.com/status-im/status-go/blob/develop/geth/node/node.go#L152-L184, please correct if wrong.

**Comment by influx6** [comment]
There was a better way discovered around https://github.com/status-im/status-go/blob/develop/vendor/github.com/ethereum/go-ethereum/les/api_backend.go#L133-L135 and https://github.com/status-im/status-go/blob/develop/vendor/github.com/ethereum/go-ethereum/eth/downloader/downloader.go#L243-L269.

They do provide a far more reliable means of validating start and progress of node synchronization.

**Comment by influx6** [comment]
@tiabc i will need further clearification on this area:

```Some tests reset chaindata. For such tests it's required to copy the chaindata in a separate directory and run that test there.```

Do I refactor the code to copy the chain data from the current one into a new place to ensure it reuses the data? Currently previous chain data is utterly deleted.

See https://github.com/status-im/status-go/blob/develop/geth/node/manager.go#L323-L328

**Comment by tiabc** [comment]
Replied in the pull request.
