### ISSUE TITLE
Implement an initial version of push notifications

### ISSUE THREAD

**Issue by sla-shi** [status-im/status-go#249]
So the first step towards push notifications implementation is having an initial version up-and-running to improve upon. For that purpose we'll keep it really simple and only implement it:
1. For 1-1 chats (only in case group chats add significant complexity).
2. Payload is sent and stored unencrypted (only in case basic encryption adds significant complexity).
3. Random thoughts on future push notifications improvement are also welcome.

Steps:

1. Complete #222 - delivery protocol, push notifications included.
2. Complete #206 -Regression tests + functional tests of the chat to include push notifications
3. Modify status-cluster to launch notification server
4. Firebase Setup

To improve
- Refactor notification service
- Payload encryption (double rachet)
- Authentication elements of the repository should be turned to private

**Comment by influx6** [comment]
Though abit unrelated to firebase, but might help to provide ideas on encryption of messages between end to end users and if possible transfer such ideas into firebase.

https://medium.com/@wireapp/the-challenge-of-implementing-ios-share-extension-for-end-to-end-encrypted-messenger-dd33b52b1e97

**Comment by tiabc** [comment]
Decreasing priority as push notifications has been spiked for status-react and now only ongoing work is expected.

**Comment by dshulyak** [comment]
Safe to close and reopen if will there will a requirement for it

**Comment by mandrigin** [comment]
replaced with https://github.com/status-im/ideas/issues/86
