### ISSUE TITLE
Introduce a new signal StopNodeAsync

### ISSUE THREAD

**Issue by MarinX** [status-im/status-go#254]
Exported method `library.go`
`
func StopNode() *C.char
`

There is currently no way to check when node is stop. (only error is returned).
We should find a way to stop node synchronously and introduce(maybe?) a new signal StopNodeAsync.

For now its causing issue in testing when we need to stop node.

**Comment by tiabc** [comment]
Currently, `StopNode` stops the node asynchronously.

Now `StopNode` will stop the node synchronously and asynchronous stop will be handled by a new signal: `StopNodeAsync`.

We'll only provide a new signal under this issue and wait until you switch to it before changing `StopNode` to stop the node synchronously.

@rasom what do you think about this API change?

**Comment by tiabc** [comment]
The same should be done for the `StartNode` signal.

**Comment by tiabc** [comment]
Increasing priority as it actually needs to be done to make tests 19 seconds faster.

**Comment by divan** [comment]
@tiabc any chance to agree on only one behaviour (sync or async) of Start/Stop Node public calls so it fits both status-react and our tests needs?

**Comment by tiabc** [comment]
@divan let's raise this question after devcon.

**Comment by MiguelMoll** [comment]
I was wondering if any design decisions have been made to move this ticket forward. Would make it easier to gauge what everyone has in mind here.

**Comment by tiabc** [comment]
Well, we're actively removing C code from our tests so this issue seem no longer. Thanks for asking, @MiguelMoll :)
