### ISSUE TITLE
Refactor access with proper mutex guard

### ISSUE THREAD

**Issue by influx6** [status-im/status-go#258]
Currently we have in `geth/node/manager.go` (see https://github.com/status-im/status-go/blob/develop/geth/node/manager.go#L35-L45), where we have both intention in code to guard synchronous access to most fields through the embedded mutex.

## Problem
But we currently have in https://github.com/status-im/status-go/blob/develop/geth/node/manager.go#L69-L71 and in many other areas within code where access to `NodeManager.node` is initially accessed without mutex guard to ensure synch access.

## Issues
We could later face issues with race conditions on access to the `NodeManager.node` field and other fields that maybe concurrently reacehed directly or indirectly.

## Fix
We need to refactor this package to ensure proper synchronouse access to the `NodeManager.node`and other fields as intended, else re-arrange `NodeManager` struct fields to ensure quick intention has to fields which mutex guards.

**Comment by JekaMas** [comment]
Actually we already got a lot of dara races in `node/manager.go`, `node/node.go` and `node/utils.go`.
I think we should turn on a data race detector in `ci`.

**Comment by tiabc** [comment]
https://github.com/status-im/status-go/issues/50

**Comment by JekaMas** [comment]
I done most of [403](https://github.com/status-im/status-go/issues/403) to complite this task:

- NodeManager is simplified
- Some e2e tests are added
- There are no race conditions when running unit tests with -race.
- NodeManager is thread-safe

**Comment by mandrigin** [comment]
@divan @adambabik closing in favour of https://github.com/status-im/ideas/issues/63
