### ISSUE TITLE
Remove dependency on cht.js hosted in Github

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#267]
When Github is down, the app can't be started because it depends on `cht.js` file located in https://gist.githubusercontent.com/tiabc/83ed515fbb0c0e9d39700a6279072b6a/raw/a8c7b08488fab3c1d9139b18af33da3df823e3ff/cht.json.

AC:
* `cht.json` hosted on Github is deprecated and won't be updated after this issue is resolved but it will stay for backward compatibility,
* `cht.json` will be embedded into a release in order to avoid centralization and GH being unavailable.

**Comment by adambabik** [comment]
Might be related to https://github.com/status-im/status-go/issues/242 as if the file is not accessible, `{"error":"there is no running node"}` is displayed.

**Comment by jarradh** [comment]
cht.json should also have a locally included resource as a fallback, and if it timesout completely then syncing can happen from 0%

We certainly shouldn't have this as somethign that breaks the application

**Comment by tiabc** [comment]
Ideally, `cht.json` should be fetched from some CDN network, we shouldn't care about its availability and should fallback to some reasonable (the current) default configuration in case of failure.
