### ISSUE TITLE
Save status-go and geth logs to a file

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#268]
After refactoring logging, we disabled saving logs to a file. We must enable it as without that we have no insight into logs in a simulator or a device.

AC:
* if `LogFile` in `NodeConfig` is enabled (has a non-empty value), logs must be forwarded to that location,
* as `LogToStderr` is not used, change it to `LogToStdout` and if set to `true` print logs to stdout.

**Comment by adambabik** [comment]
**Q: How to find `geth.log` when using iOS Simulator?**

Run the app and go to `~/Library/Developer/CoreSimulator/Devices`. In there, there are directories with UUIDs of devices. The quickest way of finding the file is to run `find . -iname "geth.log"` as otherwise you need to figure out UUID of the device and the app.

**Comment by oskarth** [comment]
@adambabik Just FYI you can get a device list (name -> uuid) with `instruments -s devices`

**Comment by adambabik** [comment]
Nice tip! Thanks @oskarth

**Comment by tiabc** [comment]
Thanks, @divan, nice work!
