### ISSUE TITLE
Update group chat name once members list has been updated

### ISSUE THREAD

**Issue by noeliaSD** [status-im/status-go#2683]
# Problem

Once members in a group chat are changed (added or removed) the name of the group chat should be updated according to the [spec](https://github.com/status-im/feature-specs/pull/75/files#diff-5a7ebd63f774e80f5d46bb9fdd7175f4ecbf9c9464a4d9cc95d0b4bca94b9347R38)

**Comment by endulab** [comment]
I am not sure about it. Group chat's name can be changed and in this situation we should not change the chat's name.
I think that members names are rather used for setting initial name.

**Comment by noeliaSD** [comment]
> I am not sure about it. Group chat's name can be changed and in this situation we should not change the chat's name. I think that members names are rather used for setting initial name.

Looking at the current [spec](https://github.com/status-im/feature-specs/pull/75/files#diff-5a7ebd63f774e80f5d46bb9fdd7175f4ecbf9c9464a4d9cc95d0b4bca94b9347R38) I cannot see a specific rule that fits with this issue so, if you can confirm with @John-44 that it is not necessary, we can maybe specify it in the spec file and close the issue.
