### ISSUE TITLE
Status-project bot stopped adding new PRs to project

### ISSUE THREAD

**Issue by churik** [status-im/status-go#2692]
# Problem
Created https://github.com/status-im/status-go/pull/2691 to test flow of automatic adding new PR to https://github.com/status-im/status-go/projects/18#card-82284336 
According to the board, it stopped working somewhere near 24.05

# Acceptance Criteria
new PRs in https://github.com/status-im/status-go/ are automatically added to https://github.com/status-im/status-go/projects/18#card-82284336

**Comment by churik** [comment]
@jakubgs 🙏  when you have a time, please

**Comment by jakubgs** [comment]
I sad it here: https://github.com/status-im/status-go/issues/2676#issuecomment-1130238490

>The card __HAS TO BE__ either first or last in the column for it to work.

![image](https://user-images.githubusercontent.com/2212681/170511409-26268281-3e93-4527-b1b3-991981ad7c9a.png)

Looks like someone moved it.

**Comment by churik** [comment]
thank you
