### ISSUE TITLE
Share image/username on separate topic on a community

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#2707]
Users should subscribe to a separate topic when they join a community and they should periodically post their profile picture/ens names etc, in the same way as we do for their personal contact code topic.

### Implementation

I think most of it should be already implemented, we just need to make sure a user subscribes to that topic when joining a community, and that it publishes on it, in `publishContactCode`

**Comment by qfrank** [comment]
I’d like to have a try :)

**Comment by John-44** [comment]
Spoke to @cammellos , apparently @qfrank is currently working on another issue so @osmaczko would you be able to pick this issue up?  If you have any questions about this issue, I recommend pinging @prichodko
