### ISSUE TITLE
Prevent chaindata from infinitely growing on mobile devices

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#277]
Currently, there're no means of restricting chaindata from growing in size and it may become a problem if an application has been installed on a device for a long time and make users re-install the app to work around this.

Since we start blockchain synchronisation from a recent block, we can safely delete old chaindata and re-synchronise from the known CHT. This is the proposed solution.

**Comment by 0xc1c4da** [comment]
The core problem here was we should also preallocate disk space, or at least check if there is enough diskspace for chaindata

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xbfd19e199906b36e0e47609ae3f8053217665ed4924f08376919081f6c331357](https://etherscan.io/tx/0xbfd19e199906b36e0e47609ae3f8053217665ed4924f08376919081f6c331357)

**Comment by mandrigin** [comment]
Let's discuss some of the implementation details, and I can try to make an acceptance criterion which is easily testable.

1. @jarradh, Should we panic if there isn't enough space? There should be some notification from the client-side as well... We don't want to silently crash if there isn't enough disk space.

2. As I understand, we need to have some "budget" for disk space (as a parameter, probably), so if we are exceeding it, we are removing the old chain and re-sync again. Is that close to being true? @adambabik @divan @themue

**Comment by themue** [comment]
IMHO it could be done with a kind of caching. Keep only the newest blocks in memory, even more cached headers, and then reload blocks on demand. Don't know how easy this could be implemented, but would try it this way as I don't expect a light client needing many blocks at the same time.

**Comment by divan** [comment]
@mandrigin the disc usage pattern by geth is something that needs to be investigated within this issue, I guess. New geth releases may have different disc space requirement/usage patterns, so if the solution will be implemented in status-go code, it needs to be syncronized.

**Comment by pablanopete** [comment]
@divan @themue what size bounty should this be?

**Comment by themue** [comment]
As mentioned on Slack LES caching in memory is limited but there's right now no garbage collection for the disk db. Zsolt said it is "not yet" implemented, so I'm currently checking the concrete plans with him.
