### ISSUE TITLE
Make errors contain error code along with an error message

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#278]
@jeluard:
> Regarding #242, on status side we only get an error message as a string. It would help us to have some error code to generate a proper message client side.

All error responses to status-react must start sending an error code.

There's a document accessible for editing by StatusIM members with the specification: https://goo.gl/gQ1CDK

**Comment by tiabc** [comment]
Closing as it's part of #408

**Comment by mandrigin** [comment]
@divan @adambabik since #408 is quite a big issue, and this one is fairly well defined, maybe we can reopen it and give it away as a bounty?

**Comment by mandrigin** [comment]
(for some context, I just stumbled upon a TODO in https://github.com/status-im/status-react/blob/develop/src/status_im/ui/screens/accounts/login/views.cljs#L30)

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by adambabik** [comment]
I am not sure we should tackle it now. I would even strengthen this statement that any work related to bindings is not a priority now. We should migrate to gomobile and design all bindings from scratch with required improvements like error codes.
