### ISSUE TITLE
accounts can't login in latest develop

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#282]
so i have account, it was created in ropsten and i can't login 

`Logged in account:  {"error":"cannot retrieve a valid key for a given account: no key for given address or file"}`

Steps to reproduce
1. Using release version of status-go, create new account
2. Change status-go on latest develop
3. Try to login

**Comment by tiabc** [comment]
@flexsurfer feel free to re-open if the issue reproduces.
