### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread

### ISSUE THREAD

**Issue by cytl5yy** [status-im/status-go#286]
when i add statusgo-android-16.aar to android project , i call  Statusgo.StartNode(config) function to sync chaindata ,the demo crash and the log show "A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread", what the problem?    the function Statusgo.GenerateConfig(dataFolder, 3,1)  can normal call.

**Comment by tiabc** [comment]
Could you provide a step-by-step description of what exactly you're doing? We use bindings in our build perfectly fine.

**Comment by cytl5yy** [comment]
I clone the status-go project to my mac pc,  and set up docker  , then i follow the doc and use command "make statusgo-android"  to build ,finally  statusgo-android-16.aar will be created . I use the  statusgo-android-16.aar for my demo  and call  Statusgo.StartNode(config) function in my code ,some times later ,the demo crash and the log show "A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread"

**Comment by tiabc** [comment]
1. What branch are you using? Could you try the latest `develop` and say if it's helped? It still has some issues but this problem may already be fixed.
2. What's the config you're trying to run the node with?

**Comment by cytl5yy** [comment]
I check the branch it is really * develop  .   the full code is ：
private void doStartNode() {
        String root = getApplicationInfo().dataDir;
        String dataFolder = root + "/ethereum/testnet";
        Log.d(TAG, "Starting Geth node in folder: " + dataFolder);

        try {
            final File newFile = new File(dataFolder);
            // todo handle error?
            newFile.mkdir();
        } catch (Exception e) {
            Log.e(TAG, "error making folder: " + dataFolder, e);
        }

        final String ropstenFlagPath = root + "/ropsten_flag";
        final File ropstenFlag = new File(ropstenFlagPath);
        if (!ropstenFlag.exists()) {
            try {
                final String chaindDataFolderPath = dataFolder + "/StatusIM/lightchaindata";
                final File lightChainFolder = new File(chaindDataFolderPath);
                if (lightChainFolder.isDirectory()) {
                    String[] children = lightChainFolder.list();
                    for (int i = 0; i < children.length; i++) {
                        new File(lightChainFolder, children[i]).delete();
                    }
                }
                lightChainFolder.delete();
                ropstenFlag.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        String config;
        String defaultConfig = Statusgo.GenerateConfig(dataFolder, 3,1);
        try {
            JSONObject jsonConfig = new JSONObject(defaultConfig);
            String gethLogFileName = "geth.log";
            jsonConfig.put("LogEnabled", true);
            jsonConfig.put("LogFile", gethLogFileName);
            jsonConfig.put("LogLevel", "DEBUG");
            jsonConfig.put("WSHost", "47.92.143.72");
            String gethLogPath = dataFolder + "/" + gethLogFileName;
            File logFile = new File(gethLogPath);
            if (logFile.exists()) {
                logFile.delete();
            }
            try {
                logFile.setReadable(true);
                File parent = logFile.getParentFile();
                if (!parent.exists()) {
                    parent.mkdirs();
                }
                logFile.createNewFile();
                logFile.setReadable(true);
            } catch (Exception e) {
                Log.d(TAG, "Can't create geth.log file!");
            }
            Uri gethLogUri = Uri.fromFile(logFile);
            try {
                Log.d(TAG, "Attach to geth.log to instabug " + gethLogUri.getPath());
//                Instabug.setFileAttachment(gethLogUri, gethLogFileName);
            } catch (NullPointerException e) {
                Log.d(TAG, "Instabug is not initialized!");
            }

            config = jsonConfig.toString();
        } catch (JSONException e) {
            Log.d(TAG, "Something went wrong " + e.getMessage());
            Log.d(TAG, "Default configuration will be used");

            config = defaultConfig;
        }
        String r = Statusgo.StartNode(config);
        Log.d(TAG, "Geth node started    "+r);
    }
the ip  47.92.143.72  is my  geth ,it is runing normal ..     if your  statusgo-android-16.aar is ok ,can you give it to me  .my email is 370385665@qq.com    thanks!

**Comment by cytl5yy** [comment]
I have other problem ,i test it for ios,and  sync the light chain, but i don't know how to get the progress ,can you help me .
