### ISSUE TITLE
desktop: can't accept contact requests

### ISSUE THREAD

**Issue by caybro** [status-im/status-go#2940]
# Problem

Likely a recent regression; trying to accept a contact request fails with this message:

```
ERR 2022-11-03 15:44:48.924+03:00 an error occurred while accepting contact request topics="contacts-service" tid=14134 file=service.nim:425 msg="\nstatus-go error [methodName:wakuext_acceptLatestContactRequestForContact, code:-32000, message:record not found ]\n"
```

status-desktop version: master (d147d7058e4a300c2e6b0bb2ce0a67ce92c8a7aa)
status-go version: v0.97.3-335-g956534210 (956534210111815202ba001bbc69a3411ebbb429)

**Comment by caybro** [comment]
Might be because of the recently introduced support for compressed keys (CC @endulab)

**Comment by 0x-r4bbit** [comment]
I just tried reproducing this with two instances of desktop using status-go `f33c1cec3` which is a good handful of commits ahead of the version you were using.

@caybro can you please verify if this is still an issue latest `develop` of status-go?
Otherwise I think this can be closed.

**Comment by caybro** [comment]
> I just tried reproducing this with two instances of desktop using status-go `f33c1cec3` which is a good handful of commits ahead of the version you were using.
> 
> @caybro can you please verify if this is still an issue latest `develop` of status-go? Otherwise I think this can be closed.

@PascalPrecht latest desktop master, status-go/develop, I'm still getting the same error message:
```
DBG 2022-11-09 12:22:23.162+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=38037 file=core.nim:20 rpc_method=wakuext_acceptLatestContactRequestForContact
ERR 2022-11-09 12:22:23.164+01:00 rpc response error                         topics="rpc" tid=38037 file=core.nim:29 err="\nstatus-go error [methodName:wakuext_acceptLatestContactRequestForContact, code:-32000, message:record not found ]\n"
ERR 2022-11-09 12:22:23.165+01:00 an error occurred while accepting contact request topics="contacts-service" tid=38037 file=service.nim:425 msg="\nstatus-go error [methodName:wakuext_acceptLatestContactRequestForContact, code:-32000, message:record not found ]\n"
DBG 2022-11-09 12:22:23.165+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=38037 file=core.nim:20 rpc_method=wakuext_getLatestVerificationRequestFrom
```

**Comment by caybro** [comment]
For the record, dismissing fails with a similar message:
```
DBG 2022-11-09 12:26:23.852+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=38037 file=core.nim:20 rpc_method=wakuext_dismissLatestContactRequestForContact
ERR 2022-11-09 12:26:23.854+01:00 rpc response error                         topics="rpc" tid=38037 file=core.nim:29 err="\nstatus-go error [methodName:wakuext_dismissLatestContactRequestForContact, code:-32000, message:record not found ]\n"
ERR 2022-11-09 12:26:23.854+01:00 an error occurred while dismissing contact request topics="contacts-service" tid=38037 file=service.nim:441 msg="\nstatus-go error [methodName:wakuext_dismissLatestContactRequestForContact, code:-32000, message:record not found ]\n"
DBG 2022-11-09 12:26:23.854+01:00 NewBE_callPrivateRPC                       topics="rpc" tid=38037 file=core.nim:20 rpc_method=wakuext_getLatestVerificationRequestFrom
```

**Comment by 0x-r4bbit** [comment]
@caybro so be sure: This is with two clean instances of desktop running latest master/develop correct?

Cause otherwise it looks like you're just in an invalid state (maybe because of switching status-go versions in between).
The assumption is that users never switched status-go versions back and forth with would possibly cause such things.

So can you confirm the above?

**Comment by caybro** [comment]
> @caybro so be sure: This is with two clean instances of desktop running latest master/develop correct?
> 
> Cause otherwise it looks like you're just in an invalid state (maybe because of switching status-go versions in between). The assumption is that users never switched status-go versions back and forth with would possibly cause such things.
> 
> So can you confirm the above?

Yes but unsure how "clean" can I get. :) I definitely switched status-go versions a couple of times back and forth. I will retry with a clean data folder and report back

**Comment by 0x-r4bbit** [comment]
> Yes but unsure how "clean" can I get. :)

Yea, so, I think first to check if this is reproducible with a clean installation. Meaning, no status-go version hopping in the past that might cause corrupt data due to changes in code.

If this is not reproducible we can be fairly certain that this is an issue because you're database is in a broken state.

Lemme know how it goes.

**Comment by caybro** [comment]
Cannot reproduce on a freshly restored account
