### ISSUE TITLE
wakuv2: status-go should reconnect to discv5 bootstrap nodes (otherwise if it reaches 0 peers, it will never find peers again)

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#2941]

**Comment by rasom** [comment]
@richard-ramos reconnect when? When there is no connection to any bootstrap node or when it reaches 0 peers?

**Comment by rasom** [comment]
Tested on iOS/Android  (`status.prod` fleet, `EnableDiscV5=true`) and can not be reproduced on wifi/cellular, the app always reconnects to some peers after having 0 peers while offline.
