### ISSUE TITLE
Restart discovery when peer count is low

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#3063]
Currently on some machines the peer counts reaches 1 and stay that way until restart.

Discovery is only run once at start up, but when successful is not run anymore.

If the peer count gets low enough, discovery should be restarted. 

Please check as well about cached peers etc, to avoid unnecessary discovery.

**Comment by John-44** [comment]
peer count is too low = any time the peer count drops to 3 or less peers

**Comment by rasom** [comment]
Just got zero peers on mobile `develop`, doesn't look like the issue is fully fixed
