### ISSUE TITLE
TestReceiveReply failed sometimes

### ISSUE THREAD

**Issue by qfrank** [status-im/status-go#3070]
# Problem

when running [TestReceiveReply](https://github.com/qfrank/status-go/blob/0135ad942784cd66940d96cd2a3e53920bdb14e6/protocol/messenger_reply_test.go#L63) multi times in local(say 20 times, u can set -test.count=20), it may fail or success.
we may also check this fail on [jenkins](https://ci.status.im/blue/rest/organizations/jenkins/pipelines/status-go/pipelines/prs/pipelines/tests/branches/PR-3069/runs/2/nodes/34/steps/39/log/?start=0)

**Comment by qfrank** [comment]
hi @jrainville , could u take a look at this? thanks

**Comment by jrainville** [comment]
My bad I didn't realize it was flaky. I'll fix
