### ISSUE TITLE
Create a dedicated Jenkins node for status-go

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#309]
Currently, status-go shares the Jenkins instance with the status-react team. As the requirements of both teams are different, we should create a new Linux node in AWS (or similar) where status-go builds could be executed.

Acceptance criteria:
- a new Jenkins node runs Linux with the prepared environment (docker and Go installed),
- the new node is available in Jenkins master and can be used by jobs.

**Comment by tiabc** [comment]
We have yet unused nodes in our scaleway cluster, is it enough? If so, please, dm me with your public key.
Please, note that all deployments should be accomplished using Ansible and status-cluster repo. Please, check your access.

**Comment by adambabik** [comment]
Some global cloud provided could be more useful for us as the Test Team needs one more Jenkins node in the USA for Appium tests. Sauce Labs doesn't have a DC in Europe and tests are super slow.

**Comment by adambabik** [comment]
It's done. We have a dedicated Linux node on which status-go builds run.
