### ISSUE TITLE
sync contact may not working proberbly

### ISSUE THREAD

**Issue by qfrank** [status-im/status-go#3099]
Say we have 2 devices A and B.

**steps to reproduce:**
- login UserA on A, make UserA and UserB as mutual contact
- recover UserA on B using seed phrase
- advertise device on B
- select paired device corresponding B on A and press `Sync all device`

**expected:** 
  UserB should appear as contact on B

**actual behavior:**
  UserB won't appear as contact on B

status-mobile version: latest branch develop
status-mobile commit id: 14c9a7c6ac003542099e0436b59021b1ba9d60ad

status-go version: latest branch develop
status-go commit id: 5a4ca8863182d424a7ae6fdae85547763f70ac3f

[relate PR](https://github.com/status-im/status-mobile/pull/14763)

**Comment by qfrank** [comment]
FYI @pavloburykh

**Comment by pavloburykh** [comment]
@qfrank yeah, I have already checked in develop and see the problem. Its not only about contacts, but also some other data. We have discussed this problem on planning and agreed that I will log separate issue on that. Thank you!
