### ISSUE TITLE
add emoji-hash to `multiaccount` struct

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-go#3162]
# Problem
Emoji Hash is required for each profile, so its better if its also a part of the `multiaccount` struct.

##Note : 
We should keep the existing EmojiHash API as it is because Desktop Team is using it.

**Comment by vitvly** [comment]
It's been discussed during the recent call that it might be best to store chat subaccount's pubkey instead, and compute derived data (like `colorHash` or `emojiHash`) on-the-fly. This might present some security issues however, as the aforementioned pubkey will be stored in the unencrypted accounts table. For now waiting on the input from security team.

cc @Samyoul @cammellos
