### ISSUE TITLE
Upgrade of `PayloadSourceConfig` into a more robust config schema

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#3198]
## Details:

With the introduction of the below PRs we are including very specific context configurations of the pairing process. There are 4 contexts to consider:

- The device is a `Sender` *(bootstrapping another device)*
- The device is a `Receiver` *(being bootstrapped by another device)*
- The device should run a `PairingServer` *(the device exposing a tls server on the LAN)*
- The device should run a `PairingClient` *(the device connecting to a tls server on the LAN)*

A device maybe a :
- `SenderServer`
- `SenderClient`
- `ReceiverClient`
- `ReceiverServer`

The application needs a much more robust config to ensure the maintainability of the code.

## Possible Solution:

One potential solution to this issue is to create a new type of config and use a component pattern to batch specific expected configs together:

```go
type PairingSenderConfig struct {...}
type PairingReceiverConfig struct {...}
type PairingServerConfig struct {...}
type PairingClientConfig struct{...}

type PairingSenderServerConfig struct {
    PairingSenderConfig
    PairingServerConfig
}

type PairingSenderClientConfig struct {
    PairingSenderConfig
    PairingClientConfig
}

type PairingReceiverClientConfig struct {
    PairingReceiverConfig
    PairingClientConfig
}

type PairingReceiverServerConfig struct {
    PairingReceiverConfig
    PairingServerConfig
}
```

This means that changes specific to each config component only apply to the respective consuming configs, we are free to extend these elements, we keep a strict separation of concerns, we are free to add additional config components.

## More information:

See for more details :
- https://github.com/status-im/status-go/pull/3179/files#r1107080212
- https://github.com/status-im/status-go/pull/3179
- https://github.com/status-im/status-go/pull/3192
- https://github.com/status-im/status-go/pull/3202 (introduces additional config fields to be considered)

**Comment by qfrank** [comment]
my two cents, I don't think we need so many struct types(it makes me feel confusing😥), we only care its role is sender or receiver in our most logical code, so PairConfig(a global level config so we can reuse the configJSON passed by client)/PayloadSourceSenderConfig/PayloadSourceReceiverConfig should be enough 🤔

**Comment by qfrank** [comment]
I pushed a remote branch `refactor/local-pairing` , pls let me know WDYT 🫶 @Samyoul

**Comment by Samyoul** [comment]
We do care about `Server` role, because the timeout property is applicable to the only `Server` context, which is independent of the `Sender` / `Receiver` context.

**Comment by Samyoul** [comment]
Following on from a conversation with @qfrank we came to an agreement on the below required changes to pairing architecture.

Originally a `PayloadRepository` could be initiated using the same config for both modes. But now there is a distinct divergence between what a sender and what a receiver require to function.

Splitting the `PayloadRepository` interface should be done. It does mean that the types that embed a `PayloadRepository` will have need to embed the successor types: `PayloadLoader` and `PayloadReceiver`.

## Split `PayloadRepository` into `PayloadLoader` and `PayloadReceiver`

We can implement a component based architecture for the highest level types:

**Example:**

Split:

```go
type Client struct {
    *http.Client
    PayloadManager
    rawMessagePayloadManager *RawMessagePayloadManager

    baseAddress     *url.URL
    certPEM         []byte
    serverPK        *ecdsa.PublicKey
    serverMode      Mode
    serverCert      *x509.Certificate
    serverChallenge []byte
}
```

Into

```go
type PairingClient struct {
    *http.Client

    baseAddress     *url.URL
    certPEM         []byte
    serverPK        *ecdsa.PublicKey
    serverMode      Mode
    serverCert      *x509.Certificate
    serverChallenge []byte
}

type PairingClientSender struct {
    *PairingClient
    PayloadManagerSender
}

type PairingClientReceiver struct {
    *PairingClient
    PayloadManagerReceiver
}

type PayloadManager struct {
    logger         *zap.Logger
    accountPayload *AccountPayload
    *PayloadEncryptionManager
    accountPayloadMarshaller *AccountPayloadMarshaller
}

type PayloadManagerSender struct {
    *PayloadManager
    payloadSender PayloadSender
}

type PayloadManagerReceiver struct {
    *PayloadManager
    payloadReceiver PayloadReceiver
}
```

Obviously apply the same architecture to `Server` types

## Multiple `PayloadRepository`s in a Single `PayloadManger`

I notice your introduction of RawMessageRepository. Which is cool.

Perhaps we could implement handling for a PayloadManager that can have multiple Repository/Sender/Receiver types.
I see the necessity of having multiple repositories because you need to handled different payloads at different times, so you can't always send the payload on every Send call.

**Comment by Samyoul** [comment]
Currently the following endpoints exist, notice how nicely they line up with the suggested solution to this issue:

<table>
<tr>
<td> API Method </td> 
<td> Required Functionality </td>
<td> Proposed Config </td>
</tr>

<tr>
<td> `GetConnectionStringForBeingBootstrapped` </td>
<td> `pairing.Receiving` `pairing.PairingServer` </td>
<td>

```go
type PairingReceiverServerConfig struct {
    PairingReceiverConfig
    PairingServerConfig
}
```

</td>
</tr>

<tr>
<td> `GetConnectionStringForBootstrappingAnotherDevice` </td>
<td> `pairing.Sending` `pairing.PairingServer` </td>
<td>

```go
type PairingSenderServerConfig struct {
    PairingSenderConfig
    PairingServerConfig
}
```

</td>
</tr>

<tr>
<td> `InputConnectionStringForBootstrapping` </td>
<td> `pairing.Client` </td>
<td>

```go
type PairingSenderClientConfig struct {
    PairingSenderConfig
    PairingClientConfig
}
```

```go
type PairingReceiverClientConfig struct {
    PairingReceiverConfig
    PairingClientConfig
}
```

</td>
</tr>
</table>

In fact because there is a distinct difference between `Sending` and `Receiving` configs, we should split the `InputConnectionStringForBootstrapping` endpoint into:

- `InputConnectionStringForBeingBootstrapped`
- `InputConnectionStringForBootstrappingAnotherDevice`

Making the endpoints be as follows:

<table>
<tr>
<td> API Method </td> 
<td> Required Functionality </td>
<td> Proposed Config </td>
</tr>

<tr>
<td> `InputConnectionStringForBeingBootstrapped` </td>
<td> `pairing.Receiver` `pairing.Client` </td>
<td>

```go
type PairingReceiverClientConfig struct {
    PairingReceiverConfig
    PairingClientConfig
}
```

</td>
</tr>

<tr>
<td> `InputConnectionStringForBootstrappingAnotherDevice` </td>
<td> `pairing.Sender` `pairing.Client` </td>
<td>

```go
type PairingSenderClientConfig struct {
    PairingSenderConfig
    PairingClientConfig
}
```

</td>
</tr>
</table>

### The current code:

```go
// GetConnectionStringForBeingBootstrapped starts a pairing.Receiving pairing.PairingServer
// then generates a pairing.ConnectionParams. Used when the device is Logged out or has no Account keys
// and the device has no camera to read a QR code with
//
// Example: A desktop device (device without camera) receiving account data from mobile (device with camera)
func GetConnectionStringForBeingBootstrapped(configJSON string) string {
	if configJSON == "" {
		return makeJSONResponse(fmt.Errorf("no config given, PayloadSourceConfig is expected"))
	}
	cs, err := pairing.StartUpPairingServer(statusBackend, pairing.Receiving, configJSON)
	if err != nil {
		return makeJSONResponse(err)
	}
	return cs
}

// GetConnectionStringForBootstrappingAnotherDevice starts a pairing.Sending pairing.Server
// then generates a pairing.ConnectionParams. Used when the device is Logged in and therefore has Account keys
// and the device might not have a camera
//
// Example: A mobile or desktop device (devices that MAY have a camera but MUST have a screen)
// sending account data to a mobile (device with camera)
func GetConnectionStringForBootstrappingAnotherDevice(configJSON string) string {
	if configJSON == "" {
		return makeJSONResponse(fmt.Errorf("no config given, PayloadSourceConfig is expected"))
	}
	cs, err := pairing.StartUpPairingServer(statusBackend, pairing.Sending, configJSON)
	if err != nil {
		return makeJSONResponse(err)
	}
	return cs
}

// InputConnectionStringForBootstrapping starts a pairing.Client
// The given server.ConnectionParams string will determine the server.Mode
//
// server.Mode = server.Sending
// Used when the device is Logged in and therefore has Account keys and the has a camera to read a QR code
//
// Example: A mobile (device with camera) sending account data to a desktop device (device without camera)
//
// server.Mode = server.Receiving
// Used when the device is Logged out or has no Account keys and has a camera to read a QR code
//
// Example: A mobile device (device with a camera) receiving account data from
// a device with a screen (mobile or desktop devices)
func InputConnectionStringForBootstrapping(cs, configJSON string) string {
	if configJSON == "" {
		return makeJSONResponse(fmt.Errorf("no config given, PayloadSourceConfig is expected"))
	}

	err := pairing.StartUpPairingClient(statusBackend, cs, configJSON)
	return makeJSONResponse(err)
}
```

### Proposed code

```go
// GetConnectionStringForBeingBootstrapped starts a server.Receiving server.PairingServer
// then generates a server.ConnectionParams. Used when the device is Logged out or has no Account keys
// and the device has no camera to read a QR code with
//
// Example: A desktop device (device without camera) receiving account data from mobile (device with camera)
func GetConnectionStringForBeingBootstrapped(configJSON string) string {
	...
}

// GetConnectionStringForBootstrappingAnotherDevice starts a server.Sending server.PairingServer
// then generates a server.ConnectionParams. Used when the device is Logged in and therefore has Account keys
// and the device might not have a camera
//
// Example: A mobile or desktop device (devices that MAY have a camera but MUST have a screen)
// sending account data to a mobile (device with camera)
func GetConnectionStringForBootstrappingAnotherDevice(configJSON string) string {
	...
}

// InputConnectionStringForBootstrapping starts a server.PairingClient
// The given server.ConnectionParams string will determine the server.Mode
//
// server.Mode = server.Receiving
// Used when the device is Logged out or has no Account keys and has a camera to read a QR code
//
// Example: A mobile device (device with a camera) receiving account data from
// a device with a screen (mobile or desktop devices)
func InputConnectionStringForBootstrapping(cs, configJSON string) string {
	...
}

// InputConnectionStringForBootstrappingAnotherDevice starts a server.PairingClient
// The given server.ConnectionParams string will determine the server.Mode
//
// server.Mode = server.Sending
// Used when the device is Logged in and therefore has Account keys and the has a camera to read a QR code
//
// Example: A mobile (device with camera) sending account data to a desktop device (device without camera)
func InputConnectionStringForBootstrappingAnotherDevice(cs, configJSON string) string {
	...
}
```

**Comment by qfrank** [comment]
I think it's a good start time to do the actual coding after this [PR](https://github.com/status-im/status-go/pull/3202) get merged 🤔 @Samyoul
