### ISSUE TITLE
Investigate why displayName field is empty in settings

### ISSUE THREAD

**Issue by vitvly** [status-im/status-go#3205]
For some reason `displayName` field in settings object we receive on mobile is an empty string as opposed to `nil` value like e.g. `preferredName`, so for now a hack is required https://github.com/status-im/status-mobile/pull/15122.

**Comment by vitvly** [comment]
Most likely this is due to `display_name` column created as `TEXT NOT NULL DEFAULT ""`, while `preferred_name` is simply `VARCHAR`

**Comment by cammellos** [comment]
> Most likely this is due to `display_name` column created as `TEXT NOT NULL DEFAULT ""`, while `preferred_name` is simply `VARCHAR`

We can `omitempty` in JSON so it's nil, instead of "", if we want

**Comment by vitvly** [comment]
Ah, yes, great option! Or alternatively https://github.com/status-im/status-mobile/pull/15125
