### ISSUE TITLE
ActivityCenter endpoints refactor

### ISSUE THREAD

**Issue by MishkaRogachev** [status-im/status-go#3232]
# Problem

ActivityCenter endpoints have overlap of functionality, no obvious names and complicated args.

# Implementation

- [ ] Remove `ReadActivityCenterNotifications`, `UnreadActivityCenterNotifications`, `UnreadActivityCenterNotificationsCount`, `UnreadAndAcceptedActivityCenterNotificationsCount` and `ActivityCenterNotifications`
- [ ] Rename `ActivityCenterNotificationsBy` and `ActivityCenterNotificationsCountBy`  to  `ActivityCenterNotifications` and `ActivityCenterNotificationsCount`
- [ ] Change  `ActivityCenterNotifications` and `ActivityCenterNotificationsCount` args with structs
- [ ] `ActivityCenterNotificationsCount` endpoint should return set of counters for provided activity types

# Notes

This is the breaking changes, mobile & desktop clients should provide PRs for switching on a new API

**Comment by ilmotta** [comment]
> Add `ActivityCenterNotificationsTotalCount` endpoint returning set of counters for each activity type

Perhaps a slight improvement @MishkaRogachev. I think the endpoint can be named just `ActivityCenterNotificationsCount` without the `Total` word. And the response can have the individual counts, as well as the sum (based on the types of course). Having the sum and the individual counts would help simplify the clients. At least in mobile, it would help us remove code.

**Comment by MishkaRogachev** [comment]
> > Add `ActivityCenterNotificationsTotalCount` endpoint returning set of counters for each activity type
> 
> Perhaps a slight improvement @MishkaRogachev. I think the endpoint can be named just `ActivityCenterNotificationsCount` without the `Total` word. And the response can have the individual counts, as well as the sum (based on the types of course). Having the sum and the individual counts would help simplify the clients. At least in mobile, it would help us remove code.

Does i get it right: ActivityCenterNotificationsCount should take as args list of activity types, read type and accepted flags and return a set/map of counters for each provided activity type?

**Comment by ilmotta** [comment]
> > > Add `ActivityCenterNotificationsTotalCount` endpoint returning set of counters for each activity type
> > 
> > 
> > Perhaps a slight improvement @MishkaRogachev. I think the endpoint can be named just `ActivityCenterNotificationsCount` without the `Total` word. And the response can have the individual counts, as well as the sum (based on the types of course). Having the sum and the individual counts would help simplify the clients. At least in mobile, it would help us remove code.
> 
> Does i get it right: ActivityCenterNotificationsCount should take as args list of activity types, read type and accepted flags and return a set/map of counters for each provided activity type?

Precisely!
