### ISSUE TITLE
Fix TestJailWhisper

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#336]
# Problem

`TestJailWhisper` is very brittle and often fails. It was noticed to fail often in #321 in the associated build: https://travis-ci.org/status-im/status-go/builds/276538718?utm_source=github_status&utm_medium=notification

However, if you look at the last 2 `develop` builds you'll see that it fails as well:
https://travis-ci.org/status-im/status-go/builds/276518047#L5110
https://travis-ci.org/status-im/status-go/builds/275958778#L2404

And sometimes it succeeds (next 2 `develop` builds) but if you re-run them it's likely to fail:
https://travis-ci.org/status-im/status-go/builds/275957274#L2512
https://travis-ci.org/status-im/status-go/builds/275953350#L2561

You can even check out a pretty old revision and try it there: 6a096607cf9133d0485a6bc8246af2f668e8eecc

# Notes

There're some known directions to dig into:

1. `topic` in `makeTopic` is created with odd length. Under the hood it uses `web3.ToHex`.
2. Filter registration in `shh_newMessageFilter` fails. The logic there is strange and needs fixing: if you invoke `var filter = shh.newMessageFilter({...});` and then check `filter.filterId`, the latter is `null`. However, at the end of the test it somehow appears.
3. I wasn't able to make test cases 4 and 5 run. 0-3 sometimes succeed but 4-5 never do it. It may be connected with `shh.newMessageFilter` against a `privateKey`. But may be not.

# Acceptance Criteria

`TestJailWhisper` always passes (say, 10 of 10 runs in a row).

**Comment by adambabik** [comment]
1. was fixed in https://github.com/status-im/status-go/pull/351 as we tried to fix all failing tests.
2. Not experienced.
3. Confirmed that 4 and 5 couldn't pass even with fixed `makeTopic`.

**Comment by tiabc** [comment]
Increasing priority as it's but the only reason why they fail. For example, the most recent `develop`: https://travis-ci.org/status-im/status-go/builds/288967901#L524

@adambabik can you work on that, please?
