### ISSUE TITLE
Migrate to Go1.9

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#337]
# Problem

Come on, it's Go1.9.

# Implementation

Migrate to Go1.9 everything we have considering [Go1.9 Release Notes](https://golang.org/doc/go1.9)

# Acceptance Criteria

The application works as before, tests pass and there's no significant performance degradation.

# Notes

#223 may be a blocker as we may need to upgrade to newer versions during this migration.

**Comment by divan** [comment]
Go 1.9.1 pre-announcement, security fix.
https://groups.google.com/forum/#!topic/golang-announce/Aqam2y8QoLA

**Comment by divan** [comment]
Go 1.9.1 released
https://groups.google.com/forum/#!topic/golang-nuts/sHfMg4gZNps

**Comment by adambabik** [comment]
@tiabc any reason why does it depend on #223? I think it can be done independently.
