### ISSUE TITLE
Review status-go wiki

### ISSUE THREAD

**Issue by rgeraldes** [status-im/status-go#339]
# Problem

- the status-go wiki lacks proper organisation/documentation/knowledge for newcomers and visitors and also for internal operations. The goal is to model our wiki after the best wikis in the software community and have a side bar detailing all the aspects of the repository. All the knowledge present across the communication channels should be included in our wiki.

# Implementation

- create a side bar modelled after the best wikis. (https://github.com/showcases/projects-with-great-wikis)
- organise/refactor the existing pages 
- add elemental pages such as the one for contributors

# Acceptance Criteria

- the wiki must be organized, concise and readable for team elements as well for newcomers.

**Comment by tiabc** [comment]
Please, use the issue template and specify your specific thoughts what needs to be done here. An issue to create a proper issue is not an issue.

**Comment by tiabc** [comment]
Closing as we're giving notion.so a try instead of wiki. Currently, there's no need to reorganize it.
