### ISSUE TITLE
Rotate community encryption keys periodically

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#3404]
We should rotate encryption keys periodically, say once a week, or when it hits a large enough sequence number (10k?) in order to make sure that the latest could be retrieved from a mailserver, and that users won't have to hash too many times to decode a message.

It's also a good opportunity to optimize rekeying.

Currently, we send a message to each user, that's wasteful in large enough communities. 
An alternative, is to send a protobuf in the form (roughly):

```
message RekeyMessage {
  string key_id = 1;
  map<string><bytes> encrypted_keys;
}
```

Where key_id is the id of the new key

while the map is indexed by the first 4 bytes (could be more/less) of the public key of the user (to save on space, and avoid too many collisions), and the value is an array of keys, encrypted with the pk of the user(s). 
The array could be either a separate protobuf, or to save space, and provided encryption is constant size, the concatenation of the encrypted keys.

A user receiving this message, would take the first 4 bytes of their key, lookup into the map to see if there's anything, if there's anything, it would split it in chunk of size `n`, where `n` is the size of the encrypted key, and then it would trial/decrypt the key.

Other methods/solutions are possible of course, feel free to discuss any and/or improvements/changes.

**Comment by Samyoul** [comment]
Break task into 2 parts.

- [ ] set rekey cycle of once per hour / 30 minutes
- [ ] batch the keys into community description level topic

**Comment by Samyoul** [comment]
Need to resolve https://github.com/status-im/status-go/issues/3675 , this blocks progress for the moment.
