### ISSUE TITLE
Wrong password error and crash on login 

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#3409]
Issue is related to https://github.com/status-im/status-mobile/issues/15653, reported by @qoqobolo 
While the original issue was fixed, a similar problem (although harder to reproduce) still happens:
https://github.com/status-im/status-go/pull/3396#issuecomment-1512839065

The mobile app fails to login with invalid password error after a lot of tries. No error could be seen on the logs.
Fixing this issue might require creating a test unit that does login/logout for N attempts to try and reproduce it

**Comment by igor-sirotin** [comment]
Closing as source issue is closed: https://github.com/status-im/status-mobile/issues/15653
