### ISSUE TITLE
Received messages are not shown when disabled ipv6

### ISSUE THREAD

**Issue by Parveshdhull** [status-im/status-go#3418]
# Bug Report

## Description

For the last 24 hrs, I am not seeing anyone online and am unable to send messages. And terminal is showing error:
```
ERR 2022-11-22 14:15:02.237+05:30 error doing rpc request
topics="rpc" tid=4213 file=core.nim:33 methodName=wakuext_startMessenger exception="\nstatus-go error [methodName:wakuext_startMessenger, code:-32000, message:subsequent listen: listen tcp6 :9025: socket: address family not supported by protocol ]\n"
```
![main-shot](https://user-images.githubusercontent.com/17097240/203269279-4bcbc4ba-36b9-4de0-b335-2a8b2fa5ef6e.png)

Logs: 
[logs.txt](https://github.com/status-im/status-desktop/files/10065631/logs.txt)

### Additional Information

Status desktop version: 0.8.0-rc.2
Operating System: Arch Linux (6.0.8-arch1-1)

**Comment by Parveshdhull** [comment]
this also might be relevant
```
ERR 2022-11-22 14:14:57.580+05:30 node.login
topics="signals-manager" tid=4213 file=signals_manager.nim:48 error="file is not a database"
ERR 2022-11-22 14:14:57.581+05:30 login error
topics="app-controller" tid=4213 file=module.nim:297 methodName=onNodeLogin errDesription="file is not a database"
```

**Comment by anastasiyaig** [comment]
@richard-ramos please check

**Comment by richard-ramos** [comment]
Hm, this error is weird. @Parveshdhull, do you have IPV6 enabled?

**Comment by Parveshdhull** [comment]
> Hm, this error is weird. @Parveshdhull, do you have IPV6 enabled?

hi @richard-ramos, no I don't have IPV6 enabled.

Also, I was testing with @cammellos and checking if I was receiving messages from him in geth.log. Apparently, messages are being received but not shown in UI.

Geth Logs: https://drive.google.com/file/d/1VGcAUy07tmgW6XvoV1Wr2dhXkDC0qDLE/view?usp=sharing

**Comment by Parveshdhull** [comment]
**UPDATE:** I have ipv6 disabled by passing kernel parameter `ipv6.disable=1`. If I enable ipv6, then it starts work again

**Comment by anastasiyaig** [comment]
@Parveshdhull @richard-ramos is it still a blocker?

**Comment by Parveshdhull** [comment]
> @Parveshdhull @richard-ramos is it still a blocker?

hi @anastasiyaig, yes its not blocker anymore.

**Comment by Parveshdhull** [comment]
### Steps to reproduce:
1. Disable ipv6
2. Restart PC
3. Open status-desktop and receive a message from another user

**Comment by iurimatias** [comment]
moved this here since this is very likely an issue with status-go

**Comment by richard-ramos** [comment]
I think this problem might have been solved. I tried running go-waku in a digitalocean droplet with IPV6 enabled and it seems to be working. @Parveshdhull is the problem still happening for you when using a recent desktop version?

**Comment by Parveshdhull** [comment]
Hi @richard-ramos, Thank you for the ping.

> I tried running go-waku in a digitalocean droplet with IPV6 enabled and it seems to be working.

Actually, the issue was happening on IPV6 disabling, when enabled it was working fine. But I just tried disabling again using kernel parameter `ipv6.disable=1` and it's still working without any issues.
So, the issue is fixed now. Thanks
