### ISSUE TITLE
Generate Users Image with their initials and Identicon ring if no profile picture is set.

### ISSUE THREAD

**Issue by J-Son89** [status-im/status-go#3429]
In the new mobile designs the user avatar has the users initials showing in the case where they have not set a profile picture. 
To simplify the logic on mobile side it is easier if the users picture comes from status-Go and the mobile client only has to render the image (With identicon included into it)

An example of these designs is here: 
https://www.figma.com/file/WQZcp6S0EnzxdTL4taoKDv/Design-System-for-Mobile?node-id=115-6787&t=SXo5k6P6jpoq6IrS-0

<img width="59" alt="Screenshot 2023-04-26 at 10 17 25" src="https://user-images.githubusercontent.com/22799766/234530504-b896107a-9166-447c-8a7c-5a1721e6989f.png">

This should also work for the desktop client if they wish to start using this approach too

**Comment by J-Son89** [comment]
discussed with @cammellos about this approach 👍

**Comment by yqrashawn** [comment]
hi @jo-mut I'm working on generating the ring background with media server
