### ISSUE TITLE
Push notifications security: investigate implications of exposing SERVER_KEY in source control / binary

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#343]
# Problem

For push notifications we use Firebase as a provider. Since status-go communicates with Firebase on the device, this requires `SERVER_KEY` being on the device.

Right now it is source control but the problem doesn't necessarily disappear if we put it in an environment variable and build it only with release. Since it's a magic string encoded in the resulting artifact, which everyone will possess, it would still be fairly straightforward for a motivated attacker to extract it.

# Implementation

Understand what can be done with Firebase SERVER_KEY on its own and the threat it poses. If it is a threat, consider solving it or proposing a solution. For example using obfuscation techniques or some sort of reflection interface to a trusted server (?).

# Acceptance Criteria

- Understanding of security implications of leaving SERVER_KEY exposed
- If it is an issue, a proposal on how to solve it would be useful

# Notes

This is an issue other apps have as well, so might be worth looking into how it is generally solved (often obfuscation, as far as I know).

# Future Steps

Undefined.

**Comment by ChrisSalisbury** [comment]
I haven't used firebase, but a year ago I did a custom Oauth2 system to access various google cloud services. Here's what I know.

The risk is unauthorized use and quota theft. This can potentially cause a lot of issues. The best practices recommended by Google are: https://support.google.com/googleapi/answer/6310037?hl=en

Perhaps the most important of those that you may not be currently doing is to create separate restricted keys for each use case and to regenerate the keys regularly. 

In my case, I set up a separate auth server and used various permission limited service accounts to generate limited permission tokens to pass to users to access services. Each token was only valid for a unique obfuscated url and expired after one hour. If the app can't get what it needed from the service in that time, it has to get another token. It was a good three weeks before this system was fully debugged and tested, but we sleep better knowing it is secure.

As I understand it, firebase does not currently support multiple keys per project, so to limit each key you would need separate projects for each use case. Setting up something like I used in my project is probably possible, but would take a lot of Google source code reading to figure it out (it did in my case as well). 

Not sure how useful this post is, but hopefully it isn't worse than nothing. :-)

**Comment by pedropombeiro** [comment]
Thanks for the insight @ChrisSalisbury!

@oskarth we should at least be restricting the API tokens based on app identity and/or fingerprint, and making use of API restrictions (so that someone in possession of a token isn't allowed to use any random Google API but only Google Cloud Messaging).

![image](https://user-images.githubusercontent.com/138074/37398642-72b47ca8-277f-11e8-970c-2b79023deff6.png)
