### ISSUE TITLE
Replace 'upstream' with 'remote'

### ISSUE THREAD

**Issue by rgeraldes** [status-im/status-go#347]
# Problem

At the moment, the remote node is being called  'upstream' and for the sake of clarity
we should rename all the upstream references to remote as its purpose is clearer.

# Implementation

- Identify all the elements in status-go geth folder that are using the name upstream
- Replace 'upstream' for 'remote'

# Acceptance Criteria

- All the tests should be successful after renaming all the 'upstream' references

**Comment by tiabc** [comment]
Seriously? An issue for that? Moved to #200
