### ISSUE TITLE
Fix nodechain synchronization issue.

### ISSUE THREAD

**Issue by influx6** [status-im/status-go#348]
# Problem

Using `MaxPeers` to `0` fails to stop node synchronization when `Upstream.Enabled` is true, currently node chain synchronization still occurs.

# Implementation

- Call `lightEthereum.Downloader().Cancel()` to terminate chain synchronization downloader and validate sync has stopped.
 
# Acceptance Criteria

- Ensure no synchronization occurs with blockchain

# Notes

Currently we are aware that `LightEthereum` is needed for `Whisper` and related prc methods like `eth_accounts` to function, hence why we need to find a way to both have an instance of `lightEthereum` to exists. But due to this we need to ensure it does not affect other areas.

Only two methods exists that allow this: `Terminate` and `Cancel` (see https://github.com/status-im/status-go/blob/develop/vendor/github.com/ethereum/go-ethereum/eth/downloader/downloader.go#L521-L551).

Am not sure how heavy terminate is so for now will use `Cancel`.

**Comment by adambabik** [comment]
It was fixed by removing `LightEthereum` dependency when using the upstream node.
