### ISSUE TITLE
Memory leak in Waku v2 implementation

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#3501]
# Problem
The [SpiffWorkflow fleets](https://github.com/status-im/infra-spiff-workflow) are currently using a `status-go` node speaking Waku v2 to send notifications about ongoing processes. It's using the dedicated [`cmd/spiff-workflow`](https://github.com/status-im/status-go/tree/develop/cmd/spiff-workflow) command in a Docker container. We have discovered a memory growth issue that can affect other containers on the hosts. Here's a pattern for 20 days:

![image](https://github.com/status-im/status-go/assets/2212681/44e06ee2-8373-44f3-8d17-46cec02e6677)

There's a clear growth trend that gets interrupted by our daily container restarts introduced as a hack fix:
https://github.com/status-im/infra-spiff-workflow/blob/master/ansible/roles/spiff-workflow/tasks/hacks.yml

**Comment by jakubgs** [comment]
The trend is more clear when we look at a 7 day graph:

![image](https://github.com/status-im/status-go/assets/2212681/eebaf1be-f145-4941-b85b-660ba2275555)

Especially the clear reset at midnight due to the Systemd timer.

I have enabled PProf on two hosts to allow Richard to debug this issue:

- https://github.com/status-im/infra-spiff-workflow/commit/a793d9cc - spiff-workflow: add support for pprof flag
- https://github.com/status-im/infra-spiff-workflow/commit/eab95faf - spiff-workflow: add missing port mapping for pprof
- https://github.com/status-im/infra-spiff-workflow/commit/f229401d - spiff: enable wakunode pprof on mod-dev
- https://github.com/status-im/infra-spiff-workflow/commit/7710c86f - spiff: enable wakunode pprof on app-dev

**Comment by richard-ramos** [comment]
`pprof` indicates that the following function is using a lot of memory:
```
File: spiff-workflow
Type: inuse_space
Time: May 17, 2023 at 10:31am (AST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 20
Showing nodes accounting for 279.49MB, 91.76% of 304.57MB total
Dropped 177 nodes (cum <= 1.52MB)
Showing top 20 nodes out of 81
      flat  flat%   sum%        cum   cum%
  219.31MB 72.01% 72.01%   219.31MB 72.01%  google.golang.org/protobuf/internal/impl.consumeBytesNoZero
```

This function is executed as part of unmarshalling waku message protobuffers when they're received as part of a subscription

**Comment by richard-ramos** [comment]
We're currently using: `google.golang.org/protobuf v1.28.1` which was released in [July 2022](https://pkg.go.dev/google.golang.org/protobuf?tab=versions)
There are some commits in the most recent version which reduce allocations, so it's worth a try to update this dependency:
- https://github.com/protocolbuffers/protobuf-go/commit/358fe40267afd0cb5380d132cc93ddcbed2beb44
- https://github.com/protocolbuffers/protobuf-go/commit/b8fc7706010499f46982c883add4351b12e30c0b

**Comment by richard-ramos** [comment]
@jakubgs can we try running this branch https://github.com/status-im/status-go/pull/3503 in one of the spiffworkflow nodes that has memory issues? it has the new protobuf version in go-waku

**Comment by jakubgs** [comment]
I've built #3503 and pushed it to `app-dev` environment:
```
 > d tag statusteam/spiffworkflow-wakunode:latest statusteam/spiffworkflow-wakunode:deploy-app-dev
 > d push statusteam/spiffworkflow-wakunode:deploy-app-dev
The push refers to repository [docker.io/statusteam/spiffworkflow-wakunode]
dacd59136d5b: Pushed 
726f6f3f2f2b: Pushed 
aec3f6134ca2: Pushed 
549baa1bdfa7: Layer already exists 
3f6924e9f8d5: Layer already exists 
bb01bd7e32b5: Layer already exists 
deploy-app-dev: digest: sha256:95dad68534c105ae07f08515ab164ba10c9c36626837b61c0d309962f3e42df6 size: 1573
```

**Comment by richard-ramos** [comment]
@jakubgs I updated the same PR #3503 with commit https://github.com/status-im/status-go/pull/3503/commits/03f0601880658b571cf838cba81e0a649d5ee14a This upgrades go-libp2p from 0.26.4 to v0.27.3.  While looking at the changelog i could notice some chages reduce the number of allocations, and should improve memory usage. 
Let's try running this branch in spiffiworkflow app-dev!

**Comment by jakubgs** [comment]
Pushed to `app-dev` as before:
```
 > d push statusteam/spiffworkflow-wakunode:deploy-app-dev
The push refers to repository [docker.io/statusteam/spiffworkflow-wakunode]
116fe8e7ce00: Pushed 
3e5a662d9511: Pushed 
354a9fd643e9: Pushed 
549baa1bdfa7: Layer already exists 
3f6924e9f8d5: Layer already exists 
bb01bd7e32b5: Layer already exists 
deploy-app-dev: digest: sha256:9305e313fdc99e1df11bc522006e6eabb2ecdd6366bf6eb5e6ee3f937317e976 size: 1573
```

**Comment by jakubgs** [comment]
I believe these issues are now resolved:

![image](https://github.com/status-im/status-go/assets/2212681/948c9ca5-7873-4b5c-b089-69378d13271a)
