### ISSUE TITLE
Flaky `TestTwitterLinkPreviewData` test

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-go#3529]
In this [commit](https://github.com/status-im/status-go/pull/3524/commits/e2887ab9d263f1d20f4ce0975f616192aab2ca1e) `TestTwitterLinkPreviewData` test is commented out, cause even after more than 10 tries (tests re-run) tests on CI didn't pass.

Weird thing is that test was passing in local:
```
[nix-shell:~/go/src/github.com/status-im/status-go]$ go test -tags gowaku_skip_migrations -run ^TestTwitterLinkPreviewData$ github.com/status-im/status-go/protocol/urls/... -v
=== RUN   TestTwitterLinkPreviewData
--- PASS: TestTwitterLinkPreviewData (0.81s)
PASS
ok      github.com/status-im/status-go/protocol/urls    0.813s
```

But on CI it was giving the following error:
```
jenkins@linux-04:~/workspace/status-go_prs_tests_PR-3524$ go test -tags gowaku_skip_migrations -run ^TestTwitterLinkPreviewData$ github.com/status-im/status-go/protocol/urls/... -v
=== RUN   TestTwitterLinkPreviewData
    urls_test.go:171: 
            Error Trace:    /home/jenkins/workspace/status-go_prs_tests_PR-3524/protocol/urls/urls_test.go:171
            Error:          Received unexpected error:
                            invalid character '<' looking for beginning of value
            Test:           TestTwitterLinkPreviewData
--- FAIL: TestTwitterLinkPreviewData (0.27s)
FAIL
FAIL    github.com/status-im/status-go/protocol/urls    0.275s
FAIL
```

All in all it should be fixed. 

Also one thing is vague here, what do we want to test with `TestTwitterLinkPreviewData` test?
Are we testing fetching data from remote? Or parsing the content of supported links?
Those 2 should be 2 independent tests and test for parsing the content should not depend on fetched data, but they should be mocked.

**Comment by Samyoul** [comment]
@saledjenic if you want you can test in go using a mock server. I've implemented a number of tests that use go's inbuilt test server, see below for an example:

https://github.com/status-im/status-go/blob/2cac37c1fbc7eb15976dea04b7c599819df07cd9/images/decode_test.go#L89-L151

I think the biggest problem with splitting this testing is because the oembed structs hardcode their endpoints, which makes them hard to test.

Perhaps we could restructure the Oembed structs so that the we have a base Oembed struct that handles the URL and getting element, this also could be mockable / configurable. Then we have an interface layer, a struct build for a specific website's structure. This will allow us to test the parsing of data and keep the http request element segregated.

What do you think?

**Comment by saledjenic** [comment]
If I got you well you're suggesting to have 2 tests, one which will test fetching the content (via http request) and another which will do the parsing.

Thinking now, why do we need to test fetching the content, that's just a simple `httpClient.Get` request call, don't see it as anything we should test. In my opinion the only we need to test is parsing data. For that we can use mocked data and test parsing for each url we want to support (what's not the case atm, we're testing only parsing twitter's response and not the others).

We can do exactly the same as in the example you provided and cover parsing data for all variants we support.

**Comment by Samyoul** [comment]
@saledjenic thank you for following up. That isn't what I mean, I wasn't very clear. Let me make a code example of how we could break the close coupling between parsing data and getting data with the oembed structs we have.

Just to be clear the getting of data should not be tested as that is definitely a runtime issue, even in the case of an oembed schema change.

**Comment by Samyoul** [comment]
Following from an exchange with @ilmotta the url functionality will be removed from the application, so working on this fix may be a little pointless.

See https://github.com/status-im/status-go/pull/3530#issuecomment-1569276279

Here is the code example I mentioned yesterday, which may still have some value: https://github.com/status-im/status-go/pull/3554

**Comment by igor-sirotin** [comment]
Looks ok now.

```nim
> stress ./protocol.test -test.run TestTwitterLinkPreviewData
5s: 764 runs so far, 0 failures, 10 active
10s: 1552 runs so far, 0 failures, 10 active
15s: 2287 runs so far, 0 failures, 10 active
20s: 3028 runs so far, 0 failures, 10 active
25s: 3778 runs so far, 0 failures, 10 active
30s: 4574 runs so far, 0 failures, 10 active
35s: 5302 runs so far, 0 failures, 10 active
40s: 5896 runs so far, 0 failures, 10 active
45s: 6674 runs so far, 0 failures, 10 active
50s: 7455 runs so far, 0 failures, 10 active
55s: 8246 runs so far, 0 failures, 10 active
1m0s: 9027 runs so far, 0 failures, 10 active
1m5s: 9825 runs so far, 0 failures, 10 active
1m10s: 10623 runs so far, 0 failures, 10 active
1m15s: 11423 runs so far, 0 failures, 10 active
```

**Comment by igor-sirotin** [comment]
Pardon, wrong test run instructions. The problem is still there.

**Comment by ilmotta** [comment]
@igor-sirotin, can't we remove the `urls` package? On the mobile client we don't consume the legacy endpoints to unfurl URLs.

**Comment by igor-sirotin** [comment]
I think we can 👍  I'll check desktop and try to remove it
