### ISSUE TITLE
Aligning mobile app with the latest accounts related changes

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-go#3531]
Changes done in https://github.com/status-im/status-desktop/pull/10724:
- `accounts` table removed;
- `keypairs` and `keypairs_accounts` tables introduced;
- accounts mapped from `accounts` table to `keypairs` table in accordance with the following:
  - for all but watch only accounts, which are derived from the same master key, a single row is added to `keypairs` table: 
    - a single row with the `"profile"` value for `type` column is added to `keypairs` table. It always be only a single row with `"profile"` type. That row should not be deleted ever, cause it refers to Status' user master key and it is present from the moment user creates Status' account for the first time;
    - whenever user imports a new seed phrase a single row with the `"seed"` value for `type` column will be added to `keypairs` table;
    - whenever user imports a new private key a single row with the `"key"` value for `type` column will be added to `keypairs` table;
  - no row added to `keypairs` table for any watch only accuount (these accounts doesn't belong to any keypair)
  - each keypair has a `name` which can be updated for all keypair but the profile keypair. Profile keypair name always follows Status' user display name;
  - each keypair has `synced_from` field which is set if a keypair was received from paired device/waku;
  - each keypair has `last_used_derivation_index` it is updated only if user adds a new account which path match the next expected derivation path (expected path means path is within the default Status' derivation tree, differs from the highest last previously saved path index for 1 if available, if not, then the first next available one). It is used to suggest user the next derivation path;
- accounts mapped from `accounts` table to `keypairs_accounts` table in accordance with the following:
  - each account which was present in the old `accounts` table is present in the new `keypairs_accounts` table as well, almost all columns are here as they were in the all table;
  - `key_uid` is foreign key in `keypairs_accounts` table and refers to `keypairs.key_uid`
  - `operable` column is added, possible values and their meaning:
    - `"no"` - means an account is non operable, it is not a keycard account and there is no keystore file for it and no keystore file for the address this account is derived from;
    - `"partially"` - means an account is partially operable if it is not a keycard account and there is a created keystore file for the address this account is derived from;
    - `"fully"` - means an account is fully operable if it is a keycard account or if it is not a keycard account then must be a created keystore file for it as well as a keystore file for the address this account is derived from;

Accounts api that can be used is at the same location: https://github.com/status-im/status-go/blob/develop/services/accounts/accounts.go

**Comment by rasom** [comment]
@saledjenic we use three methods atm:
`accounts_getAccounts", "accounts_SaveAccount", "accounts_DeleteAccount"

How did API change from this perspective? Were some fields added or parameters changed in those methods?

**Comment by rasom** [comment]
@saledjenic 
That's what I get on calling SaveAccount at the moment ("NO KEYPAIR" entry is added by me but anyway)
```
t=2023-05-26T10:49:20+0000 lvl=info msg=[AccountsAPI::SaveAccount]
t=2023-05-26T10:49:20+0000 lvl=info msg="NO KEYPAIR"
t=2023-05-26T10:49:20+0000 lvl=eror msg="RPC method accounts_saveAccount crashed: runtime error: invalid memory address or nil pointer dereference\ngoroutine 3256 [running]:\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:199 +0x89\npanic({0x10339ef60, 0x104a5e640})\n\t/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.2/share/go/src/runtime/panic.go:884 +0x212\ngithub.com/status-im/status-go/multiaccounts/accounts.(*Database).saveOrUpdateAccounts(0x104ee2b80?, 0xc007c6d600, {0xc002a994c0, 0x1, 0x0?})\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/multiaccounts/accounts/database.go:743 +0x484\ngithub.com/status-im/status-go/multiaccounts/accounts.(*Database).SaveOrUpdateAccounts(0xc002a124b0, {0xc002a994c0, 0x1, 0x1})\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/multiaccounts/accounts/database.go:780 +0x111\ngithub.com/status-im/status-go/protocol.(*Messenger).SaveOrUpdateAccount(0xc0034ba500, 0xc007132f00)\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/protocol/messenger_wallet.go:122 +0x5f\ngithub.com/status-im/status-go/services/accounts.(*API).SaveAccount(0xc0036ada70, {0xc007a0f338?, 0x1?}, 0xc007132f00)\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/services/accounts/accounts.go:42 +0x68\nreflect.Value.call({0xc00073f560?, 0xc00054a4d0?, 0x146aabd28?}, {0x10292cc2d, 0x4}, {0xc007d341e0, 0x3, 0x10188d912?})\n\t/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.2/share/go/src/reflect/value.go:584 +0x8c5\nreflect.Value.Call({0xc00073f560?, 0xc00054a4d0?, 0x16?}, {0xc007d341e0?, 0x1?, 0x1?})\n\t/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.19.2/share/go/src/reflect/value.go:368 +0xbc\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc00073f5c0, {0x1036e60f8?, 0xc0060c7380}, {0xc006dde4b0, 0x14}, {0xc007c5e1b0, 0x1, 0x100f83777?})\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/service.go:205 +0x3e5\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0036d4240?, {0x1036e60f8?, 0xc0060c7380?}, 0xc0000acbd0, 0x1?, {0xc007c5e1b0?, 0xc0008df2c0?, 0xc0008df300?})\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:391 +0x45\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc00012a900, 0xc007d36420, 0xc0000acbd0)\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:336 +0x239\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc00012a900, 0xc000600000?, 0xc0000acbd0)\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:297 +0x237\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc007d36420)\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:138 +0x35\ngithub.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:225 +0xc5\ncreated by github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc\n\t/private/tmp/nix-build-status-go-develop-unknown-ios.drv-0/go/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/rpc/handler.go:221 +0x8d\n"
```

**Comment by rasom** [comment]
I suppose `SaveKeypair` and `DeleteKeypair` should be used

**Comment by saledjenic** [comment]
@rasom here is our accounts status-go gateway: https://github.com/status-im/status-desktop/blob/master/src/backend/accounts.nim you can see there how our calls look like.

This a function used for adding watch only or new accounts to already added keyapir: 
- https://github.com/status-im/status-desktop/blob/master/src/backend/accounts.nim#L39-L60

This a function used for adding a new keypair: 
- https://github.com/status-im/status-desktop/blob/master/src/backend/accounts.nim#L62-L96

At the moment we don't use `DeleteKeypair` anywhere cause deleting the last account for a keyapir will delete keypair from the `keypairs` table as well.

This a function used for updating already created accounts (you see it calls `accounts_SaveAccount`): 
- https://github.com/status-im/status-desktop/blob/master/src/backend/accounts.nim#L103-L124

**Comment by rasom** [comment]
thanks @saledjenic 

likely unrelated to wallet but have this problem when restore an existing multiaccount:

https://gist.github.com/rasom/7a85b6632c4fff9fcf9ba80b2729f969

might be related to those keypair changes

**Comment by saledjenic** [comment]
@rasom here is our service and function how we're adding new seed phrase keypair:

https://github.com/status-im/status-desktop/blob/master/src/app_service/service/wallet_account/service.nim#L477-L498

you can see that in the line `489` we call `status_go_accounts.addKeypair` (https://github.com/status-im/status-desktop/blob/master/src/backend/accounts.nim#L62-L96)

**Comment by saledjenic** [comment]
Similar is for adding new private key keypair:

https://github.com/status-im/status-desktop/blob/master/src/app_service/service/wallet_account/service.nim#L453-L475
