### ISSUE TITLE
CallRPC()  eth_sendTransaction returns error on local node

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#354]
# Problem

CallRPC with payload

`{"jsonrpc":"2.0","id":251,"method":"eth_sendTransaction","params":[{"from":"0xd30d900ab0e09ca1d86c59acfcce588a0e316570","to":"0x0ab51d7c36bfbc61aee369cbae48432fc63f25cc","value":"0xde0b6b3a7640000"}]}`

returns
` {"jsonrpc":"2.0","id":251,"error":{"code":-32602,"message":"missing value for required argument 1"}}`

on local node

**Comment by divan** [comment]
Fixed in https://github.com/status-im/status-go/pull/355
