### ISSUE TITLE
Spiff worlflow issue with nickname

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#3541]
We are using go-waku with SpiffWorkflow to send notifications from the workflow engine to Status Desktop. We set the nickname of Waku node however it seems to forget this on redeployment.

This is apparent when we have a new status desktop account getting a contact request. For those people who have already accepted the contact request, it will stay as-is. This is an issue for us since new people using Spiff will not be able to identify who is sending the contact request, as it is random. We normally call the nickname API and set the name to "SpiffWorkflow".

We do have persistent storage so not sure why this is happening. Can chat to @jakubgs and also @burnettk about this more.

**Comment by jakubgs** [comment]
The volume is hardcode at `/tmp/ethereum`:
```
admin@node-01.sm-eu-zur1.spiff.mod-prod:/docker/spiff-workflow % grep wakunode docker-compose.yml | grep data 
      - '/docker/spiff-workflow/wakunode/data:/tmp/ethereum'
```
Because last time I checked the `-dir` flag did nothing.

**Comment by jakubgs** [comment]
The location of storage looks correct in the container, it is indeed using `/tmp/ethereum`:
```
admin@node-01.sm-eu-zur1.spiff.mod-prod:~ % d exec -it spiff-workflow-wakunode bash
82f185415812:/# lsof | grep ldb
1	/usr/local/bin/spiff-workflow	26	/tmp/ethereum/mainnet_rpc/StatusIM/nodes/000131.ldb
1	/usr/local/bin/spiff-workflow	27	/tmp/ethereum/mainnet_rpc/StatusIM/nodes/000138.ldb
1	/usr/local/bin/spiff-workflow	28	/tmp/ethereum/mainnet_rpc/StatusIM/nodes/000135.ldb
1	/usr/local/bin/spiff-workflow	29	/tmp/ethereum/mainnet_rpc/StatusIM/nodes/000132.ldb
1	/usr/local/bin/spiff-workflow	60	/tmp/ethereum/mainnet_rpc/status-db/000137.ldb
1	/usr/local/bin/spiff-workflow	65	/tmp/ethereum/mainnet_rpc/status-db/000134.ldb
1	/usr/local/bin/spiff-workflow	67	/tmp/ethereum/mainnet_rpc/status-db/000133.ldb
```

**Comment by jakubgs** [comment]
Waaaait, there's some more stuff that's not under `/tmp/ethereum`:
```
82f185415812:/# lsof | grep accounts
1	/usr/local/bin/spiff-workflow	3	/tmp/accounts.sql
1	/usr/local/bin/spiff-workflow	11	/tmp/accounts.sql-wal
1	/usr/local/bin/spiff-workflow	12	/tmp/accounts.sql-shm
```
Looks like this is the issue. For some reason `accounts.sql` ends up in `/tmp`. No idea why, but we should probably change that.

**Comment by jakubgs** [comment]
Fix from @cammellos 

* https://github.com/status-im/status-go/pull/3544
