### ISSUE TITLE
Introduce generate share urls api methods

### ISSUE THREAD

**Issue by borismelnik** [status-im/status-go#3622]
# Problem

in fact of [desktop issue](https://github.com/status-im/status-desktop/issues/10851)

# Implementation

there will be a 3 new methods to generate correct urls:
`GenerateCommuntyShareURL` which return generated url for community or encrypted community as well (`/c/` or `/c#`)
`GenerateCommunityChannelShareURL` which return url for channel (`/cc/`)
`GenerateProfileShareURL` - which return url for open 1-to-1 chat

new one method to parse the url:
`ParseSharedURL` which return embedded data from url in JSON

also, 4 tests for every each method.

**Comment by igor-sirotin** [comment]
Already implemented:
https://github.com/status-im/status-go/blob/c02ebf957cce04bd9489cd69e45ff7ab0b61a7ba/services/ext/api.go#L1665-L1695
