### ISSUE TITLE
Improve JSON-RPC handling for raw requests/responses

### ISSUE THREAD

**Issue by divan** [status-im/status-go#364]
# Problem

In `get/rpc` package we need to operate on raw JSON-RPC requests and responses. Currently we use single structure to do this - `jsonrpcMessage` which is copied directly from geth's RPC client code. This structure represents JSON-RPC message for requests, responses, successful and erroneous.

Using single structure to represent multiple slightly different things introduces subtle bugs and decrease usefullnes of such language instruments as struct tags, for example. With this bug https://github.com/status-im/status-go/issues/361, field `result`, obligatory for successful response, was missing due to `result` having `omitempty` tag.

This approach thus makes code less clear and introduces possibility of new subtle bugs.

# Implementation

Common approach to make code more clear and less convoluted is to have one structure for each type of message (request, successful response, erroneous response). For common fields just use embedding.

There is also a message type called `notification`, but it seems we don't use it anywhere. Worth investigating.

# Acceptance Criteria

 - each JSON-RPC message type (request, successful response, erroneous response) has it's own structure
 - struct tags are examined for each type, clearly representing required and optional fields according to JSON-RPC spec
 - tests are updated, added new if needed to cover related functionality

# Notes

Some links:
-  https://github.com/ethereum/wiki/wiki/JSON-RPC
- http://www.jsonrpc.org/specification

**Comment by akshaysuresh4793** [comment]
Hi
I am new to open source. I just wanted to make sure I understand this right.
The plan is to refine any call involving Raw requests and responses. In order to do that, we need to add a separate struct for each request, response ( success and error ).
Is that correct?

**Comment by tiabc** [comment]
@akshaysuresh4793 what do you mean by "each request", "each response" provided that different requests and responses have the same structure in JSON RPC?
The issue is to create and utilize separate structs for different objects:
1. JSON-RPC request.
2. JSON-RPC successful response.
3. JSON-RPC erroneous response.

The reasons are outlined in the issue description.

Would you like to make a contribution?

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0xf88f9442e0a70c68aa9550e37151f57600687af5](https://etherscan.io/address/0xf88f9442e0a70c68aa9550e37151f57600687af5)
Network: Mainnet
Paid to: monokh

**Comment by akshaysuresh4793** [comment]
@tiabc I'd like to make a contribution

**Comment by monokh** [comment]
Submitted #458 for this. Let me know if i've misunderstood the requirements 😃  thanks
