### ISSUE TITLE
HighestBlock from status-go is less than actual highestBlock on ropsten net!

### ISSUE THREAD

**Issue by violetbobo** [status-im/status-go#366]
why is highestBlock from status-go less than actual highestBlock on ropsten net! For example，highestBlock I got  from status-go was 1721748, but it was 1750660 on actual ropsten net at that time!

**Comment by adambabik** [comment]
Thanks, @violetbobo for the report. Unfortunately, it will continue to be so until we close https://github.com/status-im/status-go/issues/317.

**Comment by violetbobo** [comment]
@adambabik thanks!

**Comment by tiabc** [comment]
Must be fixed. @violetbobo thanks for the bug report! Feel free to reopen it if the bug still exists in the new version.
