### ISSUE TITLE
Orphaned Encryption Protobuf

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#3677]
This file [protocol/encryption/github.com/protocol/encryption/protocol_message.pb.go](https://github.com/status-im/status-go/blob/b8b402da8d5ee94ab1019e034156b425bd6b0f78/protocol/encryption/github.com/protocol/encryption/protocol_message.pb.go) appears to be orphaned, probably due to an old bug we had with `protoc` a while back.

Just check this code is actually orphaned and then delete it and all of its directories.

**Comment by Azanul** [comment]
May I take this up?
