### ISSUE TITLE
Make room for proper unit and integration tests

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#371]
# Problem

90% of all tests that we have now are e2e tests. We need to turn this approach upside down and start writing more unit tests. [Here is an idea](https://martinfowler.com/bliki/TestPyramid.html) how it should look like.

Current tests have a lot of issues:
- unreliable and flaky,
- very slow,
- duplicated,
- e2e tests instead of unit and integration tests,
- hard to reason about.

Lack of proper unit tests and decent test coverage can lead to elusive issues and significantly slow down development. This issue is one of many to fix our testing strategy.

# Implementation

## Phase 1

Move e2e tests into a separate package in order to make room for new unit and integration tests. The existing properly designed tests should stay.

## Phase 2

Prepare a new set of utilities to write proper unit and integration tests.

## Phase 3

Create a private blockchain network that can be used to run e2e tests locally, without connecting to the public testnets.

# Acceptance Criteria

## Phase 1

1. E2e tests are in a separate package so that we keep an ability to verify that all features are working correctly.
2. Valid unit and integration tests are left intact.
3. There is room for new unit and integration tests.

## Phase 2

1. Decide on a tool (keep `testify/suite` or move to [GoConvey](https://github.com/smartystreets/goconvey)).
2. Utility to create mocks.
3. Tests can be run using standard go tools.

## Phase 3

1. A private blockchain is easy to run on a local machine. 
2. E2e tests can be run using the private blockchain (https://github.com/status-im/status-go/issues/312).

# Future Steps

- [ ] Explain how new unit and integration tests should be written to avoid making the same mistakes.
- [ ] Fix legacy e2e tests.

**Comment by adambabik** [comment]
An alternative idea that I found is to use build tags and keep integration tests in the same place:

> Write an integration_test.go, and give it a build tag of integration. Define (global) flags for things like service addresses and connect strings, and use them in your tests.

```go
// +build integration

var fooAddr = flag.String(...)

func TestToo(t *testing.T) {
    f, err := foo.Connect(*fooAddr)
    // ...
}
```
> go test takes build tags just like go build, so you can call go test -tags=integration. It also synthesizes a package main which calls flag.Parse, so any flags declared and visible will be processed and available to your tests.

[Source](http://peter.bourgon.org/go-in-production/#testing-and-validation)

One drawback of this solution is that it's sometimes hard to decide where an integration file should be placed and it also breaks packages separation. In our model, it's much easier to divide integration tests by a role rather than a package they belong to.

**Comment by JekaMas** [comment]
As far as i see Phase 3 is on progress in https://github.com/status-im/status-go/issues/312 (Maksim Shcherbo is going to done this task).

And i cant get the point: how does this plan relate to unit tests? May be we need some refactoring to make our code testable for unit tests?

**Comment by adambabik** [comment]
@JekaMas that's great, I didn't know anyone is working on it. I would appreciate any comment in that issue.

> And i cant get the point: how does this plan relate to unit tests? May be we need some refactoring to make our code testable for unit tests?

Great question! It's about making space for unit tests. Currently, there are virtually no unit tests in the project. By moving the existing integration tests to a separate package, we will have much better insight where unit test should be added (in 90% of packages I suppose). Also, we will be able to run `go test` and other tools like race detector or test coverage and get a reasonable output within a few seconds. Finally, it will reduce dependencies between status-go packages and go-ethereum project.

I am not sure any code refactoring is required to write unit tests. We just need to start writing them :) 

This plan is not set in stone yet. I would love to get more feedback in order to come up with the best idea.

**Comment by screwyprof** [comment]
Hi Adam. My name is Max. I've started working on phase 3. Ivan has assigned this part to me.

**Comment by tiabc** [comment]
Great stuff, @adambabik, thanks for formalising it! But I can clearly see this issue is the continuation of #220, thus adding a dependency. These 3 issues (#220, #371, #312) are a mess to sort out and create a list of tests fixing and refactoring issues with proper dependencies. Also, I can clearly see 3 issues here, not one.
Would you like to sort out our tests fixing strategy or shall I do that instead?

@screwyprof is the candidate into our core team and working on tests on the private chain, yes. I wouldn't say tests on a private chain is the 3rd phase, it's rather one of the required phases.

**Comment by tiabc** [comment]
@JekaMas yes, absolutely, we're aiming to fix our code to be unit-testable and the first step is to just fix tests to pass.

**Comment by adambabik** [comment]
> this issue is the continuation of #220, thus adding a dependency

It is but at the same time #220 is more technical. Here, I wanted to outline a plan to make some room for unit tests and all other issues you mentioned.

> Would you like to sort out our tests fixing strategy or shall I do that instead?

I can take care of it. We need to collect all issues related to tests, prioritize them and set proper dependencies.

>  I wouldn't say tests on a private chain is the 3rd phase, it's rather one of the required phases.

All three phases are required. Numbers indicate the order in which they should be done. However, as it was already noticed, Phase 3 is totally independent. Phase 2 is sort of independent of Phase 1 but as Phase 1 requires moving a lot of files, it's better to do it first.

**Comment by adambabik** [comment]
After receiving very constructive feedback, I made some changes to this issue. I emphasize that this issue is about making room for improved and more reliable unit and integration tests. 

Moving the current integration and e2e tests into a separate directory should be perceived as deprecating them. They still will be used to make sure status-go works as expected but eventually they will be reduced to reliable and expressive e2e tests and integration tests will be placed next to the code.

**Comment by tiabc** [comment]
Speaking about terminology. How are e2e tests different from integration tests we have now in your understanding?

**Comment by adambabik** [comment]
Integration tests verify if separate components can work together. For instance, verify if `jail` can work with the `rpc.Client` using a `net/http/httptest.Server` mock. It's important to keep integration tests fast, reliable and predictable.

E2e tests verify if a program works properly with external systems. It should resemble the production setup as close as possible. In our case, e2e tests would use any public testnet.

I didn't cover a private network yet. I think we can use it in e2e tests and that could be a part of a pull request CI pipeline because the private network should provide much higher reliability than public testnets. The public testnets could be a part of a release CI pipeline and also run periodically every 1 hour or so. The idea is that if the public testnet is unavailable, it does not affect the development but it can affect release.

**Comment by tiabc** [comment]
So, speaking your terms, we don't have integration tests, only e2e tests, right? Thus the question: shall we rename the `integration` package, which you're separating out, into `e2e` package?

Yes, totally agree with you about the pipeline, excellent idea.

**Comment by adambabik** [comment]
Correct. In #375, I left few unit and integration tests and moved only e2e tests, which are 90% of all tests we have. And yes, very good point, it should be renamed to `e2e`. 

Unit, integration and e2e tests terminology is much more clear. Previously, I tried to divide them into unit and integration tests but it clearly wasn't the best idea.

**Comment by JekaMas** [comment]
If all agree with this terms i think we need to fix this in our docs: what is unit, integration, e2e tests, their responsibility, package path, naming.

**Comment by tiabc** [comment]
@JekaMas would you like to draft it? I think yeah, this separation makes enough sense in practical test types distinguishing.

**Comment by JekaMas** [comment]
Ok. On it, going to add this info into wiki 'Testing'.
