### ISSUE TITLE
Mixing of result of Call method

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#372]
Concurrent calls to jail receive wrong results (for instance call A receives results for call B and vice versa) when js code which is executed contains calls to web3 (like `web3.eth.gasPric` and `web3.eth.estimateGas`).

Particularly this happens with suggestions for `amount` parameter of `/send` command.
This exact function is called when user changes input field, and if user does it fast it changes frequently and we send a lot of calls. So each call contains some parameters, like `amount` in our case, which is the input changed by user. So we send a call with parameter `amount = 1` and we expect some piece of data as response and that this data also contains  `amount = 1`. But it happens that we have `amount = 1` -> `amount = 0` (and vice versa, exact values don’t matter here), which looks like we receive wrong response for call, they are shuffled.

So here is js code https://github.com/status-im/status-react/blob/release/0.9.11/resources/js/bots/wallet/bot.js#L57

That's parameters passed to Call method:

https://gist.github.com/rasom/8b6689a665c820f9e489dc87e28e3853

**Comment by adambabik** [comment]
This bug is easily reproducible when two conditions are met:
1. `jail.Call()` is called concurrently,
2. The executed script must call `jail.Send` (or `jail.SendAsync` I suppose).

If (2) is not true, it works as expected.

A simple test in `jail_test.go`:

```go
func (s *JailTestSuite) TestCallResponseOrder() {
	statusJS := baseStatusJSCode + `;
	_status_catalog.commands["testCommand"] = function (params) {
		return params.val * params.val;
	};
	_status_catalog.commands["calculateGasPrice"] = function (n) {
		var gasMultiplicator = Math.pow(1.4, n).toFixed(3);
		var price = 211000000000;
		try {
			price = web3.eth.gasPrice;
		} catch (err) {}

		return price * gasMultiplicator;
	};
	`
	s.jail.Parse(testChatID, statusJS)

	var wg sync.WaitGroup
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			res := s.jail.Call(testChatID, `["commands", "testCommand"]`, fmt.Sprintf(`{"val": %d}`, i))
			s.Equal(res, fmt.Sprintf(`{"result": %d}`, i*i))

			res2 := s.jail.Call(testChatID, `["commands", "calculateGasPrice"]`, fmt.Sprintf(`%d`, i))
			fmt.Println(res2)
		}(i)
	}

	wg.Wait()
}
```

It will print garbage like `{"error":"ReferenceError: 'price' is not defined"}`.

**Comment by divan** [comment]
Should be fixed in https://github.com/status-im/status-go/pull/368
