### ISSUE TITLE
Review and update routing for RPC calls

### ISSUE THREAD

**Issue by divan** [status-im/status-go#378]
# Problem

status-go handles each RPC request differently according a few params:
 - method
 - configuration of remote node (Upstream.Enabled/Disabled)

Routing logic is in `geth/rpc/router.go`. List of the methods that should be router to remote or local have been changed and updated, and there seems to be no clear vision if that list is complete and/or correct.

This causes bugs that hard to detect with current tests. (PR https://github.com/status-im/status-go/pull/377 as an example of solving such type of bugs).

# Implementation

 - review current list of methods in router and update it if needed
 - define clear rules of how this list is composed, which are the rules for this list
 - put it into wiki or other easily-discoverable docs platform (comments?)

# Acceptance Criteria

 - there is a documentation on the methods routing list
 - list is updated if needed after review

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x590b0f774ddfca7b32dad4235b38e599665f925dbc18ca348f6959cb5dd8be5f](https://etherscan.io/tx/0x590b0f774ddfca7b32dad4235b38e599665f925dbc18ca348f6959cb5dd8be5f)

**Comment by feuGeneA** [comment]
Please review my work in progress on #481 and let me know if I'm on the right track.  Thanks.

**Comment by divan** [comment]
closing as outdated
