### ISSUE TITLE
Implement Rinkeby faucet

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#383]
# Problem

There's no way to request test Rinkeby ether for our users.

# Implementation

1. Implement a separate application which collects ether from public Rinkeby faucets and send it to `0xadaf150b905cf5e6a778e553e15a139b6618bbb7` for further distribution to our users.
2. Fix github.com/status-im/faucet to be able to send ether to Rinkeby addresses without losing backward-compatibility.

# Acceptance Criteria

1. There's an application github.com/status-im/rinkebyminer which collects Rinkeby ether from various public sources (the name is negotiable).
2. rinkebyminer regularly steals ether but doesn't steal too much. Say, 10 ether a day is fine.

# Notes

Note that there will be more test networks and it's better to lay proper foundation for those additions.
If you don't have access to any repos, request it from @carlbennetts

# Future Steps

Contact @tiabc to deploy the new rinkebyminer and re-deploy faucet.

**Comment by JekaMas** [comment]
Am i right that we need something like Selenium for this task?

And how many eth do we need? If not too much we may use something like "[pay for task service](https://www.mturk.com/mturk/welcome)"? The task cost approximately $0.02-0.05. For a single account we got: 4 faucet request per day * 365 * $0.05 = **$73**

**Comment by tiabc** [comment]
@JekaMas I don't think so. Can you elaborate, please?

**Comment by b00ris** [comment]
@tiabc As we understand the task i need to add to some account ether via https://faucet.rinkeby.io/ and transfer it to `0xadaf150b905cf5e6a778e553e15a139b6618bbb7`.  From https://faucet.rinkeby.io/ we could add ether only using github account(+recapcha). I try to do it using selenium and several techniques cracking recapcha. 
Threre is other way to get ether via mechanical work, using SAAS(https://www.mturk.com/mturk/welcome for example) with a lot of peoples=)  @JekaMas talk about it

**Comment by tiabc** [comment]
Thanks for the explanation @b00ris! It sounds like a good idea.
This matter is pretty urgent so let's do it in the fastest possible way: manually for now. I'll check those manual work services shortly and you can proceed without implementing this crawling service until I provide you with an update.

**Comment by JekaMas** [comment]
Boris have described better tham me) yeah, i think this task is very time consuming and can replaced  by manual job. 3-5 accounts with such manual work and we got 36-60 eth on Rinkeby per day for 18-30$ per mounth.
This is common solution in Ads world:)

**Comment by b00ris** [comment]
@tiabc What do you mean, about backward compatibility(robsten+rinkeby/same arhitecture/same deployment)?

**Comment by tiabc** [comment]
Mobile nodes should not be affected by the change. Existing faucet URLs should not change as well as payload should not suffer backward-incompatible changes.

**Comment by b00ris** [comment]
@tiabc  Do you have any updates on this issue?  Our faucet could work with rinkeby now. Will we use manual working services? Should i continue working on https://faucet.rinkeby.io/ cracking? I have some ideas, but i need 3-4 days to test it. If we'll start using manual working services,  i think we need close this issue and open separated for https://faucet.rinkeby.io/ cracking with lower priority.

**Comment by tiabc** [comment]
@b00ris #404
