### ISSUE TITLE
Wallet API possible changes for mobile development

### ISSUE THREAD

**Issue by alaibe** [status-im/status-go#3834]
# Problem

Find out if the Wallet API would work for mobile

**Comment by rasom** [comment]
I don't see why this might be necessary, and I think this issue can be closed. If any issue will be found during the implementation we can handle them as they appear, otherwise there is no need in any kind of preparation or something.
@alaibe I think this one can be closed

**Comment by alaibe** [comment]
thanks for checking, let's close it
