### ISSUE TITLE
eth.accounts in jail returns array of int arrays 

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#384]
<img width="374" alt="screen shot 2017-10-05 at 19 26 49" src="https://user-images.githubusercontent.com/2364994/31242577-c6e5c7f0-aa07-11e7-9b75-ba4e570044c9.png">

Can be reproduced only with sync call in jail. Works fine when call is done using `CallRPC` method.

**Comment by divan** [comment]
Added test for this bug, but can't reproduce it so far: https://github.com/status-im/status-go/commit/ebb493b584ebdab7086b2b0f891d73d679698ed1

@rasom can you confirm this bug still exist? And if so, help to isolate it with test?

**Comment by rasom** [comment]
fixed in `develop`
