### ISSUE TITLE
Add missing unit tests - account package

### ISSUE THREAD

**Issue by rgeraldes** [status-im/status-go#386]
# Problem

There are methods in the account package that are not covered by unit tests.

# Implementation

- go over the existing files and identify the methods that are not covered by tests.
- implement the test.

# Acceptance Criteria

- All the methods must be covered by tests.
- All the tests of the account package should pass.

# Further Steps

Pick a next single package and cover it with unit tests.

**Comment by b00ris** [comment]
@rgeraldes I think it's very big issue. And it could be related to big refactoring, if we wan't to cover all codebase by unit tests. Maybe we should to make this issue - epic, or split it to several.
Do you talk in description about unit tests or all types of tests?

**Comment by tiabc** [comment]
@rgeraldes please, narrow down the scope (say, cover the smallest concrete package with unit tests). Also, you can specify in the `further steps` section that one will need to create another issues for covering other packages with unit tests.

@b00ris we're only talking about unit tests.

**Comment by tiabc** [comment]
Although this issue is important, it doesn't block anything so decreasing priority.

**Comment by dshulyak** [comment]
Account package was covered by unit tests

**Comment by mandrigin** [comment]
@divan closing it, feel free to re-open if that is a mistake.
