### ISSUE TITLE
Integrate code linters to workflow

### ISSUE THREAD

**Issue by b00ris** [status-im/status-go#387]
# Problem
Code linting is important and useful but it's not integrated into our workflow. 

# Implementation
- investigate which of linters in gometalinter is useful for our team
- add checking chosen linters to travis

# Acceptance Criteria 
- status-go should be checked by chosen linters for every PR.

# Notes
ASAP after https://github.com/status-im/status-go/issues/281

**Comment by tiabc** [comment]
Increasing priority as #281 has been closed and we don't want to occasionally miss lint checking and fix lint warnings again.
