### ISSUE TITLE
startNodeWithAccount always fails after password change, but error is ignored

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-go#3906]
# Problem

In `(b *GethStatusBackend) ChangeDatabasePassword` start node is called after db password is changed but it always fails, error is silently ignored:
`_ = b.startNodeWithAccount(*account, newPassword, nil)`

If fails, because it tries to access keystore internally, which is already reset to nil on node stopping
It does not affect anything, because UI calls Logout and Quit after it, but `status-go` must not depend on UI in this case.
Either we need this restart and run a dummy node, or we don't need it at all and should remove the lines.

**Comment by saledjenic** [comment]
It's not an issue anymore.
