### ISSUE TITLE
Make statusim/xgo image out of farazdagi/xgo

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#391]
# Problem

In development, we use Go 1.9.x branch but a docker image that we use to build mobile binaries uses Go 1.7.1.

# Implementation

We should upgrade the image to the most recent Go 1.9.x version.

# Acceptance Criteria

1. The built binaries work correctly when compiled in the app.
2. `statusim/xgo` is deployed to our dockerhub.
3. `statusim/xgo` is used for cross-compilation instead of `farazdagi/xgo`.

# Notes

#337 should be done first.

go-ethereum does not use [xgo](https://github.com/karalabe/xgo) for mobile builds anymore but [gomobile](https://github.com/golang/mobile).

# Future Steps

Decide if want to continue using `xgo` instead of `gomobile`.

**Comment by tiabc** [comment]
Edited the acceptance criteria and future steps.

**Comment by adambabik** [comment]
> Decide if want to continue using xgo instead of gomobile.

+ Allows to get rid of C bindings and use a Go struct,
+ iOS and Android packages should be smaller in size,
+ As xgo is not used to build mobile packages in go-ethereum anymore, we can't be sure future geth versions will work fine with xgo and even if xgo will still support mobile packages,
- In order to build a framework for iOS, `gomobile` requires running on macOS. It's not a big deal for us as both our Jenkins and Travis do have a macOS executors.

**Comment by mandrigin** [comment]
I see that `farazdagi/xgo:latest` is using Go 1.8.3.
Is this issue still valid?
Or do we want to migrate the Docker image to `1.9`?

**Comment by tiabc** [comment]
I think it's about time to migrate to 1.9 if nobody else has any objections.

**Comment by mandrigin** [comment]
@tiabc I see there are source files for `farazdagi/xgo` in the repo.
I can tweak them, but someone from the core team needs to create a dockerhub entry for `status-im` and push the images there. I don't want to register it myself.

**Comment by adambabik** [comment]
@mandrigin where is this information that `farazdagi/xgo:latest` uses Go 1.8.3? It sounds good, we can push it as `status-im` user.

**Comment by mandrigin** [comment]
@adambabik sorry, I mixed up, it was a base image `karalabe/xgo`.

**Comment by pedropombeiro** [comment]
@mandrigin did you end up working on this? Was going to take it, if you're not working on it.

**Comment by pedropombeiro** [comment]
@adambabik The file referenced in https://github.com/status-im/status-go/blob/develop/xgo/ios-simulator/Dockerfile#L4 should probably be hosted on an account controlled by [status.im](https://status.im/). Maybe someone from status can host that and post the link here?

**Comment by adambabik** [comment]
@PombeirP thanks! I reported this problem to our Ops and this file with iOS SDK should be moved shortly. In the meanwhile, if you start working on this issue, I think you can use the current file location.

**Comment by pedropombeiro** [comment]
@adambabik That'd be great. The only other thing I'd need from Ops is for them to create a couple of automated build at hub.docker.com (one for `/xgo/base/Dockerfile` and another for `/xgo/ios-simulator/Dockerfile`) once the PR is near approval:

![image](https://user-images.githubusercontent.com/138074/34329004-59bc87b8-e8f0-11e7-92d5-7c38a1289109.png)

**Comment by adambabik** [comment]
Thanks, @PombeirP for the detailed description. I will take care of this as soon as possible.
