### ISSUE TITLE
ci: The container name "/status-go-test-db" is already in use by container

### ISSUE THREAD

**Issue by yakimant** [status-im/status-go#3920]
# Problem

`docker run` fails:
```
+ docker run -d --name=status-go-test-db --env=POSTGRES_HOST_AUTH_METHOD=trust --publish=5432:5432 postgres:9.6-alpine

docker: Error response from daemon: Conflict. The container name "/status-go-test-db" is already in use by container "6c8522d48e4acf42ed9df348846e9e4e0ab9829cc6e7b77648237c8e9f81f97b". You have to remove (or rename) that container to be able to reuse that name.

See 'docker run --help'.

script returned exit code 125
```

`docker rm` fails:
```
+ docker rm status-go-test-db

Error response from daemon: You cannot remove a running container 6c8522d48e4acf42ed9df348846e9e4e0ab9829cc6e7b77648237c8e9f81f97b. Stop the container before attempting removal or force remove

+ true
```

Examples (builds kept forever):
- https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-3871/6/pipeline
- https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-3871/17/pipeline/

# Implementation

It's either interfiring with other build executors on same agent. Solution: have uniq name for container.
Or leftover from some broken run. Solution: rm with force.

**Comment by yakimant** [comment]
FYI @jakubgs, @richard-ramos, @cammellos, @iurimatias
Is it a known issue?

**Comment by yakimant** [comment]
Again:
https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-3750/9/pipeline

**Comment by jakubgs** [comment]
Yeah, it is. You just need to add `EXECUTOR_NUMBER` as a suffix to the container name.

**Comment by jakubgs** [comment]
Although even if that is done it probably won't work anyway, because the DB port is hardcoded:
https://github.com/status-im/status-go/blob/3bf0bed78da660b0a361afd285ec229dcef7de70/postgres/helpers.go#L9-L12
Which is a known issue. Would be nice to finally fix it.

**Comment by jakubgs** [comment]
Got another report about this being an issue from @ilmotta, and verified that the host didn't haven orphan DB containers:
```
admin@linux-03.he-eu-hel1.ci.devel:~ % d ps -a
CONTAINER ID   NAMES     IMAGE     CREATED   STATUS
admin@linux-03.he-eu-hel1.ci.devel:~ % 
```
And it didn't.

**Comment by igor-sirotin** [comment]
I think this hasn't been an issue lately. 
Please reopen if you face it again.
