### ISSUE TITLE
Don't sync AC notifications, only decisions/state

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#3949]
# Problem

It seems that currently we fully sync AC notifications.
We should only sync decisions/state but not the actual notification.

https://github.com/status-im/status-go/blob/dd3e408a4e5ca412ecd6ed69a14c1fc8e456c038/protocol/messenger_handler.go#L2281

# Acceptance Criteria

- AC notifications are always generated locally and never synced.
- AC notifications state is synced
- AC notifications decision is synced

Related bug: https://github.com/status-im/status-go/issues/3801

**Comment by igor-sirotin** [comment]
cc @saledjenic @cammellos

**Comment by qfrank** [comment]
Hi @igor-sirotin , one question for you! 

> AC notifications state is synced

the `state` you mean here is the table `activity_center_states` or something else?

**Comment by igor-sirotin** [comment]
> the state you mean here is the table `activity_center_states` or something else?

@qfrank yep, I meant the `seen` property. I guess it should be possible to implement?
