### ISSUE TITLE
sharding: community migration to different shard and links

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#3954]
When a community is migrated to a different shard, the status links that point to the community on the previous shard will stop working. A possible solution to avoid this problem would be to modify the community description to include some flag indicating that the community was migrated so the user might know that the link is not valid anymore and to ask whoever shared the link for a new one that points to the right community shard

**Comment by richard-ramos** [comment]
Besides this flag, we could also add the information about the new shard/index that the community was migrated to? Since the community description message would be stored for 30d, during that period the link would still work and we could automatically point to the new shard

**Comment by felicio** [comment]
my notes:

- keep updating "old" (inc. not sharded one) topic for `n` time
- after `n` time + retention period, don't tell user just "not found" but maybe "not found, try obtaining new url..."

**Comment by felicio** [comment]
@osmaczko while this issue was primarily created as prerequisite for status.app urls, I believe it should be considered and tracked for the "Community Directory Curation DApp" too.

I'm mentioning you because you said you've started working on the integration of the sharding feature into `status-desktop`.

@cammellos and @jrainville are aware of this issue.

Cc @borismelnik

**Comment by felicio** [comment]
@richard-ramos please, what's the status of this? @cammellos mentioned I should reach out to you instead.

**Comment by osmaczko** [comment]
@felicio sorry, I missed the message.

If this is implemented: https://github.com/status-im/status-go/issues/4230 we probably won't need shard info in links at all. There is a draft PR for that already: https://github.com/status-im/status-go/pull/4334

The idea is to periodically publish information about the community shard on the default pubsub topic. Interested parties can then easily retrieve it. The advantage of this approach is that links won't become obsolete in case the shard is created or changed.

**Comment by felicio** [comment]
Ref https://github.com/status-im/status-go/issues/4230.
