### ISSUE TITLE
sharding: community collectibles

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#3962]
In https://github.com/status-im/status-go/pull/3944 sharding for communities is introduced. However the smart contract for the collectibles does not take into account that a community might belong to a shard cluster/index. These collectibles can be used to retrieve information about a community without being part of it.

Once the smart contract is modified to include the required fields, we should modify  https://github.com/status-im/status-go/blob/272b1499b026198fb6224f7187b353f1c2a03add/services/ext/service.go#L570-L577 to include these. In the meantime to not make this a breaking change, the current behavior will be maintained and assume all communities are part of the default pubsub topic

cc: @jrainville

**Comment by richard-ramos** [comment]
What happens if a community shard is set? should a smart contract interaction happen to update the collectible?

**Comment by jrainville** [comment]
Oh that's gonna be annoying. The current behavior is gonna be ok, because we only become aware of the tokens because we are already aware of the community.

However, in 0.15, the wallet team is gonna work on a process to get a community when receiving a token. So this is something they need to be aware of.

I'm not sure what we can do if the shard  changes though. Sending a transaction to change the shard info is way too annoying.

@alaibe is the one that had an idea already as to how to handle the community link when receiving a token, so maybe it's not an issue? I think it involved sending a waku message to a wallet address, so when the shard changes, we just need to send a waku message to the token holders? What about if the token is transferred to another account afterwards though?

This is quite complex.

**Comment by alaibe** [comment]
Adding @dlipicar the reason we do this is that we need to find the metadata for the erc721 and it is inside the community. AFAIK we have no other information that the transaction at that stage...

Regarding the token, that was more for adding erc20 to the list. we assume that erc721 was already handle well as we use third party (like opensea), we didn't need a decentralized solution

**Comment by dlipicar** [comment]
Still trying to understand what sharding is and what it implies for us, but to add some clarification:

For any ERC721 token (chainID+contractAddress+tokenID) we deal with (currently owned by one of our accounts, or present in the account's activity), we first try to get metadata from some of our centralized providers (OpenSea, Alchemy). 
For most normal (i.e. not deployed by us) ERC721 contracts, the standard ERC721 `tokenURI` function returns a link (http, ipfs) to a JSON file with some standard format, containing NFT metadata (name, description, image, etc), so the providers will parse that and give you the metadata fields directly. 
The NFTs we mint for Communities cannot host such metadata in a centralized way, so we store it in Waku as part of the community info. We make the contract's `tokenURI` function return the community key (for example, `zQ3shfbgFinzDKW1Db6iYxLnLV6BJ4deYdMA4Rh1CjhGnFJd6`). Of course OpenSea and Alchemy do not understand that, so they'll return empty metadata for these NFTs. So, what we do is:
- Detect if our provider returns empty NFT metadata
- If that's the case, call the contract's `tokenURI` function, see if what's returned looks like a compressed community key
- Ask `messenger` to give us info about that community, containing NFT metadata. Use that to fill in the NFT detail fields and cache that in our db.

So, if I understand correctly, the community key is no longer the only thing required, we'd now also need to encode a "`shardCluster`" and "`shardIndex`" along with it? And these two values could change after the community's creation?

**Comment by alaibe** [comment]
`So, if I understand correctly, the community key is no longer the only thing required, we'd now also need to encode a "shardCluster" and "shardIndex" along with it? And these two values could change after the community's creation?`

Yes you're understanding is correct, however the solution is not as shard cluster and index can change over time

**Comment by alaibe** [comment]
Finally: we are going to set shard cluster and shard index into contract

**Comment by osmaczko** [comment]
> Finally: we are going to set shard cluster and shard index into contract

@alaibe I am not sure we should do that, please see: https://github.com/status-im/status-go/issues/3961#issuecomment-1785453710 and https://github.com/status-im/status-go/issues/4230

CC @jrainville

**Comment by jrainville** [comment]
Indeed, we decided that modifying the contracts for the shard info wasn't worth it and we'll do the mechanism in https://github.com/status-im/status-go/issues/4230 instead

**Comment by alaibe** [comment]
@osmaczko this has already been done! inside erc20 and erc721 contract there is information about community id.
Feel free to change that but upon receiving transaction we have the need to request community description without more knowledge than what is being store in the contract.

As soon as we can do that i am fine with any solution

**Comment by osmaczko** [comment]
> @osmaczko this has already been done! inside erc20 and erc721 contract there is information about community id.

You meant shard id?

> Feel free to change that but upon receiving transaction we have the need to request community description without more knowledge than what is being store in the contract.
> 
> As soon as we can do that i am fine with any solution

> 

Once https://github.com/status-im/status-go/issues/4230 is implemented we can remove any reference to shard index from contracts.
