### ISSUE TITLE
Implement auto-fulfilment for our Rinkeby faucet

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#404]
# Problem

We have a Rinkeby facuet but we can't mine anything due to the Clique protocol. This is why we need to request ether from faucet.rinkeby.io for further distribution to our users.
Unfortunately, it requires captcha to solve. Currently we end up with a manual "team-driven approach" where all our team request ether for our faucet address.

However, it's desirable to have an auto-fulfilling solution.

# Implementation

Probably, the first step would be to contact the Ethereum team and discuss having some "dedicated" access to their faucet.

@JekaMas also suggested a solution in #383:
> And how many eth do we need? If not too much we may use something like "pay for task service"? The task cost approximately $0.02-0.05. For a single account we got: 4 faucet request per day * 365 * $0.05 = $73

# Acceptance Criteria

Our Rinkeby faucet address https://rinkeby.etherscan.io/address/0xadaf150b905cf5e6a778e553e15a139b6618bbb7 is automatically and regularly filled with ether.

# Notes

This issue is a logical continuation of #383.

**Comment by JekaMas** [comment]
New fauset accout 0xF35E0325dad87e2661c4eF951d58727e6d583d5c
