### ISSUE TITLE
Optimize channels' members

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#4060]
> No major comments, the only concern is to do with size. On mobile, serializing/desesirializing json is quite expensive, so duplicate the member list per each channel can be potentially have a performance impact on some devices.
> 
> Is it necessary? I wonder whether it could be implied by client that if a channel is not permissioned, they should look up the whole list of members?

I wanted to go this direction at first but it was much trickier and required many changes in places not related to permissions. I have a separate [branch](https://github.com/status-im/status-go/compare/desktop/release/0.14.x...fix/community-descr-size-limit-channel-members) for that in draft state, will try to provide it on develop later if needed.

_Originally posted by @osmaczko in https://github.com/status-im/status-go/issues/4058#issuecomment-1733823907_

**Comment by osmaczko** [comment]
Another option is to have : `{"members": {"x": {"channels": [1, 2, 3]}}}` rather than ``{"channel-x": {"members": []}}``. One downside of it is the complexity as members need to be updated each time channels ordering is changed (added, removed, reordered).

**Comment by igor-sirotin** [comment]
@osmaczko I think this was done with the Bloom filter you implemented?

**Comment by osmaczko** [comment]
It is about json serialization, bloom filter didn't solve that.

PS. It was indeed resolved already, but by: https://github.com/status-im/status-go/pull/5335
