### ISSUE TITLE
Standardize Native Binding calls protocol

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#408]
# Problem

status-go provides a set of native bindings: https://www.notion.so/status/Binding-notes-344f30ce0f2845a2b43e2de70931284a

But the response returned to the caller is ad-hoc, inconsistent, errors are unintelligible and there's no specification on anything.

# Acceptance Criteria

1. There is a single document describing each native binding,
2. Each binding has documented input and output formats. Both success and failure outputs are described,
3. Error handling is also described.
4. If any binding needs to have input or output format changed, status-go provides a new binding and deprecates the old one in order to provide a seamless upgrade by status-react.

# Notes

There's a TBD document available to status.im users about standardizing errors:  https://docs.google.com/document/d/1BBit9U2_-_B12NczUiOGzrGMU8z1vQeAAuqE2HVIYKc

# Future Steps

Remove old bindings after a release.

**Comment by rasom** [comment]
Not a big deal, but i'm not sure that `JNI bindings` is a good name. Because there is no JNI on iOS (and on some other platforms which we might use in future), but we still using the same bindings. It could be `Native bindings` or something.

**Comment by adambabik** [comment]
@rasom changed. Do you know what other platforms we plan to support?

**Comment by adambabik** [comment]
This could be greatly improved if we switch to go-mobile. It would generate Java and Objective-C code that is self-documentary and native language structures and types.
