### ISSUE TITLE
Change Loop API to prevent it from accepting tasks when the loop is closed

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#415]
# Problem

The problem was identified in this comment: https://github.com/status-im/status-go/pull/401/files#r144852963

When the loop is stopped, it should not accept any new tasks and return an error.

# Implementation

Change the loop API a bit then:

1. Close `l.ready` channel when the loop is stopped,
2. `func (l *Loop) Add(t Task)` should be `func (l *Loop) Add(t Task) error` + should cancel a task in case of an error (closed loop will yield an error),
3. The same as (2) with `func (l *Loop) Ready(t Task)`,
4. `CallAsync` should take a context? And fail when it's canceled? To prevent handing forever in some strange cases.

# Acceptance Criteria

1. Loop API does not accept new tasks when it's stopped,
2. `CallAsync` has an ability to time out if processing lasts too long,
3. Unit tests are provided covering all mentioned cases.

**Comment by divan** [comment]
To provide some context - current design could (and should) be rethought. Original design from [ottoext](https://github.com/deoxxa/ottoext) package served for another use case (short lived event loops), so we're free to implement own solution with API that serves our needs better.

**Comment by tiabc** [comment]
@oleg-raev is handling this issue.

**Comment by oleg-raev** [comment]
@divan thank you for sharing the context. Seems we need to create an issue for excluding https://github.com/deoxxa/ottoext from the code by refactoring, don't we?
In my implementation of the current issue, I'll keep this in mind.

**Comment by divan** [comment]
@oleg-raev `github.com/deoxxa/ottoext` was renamed to `https://github.com/status-im/status-go/geth/jail/internal` after changing the code, so we don't use `github.com/deoxxa/ottoext` anymore.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x4f9d74f50bc4b64e343ae49202a923ab0eec15b5](https://etherscan.io/address/0x4f9d74f50bc4b64e343ae49202a923ab0eec15b5)
Network: Mainnet
Paid to: thedadams
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by al3rez** [comment]
Going to work on this.

**Comment by vedhavyas** [comment]
@azbshiri are you working on this?
If not, can I take it up?

**Comment by al3rez** [comment]
@vedhavyas not ready for pr, so I think you can.

**Comment by tiabc** [comment]
Hi @vedhavyas, is it still on your todo list to work on this issue?

**Comment by santegoeds** [comment]
If nobody else is working on this anymore I wouldn't mind to take a stab at it.  I've been eyeing the issue and should be able to get a PR ready before Monday.

**Comment by canercidam** [comment]
I can work on this as well.

**Comment by vedhavyas** [comment]
@santegoeds @canercidam not ready for PR yet. you can take it up 👍

**Comment by santegoeds** [comment]
Thank you @vedhavyas. The question was equally directed to @thedadams because he has a PR in progress that looked like it might have stalled.

I see new commits have since been added so I'm going to hold off on this for now.  If it's still not merged next time I have some free space I might take another look.

**Comment by thedadams** [comment]
Hello everyone. I have made changes that the contributors have requested and am back on track to get the PR merged.
