### ISSUE TITLE
Get rid of build/env.sh

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#418]
# Problem

`build/env.sh` adds additional complexity which may probably be safely removed. A comment in go-ethereum's Makefile makes a hint: https://github.com/ethereum/go-ethereum/blob/master/Makefile#L3

# Acceptance Criteria

1. status-go can be built with regular `go build` without any `build/env.sh` magic scripts,
2. Makefile should stay but it should not use `build/env.sh`.

# Notes

There may be reasons why it's done so and it may not work eventually. If so, the reasons should be documented.

**Comment by adambabik** [comment]
I agree that `build/env.sh` is unnecessary. At the same time, I'd like to notice that `Makefile` may be still useful even for people who are familiar with Go tools. 

Can we add to AC that `Makefile` should stay but should not contain references to `build/env.sh`?

**Comment by tiabc** [comment]
Yeah, absolutely. Please, edit the description in whichever way you find the best. I actually love the idea of having all project-related actions in a single place, `Makefile` in our case.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x6102a877655f2b1b78492561ca6ab1c226e2b73cc093a26df481585e682360e3](https://etherscan.io/tx/0x6102a877655f2b1b78492561ca6ab1c226e2b73cc093a26df481585e682360e3)
