### ISSUE TITLE
Possible `eth_CallContract` leakage

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#4201]
according to https://github.com/status-im/status-go/pull/4197 currently we have ~450 `eth_CallContract` calls per hour when idle, that alone costs over 10k requests per day.

Should be identified at first.

**Comment by rasom** [comment]
related to communities

**Comment by rasom** [comment]
@osmaczko @richard-ramos 

Hey guys, mention you because I see you changed the code which makes those calls (or is close to those lines):
as far as I can tell we call `GetCommunities` of `0x22EE86A14b49890957fE71990073C6C68E05F9C5` happens every 10 seconds which is going to be a quite costly idle load (~8.5k calls per day). So if it is intended we need to find some ways to reduce the number of calls here.

**Comment by rasom** [comment]
I was told to mention @endulab just in case

**Comment by osmaczko** [comment]
The culprit is: https://github.com/status-im/status-go/commit/756054039203bac4741121bb2036a25e66834890#diff-e8ae84ba629f58c08abd2b2b3864896c92dd9b3898cf7b450d378f76004bf312

**Comment by osmaczko** [comment]
^ @vkjr, I believe we are being too aggressive in the case of community description request failures. In my opinion, we should stop retrying after a few failures. There are no guarantees that the community in the directory was active in the last x days (mailserver store duration).

**Comment by endulab** [comment]
@rasom is it a community with some tokens minted?

**Comment by rasom** [comment]
@endulab I'm a bit out of context so I'm not sure what that means. But this happens on a newly generated account, and I did not join any community on my own there.

**Comment by endulab** [comment]
Ok, I was thinking that maybe there are some calls related to community tokens smart contracts. But a new community does not have any contracts deployed.

**Comment by rasom** [comment]
@osmaczko @vkjr 
> I believe we are being too aggressive in the case of community description request failures

just a note here, might be unrelated: all those calls were executed while the app was configured with mainnet (I tested wallet related stuff there), but I see that this contract `0x22EE86A14b49890957fE71990073C6C68E05F9C5` is on goerli. So, maybe that's by design and it is hardcoded to use goerli client there, otherwise those calls might fail because of being executed on mainnet.

**Comment by vkjr** [comment]
@rasom 
The purpose of the calls is to get a list of "curated communities" and display it to the user in case he is interested.
 I'll fix it to stop polling when community info can't be fetched after few attempts.

**Comment by rasom** [comment]
@vkjr 
> The purpose of the calls is to get a list of "curated communities" and display it to the user in case he is interested.

I understand that, what I meant is that if we are on mainnent and try to get that info from the contract which is on testnet then we likely will never get that info.

**Comment by vkjr** [comment]
@rasom
hmm, I'm sure that info was fetching at the moment I added that code

**Comment by rasom** [comment]
@vkjr I don't argue with that, and it likely works just fine on goerli. Anyways, you know what to do :)

**Comment by endulab** [comment]
@vkjr @rasom what is the status? I am reaching infura limit calls very quickly. I guess because of this issue.

**Comment by vkjr** [comment]
> @vkjr @rasom what is the status? I am reaching infura limit calls very quickly. I guess because of this issue.

Will work on it today

**Comment by osmaczko** [comment]
> @vkjr
> 
> > The purpose of the calls is to get a list of "curated communities" and display it to the user in case he is interested.
> 
> I understand that, what I meant is that if we are on mainnent and try to get that info from the contract which is on testnet then we likely will never get that info.

This was a workaround because until now we didn't have the Directory contract deployed on the mainnet; so in that case, we always fell back to the testnet.

It will be fixed with: https://github.com/status-im/status-go/pull/4258
