### ISSUE TITLE
Add application metrics for debug sessions

### ISSUE THREAD

**Issue by divan** [status-im/status-go#421]
# Problem

To ensure and maintain quality of the status-go, we need to have visibility of what's happening in a runtime.  Currently we don't have way to see many internal aspects of the status-go running - for example, if there is a goroutine leak, we have virtually no way to detect it, until app crashes in a real world usage.

Metrics allow not only to keep an eye on internals of program during debug/test sessions, but also develop intuition about program behaviour and help to set/define performance agreements and limits.

Due to the nature of status-go as a mobile app, we need an easy way to expose metrics doe debug and test sessions.

# Implementation

Well-known and standard approach in Go a is pull-based metrics collection using `expvar` package from standard library. It allows to use external tools for polling specific endpoint (`/debug/vars`) with all metrics exposed. Developers can add new metrics in 1-5 lines of code anywere in the code and it will be handled by `expvar` automatically. Any application level metrics can be added (custom counter, gauges, historgrams, text values, etc).

This approach requires http server running, so measures should be taken to not to expose it to the outside world and not to run it in the production.

# Acceptance Criteria

 - there is a way to enable/disable "debug" mode
 - metrics code is enabled only for the debug mode
 - once enabled metrics should available at the predefined URL (`/debug/vars` by default)

Initial implementation is started here: https://github.com/status-im/status-go/pull/296#issuecomment-336991399

Rules for the future PR to be accepted.

# Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by adambabik** [comment]
1. I would change the title of this issue to "Go runtime metrics". We should also have application metrics which are a different topic,
2. Pull model might not be the best choice in this case. Is it possible to access the server from a real device? 
3. It would be great if we can connect a test session recorded by the Test Team with a collected metrics. Maybe we can connect some app freezes with higher status-go CPU consumption or GC pauses?
4. Consider https://github.com/prometheus/client_golang. Prometheus would give as a nice tool to analyze these metrics. Not sure what's your current plan to analyze them. `expvarmon` looks very slick but it's only for real-time monitoring I guess.

**Comment by divan** [comment]
@adambabik thanks for response, I think I should explain purpose of this a bit better.

1. It's not about only "Go runtime metrics" it's about any measurable variable we want to keep an eye on - number of cells, stats on RPC requests, size of payloads, etc, etc - pretty much any custom metrics. Go runtime metrics just included by default.

2. Yes, for Android it's as simple as add forwarding for the exposed port: `adb forward tcp:10000 tcp:10000`. Pull based metrics approach is perfect for this case - when we have short-lived debug sessions to monitor in real time. However, it's also extendable to the push-based approach via collectors/proxy scripts, if needed (if we decide to use metrics also for TestFairy sessions, it would be trivial to implement as a separate script, no need to change the code).

3/4. Yes, that was a point - almost zero-conf metrics for development/debug purposes. Setting up metric collection/storage/display metrics infrastructure is overly complicated and unneeded. Idea is to have a simple way to understand behaviour of the program during local test/debug sessions. It doesn't substitute testing, of course, rather helps us to build intuition about internal behaviour and spot unwanted behaviour before we even realize that it might have been a problem.

Currently I have pretty uncomforable not knowing numbers behind even basic functions of the app - we can't answer questions like "how many jail cells are actually created?", "how many tasks in the event loop for the cell?", "how many pending transactions in a queue?", "how much goroutines are started on account creation", etc, etc.

**Comment by adambabik** [comment]
@divan so it's application metrics as well. Could you add more details on that to the Implementation section? 

Regarding the second point:

> Yes, for Android it's as simple as add forwarding for the exposed port
It's simple for Android but what about iOS? It must work for both platforms and for simulators and real devices. 

> Pull based metrics approach is perfect for this case - when we have short-lived debug sessions to monitor in real time.
If it's supposed to run only during development then yes.

> Setting up metric collection/storage/display metrics infrastructure is overly complicated and unneeded. Idea is to have a simple way to understand behaviour of the program during local test/debug sessions.

It's not that complicated. You run a few docker containers and that's all. What I mean here are two things:
1) Ability to compare multiple sessions or historical sessions. How do you know if some metric is not getting worse and worse with every release if you don't have any historical data?
2) The terminal-based interface looks cool but IMO its usability is very limited. Compare it with e.g. [Grafana](https://grafana.com/). Is it possible to use a different interface than the terminal-based one?

---
The fundamental question here is whether this issue is only about exposing some metrics during development or it's about creating a more versatile solution. The latter one would allow collecting metrics from any release but definitely is more complex and requires some additional infrastructure and maintenance. I am not sure we currently have people who can take care of that.

**Comment by divan** [comment]
> Could you add more details on that to the Implementation section?

Sure. Done.

> It must work for both platforms and for simulators and real devices.

I don't see any fundamental obstacles why it might have been a problem iOS simulator. It's just I don't have one running, so I can't quickly say how exactly one does port forwarding there.

> Is it possible to use a different interface than the terminal-based one?

Sure, you can setup a script (I guess there are programs/scripts already supporting expvar json) than will pull the json and forward to any other "adult" metrics solution - Prometheus, Grafana, etc.

I would say that we don't want and don't need metrics infrastructure - as you said, it's complicated and benefits from it are dim. Retrospectively comparing values between test sessions is prone to the same problem as typical benchmarking - how do you know that system was under the same load or that it was the same system/version at all?

Again, instead of trying to bring server-like metrics solutions, I want to focus on specific problem - absence of visibility of what is happening inside a program and poor intuition about internals. So this "light metrics for dev/debug session" is a good trade off between features offered and easiness to use, and it does solve the problem.

**Comment by adambabik** [comment]
> I don't see any fundamental obstacles why it might have been a problem iOS simulator.

Because it's Apple :) Just pointing out as a possible blocker for the pull-based solution. It might be trivial but I don't know.

> Retrospectively comparing values between test sessions is prone to the same problem as typical benchmarking

Correct but if you compare a few different metrics in a few sets and only one is off it may indicate some problems in that particular area. But clearly, it is not part of this issue 👍 

> Again, instead of trying to bring server-like metrics solutions, I want to focus on specific problem - absence of visibility of what is happening inside a program and poor intuition about internals.

And it's cool but let's be more specific in the title and description. "Add metrics" is pretty broad and I guess we want to "Add debug metrics". It would be also great to define a minimal set of metrics in Acceptance Criteria.

**Comment by divan** [comment]
@adambabik thanks, changed the title. As for the minimal set of metrics - there is none. Idea is that developers can add new metrics on the go without worrying much about performance impact and configuration. It should be as easy as adding a log print. Let's say, you're debugging the problem with txqueue, and realize that you have no idea how many transactions usually are in a queue, so you quickly add this metric and quickly get visibility.

**Comment by pedropombeiro** [comment]
@divan, is this something that would make sense to get the ball rolling again? That would mean:
- taking the PR you started
- adding some obvious metrics such as number of jail cells
- taking care that there is a hidden "debug" toggle on the client apps to gate this functionality(?)
- anything else?

I can also look into geth metrics and compare both solutions, if that's something we feel is worthwhile.

**Comment by divan** [comment]
@PombeirP oh, this issue is not updated as it should be, but actually we're working on it this week. There is also a related project that I plan to extend to support more custom metrics and serve as a proxy to metrics storage/analysis solutions like Prometheus. It's in https://github.com/status-im/statusmonitor repo.

**Comment by pedropombeiro** [comment]
Thanks for letting me know @divan

**Comment by divan** [comment]
Obsolete as other metrics approaches are explored.
