### ISSUE TITLE
Use CHT for Rinkeby

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#423]
# Problem

CHT doesn't work for Rinkeby.

The task is to devise a way to start syncing Rinkeby from one of the latest blocks.

# Implementation

Two options:
1. Investigate how it's done in go-ethereum and understand if there's a way to set up CHT for Rinkeby.
2. Just download state from somewhere and put it to the folder on the mobile device. Hacky and dirty but may bring results fast.

# Acceptance Criteria

Rinkeby sync on mobile devices starts from one of the latest blocks.

# Notes

 I tried asking a question in https://gitter.im/ethereum/go-ethereum but got no reply.
Some insight about CHT in Clique in general: https://github.com/status-im/status-go/issues/150#issuecomment-307152216

**Comment by themue** [comment]
@tiabc Is this a more general problem of CHT and Rinkeby or is it a Status specific problem? And how does it appear (logs, errors, panics, erroneous functionality)?

**Comment by tiabc** [comment]
It's a thing in go-ethereum and the Clique protocol, as I understand. Computing CHT for Rinkeby should be different and I'm not aware how that works. If there was anybody who know that and can share it to others or create a document explaining that, that'd be awesome both for Status and other people who keep asking about CHT in go-ethereum gitter channel.

It shows up as blockchain sync in status-go starts from block 0 if you run it on Rinkeby:
`statusd --log INFO --networkid 4 les`

**Comment by themue** [comment]
Thanks, that's a very good hint and I know where I'll start. Today already dived into the code by seeking according identifiers and comments. Will tomorrow also try to find more help on Gitter and other forums (e.g https://ethereum.stackexchange.com).

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 6000.00
Contract address: [0x6d3351a5f114f2c5f94bc42bde3740141d2b7710](https://etherscan.io/address/0x6d3351a5f114f2c5f94bc42bde3740141d2b7710)
Network: Mainnet
Paid to: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by Jasonhcwong** [comment]
For option 1: it seems that geth has not implement CHT for Rinkeby yet.
I tried Geth/v1.7.3-unstable-bfdc0fa3 and it start syncing from block 0. 

jason@jason-Lenovo:~/go/src/github.com/go-ethereum$ build/bin/geth --syncmode light --rinkeby
WARN [11-06|20:00:18] No etherbase set and no accounts found as default 
INFO [11-06|20:00:18] Starting peer-to-peer node               instance=Geth/v1.7.3-unstable-bfdc0fa3/linux-amd64/go1.8.3
INFO [11-06|20:00:18] Allocated cache and file handles         database=/home/jason/.ethereum/rinkeby/geth/lightchaindata cache=128 handles=1024
INFO [11-06|20:00:18] Initialised chain configuration          config="{ChainID: 4 Homestead: 1 DAO: <nil> DAOSupport: true EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1035301 Engine: clique}"
INFO [11-06|20:00:18] Loaded most recent local header          number=0 hash=6341fd…67e177 td=1
INFO [11-06|20:00:18] Starting P2P networking 
INFO [11-06|20:00:21] UDP listener up                          self=enode://cca1df813f70e2d2b1e341bcc09e95e4d9b6c1567e57e86ad0cd27b984059a7eb7b183ebc20ce207e68ae8fef94aebd7d96842e26ae2ae5b2f9fa5e8c582e847@[::]:30303
WARN [11-06|20:00:21] Light client mode is an experimental feature 
INFO [11-06|20:00:21] RLPx listener up                         self=enode://cca1df813f70e2d2b1e341bcc09e95e4d9b6c1567e57e86ad0cd27b984059a7eb7b183ebc20ce207e68ae8fef94aebd7d96842e26ae2ae5b2f9fa5e8c582e847@[::]:30303
INFO [11-06|20:00:21] IPC endpoint opened: /home/jason/.ethereum/rinkeby/geth.ipc 
INFO [11-06|20:00:41] Block synchronisation started 
INFO [11-06|20:00:41] Imported new block headers               count=192 elapsed=62.783ms number=192 hash=8c570c…ba360c ignored=0
INFO [11-06|20:00:42] Imported new block headers               count=576 elapsed=199.372ms number=768 hash=d2f106…d25b87 ignored=0
INFO [11-06|20:00:42] Imported new block headers               count=192 elapsed=65.050ms  number=960 hash=413833…8d126d ignored=0

**Comment by tiabc** [comment]
@Jasonhcwong thanks for getting back. Yes, we know. The goal is to understand why and whether we can improve on anything here in a reasonable time.

**Comment by pablanopete** [comment]
@adambabik @themue where did we ever end up on this? Issue is different now and should be revoked?

**Comment by themue** [comment]
As @adambabik mentioned in chat it possibly is interesting for DApps developers wanting to test their code on Status and with Rinkeby. Looks like a pretty small user group right now, but may become more interesting later with a more established Status. So I possibly would reduce priority and let it step back. Just my 2 cents.

**Comment by pablanopete** [comment]
Gotcha, thanks @themue  👍

**Comment by kishansagathiya** [comment]
@tiabc rooky question, but can you tell what is the fullform of CHT?
