### ISSUE TITLE
Fix public testnet tests

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#424]
# Problem

Our faucet account has been changed and we can't store its passphrase in plain as ether from them may easily be stolen, which already happened 3 times and caused significant inconvenience, and we don't want that even though it's test ether. Just because it costs some efforts for us.

However, we need ether on some public testnet to run tests. For that we require:
1. An encrypted account file.
2. A password to unlock it.

The first is fine, we can check it into our repo and the second is the one which a solution is to be devised for as can't store it in plain in the repo.

# Implementation

Although I see three options to choose from for achieving that, I'm really inclined to the 3rd and it's the only one I'd like to describe. Feel free to question my choice.

## 1. Request eth for a shared testnet account before tests

TBD

## 2. Request eth for a personal testnet account before tests

TBD

## 3. Store passphrase in an env var

Everyone running tests will require that environment variable set to run tests against a public testnet.

Implications:
1. Nobody will be able to run tests on a public testnet unless they have that env var set.
2. We'll have to add an encrypted variable to `.travis.yml`.

The first fact actually makes us more scalable: everybody is able to run tests against StatusChain locally but nobody is able to spend public testnet funds on their own by constantly running tests. But tests can still be run on our CI. Pretty neat.

Still any core contributor (currently less than 10 people) can run tests locally if they want as they may have the passphrase set.

# Acceptance Criteria

1. Tests can be run against public testnets.
2. No passphrase is stored in status-go in plain.
3. Account for tests is different from the faucet's so our faucet shouldn't be damaged if the test account is compromised. We'll be filling the test account manually with funds every 4 weeks, for example. This will also allow us to track faucet account and test account separately and find any inconsistencies faster.
4. e2e upstream tests are run only for public testnets.

# Notes

This issue is high-priority as we currently have no guarantee our code works without these tests.

However, #407 had better be done first as it will allow more people to run tests and tests on a private chain are more reliable and fast.

Please, regard zenhub dependency as a recommendation rather than a hard dependency, these two issues can be done simultaneously.

**Comment by adambabik** [comment]
The third option is the most straightforward and highly efficient. The plan looks solid!

**Comment by influx6** [comment]
Am rather interested in this PR has i have a project which similar requires encryption at some level, so this PR should definitely help in research for that, though it's intentions are totally different. I do have a few questions:

- Is the account file is currently being stored as plained text and if so where?
- What type of encryption are we looking at, any thoughts or am free to go plain around on choice?

**Comment by tiabc** [comment]
One of them: https://github.com/status-im/status-go/blob/90acfedf7ac60ab641e9db4cac84d7db1bad6d8e/static/keys/test-account1.pk#L1

@influx6 sorry, what do you mean? You just need to:
1. Generate two new uncompromised accounts and set 2 different hard (say, 25 alphanumeric chars) passphrases to them.
2. Replace the existing accounts with the new and request some ether for the first from a public faucet (not from ours).
3. Make use of an environment variable holding the plain passphrase in tests to unlock accounts.
4. Add an encrypted variable to `.travis.yml`: https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml
5. Fix travis to run tests on a public testnet after the private.
6. Communicate the generated passphrases with the rest of the core team via a secure medium.

**Comment by tiabc** [comment]
@JekaMas you may be interested that #430 has been merged. Please, merge `develop` asap.

**Comment by JekaMas** [comment]
@tiabc I've added file encryption in this issue so we can remove all hardcoded secure data from code.

**Comment by tiabc** [comment]
@JekaMas could you create an in-progress pr? Your words sound suspicious.

**Comment by JekaMas** [comment]
Done. Nothing suspicious i think: i've just encrypt all static/keys folder, added some commands for decrypt/encrypt into Makefile and helper function that reads encrypted data from bindata and decrypts it without storing to disc (for encryption/decryption i've added two env variables as it described in issue).
