### ISSUE TITLE
Enable usage of WakuStoreNodes in status-go

### ISSUE THREAD

**Issue by mohammad-babaei** [status-im/status-go#4269]
Currently, in the status-go configuration, there is a field WakuStoreNodes under ClusterConfig that is intended to specify Waku v2 nodes with the store protocol enabled. However, this field is not currently used anywhere in the codebase. This means that even if a user specifies Waku v2 nodes with the store protocol enabled in the WakuStoreNodes field, these nodes are not utilized by status-go.
The code warns me that no mailserver is found.
How can i have a wakuv2 fleet with store capability?

**Comment by igor-sirotin** [comment]
@mohammad-babaei thanks for your report.
Running a `StoreNode` is not something we're going to do in `status-go`. For this purposes you should run a Waku node directly. Please take a look at `nwaku` docs here: https://docs.waku.org/guides/nwaku/run-node, or `go-waku` implementation: https://github.com/waku-org/go-waku.

Let me know if you have any more questions.
