### ISSUE TITLE
Add test for WakuV2 Store

### ISSUE THREAD

**Issue by vitvly** [status-im/status-go#4317]
There is a `wakuv2.Config.EnableStore` flag that can be used to enable Store protocol on local Status node:
https://github.com/status-im/status-go/blob/010afb4b39e0d4aa2315cc438c0c5759a5742f6d/wakuv2/waku.go#L306

However, there are no associated tests. It would be good to have one in a manner similar to `TestBasicWakuV2` here: https://github.com/status-im/status-go/blob/010afb4b39e0d4aa2315cc438c0c5759a5742f6d/wakuv2/waku_test.go#L176

but using a local store node.

**Comment by plopezlpz** [comment]
**Weekly Update**

- _achieved_: worked on some tests
- _next_: #4366
