### ISSUE TITLE
Fix linter warning across the whole project

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#435]
# Problem

As we integrated pretty a lot of linters into our CI pipeline, there are many warning identified. 

# Implementation

Fix all warning reported by `make lint` across the whole project. 

`goimports` should be removed as we agreed that `gofmt` sorts modules good enough.

# Acceptance Criteria

1. `make lint` reports no errors/warnings.

# Notes

It's a blocker because none PR will be able to pass CI checks.

**Comment by b00ris** [comment]
It was fixed twise. At #388 and #387. Why do we need it? New warnings are coming from uncleaned PR.

**Comment by tiabc** [comment]
@adambabik as you've noticed that, can you fix that, please? I don't think it'll take a lot of time.

**Comment by adambabik** [comment]
Done https://github.com/status-im/status-go/pull/436
