### ISSUE TITLE
Block sending messages that exceed the waku limit and return an error

### ISSUE THREAD

**Issue by jrainville** [status-im/status-go#4355]
# Problem

A couple of times, we've been bit by the fact that waku has a size limit and we don't enforce it correctly in status-go, or at least with waku v2.

What should happen when we try to send a message that exceeds the limit is we block sending it and return an error. That way, the client can show a proper error.

What happens currently is the action is sent by the user and no error is ever shown, not even in the console, so the message will never be received by anyone.

This happened before with the community description. The community never updated anymore, but there was no info received by the clients.

# Acceptance Criteria

When a message is too big to be sent, an error is returned and gets propagated back to the client.

**Comment by jrainville** [comment]
cc @richard-ramos

**Comment by kaichaosun** [comment]
Hi @jrainville I wonder how to reproduce this issue, could you confirm if this issue still exist or not?

I tried to create a community with long description and big image, also send out long messages. I noticed that status-desktop has a length limit regarding to message length and description length (140 characters). Test against the build binary https://github.com/status-im/status-desktop/pull/12765.
Also test the big image which is actually compressed during our pair programming between @igor-sirotin and me.

When reading the code, I learn that there are some latest changes which split big message to segments (https://github.com/status-im/status-go/pull/4285).

Along with the max msg length check added by @chaitanyaprem.

**Comment by jrainville** [comment]
The problem has mostly been circumvented by @osmaczko by splitting the message in chunks, but it's an app layer mechanism and I think fixing this problem on a lower level would still help since it would make sure we have info if this happens again (for example the limit changes and we forget to update the app level mechanism).

@osmaczko can help you deactivate the mechanism and test sending a big message.

**Comment by osmaczko** [comment]
> @osmaczko can help you deactivate the mechanism and test sending a big message.

The simplest way to deactivate the message segmentation for testing purposes would be:
```diff
diff --git a/protocol/common/message_sender.go b/protocol/common/message_sender.go
index f7013b8e6..d6eb91d3d 100644
--- a/protocol/common/message_sender.go
+++ b/protocol/common/message_sender.go
@@ -1286,7 +1286,7 @@ func segmentMessage(newMessage *types.NewMessage, maxSegmentSize int) ([]*types.
 func (s *MessageSender) segmentMessage(newMessage *types.NewMessage) ([]*types.NewMessage, error) {
     // We set the max message size to 3/4 of the allowed message size, to leave
     // room for segment message metadata.
-    newMessages, err := segmentMessage(newMessage, int(s.transport.MaxMessageSize()/4*3))
+    newMessages, err := segmentMessage(newMessage, 100 * int(s.transport.MaxMessageSize()/4*3))
     s.logger.Debug("message segmented", zap.Int("segments", len(newMessages)))
     return newMessages, err
 }
```

However, I believe it should be tested in a lower layer at https://github.com/status-im/status-go/blob/develop/protocol/transport/transport.go. We should check whether `t.api.Post(ctx, *newMessage)` returns an error when the size of newMessage exceeds the limit.

**Comment by kaichaosun** [comment]
Thanks for the inputs.
I have done the check for `t.api.Post` in https://github.com/status-im/status-go/pull/4421.
But it's duplicated with what waku already done, the error raised in waku is not propagated to `t.api.Post` because it's communicated with `EventEnvelopeExpired`. 

What do you think is the next step or any suggestions? @osmaczko @jrainville

**Comment by osmaczko** [comment]
> Thanks for the inputs. I have done the check for `t.api.Post` in #4421. But it's duplicated with what waku already done, the error raised in waku is not propagated to `t.api.Post` because it's communicated with `EventEnvelopeExpired`.
> 
> What do you think is the next step or any suggestions? @osmaczko @jrainville

I believe the issue can be considered resolved. As you pointed out, we will receive an `EventEnvelopeExpired` event, [resulting in](https://github.com/status-im/status-go/blob/develop/protocol/transport/envelopes_monitor.go#L276) the message remaining in 'not sent' mode. This will be displayed as a message annotation on both the status-desktop and mobile platforms, if I'm not mistaken.

**Comment by kaichaosun** [comment]
Mark it close, feel free to reopen it if there are missing tasks.
