### ISSUE TITLE
Communities should be able to define the list of store nodes

### ISSUE THREAD

**Issue by plopezlpz** [status-im/status-go#4357]
Message history retrieval works either by using a hardcoded list of store nodes from the status fleet, or using store nodes that were added manually via the advanced settings. Communities should be able to define the list of store nodes, either via a DNS discovery URL or specifying the list of nodes.

#### Scenario 1: _Get new storenode info from fetching community info:_
  1. Owner creates a community
  2. Owner sets the store node for the community
  3. Owner sends a message to the "general" community chat
  4. Bob joins the community and fetches the community info including the storenode info for that community
  5. Bob can see the community message fetched from the appropriate storenode

#### Scenario 2  _Get new storenode info from control message:_
  1. Owner creates a community
  2. Bob joins the community
  3. Owner sets the storenode for the community
  4. Bob gets the new storenode info from the control message
  5. Owner sends a message to the community chat
  6. Bob can see the community message fetched from the appropriate storenode 

#### Scenario 3: _Get new storenode info from fetching community info:_
  1. Owner creates a community
  2. Owner sets the store node for the community
  3. Owner sends a message to the "general" community chat
  4. Wait 30 days for the community description 
  5. Bob joins the community and fetches the community info including the storenode info for that community
  6. Bob can see the community message fetched from the appropriate storenode

**Comment by plopezlpz** [comment]
https://github.com/status-im/status-go/pull/4364

**Comment by chair28980** [comment]
commenting to force re-index of github's search
