### ISSUE TITLE
fatal error: memory violation when syncing rinkeby

### ISSUE THREAD

**Issue by ligi** [status-im/status-go#439]
Just wanted to try out the network switching and status-im with rinkeby so I can test for interoperability with WALLETH. Unfortunately it is crashing for me when syncing rinkeby. The StackTrace is too long to embed in the issue - so I put it in a gist: https://gist.github.com/ligi/1235ddf4cc0bd2c7bb47e3207f8d4b4b

**Comment by rasom** [comment]
Can you try to switch to rinkeby with upstream RPC meanwhile? No need to wait for synchronization in this case.

**Comment by ligi** [comment]
Yes did this afterwards - this works - thought I report the crash anyway.

**Comment by tiabc** [comment]
The supposed cause of the issue was too high CPU consumption while syncing and the OS killed the process. I'll leave the issue open while we're working on optimization.

@ligi, what's your phone model, hardware and the OS version?

**Comment by ligi** [comment]
The phone this crash happened on was a Galaxy Note 4 running the official 6.0.1 for this phone (no custom ROM)

**Comment by dshulyak** [comment]
I will close this issue cause geth version moved to far
