### ISSUE TITLE
Clean up Status native bindings

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#440]
# Problem

status-go exposes a bunch of functions (bindings) that can be called as C code. This requirement and the way it was built impede testing end extending this functionality.

1. Even though there is `geth/api` package, there is still a lot of business logic in some bindings,
2. Many tests in `utils.go` are duplicated in `e2e/` packages,
3. Due to the fact that tests call C functions, they must be put in `utils.go` and called from `library_test.go`.

# Implementation

This is a huge task and should be split into smaller ones before starting work. 

The most important goal is to move all business logic from bindings to `StatusAPI` struct. The bindings should merely call the `StatusAPI`, handle errors and format the output accordingly. This way, we will be able to add other interfaces to `StatusAPI` like `gomobile` without duplicating any business logic.

# Acceptance Criteria

1. Business logic is moved away from bindings to `StatusAPI`,
2. There are no e2e tests testing bindings,
3. Bindings have unit tests with mocked `StatusAPI` which will verify error handling and output formats.

# Future Steps

Switch to gomobile if decided it https://github.com/status-im/status-go/issues/391.

**Comment by divan** [comment]
@adambabik this PR (https://github.com/status-im/status-go/pull/441) (still in progress) might be related to this issue.

**Comment by tiabc** [comment]
@adambabik

The first point from implementation is #408. Can you further specify #408 and remove that point from the list?

The only question here is how do we test native bindings before we switch to `gomobile`? It seems we need to discuss and switch to it first, right? Because if we switch to `gomobile`, there won't be a need to have them tested in some special way, right?

**Comment by adambabik** [comment]
> The first point from implementation is #408. Can you further specify #408 and remove that point from the list?

Sure.

> The only question here is how do we test native bindings before we switch to gomobile? 

My idea is that we move business logic from bindings to `StatusAPI` (the majority of bindings are already written in this way). We may need to add e2e tests to some of `StatusAPI` methods. Bindings will be tested with the `StatusAPI` mock to just verify proper output data formats.

> It seems we need to discuss and switch to it first, right? Because if we switch to gomobile, there won't be a need to have them tested in some special way, right?

Do you mean to first switch to `gomobile`? I think we can do that in parallel as long as the whole business logic is in `StatusAPI`. And yes, with `gomobile` we won't be using Cgo so tests can be written normally. It may be even possible to expose `StatusAPI` as a module or just compose it into something like `StatusMobileAPI` struct as, for example, `gomobile` does not support returning multiple arguments.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd97d142ad2148b4d80afe43567a4dd6771e3e29ad44218cec8485372c22df48b](https://etherscan.io/tx/0xd97d142ad2148b4d80afe43567a4dd6771e3e29ad44218cec8485372c22df48b)

**Comment by jonprice** [comment]
I was going to take a look at this. I was planning on moving the business logic of creating the geth/common types into the StatusAPI, was this expected or should the StatusAPI function's signature stay the same.

**Comment by adambabik** [comment]
Hey @jonprice. Not sure what you exactly mean by 
> moving the business logic of creating the geth/common types into the StatusAPI

To direct you into specific code fragments, take a look at `lib/library.go`. It's a file where all bindings are collected as C functions. Most of them just forward calls to `StatusAPI`, for instance, `StartNode(configJSON *C.char) *C.char` or `func StopNode() *C.char`. However, there are a few that have more business logic which should not be there like `ValidateNodeConfig`.

Regarding `ValidateNodeConfig`, we could move its logic to `StatusAPI.ValidateStringConfig(config string) (common.APIDetailedResponse)` and call it from `ValidateNodeConfig` C binding like this:
```go
func ValidateNodeConfig(rawConfig *C.char) *C.char { 
  result := statuAPI.ValidateStringConfig(C.GoString(rawConfig))
  response, err := json.Marshal(result)
  if err != nil {
    return makeJSONResponse(err)
  }
  return C.CString(string(response))
}
```

The next step is to test `ValidateNodeConfig` C binding using a mock or something like that. We just want to check if it calls `statusAPI.ValidateStringConfig` and properly marshals the response.

If you'd like to work on this, I would suggest proceeding with one binding, for instance, `ValidateNodeConfig` so that we can evaluate your solution and if it's correct, we can move forward with the rest. Also, we will review this issue to reduce scope to just a few specific bindings. Does it sound ok?

**Comment by jonprice** [comment]
I think your example matches what I was thinking, for example updating the StatusAPI.CreateAccount to return common.AccountInfo instead of 4 string fields. 

I'll go ahead and proceed with that change, should I create a pull request to get feedback on the change, or do you prefer pull requests wait until an issue is completed?
