### ISSUE TITLE
Package status-go as a node.js native module

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#447]
# Problem

We want to run status-go within electron desktop app and communicate with it from node js environment

# Implementation

https://stackoverflow.com/questions/20728255/could-one-write-a-native-node-js-extension-in-go-as-opposed-to-c

**Comment by divan** [comment]
Related discussion: https://github.com/status-im/ideas/issues/2

**Comment by divan** [comment]
Implemented in https://github.com/status-im/status-nodejs
