### ISSUE TITLE
bug: missing commits in `develop` from release branch:

### ISSUE THREAD

**Issue by richard-ramos** [status-im/status-go#4529]
The following PRs do not have an equivalent in `develop` and should be cherry-picked:
- [ ] https://github.com/status-im/status-go/pull/4455
- [ ] https://github.com/status-im/status-go/pull/4405

**Comment by igor-sirotin** [comment]
Working on a cherry pick.
Not to forget a link: https://github.com/status-im/status-go/pull/4401

**Comment by igor-sirotin** [comment]
@richard-ramos thanks for noticing!
I cherry picked my part here: https://github.com/status-im/status-go/pull/4538

@endulab I didn't pick https://github.com/status-im/status-go/pull/4455, not to mess things up.

**Comment by endulab** [comment]
I added here: https://github.com/status-im/status-go/pull/4540
