### ISSUE TITLE
Nightly tests crash with "C malloc failed"

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#4586]
https://github.com/status-im/status-go/issues/4264#issuecomment-1869004017

**Comment by osmaczko** [comment]
I haven't observed it locally, nor have I observed a memory leak in tests. This is most likely due to the Jenkins node running out of memory, resulting in a malloc failure. @yakimant, can you please help me figure that out? If this error occurred, how much memory did the Jenkins node use?

**Comment by osmaczko** [comment]
Stopped working on it; the malloc issues don't break or hang the whole thing, so they're not critical.

**Comment by yakimant** [comment]
I don't see any memory issues while protocol tests were running:

```
[2024-01-23T03:25:55.274Z] Testing: github.com/status-im/status-go/protocol
[2024-01-23T05:32:14.082Z] Failed, see the log: /home/jenkins/workspace/status-go/tests-nightly/protocol/test.log
```

```
TestMessengerSyncWalletSuite: 25.0% (1 of 4 failed)
TestMessengerSyncWalletSuite/TestSyncWallets: 25.0% (1 of 4 failed)
TestMessengerSendImagesAlbumSuite: 20.0% (1 of 5 failed)
TestMessengerSendImagesAlbumSuite/TestAlbumImageMessagesWithMentionSend: 20.0% (1 of 5 failed)
TestMessengerStoreNodeRequestSuite: 20.0% (1 of 5 failed)
TestMessengerStoreNodeRequestSuite/TestConsecutiveRequests: 20.0% (1 of 5 failed)
TestMessengerStoreNodeRequestSuite/TestFetchRealCommunity: 20.0% (1 of 5 failed)
TestMessengerStoreNodeRequestSuite/TestFetchingCommunityWithOwnerToken: 20.0% (1 of 5 failed)
```
- should be "out of 20"

![Screenshot 2024-01-24 at 15 51 55](https://github.com/status-im/status-go/assets/1529006/c9e1bf92-d60f-40bf-af83-55f5ce734a98)
https://grafana.infra.status.im/goto/tKM0sRtSz?orgId=1

**Comment by osmaczko** [comment]
![image](https://github.com/status-im/status-go/assets/33099791/2ae07599-0fa3-4a29-81cf-23969ed0e3cf)

Isn't this suspicious? At peak, node used ~20GB of RAM, it seems way too much. I know there is much RAM left, but maybe there is ulimit or something that kills the process?

**Comment by yakimant** [comment]
I don't know much about `status-go`, so hard to tell.

I wonder if it is always failing at the same test or not?
