### ISSUE TITLE
Nightly tests output isn't parsed properly

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#4587]
https://github.com/status-im/status-go/issues/4264#issuecomment-1868999107

**Comment by osmaczko** [comment]
@yakimant could you please check what version of `go-junit-report` is used on CI? Version >=v2.1.0 contains: [Fix #140: Escape illegal XML characters in junit output](https://github.com/jstemmer/go-junit-report/pull/140), which should effectively fix our problem.

**Comment by yakimant** [comment]
Nice finding! We have `2.0.0`. Will be quite easy to upgrade:
https://github.com/NixOS/nixpkgs/commit/8ee045a5b147a16cb20c273ca269d52396614899

I will make a PR for that.

**Comment by yakimant** [comment]
@osmaczko, I've checked the test stats report, it works again.
Thanks for your finding!
