### ISSUE TITLE
Configure codeclimate test coverage

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#4588]
For a start just to see the values.

**Comment by igor-sirotin** [comment]
cc @apentori @yakimant 
@apentori has full input.

**Comment by apentori** [comment]
![image](https://github.com/status-im/status-go/assets/124469871/37e0b8d8-46b4-4441-8161-594922b72861)

Unfortunately I don't have permission> 
@jakubgs link of code climat https://codeclimate.com/github/status-im/status-go/pull/4584

**Comment by yakimant** [comment]
Link to documentation:
https://docs.codeclimate.com/docs/im-seeing-a-403-permission-error

**Comment by jakubgs** [comment]
This is hilarious, I'm trying to add `status-go` repo on CodeClimate but it thinks it's another repo:

![image](https://github.com/status-im/status-go/assets/2212681/71310b1d-496c-45d7-866d-1cb13e7883ae)

I clicked the button for `status-go`.

**Comment by jakubgs** [comment]
Okay, looks like one has to scroll, because if `ctrl+f` is used then buttons are broken. Very cute.

Done: https://codeclimate.com/github/status-im/status-go

**Comment by igor-sirotin** [comment]
What's the state on this issue? 
@yakimant, could you please take another look?

**Comment by yakimant** [comment]
I'm a bit out of the context.

So test coverage is not setup, but code climate was used for a long time for another purpose?
`.codeclimate.yml` is 6 years old.

**Comment by yakimant** [comment]
Docs:
- https://docs.codeclimate.com/docs/configuring-test-coverage
- https://docs.codeclimate.com/docs/getting-started-test-coverage
- https://docs.codeclimate.com/docs/jenkins

Test reporter settings page:
https://codeclimate.com/repos/5a27e6e598ad8b056c002ca2/settings/test_reporter

**Comment by yakimant** [comment]
1. [ ] Install test reporter tool: https://github.com/codeclimate/test-reporter/
2. [ ] Set ENV var with test reporter id: `CC_TEST_REPORTER_ID`

**Comment by yakimant** [comment]
added credential, you can use it in Jenkinsfile:
```
        withCredentials([
          string(
            credentialsId: 'codeclimate-test-reporter-id',
            variable: 'CC_TEST_REPORTER_ID'
          ),
        ]) {
...
        }
```
