### ISSUE TITLE
Ensure tests pass in PRs from other repos

### ISSUE THREAD

**Issue by tiabc** [status-im/status-go#459]
# Problem

In PRs from forked repos back to upstream it's impossible to access Travis secret values and it's correct. However, we need a fast and consistent way to ensure a PR is correct and should fix CI for this purpose.

# Implementation

1. Don't run the last stage (e2e tests on a public testnet) for PRs.
2. Fix or remove failing tests (please, justifying your decision):
```
--- FAIL: TestVerifyAccountPassword (1.52s)
	Error Trace:	accounts_test.go:81
	Error:      	unexpected error: expected 
	            	'<nil>', got 
	            	'could not decrypt key with given passphrase'
--- FAIL: TestVerifyAccountPasswordWithAccountBeforeEIP55 (1.51s)
	Error Trace:	accounts_test.go:110
	Error:      	Received unexpected error:
	            	could not decrypt key with given passphrase
FAIL
coverage: 12.2% of statements
FAIL	github.com/status-im/status-go/geth/account	3.157s
```

# Acceptance Criteria

CI for a PR from a forked repo for this issue pass

# Notes

Setting `high-priority` as it hinders external contributions.

If you're not a core contributor, you may have to contact one of the core contributors to adjust what Travis runs on PRs.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2000.00
Contract address: [0x67571bd5cb9b2bcf7e139ca8c4cfc0cad09c949f](https://etherscan.io/address/0x67571bd5cb9b2bcf7e139ca8c4cfc0cad09c949f)
Network: Mainnet
Paid to: perissology

**Comment by monokh** [comment]
@tiabc The tests in question also fail locally which makes running the unit test suite difficult. 
I can't confidently say if this test is necessary or not... but what if we moved it to the e2e stage?

**Comment by tiabc** [comment]
Well, these tests ensure account decryption works properly and they're worth keeping.
As an option, you can create new accounts with no funds and passwords stored in plaintext just to test their decryption. This would do.

**Comment by ewingrj** [comment]
how can I create a pre-eip 55 keystore?

**Comment by adambabik** [comment]
@perissology the only difference is an address format. Pre EIP55 addresses have all characters lower case.
