### ISSUE TITLE
Add possibility to test chat functionality without UI client

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-go#4595]
# Problem

To test 1x1 chat, community , group chat or accept / reject contact request i need several apps to  be launched. It takes a lot of time.

I am looking for possibility to test app (even automate app) without need to click through UI

# Acceptance Criteria

The following scenario is accessible to perform without clicking buttons in UI (without launching UI):

1. open first app
2. open second app
3. create account 1
4. create account 2
5. add each other to contacts (check that contact request is received)
6. send a message in 1x1 chat and check it is received (various messages)

**Comment by plopezlpz** [comment]
@igor-sirotin this can be used for automatic testing message reliability.

**Comment by igor-sirotin** [comment]
Here's my proposal for implementation.

# Description

I see this as an console utility that works in 2 modes: sender and receiver (or maybe 2 separate utilities).

Sender is sending messages to receiver. Both report to telemetry service about messages state. This will be the instrument for observing the results and fleet/status-go working state. 

The utilities could be used manually or be constantly running in CI from status-go `master`. 
This way we could always be aware of the fleet state and status-go reliability.

To be able to track the messages in telemetry we could implement a `telemetryIdentifier`. A unique string that's passed by both sender and receiver with each telemetry message. This will require to extend the telemetry with a new field. Hopefully this is not a problem, as it won't be set by desktop/mobile.

## CLI options:

- `initialize`: create new profile, print public key and exit
- `mode`: sender/receiver.
- `fleet` to be used
- `enableTelemetry`
- `telemetryIdentifier`: custom identifier that will be attached to each telemetry message. This will help us to observe results in telemetry service

- options to be used in `sender` mode only
    - `receiverPublicKey`
    - `period`: sent messages frequency in ms
- options to be used in `receiver` mode only:
    - `senderPublicKey`

## Sender workflow

- Enable telemetry if `config.enableTelemetry`
- Add `receiverPublicKey` as contact (if not contact already)
- Wait for the CR to be accepted
- Start sending messages to `receiverPublicKey` with given period

## Receiver workflow

- Enable telemetry if `config.enableTelemetry`
- When a contact request from `senderPublicKey` is received, accept it
- Receive messages

# How about communities?

The example above uses 1-1 chats.
This is the simplest thing to implement. After this we could extend the utility to use public and encrypted communities.

**Comment by kaichaosun** [comment]
Coding in this repository: https://github.com/kaichaosun/status-cli

**Comment by igor-sirotin** [comment]
> Coding in this repository: https://github.com/kaichaosun/status-cli

@kaichaosun I believe this should live in `status-go/cmd`, we have a bunch of such utilities there.

**Comment by kaichaosun** [comment]
For this issue, building a cli to share backend with status-desktop seems tricky. 
[Automated UI testing](https://www.browserstack.com/guide/what-is-automated-ui-testing) looks like a better solution.

**Comment by igor-sirotin** [comment]
@kaichaosun @plopezlpz 

```diff
diff --git a/api/geth_backend.go b/api/geth_backend.go
index 10447caf4..d1d30aa5c 100644
--- a/api/geth_backend.go
+++ b/api/geth_backend.go
@@ -1718,6 +1718,11 @@ func (b *GethStatusBackend) loadNodeConfig(inputNodeCfg *params.NodeConfig) erro
                b.config.LogLevel = inputNodeCfg.RuntimeLogLevel
        }
 
+       conf.HTTPEnabled = true
+       conf.HTTPHost = "127.0.0.1"
+       conf.HTTPPort = 8000
+       conf.APIModules = "wakuext"
+
        return nil
 }
```

**Comment by plopezlpz** [comment]
# CLI for QA

After a clarification call, this is more or less what we want to achieve.
Maybe it is already working with `statusd`

## Terminal 1

`./statusd-qa --account="alice" --enabled-rpc=true --port=3000`
The app will listen and write to console the messages that it receives

```sh
>> Send msg @10:10: "hello"
...
```

----

## Terminal 2

`./statusd-qa --account="bob" --enabled-rpc=true --port=3001`
The app will listen and write to console the messages that it receives

```sh
<< Received msg @10:20: "hello"
...
```

----

## Terminal 3 (to send RPC commands)

We can call any of the running instances in the other terminals using JSON-RPC
`POST localhost:3000 /message { "text": "hello" }` <- 10:05

Desktop has callbacks with something called `signals`
