### ISSUE TITLE
add build flags for message reliability logging 

### ISSUE THREAD

**Issue by siddarthkay** [status-im/status-go#4624]
# Problem

This PR introduced https://github.com/status-im/status-go/pull/4494 logging of message information in debug mode.
However as pointed out it can be harmful should this code slip into release.

# Implementation

Introduce new build flags and only perform the logging if the build flag is found.
Use this build flag in status-mobile repo and test it with PRs to see if message logging only works in PRs and not in nightlies.

**Comment by igor-sirotin** [comment]
The logs were removed here:
- https://github.com/status-im/status-go/pull/5608

Please let me know if they're still relevant. We can bring them back, but only with special build flags.

The info we're talking about is **message text**.

cc @churik @anastasiyaig
