### ISSUE TITLE
Separate rpc client api from state

### ISSUE THREAD

**Issue by nexthack** [status-im/status-go#465]
Currently the rpc [client](https://github.com/status-im/status-go/blob/086747a69599129e15cb7567193c454a20a7448a/geth/rpc/client.go#L22) is a struct.
If we can have an interface(Client) with all the apis of the client and a  client struct implement this interface,it will help in abstracting out the actions that can be performed on the cleint.

Please let me know your points on this.

**Comment by divan** [comment]
@crackerplace what problem should it solve?

**Comment by nexthack** [comment]
@divan 

If we have an interface for the rpc client with an impl struct,it helps in better readability of the methods supported by the client and also we can abstract any unintended exposure of state.

**Comment by divan** [comment]
`rpc.Client` has exactly 3 exported methods and they're very readable. I don't see any need to improve readability here.

An interface should be created by consumer — the code that needs that interface. SImply abstracting type with methods into own interface is a common misuse of interfaces in Go.

**Comment by nexthack** [comment]
Sure.Yes,the preemptive interface anti-pattern is kind of a carry on from oop languages.

In this case,as 4 methods are exported for Client across 2 files,this change is not immediate need unless package kind of has many files with exported methods in many of them.
