### ISSUE TITLE
bug: Filter subscribe and unsubscribe seem to happen out of order

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-go#4659]
# Problem

Filter unsubscribe and subscribe happened out of order causing status-mobile to think it is subscribed to filter where as Fleet node thinks subscription is unsubscribed.
Reference discussion [here](https://github.com/status-im/status-go/issues/4459#issuecomment-1916144642)

# Acceptance Criteria

Where-ever there is Filter unsubscribe and subscribe, these should happen in sequence.

**Comment by vitvly** [comment]
Coding a PR for this - this will ensure that filter requests for each particular filter are not out-of-order.

**Comment by chaitanyaprem** [comment]
> Coding a PR for this - this will ensure that filter requests for each particular filter are not out-of-order.

Thanks!
Just wanted to track this separately as the original issue was becoming hard to track conversations.

**Comment by vitvly** [comment]
One possible case for the scenario described [here](https://github.com/status-im/status-go/issues/4459#issuecomment-1916144642) is that when a peer ping failed, unsubscribes and subscribes were scheduled, but for some reason subscribe succeeded to the same peer that previously failed (e.g. intermittent network failure).
