### ISSUE TITLE
bug: peers are descored due to message validation failure

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-go#4660]
# Problem

It has been noticed a couple of times by @mprakhov and @anastasiyaig that relay is not receiving some of all messages. 
On analysis it has been observed that peer scores for all peers have been dropped too low causing some of them to move to graylist and ignornig IWANT/IHAVE messages from others. 

Root Cause seems to be message validation failure which occurs due to unable to decrypt messages received on particular shard/pubsubTopic. 

Ref discussion and analysis https://github.com/status-im/status-go/issues/4459#issuecomment-1918433759

Per @richard-ramos 

```
I believe this problem might be happening due to https://github.com/status-im/status-desktop/issues/13267 . I suspect that a shard assignment removal or change happened before, but the private key used originally for the community was not removed, so the topic validation in relay would still be applying a wrong key, and end up penalizing peers by mistake.

if the problem is due to that, then likely it is fixed in https://github.com/status-im/status-go/pull/4627 (this is already in desktop master)
```

@anastasiyaig Do update once you test the nightly build in your windows machine where you saw this issue recently and update.

**Comment by chaitanyaprem** [comment]
Workaround is to use different shard for each community that is being created . 
In order to avoid conflict amongst users, maybe a common page to be maintained where users indicate which shard is being used for each community in order to avoid such issues.

We must not reuse same shard for 2 communities as this will lead to validation failure. More information mentioned in https://github.com/waku-org/go-waku/issues/1022

**Comment by chair28980** [comment]
Related to https://github.com/status-im/status-desktop/issues/1

**Comment by chaitanyaprem** [comment]
> Related to [status-im/status-desktop#1](https://github.com/status-im/status-desktop/issues/1)

Looks like wrong reference @chair28980 .

**Comment by chair28980** [comment]
Closing per discussion with Status QA, issue not observed in latest release.
