### ISSUE TITLE
Add shh_requestMessages to whisper rpc api

### ISSUE THREAD

**Issue by b00ris** [status-im/status-go#470]
# Problem

There is no way to request historic messages via Whisper RPC API. Our idea is to extend Whisper RPC with `shh_requestMessages` method which can be implemented purely on status-go side.

# Implementation

There are two ways to implement this. 

## Pure status-go implementation

Similarly to [`eth_accounts` and `eth_sendTransaction`](https://github.com/status-im/status-go/blob/21beb685b4d99c19e0999373c2037e7e5ea42b42/geth/api/backend.go#L246-L247), it can be done purely on status-go side.

## go-ethereum implementation

It narrows down to adding a new method in [`whisper/whisperv5/api.go`](https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv5/api.go).

# Acceptance Criteria

1. `wnode-status` should accept `shh_requestMessages` JSON-RPC method with parameters like `start` and `end` (possibly others that MailBox understands). 
2. `wnode-status` after receiving `shh_requestMessages` should send archived messages to the requester.

# Notes

Some example usage: 
https://github.com/status-im/status-go/blob/e53f808edcd673f2ffa5683cbb26eb9e5e630503/cmd/wnode-status/whisper_messages_test.go

Related to `idea#1` https://github.com/status-im/ideas/issues/1

**Comment by oskarth** [comment]
Additionally, this  `shh_requestMessages` should be mirrored in our version of web3.js so we can call it via HTTP-RPC. I tried to create an issue here by don't seem to have permissions: https://github.com/status-im/web3.js

@carlbennetts Can you check what's up with permissions in this repo? https://github.com/status-im/web3.js I can't see the Issues tab there. For other forked repos like  go-ethereum I see it.
UPDATE: This has been fixed.

**Comment by oskarth** [comment]
Is there something blocking this @b00ris?

**Comment by oskarth** [comment]
@b00ris Is there something blocking this?

Also, what's the proposed signature for this? In diagram it says:

`shh_requestMessages(peerID: string = mailboxPeerID, envelope: envelope)`

But in thread on Friday you said " We use this symkey only to requestMessages call(to mailbox)." and I don't see a symkey in the above signature.

Am I missing something?

Additionally, what is the return value? Success/fail essentially or more granular information?

**Comment by adambabik** [comment]
The request for messages to MailServer will look like this:
1. A symmetric key from password must be created and added to Whisper using: `shh_generateSymKeyFromPassword`. The same password that is used to start a wnode must be used. This command returns a symmetric key ID,
2. Node needs to call `shh_requestMessages` but I believe that its signature will be different. Something like this: `shh_requestMessages(mailserverPeerID: string, symKeyID: string, start: number, end: number)`. `mailserverPeerID` is an ID returned by `AddPeer` binding that needs to be exposed. `symKeyID` is an ID returned in (1). `start` and `end` are timestamps in seconds.

**Comment by b00ris** [comment]
@oskarth Symkey is included into envelop.
shh_requestMessages params:
"enode" string - maiserver enode,
"topic"  string 
"symKeyID" string - mailserver key id
"from" uint - messages from time in unix timestamp
"to" uint - messages in time in unix timestamp

**Comment by oskarth** [comment]
Already resolved :) https://github.com/status-im/status-react/pull/2624/files
