### ISSUE TITLE
Clean up and refactor wnode-status config to run MailServer

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#471]
# Problem

For offline inboxing, we need a way to run a node with MailServer from the command line so people can get their historic messages.

# Implementation

We have a `wnode-status` which purpose is not known for 100%. It may be possible to refactor this command and add a MailServer support.

`wnode-status` was already used to test Push Notifications. More details in `whisper.js` file.

# Acceptance Criteria

1. A command to run `wnode-status` with MailServer.
2. (Optional) It would be great if we could write a scenario in JavaScript.
2.1. It would start a `wnode-status` first,
2.2. Next, it would start node A and send some messages to offline node B. 
2.3. Next, node B would start, message filter would be created and request for messages sent.
2.4. After verifying that messages got received, all nodes would be shutdown. 

# Notes

See https://github.com/status-im/status-go/tree/debug/mailbox_experiments for @b00ris and @JekaMas's progress so far.

https://github.com/status-im/ideas/issues/1 for swarm idea.

https://github.com/status-im/ideas/pull/36 for MVP scope.

# Future Steps

Start one `wnode-status` in our cluster with a known address and password.

**Comment by oskarth** [comment]
cc @b00ris @JekaMas @adambabik

**Comment by JekaMas** [comment]
@oskarth Do we need this issue? "A command to run wnode-status with MailServer." - we already have it.

**Comment by oskarth** [comment]
@adambabik 

Re
> (Optional) It would be great if we could write a scenario in JavaScript. [...]

We can do this on Clojurescript side too https://github.com/status-im/status-react/blob/develop/test/cljs/status_im/test/protocol/core.cljs

**Comment by adambabik** [comment]
@oskarth already did some initial work https://github.com/status-im/status-go/pull/477/files#diff-391ebc7dfc465e8e176ddd5f78eb59e1. I don't know Clojurescript :( and JS may be more approachable. Also, I think it should stay on status-go side because it's easier to test new features or changes to MailServer rather than switching between repos.

**Comment by oskarth** [comment]
Sounds good. I meant that I can do it over there :) But there's value in having sanity check in this repo too.

**Comment by adambabik** [comment]
It's done in #477.
