### ISSUE TITLE
Flaky tests TestMessengerCommunitiesTokenPermissionsSuite

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#4750]
TestMessengerCommunitiesTokenPermissionsSuite – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestCommunityTokensMetadata – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestCreateTokenPermission – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestEditSharedAddresses – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestEditTokenPermission – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestJoinCommunityAsAdminWithMemberAndAdminPermission – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestJoinCommunityAsMemberWithMemberAndAdminPermission – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestJoinCommunityWithAdminPermission – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestJoinedCommunityMembersMultipleSelectedSharedAddresses – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestJoinedCommunityMembersSelectedSharedAddress – github.com/status-im/status-go/protocol
TestMessengerCommunitiesTokenPermissionsSuite/TestJoinedCommunityMembersSharedAddress – github.com/status-im/status-go/protocol
```
2024-02-17T14:25:36.324Z	DEBUG	alice	protocol/messenger.go:1937	running shutdown task	{"n": 6}
panic: send on closed channel
goroutine 916279 [running]:
github.com/status-im/status-go/wakuv2.(*Waku).Start.func1()
	/home/jenkins/workspace/status-go_prs_tests_PR-4741/wakuv2/waku.go:1247 +0x7b5
created by github.com/status-im/status-go/wakuv2.(*Waku).Start
	/home/jenkins/workspace/status-go_prs_tests_PR-4741/wakuv2/waku.go:1231 +0x56b
```

**Comment by igor-sirotin** [comment]
### `TestEditSharedAddresses`

```go
    communities_messenger_token_permissions_test.go:604: 
                Error Trace:    /Users/igorsirotin/Repositories/Status/status-go/protocol/communities_messenger_token_permissions_test.go:604
                Error:          Not equal: 
                                expected: "0x0210000000000000000000000000000000000000"
                                actual  : "0x0200000000000000000000000000000000000000"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -0x0210000000000000000000000000000000000000
                                +0x0200000000000000000000000000000000000000
                Test:           TestMessengerCommunitiesTokenPermissionsSuite/TestEditSharedAddresses
```
