### ISSUE TITLE
Flaky tests using `NewTestWakuV2`

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#4764]
Sometimes tests fail with
```
    waku_builder_test.go:85: 
                Error Trace:    /Users/igorsirotin/Repositories/Status/status-go/protocol/waku_builder_test.go:85
                                                        /Users/igorsirotin/Repositories/Status/status-go/protocol/communities_messenger_token_permissions_test.go:144
                                                        /Users/igorsirotin/Repositories/Status/status-go/vendor/github.com/stretchr/testify/suite/suite.go:187
                Error:          Received unexpected error:
                                failed to dial: failed to dial 16Uiu2HAm5AmQSRSrdrN7oMygWpsMN13w9tKrDZqMvJs4zwxGxRzA:
                                  * [/ip4/77.44.69.184/tcp/56875] dial tcp4 77.44.69.184:56875: connect: connection refused
                Test:           TestMessengerCommunitiesTokenPermissionsSuite/TestJoinCommunityAsMemberWithMemberAndAdminPermission
```

**Comment by igor-sirotin** [comment]
Full log:
[scratch_40.log](https://github.com/status-im/status-go/files/14337527/scratch_40.log)

**Comment by igor-sirotin** [comment]
@jrainville I'm not sure if this particular one is actually urgent. I've only faced this locally so far. 

Maybe we could wait for nightly test runs to finish and see if this one appears there. Could even be just a local network glitch or smth.

**Comment by jrainville** [comment]
@igor-sirotin ok no problem. I didn't know which flaky test issue to assign to you. If you feel like another one would be more priority we can switch it. Otherwise, we can just wait like you said

**Comment by igor-sirotin** [comment]
This doesn't appear in nightly tests. Closing for now, but we can reopen this if needed.
