### ISSUE TITLE
Flaky test: TestRequestProfileInfo

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#4845]
[TestMessengerStoreNodeRequestSuite/TestRequestProfileInfo: 10.0% (2 of 20 failed)](https://ci.status.im/job/status-go/job/tests-nightly/142/Reports/)

```
/home/jenkins/workspace/status-go/tests-nightly/protocol/messenger_storenode_request_test.go:586
        	Error:      	Expected value not to be nil.
        	Test:       	TestMessengerStoreNodeRequestSuite/TestRequestProfileInfo
    --- FAIL: TestMessengerStoreNodeRequestSuite/TestRequestProfileInfo (2.35s)
```

https://ci.status.im/job/status-go/job/tests-nightly/142/testReport/github/com_status-im_status-go_protocol/TestMessengerStoreNodeRequestSuite_TestRequestProfileInfo/

**Comment by igor-sirotin** [comment]
I wasn't yet able to reproduce this. But from the logs I can see that the store node wasn't available.
I improved this part of the code here: https://github.com/status-im/status-go/pull/4860

let's see if it helps.

**Comment by igor-sirotin** [comment]
Still reproducible: https://ci.status.im/job/status-go/job/tests-nightly/146/testReport/github/com_status-im_status-go_protocol/TestMessengerStoreNodeRequestSuite_TestRequestProfileInfo/
