### ISSUE TITLE
feat: implement rate-limit config for Waku server side of light protocols

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-go#4857]
# Problem

As status-go and status-desktop(in relay mode) also acts as a server/service-node for various Waku light-protocols, it is important to have a rate-limit defined so that status-desktop node doesn't get overloaded with requests from Lightclients (i.e status desktop/mobile running in lightMode).
Following are the protocols for which rate-limits are required:
1. Lightpush 
2. PeerExchange

Note: Filter doesn;t need specific rate-limit as number of Filter-subscriptions a node can handle is already configurable which acts as a sort of rate-limit.

# Implementation

Define default rate-limit configs for LightPush and PeerExchange and implement rate-limiters for them.
These rate-limiters can be passed onto Waku protocol initialization with `WithRateLimiter` option.

# Acceptance Criteria

Tests have pass that would validate rate-limiter usage for the protocols.

# Notes

The functionality of specifying a rate-limiter for such light-protocols has been added in go-waku already in https://github.com/waku-org/go-waku/pull/1043 and https://github.com/waku-org/go-waku/pull/1024. 

# Future Steps

None

**Comment by chaitanyaprem** [comment]
@vpavlin , noticed while reviewing issues that i had created this to track rate-limiting for light-protocols in status-go. 
I remember you are working on this, and hence assigned this to you.
Not sure if this is part of next release, but since light protocol usage is planned for next release, maybe better to have rate limits to be applied on status-desktop which will act as Lightpush and filter service nodes to control spam and over-usage of bandwidth.

**Comment by vpavlin** [comment]
Both Lightpush and PeerExchange rate limits were added with "default" values of 1msg/s (lightpush) and 1request/s (PX) to status-go.

@chair28980 not sure if this is enough for closing this?
