### ISSUE TITLE
Add standalone mode to wnode-status

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#486]
# Problem

We need a standalone mode in `wnode-status` so that it does not actively discover and connect with other peers.

This will be useful for writing tests. (any other use cases?)

# Implementation

Add `-standalone` flag to `wnode-status` command.

# Acceptance Criteria

AC:
* standalone mode does not actively connect with any peers, except for explicitly added ones with `AddPeer`.

**Comment by JekaMas** [comment]
@adambabik Could it better to add 'bootstrap' mode, whisper hasn't 'standalone' mode?

**Comment by adambabik** [comment]
@JekaMas this terminology is a bit confusing. In go-ethereum, it's called "bootstrap mode" but the flag is named `standalone`. Is "bootstrap mode" defined anywhere? How do you define it?
