### ISSUE TITLE
Offline Inboxing: expose AddPeer bindings

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#487]
# Problem

For offline inboxing, we need to be able to add MailServer as a peer so we can request historic messages.

# Implementation

Add `AddPeer(enode string) string` as part of the exposed bingins that status-react can consume. See https://github.com/status-im/status-go/blob/086747a69599129e15cb7567193c454a20a7448a/geth/node/manager.go#L263-L274

# Acceptance Criteria

1. `AddPeer` C binding in `lib/library.go`.

# Notes

It appears `addPeer` is a private API, which means it is available only via IPC, not JSON-RPC. We can thus not call it via HTTP-RPC web3.js like we can with, say, `shh_markTrustedPeer`.

(From https://github.com/ethereum/wiki/wiki/JSON-RPC and https://github.com/ethereum/go-ethereum/wiki/Whisper-v5-RPC-API and grepping web3/status-go/go-ethereum).

There is a JS command `admin.addPeer` but this isn't from web3.js as I understand it, but some JS console that attaches to a geth node. Please correct me if I'm wrong in this.

> You can also add static nodes at runtime via the js console using admin.addPeer(): (https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network)

# Future Steps

TBD.

**Comment by oskarth** [comment]
@adambabik @b00ris @JekaMas Please let me know if you disagree with this description and proposed solution above or if I missed something important.

Also see https://github.com/status-im/status-react/issues/2570#issuecomment-348690731

**Comment by adambabik** [comment]
@oskarth it looks good. I edited it a bit.
