### ISSUE TITLE
Login impossible with NO SUCH COLUMN: PEER_SYNCYNC_ENABLED

### ISSUE THREAD

**Issue by jrainville** [status-im/status-go#4876]
# Problem

![image](https://github.com/status-im/status-go/assets/11926403/9ff6bf9a-6322-423f-93d5-253086dfdbec)

# Implementation

On desktop, trying to use latest develop doesn't let us login with the error `NO SUCH COLUMN: PEER_SYNCYNC_ENABLED`

I tried an earlier commit (`bdb2b261a63c223083ec5433f2f85d6420ad9b52`) and it works fine.

I think the faulty commit is `26bc564b38948753b87bb63c6f87d7c723935cc3`. 

# Acceptance Criteria

Login is possible

**Comment by jrainville** [comment]
@alwx would you mind checking it out. I think it's your commit that caused the issue.

**Comment by cammellos** [comment]
This should be fixed now, @alwx can you confirm and we can close the issue?

**Comment by alwx** [comment]
Confirmed & closed.
