### ISSUE TITLE
Offline inboxing: hardcode MailServer password

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#488]
# Problem

MailServer requires a password for DDoS prevention. For MVP we want to hardcode this.

# Implementation

Hardcode MailServer password to `status-offline-inbox`. This way symmetric key creation is deterministic and consumers like status-react can proceed with this assumption when requesting messages https://github.com/status-im/status-go/issues/470#issuecomment-348693204.

# Acceptance Criteria

MailServer password and associated symkey is set to `status-offline-inbox`.

# Notes

N/A

# Future Steps

TBD.

**Comment by adambabik** [comment]
I am not sure we actually need to hardcoded in the code. Let's just use `status-offline-inbox` as a password everywhere. A wnode will be started like `wnode-status -password=status-offline-inbox ...` and on the status-react side, this password will be used to get a symmetric key ID which will be sent in `shh_requestMessages`.
