### ISSUE TITLE
Permissions cannot be upgraded from -> view only to post (or viceversa) for existing users

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#4905]
```
			if response.ViewOnlyPermissions.Satisfied || response.ViewAndPostPermissions.Satisfied {
				channelRole := protobuf.CommunityMember_CHANNEL_ROLE_VIEWER
				if response.ViewAndPostPermissions.Satisfied {
					channelRole = protobuf.CommunityMember_CHANNEL_ROLE_POSTER
				}
				if !isMemberAlreadyInChannel {
					_, err := community.AddMemberToChat(channelID, memberPubKey, []protobuf.CommunityMember_Roles{}, channelRole)
					if err != nil {
						return nil, err
					}
				}
			}

```

I was investigating some issues, but I think the code above might have a bug, I haven't replicated yet, and I will try, but in the meantime I'll open an issue not to forget (i can probably fix it as well, though I am on another issue)

If you see the code above, if a user is already a member of a channel, and goes from -> `VIEWER` to -> `POSTER`, it will never be updated, since we only check `isMemberAlreadyInChannel`, we should check that the role has changed as well.

**Comment by cammellos** [comment]
cc @jrainville @endulab 
In case you can confirm is a bug indeed and I am not missing anything

**Comment by jrainville** [comment]
Ah it is a bug! I fixed it in my latest PR https://github.com/status-im/status-go/pull/4900

I found it last Thursday. I didn't open an issue for it because I was already fixing issues
