### ISSUE TITLE
Refactoring of pprof usage

### ISSUE THREAD

**Issue by themue** [status-im/status-go#491]
# Problem

So far the `pprof` package is imported and integrated to write into files by library commands. This now shall be changed to be started in `statusd` on demand and exporting the HTTP interface on a configurable port. This way tests interactively can be monitored.

# Implementation

- Remove `helpers/profiling`
- According cleanup of `lib/library.go`
- Extend `statusd.go` with arguments for starting and configuring `pprof`

# Acceptance Criteria

`statusd` started with according arguments can be connected via browser or `go tool pprof`.

# Notes

None.

# Future Steps

Extend the combination of CLI and `statusd` debug based on lessons learned and needs during performance analysation and optimisation.

**Comment by phcurtis** [comment]
do you need some help on this ?

**Comment by themue** [comment]
Thanks for offer, it's only on hold. Branch is almost done.

**Comment by themue** [comment]
Branch is https://github.com/status-im/status-go/tree/refactoring/pprof-usage-491

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by themue** [comment]
See also https://rakyll.org/pprof-ui/.

<blockquote><img src="/favicon.png" width="48" align="right"><div><strong><a href="https://rakyll.org/pprof-ui/">pprof user interface · Go, the unwritten parts</a></strong></div></blockquote>
