### ISSUE TITLE
Upgrade community ERC721 contracts

### ISSUE THREAD

**Issue by endulab** [status-im/status-go#4947]
Community contracts has been upgraded recently.
Changes can be found [here](https://github.com/status-im/communities-contracts/blob/main/CHANGELOG.md#100-2024-02-28)

ToDo:
- generate Go API for new contracts and use them in community tokens service
- if the API is the same investigate if we can use new contract API for older tokens
- add contracts versioning in database
- update deployer contracts' addresses and generate a new Go API for them

**Comment by jrainville** [comment]
Moved back to 2.30 so that we can have the latest contract for new communities to support the new functionality
