### ISSUE TITLE
StatusAPI.NotifyUsers is exposing its implementation details through its parameters  

### ISSUE THREAD

**Issue by jonprice** [status-im/status-go#499]
# Problem

The StatusAPI has a function `func (api *StatusAPI) NotifyUsers(message string, payload fcm.NotificationPayload, tokens ...string) error {
` with fcm been the Firebase Cloud Messaging client package. 

Reviewing the code in the notification and geth/common package it looks like there is an intent that notification is a pluggable service. Additionally, there is an unused notification/Payload struct. 

# Implementation

# Acceptance Criteria

# Notes

It looks like NotifyUsers is not used be status-react yet status-im/status-react#2287

# Future Steps

**Comment by pedropombeiro** [comment]
@jonprice Is this something we want to solve now, or leave for later until this GHI is fleshed out? Is it enough to start accepting the `notification/Payload` type in `NotifyUsers` and convert that to an fcm notification struct before passing it off to the `NotificationConstructor`?

**Comment by jonprice** [comment]
It was just something that I noticed while refactoring while working on #440 so created the ticket

**Comment by dshulyak** [comment]
Looks like there is no plan to refactor it, cause the implementation behind PN's will be chnged
