### ISSUE TITLE
Cleanup `hash_ratchet_encrypted_messages` periodically

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#5036]
# Problem

The `hash_ratchet_encrypted_messages` table is utilized for storing messages that are unable to be decrypted. Currently, there is no mechanism in place for cleaning up this storage, particularly when the necessary encryption keys are not obtained. This lack of cleanup becomes problematic for clients who participate in communities but lack access to certain private channels, leading to uncontrolled and potentially infinite growth of the table. This growth adversely impacts performance, as the table is queried each time a hash ratchet is received, whether from store nodes or relays.

![Screenshot from 2024-04-10 08-38-00](https://github.com/status-im/status-go/assets/33099791/f5639fdd-95b7-4ad4-bf7a-aedce8bbc1fa)

`SELECT count(*) FROM hash_ratchet_encrypted_messages` -> 653
`SELECT timestamp FROM hash_ratchet_encrypted_messages ORDER BY timestamp ASC LIMIT 1` -> 1709136641 (Feb 28 2024)

# Implementation

Clean up the `hash_ratchet_encrypted_messages` periodically. The condition would be: If a message remains unencrypted for 14 days, remove it.

# Acceptance Criteria

- [ ] remove unencrypted messages received more than 14 days ago from `hash_ratchet_encrypted_messages`

# Notes

- [x] add index to `hash_ratchet_encrypted_messages.key_id` for immediate improvement

# Future Steps

As a future improvement, we should not subscribe to chats (channels) we do not have permission for. This way, we would not be saving messages from private channels at all.

**Comment by jrainville** [comment]
> As a future improvement, we should not subscribe to chats (channels) we do not have permission for. This way, we would not be saving messages from private channels at all.

@osmaczko have you opened an issue for this?

**Comment by osmaczko** [comment]
> > As a future improvement, we should not subscribe to chats (channels) we do not have permission for. This way, we would not be saving messages from private channels at all.
> 
> @osmaczko have you opened an issue for this?

Not yet. Since we introduced indexing and have cleanup on the horizon, I am unsure if it's worth it. Many things can go wrong; there might be paths where subscription is skipped, and we'll end up with hard-to-investigate bugs.
