### ISSUE TITLE
Fix ENS tests not to connect to the real services that were failing on release/0.177.x

### ISSUE THREAD

**Issue by stefandunca** [status-im/status-go#5085]
The tests `services/ens/api_test.go` should be converted to use mocks

Disabled here: https://github.com/status-im/status-go/pull/5081

**Comment by iurimatias** [comment]
@stefandunca was this done?

**Comment by stefandunca** [comment]
> @stefandunca was this done?

No, the tests are still skipped.

**Comment by igor-sirotin** [comment]
Duplicate of https://github.com/status-im/status-go/issues/5087
