### ISSUE TITLE
Group messaging workflow investigation 

### ISSUE THREAD

**Issue by b00ris** [status-im/status-go#514]
# Problem
There are no working workflow for group messaging.
Request historic messages request for group messaging don't covered by tests. 

# Acceptance Criteria
1. Sequense diagramm which describes communication flow between Alice, Bob, Charlie and mailbox node
2. Test which test this workflow

**Comment by b00ris** [comment]
![group_chatting_mailbox](https://user-images.githubusercontent.com/4943570/34040873-c455e200-e1a6-11e7-92a4-63a64a3312ba.png)

**Comment by adambabik** [comment]
@b00ris I believe this is done, right?

**Comment by oskarth** [comment]
@b00ris @adambabik decoupling this from offline inboxing iteration as we are closing down the swarm, please decide what you want to do with this issue.

**Comment by b00ris** [comment]
Merged
