### ISSUE TITLE
 Direct Message Testing : status reliability testing in unreliable network conditions

### ISSUE THREAD

**Issue by plopezlpz** [status-im/status-go#5144]
# Problem

We want to test **direct messages** used for critical chat features: contact request, community join request and response, 1:1 chat and private group. Using the CLI provided [here](https://github.com/status-im/status-go/issues/5143)

# Acceptance Criteria

Using the CLI from [here](https://github.com/status-im/status-go/issues/5143)

1. Have a plan for regression testing under **unreliable network conditions** (e.g.: disconnects, high latency and low bandwidth connections) of the following status-go features:
   - [x] 1:1 chat
   - [x] contact request/response
   - [x] community join request/response
   - [x] private group
2. ✅ Setup plan to running these tests periodically (could be before release or daily or on merging to master keeping in mind that these tests might be slow to run)

**Comment by fbarbu15** [comment]
Added some initial tests in this [PR](https://github.com/status-im/status-cli-tests/pull/1) for 1:1 chat and while I can see that the message reliability decreases with bad network conditions, [see report](https://status-im.github.io/status-cli-tests/49/#suites/bd240acfdb98595cfcc209dacdee0d38/ca1d26fb68dbca06/), messages are lost also when network is good (see `test_baseline` where 11 messages out of 100 were not received).

**Comment by fbarbu15** [comment]
@plopezlpz  I have a question about `contact request/response` testing. 
I saw that this is a one time thing. Once a contact request was accepted (and I can see AcceptContactRequest in the receiving node), subsequent contact requests no longer generate an AcceptContactRequest so I have no idea if they were successful or not in the tests.

So not sure if it makes sense to start 2 nodes and send 100 contact requests to test reliability.

An idea is for the test to just start 2 nodes and send only one contact request and monitor if it was accepted. Then stop the nodes. And repeat this 100 times.

WDYT? lmk if you have other ideas

**Comment by plopezlpz** [comment]
nighlty tests here: https://github.com/status-im/status-cli-tests

**Comment by plopezlpz** [comment]
List of PRs:
- [ ] https://github.com/status-im/status-cli-tests/pull/2
- [ ] https://github.com/status-im/status-cli-tests/pull/1
- [ ] https://github.com/status-im/status-cli-tests/pull/3
- [ ] https://github.com/status-im/status-cli-tests/pull/4
- [ ] https://github.com/status-im/status-cli-tests/pull/5
