### ISSUE TITLE
Collect basic Whisper statistics

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#517]
# Problem

Whisper does collect some basic statistics but it's not exposed. We should try to collect them and expose somehow through status-go.

# Implementation

The goal is to expose [basic Whisper statistics](https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv5/whisper.go#L40-L46) and present them as a chart. It should be possible to do so with Status running on a physical device as well.

# Acceptance Criteria

1. Expose basic Whisper statistics,
1. It should be possible to see a graph that updates over time.

# Notes

Prometheus seems like a nice tool. It can be integrated with Go code easily.

1. https://prometheus.io
1. https://github.com/prometheus/client_golang

**Comment by JekaMas** [comment]
It is exposed in method 'Stats() Statistics' - https://github.com/ethereum/go-ethereum/blob/master/whisper/whisperv5/whisper.go#L73-L736

**Comment by pedropombeiro** [comment]
Any reason why https://github.com/status-im/status-go/issues/421 wouldn't work for this?

**Comment by adambabik** [comment]
@PombeirP #421 is more about how to expose metrics, which library use. This issue is about exposing specific metrics -- Whisper messages stats.

#421 should be probably finished before this issue.

**Comment by pedropombeiro** [comment]
@adambabik yeah, I was just wondering why the infrastructure built in #421 wouldn't work for exposing these metrics as well. After all, you can select which metrics to see by passing arguments to `expvarmon`.

**Comment by adambabik** [comment]
@PombeirP As far as I remember, I haven't said anywhere that #421 implementation won't work for these metrics. However, as long as `expvar` is a standardize and preferred way of exposing metrics, I'd like to have them in another system in order to analyze and visualize. Prometheus and Grafana look like a good candidate. Both systems can work at the same time actually. To expose `expvar` to Prometheus [this collector](https://github.com/prometheus/client_golang/blob/master/prometheus/expvar_collector.go) can be used. We can include it conditionally using build tags for example.
