### ISSUE TITLE
Cannot login on Windows

### ISSUE THREAD

**Issue by Seitseman** [status-im/status-go#5186]
# Problem

During login of existing account, or creation o new account or syncing between two apps, Windows desktop client will error out and not login 

![image](https://github.com/status-im/status-go/assets/5157464/93314d71-777a-4619-9c86-394470c6e732)

logs:

```
DEBUG[05-17|21:05:54.175|github.com/status-im/status-go/services/wallet/collectibles/commands.go:340]       end loadOwnedCollectiblesCommand         chain=10 account=0x4d910637189E01cbd5f3BF310f92Ed7993DC707f in=593.4971ms
DEBUG[05-17|21:05:54.185|github.com/status-im/status-go/node/get_status_node.go:510]                        status node stopped                      package=status-go/node.StatusNode
ERROR[05-17|21:05:54.185|github.com/status-im/status-go/mobile/status.go:319]                               loginAccount failed                      error="mkdir D:\\Projects\\status-desktop\\Status\\data\\D:: The filename, directory name, or volume label syntax is incorrect."
``` 

# Notes
It looks like 
vendor\status-go\api\geth_backend.go
```
conf.ShhextConfig.BackupDisabledDataDir = filepath.Join(b.rootDataDir, conf.ShhextConfig.BackupDisabledDataDir)
```
is causing this problem, because in 
vendor\status-go\services\ext\service.go
```
func (s *Service) InitProtocol(nodeName string, identity *ecdsa.PrivateKey, appDb, walletDb *sql.DB, httpServer *server.MediaServer, multiAccountDb *multiaccounts.Database, acc *multiaccounts.Account, accountManager *account.GethManager, rpcClient *rpc.Client, walletService *wallet.Service, communityTokensService *communitytokens.Service, wakuService *wakuv2.Waku, logger *zap.Logger) error {
....
	dataDir := filepath.Clean(s.config.ShhextConfig.BackupDisabledDataDir)

	if err := os.MkdirAll(dataDir, os.ModePerm); err != nil {
		return err
	}

...
```

there dataDir  will contain 'self-duplicated' path (in my case it is  D:\Projects\status-desktop\Status\data\ D:\Projects\status-desktop\Status\data\

Commenting out ```conf.ShhextConfig.BackupDisabledDataDir = filepath.Join(b.rootDataDir, conf.ShhextConfig.BackupDisabledDataDir)
``` locally will make the app to properly login and ```dataDir := filepath.Clean(s.config.ShhextConfig.BackupDisabledDataDir)``` contain proper path

**Comment by jrainville** [comment]
Nice investigation. There was a one member that had the same issue.

**Comment by jrainville** [comment]
@Seitseman does this issue happen only in 2.28.1 or also in master/develop?

I'm asking because Igor refactored the login flow and we don't use the same config to login now.

**Comment by jrainville** [comment]
@Cuteivist would you mind taking a look? You're the only one that develops on Windows, so it should be quite easy for you.

As far as I could see, we pass `./` as `BackupDisabledDataDir` in Nim to status-go when logging in, though that was before the refactor. I'm not fully sure if it still happens.

I assume that `./` is badly converted on Windows when doing the path join.

**Comment by marcioatdias** [comment]
> Nice investigation. There was a one member that had the same issue.

It was me, and I was trying it directly on master. I tried to compile on Windows, but it was not easy to find the root cause. I gave up and now I'm doing it on Linux. For sure with @Seitseman investigation the problem could have a solution soon and maybe I could compile on windows :D

**Comment by marcioatdias** [comment]
> @Cuteivist would you mind taking a look? You're the only one that develops on Windows, so it should be quite easy for you.
> 
> As far as I could see, we pass `./` as `BackupDisabledDataDir` in Nim to status-go when logging in, though that was before the refactor. I'm not fully sure if it still happens.
> 
> I assume that `./` is badly converted on Windows when doing the path join.

"BackupDisabledDataDir" is "./" by default but is overriden on "loadNodeConfig" func (node_config.go) after getting value from database

![image](https://github.com/status-im/status-go/assets/8908607/88541f66-d998-4ef7-ae35-87bdc0a6e593)

Probably first time DB is created that field on table is being set incorrectly

**Comment by Cuteivist** [comment]
Never encountered this issue, but maybe because I base everything on git bash which uses unix-like paths.

@jrainville  I'm traveling next 2 weeks so I won't be able to check it.

**Comment by marcioatdias** [comment]
I just want complement the great work already done by [Seitseman](https://github.com/Seitseman)

### Problem
Not able to login on Windows after a new user is created.

![image](https://github.com/status-im/status-go/assets/8908607/43ff12ee-fd17-410a-824b-dca9183ab62f)


### Why does this happen??

1. During the process of creating a new user at `accounts\service.nim` on `proc buildCreateAccountRequest`, `backupDisabledDataDir` variable is set through the constant `main_constants.STATUSGODIR` which is set as `STATUSGODIR* = joinPath(baseDir, "data") & sep` at `constants.nim` 

2. During the login process this value is used again, more specifically at `geth_backend.go ` on `loadNodeConfig` function 

`conf.ShhextConfig.BackupDisabledDataDir = filepath.Join(b.rootDataDir, conf.ShhextConfig.BackupDisabledDataDir)`

 where is oddly set because both parameters have the same value, creating a path similar to :

**Linux;**
`/home/user/status-desktop/Status/data/home/user/status-desktop/Status/data`


**Window**
`C:\workspace\status-desktop\Status\data\C:\workspace\status-desktop\Status\data`

**Why does it work on linux  but not on windows?**

Because in linux it's a valid path but in windows it's not because of the special character ":"

I hope this could help to solve the problem

**Comment by jrainville** [comment]
@Seitseman could you look into fixing this issue as it's a blocker for some users and you have a good repro state. cc @caybro if you're fine with him working on it even if it's not UI related.

**Comment by caybro** [comment]
> @Seitseman could you look into fixing this issue as it's a blocker for some users and you have a good repro state. cc @caybro if you're fine with him working on it even if it's not UI related.

Yeah pls go ahead @Seitseman , this is quite critical to fix. The path is wrong in any case, even in Linux

**Comment by caybro** [comment]
Encountered something similar here: https://github.com/status-im/status-desktop/issues/14889#issuecomment-2126813949

**Comment by Seitseman** [comment]
@jrainville , @Cuteivist,  @caybro sorry for such a long delay. I will switch to it immediately.
