### ISSUE TITLE
Check Validity of `fromLockedAmount` in `SuggestedRoutesV2`

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-go#5227]
### Description
We need to enhance the `SuggestedRoutesV2` function to check the validity of the `fromLockedAmount` at the time it is called. The current implementation does not verify if all entries in `fromLockedAmount` are not negative. Additionally, there is no validation to prevent duplicate network IDs within a given route.

### Details
The `fromLockedAmount` should be validated to ensure that all entries are positive. This check is crucial because if the user deliberately does not want to send any amount from a certain chain, there are two appropriate actions to handle this from the UI side:
1. **Disable the chain**: The chain should be added to the `DisabledFromChainIDs` array.
2. **Set a 0 value for the locked amount on that chain**: This indicates that no amount should be sent from that chain.

Moreover, routes should be validated to ensure there are no duplicate network IDs. This is important because each network should only appear once in a route to ensure proper routing logic.

### Proposed Solution
- [x] 1. Implement a check in the `SuggestedRoutesV2` function to ensure all values in the `fromLockedAmount` map are not negative.
    - Resolved by https://github.com/status-im/status-go/pull/5293
- [x] 2. If any value is found to be negative, return an error or handle it appropriately.
    - Resolved by https://github.com/status-im/status-go/pull/5293
- [x] 3. Add validation to ensure there are no duplicate network IDs within a given route. If duplicates are found, return an error or handle it appropriately.
- [x] 4. Add validation to prevent all supported networks from being excluded.

### Benefits
This change will:
- Improve the robustness of the route suggestion mechanism.
- Prevent invalid configurations from being processed.
- Align the backend logic with the intended UI behavior.
- Ensure unique network IDs within routes for proper routing.

### Notes
- Ensure that the new checks do not affect existing functionality adversely.
- Update any related tests to cover scenarios with invalid `fromLockedAmount` entries and duplicate network IDs.

### Suggestion
```go
func SuggestedRoutesV2(...) {
    // Check for non-negative entries in fromLockedAmount
    for _, amount := range fromLockedAmount {
        if amount.ToInt().Cmp(big.NewInt(0)) < 0 {
            // Handle invalid amount
            return nil, fmt.Errorf("invalid locked amount: must not be negative")
        }
    }
    
    // Check for duplicate network IDs in routes
    networkIDSet := make(map[uint64]struct{})
    for _, route := range routes {
        for _, path := range route {
            if _, exists := networkIDSet[path.From.ChainID]; exists {
                // Handle duplicate network ID
                return nil, fmt.Errorf("duplicate network ID found: %d", path.From.ChainID)
            }
            networkIDSet[path.From.ChainID] = struct{}{}
        }
    }

    // Existing logic
}
```

### Additional Information
- Consider edge cases where all amounts are zero or negative.
- Discuss with the UI team to ensure the backend validations align with the front-end handling of chain selections and locked amounts.
- Ensure routes do not contain duplicate network IDs to maintain routing integrity.

### References
- [Related Code Section](https://github.com/status-im/status-go/issues/link-to-code-section)
- [Previous Discussions](https://github.com/status-im/status-go/pull/5177/files#r1606394729)

CC @saledjenic @micieslak

**Comment by saledjenic** [comment]
Nice task definition @Samyoul 

> Implement a check in the SuggestedRoutesV2 function to ensure all values in the fromLockedAmount map not negative.
If any value is found to be non-positive, return an error or handle it appropriately.

We will add this validation on the backend side, but verification and validation should be done on the UI side for sure and call the Router logic only if an entry passes them.

Part of the validation process should be:
- if amounts are **locked for each of enabled networks** on the "from" side then the sum of locked amounts **must be equal** to the total amount the user is trying to send
- if amounts are **locked for some of enabled networks** on the "from" side then the sum of locked amounts **must be less** than the total amount the user is trying to send

**Comment by Samyoul** [comment]
100% I agree @saledjenic . There are certain things that the user should be warned about immediately before any data is sent to the API. And validation on the API is also sensible to protect the UI from any future changes that are incompatible with the backend `Router` logic.

If there is anything on this issue that you need me to do please let me know and I'll be more than happy to help as much as I can.

**Comment by saledjenic** [comment]
> If there is anything on this issue that you need me to do please let me know and I'll be more than happy to help as much as I can.

@Samyoul yes we need to add this, but I think it's pretty related to the changes done in this PR https://github.com/status-im/status-go/pull/5177 so, once that one is merged we can check if this issue is still valid and add the necessary checks/validations.

**Comment by Samyoul** [comment]
I'm working on this now I've finally merged https://github.com/status-im/status-go/pull/5257
