### ISSUE TITLE
Use store V3 to improve reliability for Relay

### ISSUE THREAD

**Issue by plopezlpz** [status-im/status-go#5234]
# Problem

Use store v3 in status-go to improve reliability for relay

Ensure that MVDS is used in all direct message scenarios: 
- 1:1 message
- community join request/response
- group chats
- contact request/response

# Implementation

Use store v3 recently implemented in go-waku inside status-go.

# Acceptance Criteria

Store v3 is used in status-go and tests implemented

**Comment by chaitanyaprem** [comment]
@plopezlpz this is completed since we do frequent check for missing messages and also confirmations of sent messages via storev3.
is there something pending , else we can close this.

**Comment by kaichaosun** [comment]
I believe it's finished, feel free to reopen if more work needs to be done.
