### ISSUE TITLE
Use a single flow to send a transaction for remote and local nodes

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#529]
# Problem

It is described in [this comment](https://github.com/status-im/status-go/issues/338#issuecomment-331389930). 

The problem is that having two separate flows to send a transaction introduces subtle differences that may be hard to debug, maintain and can lead to inconsistencies.

# Implementation

Create a single flow in status-go to send all transactions via `eth_sendRawTransaction` regardless which node is used.

# Acceptance Criteria

1. There is a single flow to send a transaction,
1. The whole code related to gas estimation, getting a nonce etc. is in one place,
1. Sending a transaction works with local and remote nodes.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 870.00
Contract address: [0x9ee854507d03f592ec5bfe47e214a34f6e884c16](https://etherscan.io/address/0x9ee854507d03f592ec5bfe47e214a34f6e884c16)
Network: Mainnet
Paid to: dshulyak
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
