### ISSUE TITLE
Relay disconnection/connection speed

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-go#5303]
# Problem

Doing some basic tests to understand Waku Relay disconnect/connection behaviour.

1. Start the app
2. Check number of peers in node management: 8
3. Drop a message in private group
```
DBG 2024-06-06 16:05:41.148+10:00 NewBE_callPrivateRPC                       topics="rpc" tid=80348 file=core.nim:27 rpc_method=wakuext_sendChatMessage
```
4. Kill internet, start stopwatch
5. Wait for # of peers to go to zero-> takes 35s

Around this time:
```
INF 2024-06-06 16:06:42.985+10:00 history request failed                     topics="mailservers-service" tid=80348 file=service.nim:176 requestId=83ec1ef6189e35a3b6704d793fa6d087067c3d552eb19e8f345caeee2abb146f peerId=16Uiu2HAm9CQhsuwPR54q27kNj9iaQVfyRzTGKrhFmr94oD8ujU6P errorMessage="stream reset"
```

6. Resume connectivity
7. new peer in 7s, 5 peers in 23 s, looks fine.
8. Send message, looks fine.

9. Then tried again, 27s to 0 peers (16:09)

10. spammed retry button (ignore that, I forgot to resume connectiviity
```
DBG 2024-06-06 16:10:20.012+10:00 NewBE_callPrivateRPC                       topics="rpc" tid=80348 file=core.nim:27 rpc_method=wakuext_reSendChatMessage
```

11. Resume connectiivty
12. 1min to get 1 peer around 16:13:35.
13. Send message, looks sent fine.

14. Disconnected again and sent messages as soon as disconnected, before peers drop to 0:

```
DBG 2024-06-06 16:18:46.910+10:00 NewBE_callPrivateRPC                       topics="rpc" tid=80348 file=core.nim:27 rpc_method=wakuext_sendChatMessage
```
Message not marked as failed at first. But then marked as failed when peer number reaches 0.

I also noticed that a message sent just before the disconnection was marked as "not sent".

15. Finally, by 16:27, I still have a infinite wheel of death on top of the chat room, is there a pending store query that never gets resolved?

Note, all messages were sent in chat group (ie, with MVDS).

## Learnings

I did few more tests, it takes 20 to 40 s to go to 0 peers from internet loss.

Interesting that a message I sent before disconnection was not sent. What is the delay between clicking enter and message over the wire?

Note that no banner ever opens when we know relay is disconnected (0 peers), but we have banners for external services.

## Questions

1. What is the delay between clicking "enter" and message sent over the wire? seems to be more than 1 sec (I haven't tested thoroughly)?
2. If we know that we are connected to 0 peers (from node management tab), why aren't we showing a banner?
3. From a user PoV, what kind of timeframe should we be aiming for between the moment they are disconnected to the momen they get the feedback on desktop? sub second may not be realistic. is under 10s good enough? under 5s?
4. wheel of death feedback: What is going on? is it a store query sent when we did not know we were disconnected? Would be good to fix/investigate.
5. 1 minute to get first peer seems quite slow, can this be improved?

[app_20240606_160439.log](https://github.com/user-attachments/files/15604734/app_20240606_160439.log)
[geth.log](https://drive.proton.me/urls/V4JTZN5VVW#y1JfC0dvGh87)

**Comment by fryorcraken** [comment]
wheel of death I am referring to:

![image](https://github.com/status-im/status-go/assets/110212804/c4f905c8-7063-4166-b3eb-ce627452db11)

**Comment by fryorcraken** [comment]
> 2. If we know that we are connected to 0 peers (from node management tab), why aren't we showing a banner?

Actually I see a banner now. Not sure if it's me or random. Will test more.

**Comment by fryorcraken** [comment]
Redid a test around 17:12 and the reconnection was almost instantaneous.

logs:

[app_20240606_170515.log](https://github.com/user-attachments/files/15607296/app_20240606_170515.log)
[geth.log](https://drive.proton.me/urls/G5ASCQGQ7M#WURm6CwtCO3i)

**Comment by chaitanyaprem** [comment]
@fryorcraken Do you still see this issue? 
If not, we can close this.

**Comment by fryorcraken** [comment]
I reported quite a few things in there. Will check again.
