### ISSUE TITLE
Remove useless PR checks

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#5337]
# Problem

We don't use these 2 checks:
![image](https://github.com/status-im/status-go/assets/25482501/edb51ac3-8b0d-4751-ad50-2b978c85558a)

- WIP: we use draft PRs instead
- packages bot: we don't have any npm packages

We have @cammellos blessing on doing this 🙂

**Comment by igor-sirotin** [comment]
@apentori @yakimant can you guys please take a look?
I guess it should be an easy thing to do 🙂

**Comment by yakimant** [comment]
- https://github.com/status-im/packages-check-bot
- https://github.com/marketplace/wip

Not sure, how it is setup, maybe per org?

**Comment by igor-sirotin** [comment]
> Not sure, how it is setup, maybe per org?

@yakimant Don't know as well. Could not find any traces of those in the repo 👀

I thought maybe it somewhere in Github Actions page? Though these workflows are usually set up from code 🤔

**Comment by jakubgs** [comment]
The [packages-check-bot](https://github.com/status-im/packages-check-bot) is deployed via Dokku on `node-01.do-ams3.dokku.misc`:
```yaml
  - name: 'packages-check-bot'
    repo: 'https://github.com/status-im/packages-check-bot'
    env:
      APP_ID: 23699
```
https://github.com/status-im/infra-misc/blob/bef27fb4/ansible/group_vars/dokku.yml#L26-L29

The `WIP` bot is a generic one that has been added from an external source.

As for the configuration, you can find the bots configured for a given repo under `GitHub Apps` settings:
https://github.com/status-im/status-go/settings/installations

There you can click on `configure` for a specific bot and find which repos it's enabled for:

![image](https://github.com/status-im/status-go/assets/2212681/9519e0ad-8269-4dd7-bb1f-3129c2ceed74)

https://github.com/organizations/status-im/settings/installations/81515

It might be worth asking if it's useful for the other repos there as well, so maybe we can get rid of it entirely.

**Comment by yakimant** [comment]
Thanks! I've disabled both.

From the list of the repos - I think https://github.com/status-im/status-mobile/ is the most active.
@cammellos, @churik, @siddarthkay, do you think they are useful or needs to be switched off too?

# Packages Check
<img width="1051" alt="Screenshot 2024-06-24 at 14 16 36" src="https://github.com/status-im/status-go/assets/1529006/5e94ae7f-6eaf-4b30-8f36-7ee5b51853a8">

# WIP
<img width="888" alt="Screenshot 2024-06-24 at 14 15 50" src="https://github.com/status-im/status-go/assets/1529006/0b411d42-b49b-42fe-84b0-a298dbf1dee6">
<img width="1104" alt="Screenshot 2024-06-24 at 14 15 30" src="https://github.com/status-im/status-go/assets/1529006/6ae8201e-3e3d-4a06-92ca-9b1b26a38a9e">

**Comment by yakimant** [comment]
@igor-sirotin, can you please check and close the ticket if it worked.

**Comment by igor-sirotin** [comment]
Looks good, thank you!

<img width="871" alt="image" src="https://github.com/status-im/status-go/assets/25482501/c19ff148-8ab1-4451-a24b-f12b09cbaf7c">
