### ISSUE TITLE
bug: find out why filter subscriptions are taking time to stabilize when non fleet nodes are used

### ISSUE THREAD

**Issue by chaitanyaprem** [status-im/status-go#5344]
# Problem

As of now peerExchange Client has been disabled so that only fleet nodes will be used for Filter. 
While testing e2e tests, we have noticed that lot of tests fail due to the fact that filter subscriptions take time when other desktop instances are involved. 

Due to this message delay is noticed. 

Need to analyze why failures are happening especially when peers are returned via pxClient. Especially noticed connection failures while trying to connect to peers.

# Acceptance Criteria

Validate Filter with non fleet peers to work properly.

**Comment by danisharora099** [comment]
Interesting. I've opened an issue on js-waku side to investigate this to see if this is reproducible, and thus deduced this problem is indeed client-agnostic. Part of the investigation process is also finding a solution that can fix this issue, ideally @chaitanyaprem

**Comment by danisharora099** [comment]
Oh, I see that there is a PR for status-go on this already: https://github.com/status-im/status-go/pull/5350

So to summarise and understand the issue, the problem in status-go is that it does not filter peers discovered using Peer Exchange by the pubsub topics that are actually configured on the node, and thus ends up finding, and attempting subscriptions to, unsupported pubsub topic nodes
