### ISSUE TITLE
Collect Whisper metrics in MailServer

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#536]
# Problem

We'd like to collect some Whisper metrics to assess Status usage. E.g. we'd like to see a consistent increase in the number of exchanged messages.

# Implementation

Add metrics to `wnode-status` that runs as a MailServer. https://github.com/status-im/status-go/pull/523 has some initial work on gathering peers info that can be useful.

# Acceptance Criteria

1. The number of exchanged messages,
1. The volume of cached messages.

# Notes

Bear in mind that these metrics must be easy to visualize with Grafana.

It's part of https://github.com/status-im/ideas/issues/68

**Comment by xackery** [comment]
Would prometheus be viable for metrics gathering?

**Comment by adambabik** [comment]
I plan to write a simple abstraction or use https://github.com/go-kit/kit/tree/master/metrics in order to support multiple collectors. 

One huge disadvantage of `expvar` is no labels support. We have a use case where we'd like to count messages by topic. With `expvar` it's only possible by using [`expvar.Map`](https://golang.org/pkg/expvar/#Map), however, additional logic to prune old topics is required. 

Prometheus, on the other hand, has labels support built-in and provides much better integration with tools like Grafana.

Another thing to consider is server vs mobile node. It's ok to use Prometheus in the server node but it does not really make sense to use it in the mobile nodes. Thanks to the mentioned abstraction, we can select a proper tool depending on a use case.

**Comment by xackery** [comment]
When you speak of abstraction, you mean you just plan to write an interface and wrap prometheus/other to implement it?

**Comment by xackery** [comment]
Mainly just looking to do some PRs, this is one around my ballpark is why I shot the comment out. If it's claimed I'll lurk for another.

**Comment by adambabik** [comment]
@xackery great to hear that! This issue is kind of in progress already but I have a different one that is related to metrics: https://github.com/status-im/status-go/issues/546. Would you be able to work on that one?

**Comment by adambabik** [comment]
Done in #558
