### ISSUE TITLE
missing communityRequestToJoin message

### ISSUE THREAD

**Issue by plopezlpz** [status-im/status-go#5412]
# Problem

communityRequestToJoin might be missing by the control node if computer is sleeping and back to awake

## Steps to replicate
1. Alice is the control node
2. Alice's computer goes into sleep for 1 minute
3. Bob sends a request to join community during that minute
4. Alice doesn't get the message

**Comment by plopezlpz** [comment]
relates to: #5422

**Comment by jrainville** [comment]
> relates to: #5412

I think you mistyped/pasted. It does relate to itself, that's for sure :joy:
