### ISSUE TITLE
[Browser plugin connector service] Implement locally handled API's

### ISSUE THREAD

**Issue by kounkou** [status-im/status-go#5417]
# Problem

Connector service aims at handling `eth_` methods received through RPC or WS endpoints. However, some API's must be implemented locally. That's the case for `eth_sendTransaction` or `eth_sign`. THis ticket is created to implement those API's in connector service.

# Implementation

- Add Command design pattern for Handle locally handled API's
- Add Transaction API implementation
- Add sign API implementation
- Add tests for >= 50% coverage 

# Acceptance Criteria

- [ ] A user is able to trigger `eth_sendtransaction` call
- [ ] A user is able to trigger `eth_sign` call 
- [ ] A user is able to trigger `eth_chainId` call
- [ ] A user is able to trigger `eth_requestAccounts` call

**Comment by MishkaRogachev** [comment]
PR: https://github.com/status-im/status-go/pull/5433
