### ISSUE TITLE
Remove API/wrappers from test coverage

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#5466]
# Problem

Example PRs:
- https://github.com/status-im/status-go/pull/5434

  - `services/wallet/api.go`
  
    <img width="667" alt="image" src="https://github.com/status-im/status-go/assets/25482501/b6004702-3ac7-41f7-8eb2-c1af80e462b6">

- https://github.com/status-im/status-go/pull/5456

  - `eth-node/bridge/geth/wakuv2.go`
  
    <img width="683" alt="image" src="https://github.com/status-im/status-go/assets/25482501/b2aedd4b-492a-46bf-8bc3-f339dc44c1fc">
  - `services/ext/api.go`
  
    <img width="691" alt="image" src="https://github.com/status-im/status-go/assets/25482501/5fbc355a-0a87-4e82-9cf2-d2f5f3652018">
  

# Implementation

There're 4 ways to approach this.

## 1. Write the tests

You'd never thought of this, but it is a way as well 😄 
For example:
https://github.com/status-im/status-go/blob/e0c762c0d4d4e07c4356a31a859ae3ef2d9b4bc0/services/wallet/api_test.go#L13-L23

## 2. Remove according files from the report

Just the same as we do with `./cmd/*`:
https://github.com/status-im/status-go/blob/e2846f3936d7ffab833f1eef68b500d6224055cc/_assets/scripts/run_unit_tests.sh#L141-L142

## 3. Re-arrange the files, so that api/wrappers packages doesn't contain any tests

The packages that don't have any tests at all, don't affect the coverage report.
If we wouldn't have those files:
- `services/ext/api_tests.go`
- `services/ext/mailrequests_test.go`
- `services/ext/requests_test.go`
... then the `ext` package wouldn't have this problem.

## 4. Don't write wrappers

I'm not sure if this is possible.
But I think `gethWakuV2Wrapper` could be replaced with an interface, e.g. Or some other solution that would make it possible not to write such api/wrappers at all.

# Notes

Not all `api.go` functions are pure wrappers.
It's important to ensure that (if we exclude such files from coverage report) we simplify such functions to wrap-only funcionality:
https://github.com/status-im/status-go/blob/e0673ad1ffec65e3bd96a46b5054fc2d36071cc4/services/ext/api.go#L1435-L1450

**Comment by Samyoul** [comment]
I think we should implement solution 2 now and then work towards implementing solution 3.

**Comment by igor-sirotin** [comment]
Keeping those, as they don't have tests:
- github.com/status-im/status-go/eth-node/bridge/geth/public_waku_api.go
- github.com/status-im/status-go/eth-node/bridge/geth/public_wakuv2_api.go
- github.com/status-im/status-go/services/appmetrics/api.go - not a pure wrapper
- services/browsers/api.go - not a pure wrapper
- services/chat/api.go - no tests
...

At this file `services/communitytokens/api.go` I though that I'm not sure anymore if this is a good idea to do.
Half of the functions are pure wrappers, half of them have logic that should be covered with tests.

I'll think about it, but no I think that we shouldn't exclude such files. In most cases they shouldn't be a problem because a usual wrapper is 1 line of code, while the wrapped function is more and it should be covered with tests. That should give enough coverage to pass 50%.

**Comment by igor-sirotin** [comment]
Took another look.

`eth-node/bridge/geth/waku.go` - this file is in `gethbridge` package, which doesn't have any `_test.go` files.
So in normal case it would not appear in tests. But it did, I assume because of this PR:
- https://github.com/status-im/status-go/pull/5390

But it was actually needed, because we have integration tests, so tests from package A might test functions from package B.

**Comment by igor-sirotin** [comment]
Another example:
- https://github.com/status-im/status-go/pull/5514

**Comment by igor-sirotin** [comment]
This doesn't need to be done now, because functional tests that use `status-backend` make the coverage for such functions.
