### ISSUE TITLE
Empty response for eth_getTransactionReceipt call

### ISSUE THREAD

**Issue by rasom** [status-im/status-go#547]
# Problem
related to https://github.com/status-im/status-react/issues/2653

When we are calling `eth_getTransactionReceipt` right after sending transaction response is an empty string:
```
01-10 17:29:00.287 11348 23739 D StBridge: payload: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0ca0d8f2422f62bea77e24ed17db5711a77fa72064cccbb8e53c53b699cd3b34"],"id":5}
01-10 17:29:00.407 11348 23739 D StBridge: response:
```
20-30 seconds later we can get a valid response for the same call
```
01-10 17:49:16.767  6004 11537 D StBridge: response: {"jsonrpc":"2.0","id":14,"result":{"blockHash":"0x5253757bb75a48d606566ec72e4081aeaabc23ee3768cf187900ae4cb7b46335","blockNumber":"0x2520f7","contractAddress":null,"cumulativeGasUsed":"0x78283","from":"0xafad068ac92da054741ba7dba43f3b49f6e3f2f3","gasUsed":"0x160fc","logs":[],"logsBloom":"...","status":"0x1","to":"0xd1555741b88895a38cd456842188df2cd112b4ba","transactionHash":"0x22cf84819308e72232791447cf9fb69ec7c7fb2abfc003e1ecc62e5570ba4c72","transactionIndex":"0x7"}}
```

`Statusgo.CallRPC` is used.

**Comment by dshulyak** [comment]
I don't think this is a bug on golang side. Usually if you need to wait until tx is mined or contract is deployed you have to poll the node for some time. For example in go-ethereum implementation there is utility function for that https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/util.go#L31-L53

**Comment by adambabik** [comment]
_As we talked on Slack and just to have a reference._ 

@rasom found that Infura returns `null` in such a case:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}
```

Also, [the docs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) say: 
> Object - A transaction receipt object, or **null** when no receipt was found

So, it indicates that our `rpc` package has a bug.

**Comment by oskarth** [comment]
@divan @adambabik Was this closed in error? #548 is about adding a test case, not fixing the problem, AFAICT.

**Comment by adambabik** [comment]
@oskarth yeah, what has been added there is better handling of errors. At the same time, I could not reproduce this issue with the code or on a simulator.

**Comment by rasom** [comment]
it's already fixed in status-go's `develop`, but we are using outdated version of status-go in the app. Will be fixed with this PR https://github.com/status-im/status-react/pull/2954

**Comment by adambabik** [comment]
That's cool. I will try to look at the commits history and figure out which actually resolve this issue. @rasom do you remember git commit sha of the status-go that caused the problem? If it was the one overridden by status-im/status-react#2954 then it was pretty outdated.

**Comment by rasom** [comment]
@adambabik, yes that's the one which is overridden in PR
