### ISSUE TITLE
Merge status and wnode-status commands

### ISSUE THREAD

**Issue by divan** [status-im/status-go#549]
# Problem

Because of historical/legacy reasons, we now have two commands – `statusd` and `wnode-status`. This is confusing because `wnode` sounds like a counterpart of geth's `wnode` command, and it's not. `wnode-status` is just a statusd with LES protocol disabled and Whisper protocol enabled. It also injects test accounts on the start, but that's obsolete and should be removed.

# Acceptance Criteria

 - there is only one command as a result – `statusd`
 - there is a way to disable/enable LES/Whisper protocols via command line and/or config

**Comment by phcurtis** [comment]
Is test_accounts.go in wnode-status obsolete as well?

**Comment by phcurtis** [comment]
can you assign this to me ... I'll work on it

**Comment by andytudhope** [comment]
I can't assign non-members @phcurtis - but please do go ahead here. Will see how the team feels about a small bounty here too 👍

**Comment by phcurtis** [comment]
okay working on it,
a case I see with data-dir ... in flags stuff default will remain as in statusd: params.DataDir not wnode-data as found in wnode-status/config.go , ... so if one is enabling whisper they likely will also need to change that on invocation ... is there any known problem with that approach? ... there may be some other such scenarios I have yet to find ....

**Comment by phcurtis** [comment]
submitted pull request with #549 resolution a few minutes ago.
