### ISSUE TITLE
Include hibernate test

### ISSUE THREAD

**Issue by plopezlpz** [status-im/status-go#5531]
# Problem

`status-go` runs in desktops and mobile devices, many times the OS hibernates or sleeps pausing the process. `status-go` has multiple loops that run periodically, those might get stopped and resumed and sometimes that might cause issues (e.g.: we used to have an issue where we didn't detect sleep times and therefore on resuming we didn't fetch messages that where sent on this time). 

# Implementation

In order to test for future problems like this we want to add a use case to the ones already running [here](https://github.com/status-im/status-cli-tests) (i.e.: latency, packet loss, low bandwidth) that pauses the cli process for 40 seconds and resumes.
So the scenario would be:
1. Alice and Bob are running
2. Alice's process is paused
3. Bob sends message to Alice
4. Alice's process resumes in 40 seconds
5. Alice should get the message in the next 5 seconds from being resumed

# Acceptance Criteria

Test implemented

**Comment by plopezlpz** [comment]
@fbarbu15 in order to pause/resume you can try with this (as suggested by @fryorcraken): https://unix.stackexchange.com/questions/2107/how-to-suspend-and-resume-processes

**Comment by fbarbu15** [comment]
PR: https://github.com/status-im/status-cli-tests/pull/6
