### ISSUE TITLE
Fix blockchain RPC providers down event happening too often

### ISSUE THREAD

**Issue by IvanBelyakoff** [status-im/status-go#5555]
# Problem

POKT/Infura provider is down banner happens pretty often, which may cause issues with getting routes, sending tx, and overall spoil user experience

# Implementation

Research what causes it. Suspects:
- context cancellation for some commands can cause commands finishing with error "context cancelled" not handled properly
- reaching RPC limits per acc/total per day for history requests causing context cancellations as well
- missing trie node errors handling (archival blocks not available)

# Acceptance Criteria

#POKT/Infura provider is down" banner seen less often

**Comment by churik** [comment]
On mainnet (mobile) I can see the banner 3-10 times per minute:


https://github.com/user-attachments/assets/30fe50b6-e573-45b7-b406-6a1fb9ebf096



Logs: [logs (101).zip](https://github.com/user-attachments/files/16363389/logs.101.zip)

On testnet it is better, I couldn't catch one in several minutes
