### ISSUE TITLE
Create a vendor check for dependencies

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#556]
# Problem

Currently, our CI process doesn't ensure that the dependencies in `vendor` folder are the same as in `Gopkg.lock` file.

# Implementation
The script should run `dep ensure` and then check if anything was changed in the `vendor` directory. If so — fail the pipeline.

The command to run this script should be `make vendor-check`

See [this thread](https://github.com/status-im/status-go/issues/223#issuecomment-357777118) for more practical advice.

1st party implementation is coming to `dep`: [golang/dep#121](https://github.com/golang/dep/issues/121).

# Acceptance Criteria

1. A makefile target is created that fails if there is something in a `vendor` folder that isn't in `Gopkg.lock`. Or if `dep ensure` changes something in the `vendor` folder.

2. `.travis.yml` is updated to have a step of checking dependencies before building or running any tests. (NOTE: Travis restarts builds on every push. If you need to force restarting it and have no changes to commit, just alter the latest commit message with `git commit --amend` and push. That should do the trick).

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 735.00
Contract address: [0x6d179a2fa3a800baa30c1d0aa32b287d5450b260](https://etherscan.io/address/0x6d179a2fa3a800baa30c1d0aa32b287d5450b260)
Network: Mainnet
Paid to: azer
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
