### ISSUE TITLE
Rewrite lint.mk to a configuration file

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#559]
# Problem

We store linter ([gometalinter](https://github.com/alecthomas/gometalinter)) configuration directly in a Makefile which is hard to find and there are a lot of duplications and inconsistency.

# Implementation

Rewrite `lint.mk` into `.gometalinter.json` as described [here](https://github.com/alecthomas/gometalinter#configuration-file).

# Acceptance Criteria

1. The same linters check the same packages,
2. Linter check passes in CI.

# Notes

It may happen that some options are not available in a configuration file. The first step should be carrying out research if `.gometalinter.json` has all features that we use via command line flags. If not, we should discuss how to bypass that.

**Comment by dnephin** [comment]
All features are available from the config file, the flags just set values on the Config object.

**Comment by adambabik** [comment]
That's great! Thanks for the information @dnephin.

**Comment by sebastiandelgado** [comment]
Hey, I'm a new contributor. I'll be taking a jab at this today, since nobody is assigned. I'll be checking here in case that changes. Thanks!
