### ISSUE TITLE
Implement `SensitiveString` type

### ISSUE THREAD

**Issue by qfrank** [status-im/status-go#5678]
Though I there's a drawback here. Adding a field that _should be logged_, will require user to keep in mind to add it to `Marshal` function.

I googled [this solution](https://www.reddit.com/r/golang/comments/z6wf1u/comment/iy5hj55/), it looks much cleaner and scalable:

```go
type SensitiveString string {}

func (SensitiveString s) String () string {
    return "****"
}

func (SensitiveString s) Value() string {
    return s
}
```

I guess we can merge as is and open an issue to fix all places for to use such approach.
cc @osmaczko

_Originally posted by @igor-sirotin in https://github.com/status-im/status-go/pull/5677#pullrequestreview-2227586818_

**Comment by friofry** [comment]
as discussed on status-go guild: (https://docs.google.com/spreadsheets/d/1CerD7oQZVt0kYeSve9IGOtnIgJZ0MPLyTKwoKC77Dtc/edit?gid=0#gid=0)


We can have a 'sensitive string' data type, which will also log nothing in any production build
