### ISSUE TITLE
Community is not published periodically

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#5687]
The periodic community publishing seems broken.

# Problem

I have a community `0x02d3c8b3a47ffea1b5064031f7e5702f8b8bac2ce200fa6a4ca3ab1096f32822c4`
Here's it's current latest description in store nodes:
```nim
store-02.do-ams3.status.prod --- envelopes fetched: 1, community - clock: 1723124729410, name: 'bubego-open-3', members: 2
	shard envelope   1: 0x2d4a8bcbe82dd5afbe495a92208723480e342e812e86c11dc3f3ef7d3c59944d, timestamp: 1723124729417312000 (2024-08-08 13:45:29.417312 +0000 UTC), size: 284 bytes, contentTopic: /waku/1/0x6c38ff95/rfc26, pubsubTopic: /waku/2/rs/16/64
	description envelope   1: 0x0cf24470d839f1f30cea8c597cd04eae4b3b37c1b987929561edd20def6e66cd, timestamp: 1723124729416060000 (2024-08-08 13:45:29.41606 +0000 UTC), size: 796 bytes, contentTopic: /waku/1/0x82fc051a/rfc26, pubsubTopic: /waku/2/rs/16/32
```

Community Clock: 2024-08-08 13:45:29
Envelope timestamp: 2024-08-08 13:45:29.41606

**So it was last published yesterday. I assume when I launch control node, the description will be published.**

Yet I can see this behaviour:
1. In 5 minutes after launch the first `tick` happens
https://github.com/status-im/status-go/blob/5212f337d75fb9902f482edcbf4023cd3ce3bf89/protocol/messenger_communities.go#L479
2. We get into `publishOrgAndDistributeEncryptionKeys`
3. And publishing is ⚠️ SKIPPED with this condition
https://github.com/status-im/status-go/blob/5212f337d75fb9902f482edcbf4023cd3ce3bf89/protocol/messenger_communities.go#L323-L325
    ```nim
    <<< skip as recently published           communityClock=1,723,124,729,410 recentlyPublishedOrgClock=1,723,124,729,410
    ```
4. With no doubts, we set `lastPublished` (though it wasn't published)
https://github.com/status-im/status-go/blob/5212f337d75fb9902f482edcbf4023cd3ce3bf89/protocol/messenger_communities.go#L504
5. After 5 minutes, next attempt comes.
6. This time we ⚠️SKIP with this condition:
https://github.com/status-im/status-go/blob/5212f337d75fb9902f482edcbf4023cd3ce3bf89/protocol/messenger_communities.go#L485-L488

But even if I wait for another hour, we block publishing community description with same clock. 

# Acceptance Criteria

1. Community description is published every hour
2. When launching control node, if last community description publish happened more than 1 hour ago, it should be published immediately.

**Comment by igor-sirotin** [comment]
cc @osmaczko

**Comment by igor-sirotin** [comment]
The fix is not difficult. But I wasn't sure if we update clock when publishing a community description each hour, if there's changed in between 🤔

**Comment by osmaczko** [comment]
> The fix is not difficult. But I wasn't sure if we update clock when publishing a community description each hour, if there's changed in between 🤔

We don't. We should publish with the same clock. Clock is only increased on actual change.

**Comment by fryorcraken** [comment]
cc @jm-clius @kaichaosun

**Comment by fryorcraken** [comment]
> Community description is published every hour

Why such a high frequency? What information in the community message needs to be an hour or less "fresh"?

**Comment by osmaczko** [comment]
> > Community description is published every hour
> 
> Why such a high frequency? What information in the community message needs to be an hour or less "fresh"?

1 hour was too aggressive. [We agreed on 24 hours, since some clients still sync 24 hours of data](https://discord.com/channels/1210237582470807632/1217172931197800468/1271573008430927873). [The change](https://github.com/status-im/status-go/pull/5715/files#diff-12e1567f20b885c074b2a1213664d43a77fbc87c34b5dc42cdb6d4526a86460d) is merged already.

Please note that the entire community description will be published immediately each time there is a change in the community, such as changes to the member list, channels, etc.
