### ISSUE TITLE
Add an option to keep non-go files to `dep`

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#569]
# Problem

Currently `dep prune` removes non-go files from all the packages. That doesn't work for us because some packages we use have C sources in it. In the next release of `dep` there [would be an option](https://github.com/golang/dep/pull/1226) to keep non-go files intact.

When it is released, let's use it and use `dep prune` to keep our vendor folder nice and slim.

# Acceptance Criteria

1. Essential non-go files aren't touched when `dep prune` is called.
2. `Gopkg.toml` has `[prune]` section with options set.
3. Updated (after `dep prune`) `vendor` folder is committed. Tests are removed, unused packages are removed.
4. Tests pass and the library still builds.

**Comment by dshulyak** [comment]
was implemented in https://github.com/status-im/status-go/pull/551
