### ISSUE TITLE
Add MVDS per message type usage as an status RFC

### ISSUE THREAD

**Issue by plopezlpz** [status-im/status-go#5694]
# Problem

Add MVDS per message type usage as an status RFC

# Implementation

As part of this https://github.com/status-im/status-go/issues/5462 @kaichaosun created a table with current ussage of MVDS per message type in status, we want to keep it as an RFC so that we are clear what message types should use MVDS and which should not.

# Acceptance Criteria

RFC with the table from https://github.com/status-im/status-go/issues/5462 is created

**Comment by kaichaosun** [comment]
The repo seems pretty outdated, https://github.com/status-im/specs
should we instead add it to waku/specs?

cc @plopezlpz @jm-clius @fryorcraken
