### ISSUE TITLE
Document all of the prerequisites for running tests on public eth network

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#571]
# Problem

End to end tests, for the public network, has several requirements that are not immediately obvious to the newcomer.

# Acceptance Criteria

Written instructions that would be easy to follow and get a successful test run on a public network.

**Comment by dshulyak** [comment]
@divan @themue @adambabik guys, do you know why we are using go-bindata for keys?

**Comment by adambabik** [comment]
I don't really know the reason. It may be unnecessary and we could keep them directly in Go.

**Comment by dshulyak** [comment]
what about this whole static directory, it just uses web3 library, e.g simple jsonrpc calls, to test statusd and ethereum logic.
anyone runs those tests, maybe some job on ci?
can we perhaps open an issue to rewrite missing tests in golang, and get rid of static directory?

**Comment by dshulyak** [comment]
Regarding static directory and using go-bindata. 
My current understanding is that the only file that needs to be embedded into golang codebase is `cht.json`. Which is not about CHT but default bootnodes, as we are updating CHT by patching geth. I would simply move those values to golang codebase as a native data structures, without using go-bindata.

Next, all kind of configurations for testing. Genesis for status network, accounts for status network, accounts for public network and various keys that are used in tests can be read from files during the test setup.

Tests that are written in javascript with web3.js. I still need to take a closer look at them, but atm I don't see what the point of maintaining tests in js and I would create an issue. Possibly we can port them to golang or, otherwise, enable them on CI if it is not possible to easily rewrite them.

@divan @themue @adambabik please, share your thoughts

**Comment by dshulyak** [comment]
Looks like some of that javascript is used for testing jail functionality as a part of lib tests. No reason for refactoring static directory I guess
