### ISSUE TITLE
Unexcepted envelops are decoded in milti topic iisue

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#574]
# Problem

After codding session with @b00ris and @yenda we've discovered that Ethereum side still creates a filter with 'nil' topic. This happens even after https://github.com/ethereum/go-ethereum/issues/15811

# Implementation

Work branch is `https://github.com/status-im/status-go/tree/debug/many_topics`

# Acceptance Criteria

Only user's filters should be created.

# Notes

This influence on offline mailboxing too.
Here is logs written while multi topic testing:
[multi_topic_logs.tar.gz](https://github.com/status-im/status-go/files/1667726/multi_topic_logs.tar.gz)

# Future Steps

Recompile Status application and check that no unexpected envelops are decoded.

**Comment by b00ris** [comment]
Problem was in testing branch. No need to fix in statusgo. Resolved.
