### ISSUE TITLE
Update geth-patches readme with dep instruction and creating patches

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#578]
# Problem

After merging `dep` https://github.com/status-im/status-go/pull/551, working with patches changed a bit, however, [README.md](https://github.com/status-im/status-go/blob/develop/geth-patches/README.md) has not been updated.

# Acceptance Criteria

1. Update `Vendor patched version` section,
2. Create a new section which explains how to create a patch. (This is not related to #551 but it looks like it's missing.)
3. Add a link to the [rebasing docs on Notion](https://www.notion.so/status/Rebasing-go-ethereum-82de0bbebe684826b62d81bc688e5e89)

**Comment by mandrigin** [comment]
@adambabik btw, how is that relates to the README?
https://www.notion.so/status/Rebasing-go-ethereum-82de0bbebe684826b62d81bc688e5e89

<blockquote><img src="https://www.notion.so/images/meta.png" width="48" align="right"><div>Notion</div><div><strong><a href="https://www.notion.so">Notion – Docs, Wikis, Tasks. Seamlessly in one.</a></strong></div><div>A new tool that blends your everyday work apps into one. It's a unified and collaborative workspace for you and your team</div></blockquote>
