### ISSUE TITLE
Run tests on each commit in `develop` branch

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#5809]
# Problem

Would be great to have tests executed for each commit in `develop` branch

This is needed for:
1. Proper measurement and comparison of coverage.
    Currently we compare with nightly runs, but this is not quite right.
    https://docs.codecov.com/docs/error-reference#section-missing-base-commit

2. Detect if merged changes broke something on top of latest `develop`
    (As we don't use merge queue)

# Acceptance Criteria

`Jenkinsfile.tests` and `Jenkinsfile.tests-rpc` jobs are launched for each commit in `develop` branch.

# Notes

Before I thought it would be inappropriate, because the tests were running for too long. But now the statistics are better.

1. Test runtime ~30 minutes
    <img width="500" alt="image" src="https://github.com/user-attachments/assets/ec38541e-6917-409f-9276-1a6a495a920b">
    And we're working towards making the tests to run even faster, but I don't expect massive improvements soon. 

2. ~5 PRs in daily average lately
    <img width="500" alt="image" src="https://github.com/user-attachments/assets/91981ae4-601b-4c73-9932-0207236c8a00">

# Future steps

1. Ensure this it doesn't lead slow down of PRs tests. 
If we reuse the same machines for `develop` tests and PRs, there might appear a queue of wait to execute the tests for PRs.
This would be unacceptable I think.

2. Ensure that Codecov behaves correct when PR tests were executed earlier than the base commit tests.
(this might be possible, right?)

**Comment by igor-sirotin** [comment]
cc @jakubgs @yakimant

**Comment by igor-sirotin** [comment]
@yakimant just to clarify: we want this on each PR merge, not on each commit in `develop` .
Now the `Rebase and Merge` PR option is enabled, so it's possible for multiple commits to appear on `develop`. No need to run tests on each of them, just the top one.

**Comment by jakubgs** [comment]
>we want this on each PR merge, not on each commit in develop

How are those two different tho?

**Comment by igor-sirotin** [comment]
> > we want this on each PR merge, not on each commit in develop
> 
> How are those two different tho?

@jakubgs If you have multiple commits in a PR and use `Rebase and merge` option, all commits will appear on top of `develop`.
In such case we don't want to run tests for each rebased commit, just the top one.

**Comment by jakubgs** [comment]
Is that a common occurrence or are we just trying to optimize for an edge case by adding unnecessary complexity?

It's way easier to just run a job on every commit.

**Comment by igor-sirotin** [comment]
> or are we just trying to optimize for an edge case by adding unnecessary complexity?

Yes😄
But I didn't know it is more complex.


> It's way easier to just run a job on every commit.

@jakubgs If it is easier to make for each commit, then surely let's do it that way.

The case I described is quite rare and we're even discussing to forbid it.

**Comment by yakimant** [comment]
I will check this. But for example Teamcity has a feature of delaying the build for 1 to pick up all the commits.
Probably Jenkins has this too.

**Comment by yakimant** [comment]
There is such an option:
![Image](https://github.com/user-attachments/assets/4d50e95b-964b-41d2-b804-5537daefdc2a)

And this:
![Image](https://github.com/user-attachments/assets/2c3305bb-fc8c-4dee-acaf-7e5d2813eafb)

**Comment by jakubgs** [comment]
Oh, I never actually used the quiet period option, might be worth a try.

**Comment by yakimant** [comment]
@igor-sirotin, please have a look, is it what you want:
https://ci.status.im/job/status-go/job/tests-develop/

Note, that `_assets/ci/Jenkinsfile.tests` has a lot of checks for nightly builds.
This `tests-develop` will be treated as PR build. Maybe some should be fine-runed, eg `UNIT_TEST_RERUN_FAILS`

**Comment by igor-sirotin** [comment]
@yakimant looks like what we need, thank you ❤  

Can we please do the same for `Jenkinsfile.tests-rpc`?

> Maybe some should be fine-runed

Yes, indeed. Where can I tweak this? Or should I just tell you what's needed?

**Comment by yakimant** [comment]
> Can we please do the same for Jenkinsfile.tests-rpc?

Yes, will do tomorrow

> Yes, indeed. Where can I tweak this? Or should I just tell you what's needed?

You can modify the Jenkinsfile (don't forget to ask for review).

**Comment by yakimant** [comment]
I've added a job for tests-rpc too:
https://ci.status.im/job/status-go/job/tests-rpc-develop/

It wasn't triggered yet, will watch.

**Comment by yakimant** [comment]
quiet time is 5s, we can increase in the future if we have too many runs
