### ISSUE TITLE
dependence  network consumption on the number of peers

### ISSUE THREAD

**Issue by b00ris** [status-im/status-go#583]
# Hypothesis
Increasing number of node peers increase network usage.

# Implementation
We need to investigate how network overhead of statusgo(https://github.com/status-im/status-react/issues/2965) depends on number of peers.
Compare network usage for different number of peers

# Acceptance Criteria
Add investigation and testing scenario to https://github.com/status-im/ideas/issues/71  

# Notes
Part of https://github.com/status-im/ideas/issues/71
Part of https://github.com/status-im/status-go/issues/576

# Future Steps
Find the optimum number of peers

**Comment by adambabik** [comment]
In case of Whisper, it looks like there is a linear correlation between the number of peers and the messages volume. It makes sense as Whisper sends a message to each peer. It's worth to research how it looks overall though 👍
