### ISSUE TITLE
Single 1-1 chat test network overhead scenarios for Geth and Status

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#586]
# Problem

Ability to reproducible testing 1-1 group chatting Status and Geth stats baseline.
The issue is a part of https://github.com/status-im/status-go/issues/576

# Implementation

Add support of test scenario for Status containers in testing tool https://github.com/JekaMas/ether_tester
Single 1-1 chat test scenarios for Geth and Status (60rpm per node). With and without upstream. 2 tests in total.

# Acceptance Criteria

Meaningful Status statictics and Geth baselines.

**Comment by pedropombeiro** [comment]
@JekaMas I've been able to sync the blockchain while running as unpriviledged user, but the output still shows no messages circulating. [This commit](https://github.com/PombeirP/ether_tester/commit/c4433782a54a59e02d8f9a0ffbaaeacbefe0fff7) shows the code as well as the log file. Not sure if you can see any reason why this shouldn't work.

**Comment by JekaMas** [comment]
@PombeirP I'm going to check the test tommorow. Thanks for logs and commit!

**Comment by pedropombeiro** [comment]
@JekaMas I implemented a routing provider in the Python codebase, but it looks like none of the Whisper methods are supported by Infura. I get:

For `newMessageFilter`
> `405 Client Error: Method Not Allowed for url` :-/

For `post`:
> {'code': -32601, 'message': 'The method shh_post does not exist/is not available'}

Or is the goal just to activate upstream and still call all `shh` APIs over the local RPC server?

FWIW, this is what I'm getting:

Statistics:
Geth without upstream
Stats (bytes/s):

||Receive|Transmit|Total
|---|---|---|---|
count|175|175|175
mean|462399|451357|913757
std|268305|256868|525137
min|1757|617|2374
25%|241017|229811|470829
50%|459297|448578|907875
75%|689063|671024|1360087
max|917343|894746|1812089

Geth with upstream
Stats (bytes/s):

||Receive|Transmit|Total
|---|---|---|---|
count|175|175|175
mean|432307|462308|894616
std|265093|268134|533119
min|8107|10697|18804
25%|205747|236247|441995
50%|413936|454673|868609
75%|658499|694247|1352746
max|913134|926705|1839839
