### ISSUE TITLE
Add the commit check for `logOnPanic`

### ISSUE THREAD

**Issue by qfrank** [status-im/status-go#5866]
# Description

We want all goroutines to use `defer common.LogOnPanic()`. Otherwise it's difficult to trace the panic on mobile.
To force this, we need a PR level check that will ensure that all goroutines use this logging.

More details here on implementation here: 
- https://github.com/status-im/status-go/pull/5849#discussion_r1768494945

**Comment by igor-sirotin** [comment]
This doesn't seem to be an urgent task, yet not good to postpone.
I was curious to do it, so I used my time off for it. Results are in `feat/LogOnPanic-linter` branch.

https://github.com/status-im/status-go/blob/2b8fcb727a3cfcc37603a5ad1b71148ee6e7fd41/cmd/lint-panics/main.go#L18

# TODO

Some more work is needed there:
- Add proper parametrization:
    - A list of directories? 
    - `-skip` argument?
    - `-pattern=LogOnPanic` argument?
- Properly filter results directories
    - `./vendor` directory, because we can't change it
    - Though we can change `waku` code. Not sure what's the way to go here.
    - Maybe only print the directories that were given as input?

# Which repo?

We have the same check in waku repo, so we might want to extract this app to a separate repo. Or even wrap it into a Gihub Action right away, to be easily used in both repos.

**Comment by igor-sirotin** [comment]
This is also important for https://github.com/status-im/status-go/issues/5895, as it will probably have to be integrated into each goroutine.
