### ISSUE TITLE
Filter out `gas` linter error checks for `fmt.Fprintf` commands

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#590]
# Problem

We have a lot of unnecessary `// nolint: gas` comments near `fmt.Fprintf`.
We never want to check error value of `Fprintf` anyway.

# Implementation

1. Remove `// nolint: gas` comments from `fmt.Fprintf`
2. Tweak the `gometalinter` config to ignore these warnings from `gas`. Keep the other warnings intact.

# Acceptance

1. There are no `// nolint: gas` comments near `fmt.Fprintf`.
2. `make lint` shows no warnings
3. Other warnings from `gas` aren't ignored.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 225.00
Contract address: [0xe373495788dfddb92e873dee01ed83410194acdc](https://etherscan.io/address/0xe373495788dfddb92e873dee01ed83410194acdc)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by alexkohler** [comment]
I have a branch that removes the directives, however, I'm not sure if gometalinter exposes the gas output in a manner that allows someone to know *what* error was found, it just assigns it a severity. 

**gometalinter gas output:**

```
$ make lint
lint
...
geth/jail/console/console.go:21::warning: Errors unhandled.,LOW,HIGH (gas)
geth/log/log.go:94::warning: Errors unhandled.,LOW,HIGH (gas)
```

**The actual gas output:**

```
status-go/geth/log/log.go:94] - Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > fmt.Fprintf(os.Stderr, "Incorrect log level: %s, using defaults\n", level)


Summary:
   Files: 1
   Lines: 136
   Nosec: 0
  Issues: 1
```

We could probably write a special regex for gas to ignore fmt.Fprintf calls, **but then *all* Fprintf calls would be ignored by gas** :

**.gometalinter.json example**
(the Pattern would need expanded to ignore fmt.Fprintf)
```
"Linters": {
    "gasv2": {
      "Command": "gas",
       "Pattern": "^(?P<path>.*?\\.go),(?P<line>\\d+),(?P<message>[^,]+,[^,]+,[^,]+)"
    }
},
    "Enable": [
        ...
        "gasv2"
    ],
```

Any thoughts?

**Comment by alexkohler** [comment]
I've done a little debugging, manually running gometalinter and running only on the cmd/statusd package

```Bash
$ gometalinter --no-config --disable-all --enable=gas cmd/statusd --debug                                                                           
DEBUG: PATH=(omitted)
DEBUG: GOPATH=/home/alex/status-go
DEBUG: GOBIN=/home/alex/go/bin
DEBUG: linting path ./cmd/statusd
DEBUG: [gas.1]: executing /home/alex/go/bin/gas -fmt=csv cmd/statusd/main.go cmd/statusd/whispercfg.go
DEBUG: [gas.1]: warning: /home/alex/go/bin/gas returned exit status 1: [gas] 2018/01/31 12:38:12 including rules: default
[gas] 2018/01/31 12:38:12 excluding rules: default
[gas] 2018/01/31 12:38:12 Searching directory: /home/alex/status-go/cmd/statusd/main.go
[gas] 2018/01/31 12:38:12 readdirent: not a directory

DEBUG: [gas.1]: gas hits 0: ^(?P<path>.*?\.go),(?P<line>\d+),(?P<message>[^,]+,[^,]+,[^,]+)
DEBUG: [gas.1]: gas linter took 125.688307ms
DEBUG: total elapsed time 136.122448ms
```

**Comment by mandrigin** [comment]
Hi! Thanks for your input. Is it possible to tweak the pattern you mentioned so `gometalinter` actually prints the LoC that `gas` provided?

If so, we can always use `gometalinter --exclude <regex>` that has both "Errors unhandled" and `fmt.Fprintf` in.

**Comment by alexkohler** [comment]
I think that is possible, but similar to my solution I think we'd ignore *all* gas static analysis that contains `fmt.Fprintf`. If we're okay with that, I can continue with that solution.

**Comment by mandrigin** [comment]
@alexkohler hmm, that means that it won't be possible to both print `"Errors unhandled"` and the line that caused it?

**Comment by alexkohler** [comment]
@mandrigin -ah, I think I originally misunderstood your proposal. I will double check on this. If we can use a multi line regex I think that’ll let us suppress unhandled errors for only fmt.Fprintf calls👍
