### ISSUE TITLE
#576 - Discuss approach to automated Geth/statusd performance testing

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#597]
# Problem

We need a way to do reliable automated testing for geth and statusd (network, CPU, etc) in different use cases. @JekaMas already has a great headstart with https://github.com/JekaMas/ether_tester. The current tool however only allows specifying single lines of sequencial code which can reference results from previous instructions. Although this works for very simple scenarios, it is hard to make it work (or be performant) if you need to do e.g. more complex initialization and a loop using the results from the initialization.

The goal of this GHI is to be a forum to propose ideas of how to achieve that goal as quickly as possible, so that we can do the testing required for https://github.com/status-im/status-go/issues/576.

# Implementation

Ideally we'd be able to specify a JavaScript file to execute on each Docker container (both for Geth and Statusd containers).

# Acceptance Criteria

The accepted idea has to:
-  work for both Geth and Statusd;
- allow plenty of flexibility for more complex flows of execution.

**Comment by pedropombeiro** [comment]
One idea I floated in Slack was the following:

> Maybe we could have a `.js` file alongside each use case, and pass the `.js` file to geth with `geth --preload "./usecases/myusecase1.js" console`, or as mentioned in https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#non-interactive-use-jsre-script-mode ? Not sure if this is also available for statusd (not at my PC atm).

But according to @JekaMas, `statusd` doesn't work the same way. The question then becomes: is it easy to implement the same support in statusd (i.e. a few hours work?)

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>

**Comment by dshulyak** [comment]
I've been thinking about perf testing for a change that I want to try. This is somewhat different from what is proposed here, but anyway I will share:

I will use https://github.com/status-im/status-go/tree/develop/docker made by @adambabik to bootstrap a cluster. Connect with any client library to all of the whisper nodes and generate messaging scenarios. It will be just a separate script running on my host. What would be the reason for having that script in container, anyway?

Data that I need (general number of message and new messages) will be already available in prometheus. I won't be writing any automation, but if I wanted - there will be no issues with collecting info directly from container http handler or prometheus.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by dshulyak** [comment]
In general,  I think it is very important to have a time-series data for this. Otherwise how to properly measure CPU or memory usage?

**Comment by pedropombeiro** [comment]
If I understand correctly, the script would run on an arbitrary machine and target the cluster, where the metrics are collected. So we wouldn't collect any metrics on the node which is running the script. Is that correct?

**Comment by pedropombeiro** [comment]
It does seem like there is some overlap in both tools. Ideally we'd maintain a single tool to avoid confusion and promote synergies. Maybe we could merge them in a way that @JekaMas's ether_tester leverages the cluster/collector by dynamically generating a `wnode-test-cluster/docker-compose.yml` file that describes the intended test scenario (number/composition of nodes, etc). Does that make sense?

**Comment by JekaMas** [comment]
The point of `ether_tester` is to compare Geth as baseline vs Status or different versions of Status in given scenarion. It's more about QA automation not monitoring. `ether_tester` is for fast testing that can be run many times by dev or QA.
`node-test-cluster` looks more like monitoring tools for researching, finding bottleneck in realtime.
Its like 'testing' vs 'benchmark'. Pretty similar but different approaches.

**Comment by divan** [comment]
We have https://github.com/status-im/ideas/issues/51 for running test cluster to make reliable tests/benchmarks.
There is also Appium testing code that even uses real device simulators to run difference scenarios: https://github.com/status-im/status-react/tree/develop/test/appium/tests

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by JekaMas** [comment]
Could it be used for such testing?
1. Start geth node.
2. Start status node.
3. Wait for sync.
4. Fix 0 point for given metric
5. Run given test scinario at the same time on both nodes. Scenario example: create an account, get a key pair, create a message filter, send few messages, repeat for 60sec.
6. Return stats of Status wrt Geth: total, min, max, median, mean etc.

My point is about to have small, simple tool for testing. Its not about monitoring or cluster's health. Its more about isolated and repeated testing. Its something that developer can run each minute and get fast result.
As far as i can see #51 solves more general task. May be i'm wrong and it suitalbe for everyday testing. I'd be happy to know that.

**Comment by dshulyak** [comment]
> Start geth node.

docker compose
> Start status node.

docker compose

> Wait for sync.

single subscription call with a client
> Fix 0 point for given metric

metric value before test run is started or what?

> Run given test scinario at the same time on both nodes. Scenario example: create an account, get a key pair, create a message filter, send few messages, repeat for 60sec.

that's a matter of writing a client with this scenario codified
> Return stats of Status wrt Geth: total, min, max, median, mean etc.

prometheus stores time-series data, not a problem to compute all those values

**Comment by dshulyak** [comment]
https://github.com/status-im/status-go/pull/609

**Comment by dshulyak** [comment]
I don't feel that we need to have it open, there are bunch of swarms that can be used for such discussion.

Feel free to re-open if needed
