### ISSUE TITLE
Check is it possible and safe to use WhisperV6

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#598]
# Problem

WhisperV6 is in Ethereum master https://github.com/ethereum/go-ethereum/tree/master/whisper/whisperv6
It should be checked:

- does it suitable for Status? Does network and CPU overhead reduced?

- is it safe to use bloom filters? Is it possible to restore topics from bloom filter on peer's side?

- does migration on WhisperV6 brokes down capability with WhisperV5? It seems like whisperV5 nodes are going to be marked as 'spammers' by WhisperV6 nodes with bloom filters.

- Does the spam detection is safe for network connectivity?

- Should be used a more reliable hash function like https://github.com/dgryski/go-boomphf/blob/master/boomphf.go ?

# Implementation

We have an investigation of the bloom filter's hash function https://github.com/JekaMas/whisper_hash_test

# Acceptance Criteria

Some description where and how whisperV6 could be useful for Status and perhabs a bug list.

# Notes

Part of https://github.com/status-im/ideas/issues/71

**Comment by JekaMas** [comment]
We have first results from 55b swarm. This morning @b00ris and me have done first green test of WhisperV6 in Status-go with some of our patches on it. After patching it works as expected, drastically decreasing the amount of receiving by user messages.
Here is the test data.

## Tests
Common conditions:

- there're 4 users (Alice, Bob, Charlie, Grinch) + mail server
- Alice sends 100 messages to group chat with some delay
- User Grinch is a spammer or additional network load

Test cases:
1. Grinch is connected to all users, but doesn't send anything
2. Grinch sends messages with random topics
3. All tests have been done on all networks with whisperV5 and whisperV6 messaging

The numbers in table below is an amount of received messages by user (i mean "received by network").

| Test case  | Alice (send/receive)  | Bob  | Charlie  | Grinch (send/receive)  | Mail server  | Total  |
| -------------| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| V6 Rinkeby+upstream w/o additional load  | 100/102  | 307  | 396  | 0/395  | 303  | 1503  |
| V5 Rinkeby+upstream w/o additional load  | 100/102  | 464  | 562  | 0/559  | 559  | 2246  |
| Difference    | **0%**  | **51%**  | **42%**  |   |   |
|     |   |   |   |   |   |
| V6 Rinkeby+upstream with additional load  | 100/6  | 334  | 299  | 3999/295  | 468  | 1402  |
| V5 Rinkeby+upstream with additional load  | 100/11796  | 19272  | 18408  | 3771/2403  | 19441  | 71320  |
| Difference    | **196500%**  | **5670%**  | **6057%**  |   |   |
|     |   |   |   |   |   |
| V6 Ropsten+upstream w/o additional load  | 100/156  | 303  | 347  | 0/401  | 349  | 1556  |
| V5 Ropsten+upstream w/o additional load  | 100/2170  | 2748  | 2864  | 0/2842  | 2701  | 13325  |
| Difference    | **1291%**  | **807%**  | **725%**  |   |   |
|     |   |   |   |   |   |
| V6 Ropsten+upstream with additional load  | 100/44  | 286  | 291  | 3859/391  | 506  | 1556  |
| V5 Ropsten+upstream with additional load  | 100/55338  | 53755  | 57233  | 3254/42823  | 56699  | 265848  |
| Difference    | **125668%**  | **18695%**  | **19568%**  |   |   |
|     |   |   |   |   |   |
| V6 Mainnet+upstream w/o additional load  | 100/0  | 101  | 101  | 0/101  | 101  | 404  |
| V5 Mainnet+upstream w/o additional load  | 100/0  | 103  | 102  | 0/104  | 102  | 411  |
| Difference    | **0%**  | **2%**  | **1%**  |   |   |
|     |   |   |   |   |   |
| V6 Mainnet+upstream with additional load  | 100/1  | 101  | 101  | 3780/191  | 309  | 602  |
| V5 Mainnet+upstream with additional load  | 100/3906  | 4008  | 3998  | 3920/102  | 4012  | 16026  |
| Difference    | **390500%**  | **3868%**  | **3858%**  |   |   |

## Results
Almost all unwanted network traffic is eliminated. The more whisper users in network the more significant difference. So for me it looks like a good scalable sotution.
Moreover the bloom filters in whisperV6 are done in such way that for each user's topic there're 200 collisions. So for example is user have subscribed for 10 topics bloom filter will matches by > 2000 topics. This keeps the guarantees of anonymity and security.
I'm goint to plan whisperV6 integration in 55b swarm. According to my preliminary assessment it will take up to a month, maybe 2 weeks.

**Comment by JekaMas** [comment]
@dshulyak I'm really looking for you in 55b swarm :) You branch with additional message type looks promising. Do you want to join?

**Comment by dshulyak** [comment]
@JekaMas sure, I can work on these things as a part of 55b.
That branch may somewhat reduce duplicates of wanted packets, but it should have higher impact if load will be increased.

**Comment by JekaMas** [comment]
Yeah, i've read your code. It should works just like you wrote.
The main question for me is how we're going to implement this:
1. As a new version of Whisper specification that all clients agree with (like WhisperV6)
2. Like our own protocol extension.

**Comment by JekaMas** [comment]
@dshulyak I tested again with the same topology of fully connected network:
Alise's peers: 4
Bob's peers: 4
Charlie's peers: 4
Grinch's peers: 4
Mail server's peers: 4

While tests running new peers didn't added (i just turned off Internet)

| Test case  | Alice (send/receive)  | Bob  | Charlie  | Grinch (send/receive)  | Mail server  | Total  |
| -------------| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| V6  | 100/45  | 376  | 387  | 3999/261  | 351  | 3788  |
| V5  | 100/6336  | 11976  | 13580  | 3766/894  | 12780  | 45566  |
| Difference    | **13980%**  | **3085%**  | **3409%**  |   |   |

So it looks like pretty the same result

**Comment by dshulyak** [comment]
@JekaMas These results are comparable with mainnet results from the previous section. I said before that it is clear that there are no additional sources of traffic in this case. Now let's compare with results for ropsten network, amount of received packets for Bob is 53755, It is very likely that there is another source of network traffic there. So, what I tried to say is that in case of ropsten network with v5 there will be additional peers (not 4), and with v6 there will be only 4 peers.

**Comment by JekaMas** [comment]
You're right. Mainnet doesn't use whisper heavely so isolated results is the same as mainnet.
In Ropsten there're a lot of whisper traffic. I can remake Ropsten test with fixed configuration. I'll publish the results tomorrow morning.

**Comment by JekaMas** [comment]
closed as devided to implement whisperV6 https://github.com/status-im/status-go/issues/634
