### ISSUE TITLE
Functional tests running on `develop` branch don't report failure

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#5980]
Here's a PR job, properly failing: https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests-rpc/detail/PR-5969/15/pipeline/

![Image](https://github.com/user-attachments/assets/f3cc6533-cb5c-49c4-8f42-d9c77e9e7285)

And here is the job for `develop` branch getting same error, but passing:

https://ci.status.im/blue/organizations/jenkins/status-go%2Ftests-rpc-develop/detail/tests-rpc-develop/7/pipeline/

![Image](https://github.com/user-attachments/assets/9703ed86-aeb6-475e-a953-7c04223c63d9)

-----

So it looks like all jobs are passing. But in fact all of them have failed 🙁 

![Image](https://github.com/user-attachments/assets/1f215b53-4c81-45d8-bd34-218454c3bb43)

**Comment by igor-sirotin** [comment]
The issues that lead to failure are fixed here:
- https://github.com/status-im/status-go/pull/5979

**Comment by yakimant** [comment]
I would make a branch from failing commit, add sebug to the `_assets/scripts/run_functional_tests.sh`.

**Comment by igor-sirotin** [comment]
Actually, the error `.../bindata.go": no such file or directory` is coming from the `go tool covdata` command. That's why it doesn't affect the final exit code. Not sure if it should. 
The actual bug of not generating files was fixed here: https://github.com/status-im/status-go/pull/5979
