### ISSUE TITLE
Replace `geth.Logger` usage with `zap.Logger` across status-go repo

### ISSUE THREAD

**Issue by osmaczko** [status-im/status-go#6002]
### Description

Replace calls to geth.Logger with zap.Logger across status-go repo.

**Comment by igor-sirotin** [comment]
@osmaczko This should probably be in status-go repo?

**Comment by osmaczko** [comment]
> [@osmaczko](https://github.com/osmaczko) This should probably be in status-go repo?

Yes, ideally it should. However, since the parent resides in status-desktop, I would prefer to keep it as is. By the way, I am aware that the parent should also belong to status-go, and it did previously, but I moved it because the goal labels in status-desktop aren't accessible in status-go 🙈

**Comment by igor-sirotin** [comment]
@osmaczko I guess we should copy the goals labels to status-go then.
