### ISSUE TITLE
Enforce type safety in `NodeCrashEvent`

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#602]
# Problem

Currently, `NodeCrashEvent` has an `Error` field that that is of `string` type. That is both misleading and weakens the type safety. It is nice to make it of `error` interface type.

On the other hand, we still need to marshal `NodeCrashEvent` to json without losing the error description.

# Implementation

We should make a custom JSON marshaller for `NodeCrashEvent` to convert `error` interface to `string`.

# Acceptance Criteria

1. `NodeCrashEvent` has `Error` field that is of `error` type.
2. `NodeCrashEvent` marshalls to json successfully: `NodeCrashEvent{Error: errors.New("test-error")} -json-> { "error": "test-error" }`
3. There is a unit-test that checks the marshalling.

**Comment by sebastiandelgado** [comment]
I'll be taking a jab at this. Should have a PR for it soon.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 225.00
Contract address: [0x11d0da14c73b1d5a832a503e283fafa28efb045d](https://etherscan.io/address/0x11d0da14c73b1d5a832a503e283fafa28efb045d)
Network: Mainnet
Paid to: sebastiandelgado
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
