### ISSUE TITLE
Create a script that auto-applies `geth-patches`.

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#603]
# Problem

We have a number of patches for `go-ethereum` that are located in `/geth-patches` folder.
We apply all of them manually.
We need a script that will apply these patches automatically.

# Acceptance Criteria

1. There is a script that applies `/geth-patches` to a specified directory.
2. If there is no directory specified — apply it to `./vendor/ethereum/go-ethereum`
3. If the patch was already applied — do not apply it > 1 time. (e.g. keep track of applied patches in the target directory).
4. The script should exit if a patch could not be successfully applied.
5. (Preferably) no external dependencies should be brought by this script. (We assume `bash` and `git` are installed).
6. The patch that failed should be rolled back, so a developer using this script is able to fix it and try again.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 900.00
Contract address: [0x9be82b7ac8c12cb481de16bfb5b98a9fee07174f](https://etherscan.io/address/0x9be82b7ac8c12cb481de16bfb5b98a9fee07174f)
Network: Mainnet
Paid to: canercidam
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by sebastiandelgado** [comment]
I'm interested in this. A couple questions though:

- Do you want to include the steps of cloning a fresh copy of ethereum/ethereum-go to the specified directory? In this case, we'd be deleting the specified local copy of etheruem-go.
- When you say that a failed patch should be rolled back, do you mean that if patch 0005 fails, the script should leave the repo in the state it was after the application of patch 0004 and then exit? This way the dev can fix the patch, then re-run the script to get a fresh copy of ethereum-go and apply all the patches all over again.

**Comment by mandrigin** [comment]
@sebastiandelgado wow, I just noticed your answer. Thanks for your interest!

(1) Nope, we usually will use this script with already checked out `go-ethereum` in vendor or **somewhere else** (that's important).
(2) Exactly!

**Comment by canercidam** [comment]
Hi @sebastiandelgado, sorry for submitting a PR before you but it's been a while and I already had a solution. Don't hate me, please. :stuck_out_tongue:

**Comment by sebastiandelgado** [comment]
@mandrigin Thanks! @canercidam No worries! Hadn't started working on it anyways.
