### ISSUE TITLE
Use non-privileged user in Ethereum's Dockerfile

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#608]
# Problem

The Ethereum issue with docker privileges slows our progress in testing.

# Implementation

Resolve https://github.com/ethereum/go-ethereum/issues/15816

# Acceptance Criteria

Issue is resolved and merged into Ethereum master.

Part of https://github.com/status-im/ideas/issues/71

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x05152bc612e9c38b1c343efe328fd2f9c0e55fd8d9544ed0ffee057aaec2bac6](https://etherscan.io/tx/0x05152bc612e9c38b1c343efe328fd2f9c0e55fd8d9544ed0ffee057aaec2bac6)

**Comment by adambabik** [comment]
What's the problem with using a privileged user in a docker container?

**Comment by fgimenez** [comment]
I've already proposed https://github.com/ethereum/go-ethereum/pull/16052 to address this one, still being reviewed though.

**Comment by dshulyak** [comment]
do we depend on it in any way? looks like that we don't use ethereum containers

i will close it, but feel free to re-open if you feel strongly that we need it.
also even if it is good thing by itself - this is status-go repository :)
