### ISSUE TITLE
Add a test case with concurrent transactions and upstream node

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#613]
# Problem

To reproduce the problem described in https://github.com/status-im/status-go/pull/538 with upstream network we need to have a test case that will send multiple concurrent transaction with enabled upstream node.

# Implementation

We already have a test TestCompleteMultipleQueuedTransactions in TransactionsTestSuite but it uses local ethereum node. Implementation should reuse this test but with enabled upstream node. For an example see TestCallRPCSendTransactionUpstream.

# Acceptance Criteria

Test that is based on TestCompleteMultipleQueuedTransactions uses upstream node for sending transactions.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x281aa9b2b68ccd43c84fc3af6e3dfcc295947928](https://etherscan.io/address/0x281aa9b2b68ccd43c84fc3af6e3dfcc295947928)
Network: Mainnet
Paid to: fgimenez
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
