### ISSUE TITLE
Provide test proxy credentials for functional tests

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#6145]
We need _test proxy_ credentials in the functional tests. In the future we'll mock the providers, but we can't do it quickly right now.

Functional tests will expect these env vars:
- `STATUS_PROXY_USER`
- `STATUS_PROXY_PASSWORD`

Tests side done here:
- https://github.com/status-im/status-go/issues/6144

**Comment by jakubgs** [comment]
Are we sure the tests won't create a very large volume of requests? What's expected?

**Comment by igor-sirotin** [comment]
> Are we sure the tests won't create a very large volume of requests? What's expected?

@jakubgs I can't promise anything about the usage 😐. But right now this is blocking functional test runs.

We will eventually, but it's not fast:
- mock the providers and try to make 0 requests
- implement "smart caching" on proxy

**Comment by jakubgs** [comment]
I see, that's fair, and indeed in a perfect world we'd mock everything, but it's understandable this is the simplest approach.

@mendelskiv93 could you please ensure the `status-go` tests have access to credentials to use `proxy.test` fleet.

But I would recommend creating a separate username and password for this purpose:
https://github.com/status-im/infra-proxy/blob/e815a56fd90fc34615201e87490c8a72ba11ab59/ansible/group_vars/proxy.test.yml#L13-L17

So it's easier to revoke this access in the future when we will probably create separate `proxy.staging` for tests like this.

**Comment by mendelskiv93** [comment]
@igor-sirotin Is there a way we can do: 
```
      usernameVariable: 'STATUS_BUILD_PROXY_USER',
      passwordVariable: 'STATUS_BUILD_PROXY_PASSWORD'
```
like in [status-mobile](https://github.com/status-im/status-mobile/blob/1faa2e8f88553705a845b1ca839f4d4eab4c67c4/src/status_im/contexts/profile/config.cljs#L18) and [status-desktop](https://github.com/status-im/status-desktop/pull/16093)?

**Comment by igor-sirotin** [comment]
@mendelskiv93 if these are already available in `status-go` repo, then sure, we can use it 👍

**Comment by mendelskiv93** [comment]
@igor-sirotin yes they are!

**Comment by igor-sirotin** [comment]
@mendelskiv93 just in case, did you create separate credentials for this purpose?

This case is dangerous because we could potentially (but we'll prevent it as much as possible) leak the key in logs. So we must have dedicated username/password for simple revoke/rotate later.

**Comment by mendelskiv93** [comment]
@igor-sirotin yes I did, it will be used only by `status-go`.
Hopefully will not come to that but it can be easily removed.

**Comment by igor-sirotin** [comment]
Done now, thank you!
