### ISSUE TITLE
Setup Sentry Github integration

### ISSUE THREAD

**Issue by igor-sirotin** [status-im/status-go#6152]
<img width="932" alt="image" src="https://github.com/user-attachments/assets/7001485e-e97e-4204-bf4a-1b36a720fabb">

- Docs here: https://develop.sentry.dev/integrations/github/

- Some more details here: https://github.com/status-im/status-desktop/pull/16845#issuecomment-2508910728

**Comment by markoburcul** [comment]
@igor-sirotin could you try to test the desktop application again and see if in Sentry there will be code associated with the error? We managed to add github integration to sentry..

**Comment by markoburcul** [comment]
No need to do it, the old errors will work!
![Image](https://github.com/user-attachments/assets/dd26c2b1-9aaa-4d22-b439-606cd061f30f)

**Comment by igor-sirotin** [comment]
There're some problems I'm trying to investigate now. Will write them down to go crazy.
I'm investigating. 

The Github Integration seem to be in place, but not yet helping, because it's not disabled for non-InApp frames.

## `In App` is detected wrong when built as part of `status-desktop`([example](https://sentry.infra.status.im/organizations/sentry/issues/136/?project=7&query=is:unresolved&statsPeriod=30d&stream_index=0)):

![Image](https://github.com/user-attachments/assets/31c09fb0-bff7-4053-8182-388633ff4a4e)

Most probably it's related to the way `InApp` is calculated:

https://github.com/status-im/status-go/blob/f15c64ced3de797dbf329917188b58ae1ec7f780/vendor/github.com/getsentry/sentry-go/stacktrace.go#L338-L346

There's a check for `vendor`. And the path is `status-desktop/vendor/status-go`.
Though it's checking for `Module` which is actually `github.com/status-im/status-go/...`, looking at the event JSON:
```json
{
  "function": "IntendedPanic",
  "module": "github.com/status-im/status-go/mobile",
  "filename": "/Users/igorsirotin/Repositories/Status/status-desktop/vendor/status-go/mobile/status.go",
  "abs_path": "/Users/igorsirotin/Repositories/Status/status-desktop/vendor/status-go/mobile/status.go",
  "lineno": 2318,
  "pre_context": [
    "",
    "func IntendedPanic(message string) string {",
    "\ttype intendedPanic struct {",
    "\t\terror",
    "\t}"
  ],
  "context_line": "\treturn callWithResponse(func() {",
  "post_context": [
    "\t\terr := intendedPanic{error: errors.New(message)}",
    "\t\tpanic(err)",
    "\t})",
    "}",
    ""
  ],
  "in_app": false,
  "data": {
    "orig_in_app": 1
  }
}
```

## `pre_context`, `context_line` and `post_context` are missing for CI-builts.

When testing locally, the context is always there.

Looking at `sentry-go` code, context should not be added when `!frame.InApp `:

https://github.com/status-im/status-go/blob/f15c64ced3de797dbf329917188b58ae1ec7f780/vendor/github.com/getsentry/sentry-go/integrations.go#L262-L296

But I definitely see context for some not `InApp` frames, e.g. [here](https://sentry.infra.status.im/organizations/sentry/issues/136/events/1b431cc70c36403c861aeb22059d683d/):
![Image](https://github.com/user-attachments/assets/9fb709f0-ea0f-41fa-9225-f60a06c3a368)

**Comment by igor-sirotin** [comment]
Alright, after setting up some [stack trace rules](https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/), I can see the `In App`.

So I confirm the Github Integration is working now, thank you 👍 

![Image](https://github.com/user-attachments/assets/758cb6bf-f1d9-4784-bc47-feba1a069364)

I hoped that will show the code even when context is missing in the event JSON, but doesn't seem to solve the issue 🙁 
Will continue investigating separately.

-----

Another interesting thing I realised is that Sentry doesn't have direct access to commit hash, only as part of the `release`. So it's always pointing to `develop` branch on Github 🤦

**Comment by igor-sirotin** [comment]
oh wait, of course code context is missing for CI builds.
Because the app binary doesn't contain the source code and Sentry can't find it locally with given paths 🤦 

I tried [Associate commits](https://docs.sentry.io/product/releases/associate-commits/), but this didn't help.
Anyway, it's not a big deal, we still can see the the stack trace in raw form, just without embedded code.
