### ISSUE TITLE
Use of internal package is not allowed

### ISSUE THREAD

**Issue by jgimeno** [status-im/status-go#617]
# Problem

Hi! I don't know if this is the correct way to ask this, but I am playing with the codebase. As soon as I run the tests I get some errors because of the jail package. It says to me that internal packages are not allowed. I haven't seen in the Makefile that this package is not excluded from the unit test so I guess I should have something wrong in my environment.

Thanks!

**Comment by canercidam** [comment]
Is your clone in `$GOPATH/src/github.com/status-im/status-go`?

**Comment by jgimeno** [comment]
Thanks! My fault, I forked the repo and I was trying it from there. I close this!
