### ISSUE TITLE
flowType missing for UserProfileCreatePassword and UserProfileConfirmPassword

### ISSUE THREAD

**Issue by glitchminer** [status-im/status-go#6183]
flowType is being logged as *** for 2 screens during the new keys onboarding flow.

```
DEBUG    RequestLogger    call    {"method": "addCentralizedMetric", "duration": "212.958µs", "request": [{"metric":{"appVersion":"2.32.0-rc.3","eventName":"navigation","eventValue":{"flowType":"***","viewId":"UserProfileCreatePassword"}

DEBUG    RequestLogger    call    {"method": "addCentralizedMetric", "duration": "161.833µs", "request": [{"metric":{"appVersion":"2.32.0-rc.3","eventName":"navigation","eventValue":{"flowType":"***","viewId":"UserProfileConfirmPassword"}
```

@qfrank @igor-sirotin , identified as likely being related to this function: https://github.com/status-im/status-go/blob/cdc41c3b6459924b9ac30e1b60b34669e48984bd/mobile/callog/status_request_log.go#L105-L111

**Comment by qfrank** [comment]
Hi @glitchminer , could you help check if #6188 fixed the issue?

**Comment by glitchminer** [comment]
Resolved - UserProfileCreatePassword and UserProfileConfirmPassword now appear in log.
