### ISSUE TITLE
Group tests in a dedicated testing package

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#620]
# Problem

Our tests are in the root package now (`e2e`, `testing`).
I'd be nice to move them to dedicated test package.

# Implementation

The package name should be `t`, to make it stand out and short.
`e2e` should be moved to `t/e2e`.
`testing` should be renamed to `t/utils`

# Acceptance Criteria

Tests still run and pass for:
* `make test-unit`
* `make test-e2e`

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 225.00
Contract address: [0x09b1649cae5e92b35ed5f583d4eb3f16d16e1b05](https://etherscan.io/address/0x09b1649cae5e92b35ed5f583d4eb3f16d16e1b05)
Network: Mainnet
Paid to: sekl
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by sekl** [comment]
Looks like a good first issue to work on, so I'll take it if nobody else has started it yet. ;)
