### ISSUE TITLE
Move non-go related files to the `_assets` folder.

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#621]
# Problem

Some of the directories in our root dir are valid go packages. Some aren't.
That makes it harder to understand what is what.

# Implementation

Let's create an `_assets` directory and group these files/packages there (as much as we can).
The proposal looks like that.
```
SOURCE                        TARGET
.gitignore
.gometalinter.json       * -> _assets/
.travis.yml              *
DEPENDENCIES.md          * -> _assets/docs/
Dockerfile               * -> _assets/build/
Gopkg.lock
Gopkg.toml
Jenkinsfile              * -> _assets/ci/
Jenkinsfile-manual       * -> _assets/ci/
LICENSE.md
Makefile
README.md
build                    * -> _assets/build/
ci                       * -> _assets/ci/
cmd
docker                   * -> _assets/compose/
extkeys
geth-patches             * -> _assets/patches/geth
lib
metrics
package-lock.json        * -> _assets/
package.json             * -> _assets/
profiling
static
vendor
xgo                      * -> _assets/build/
```

# Acceptance Criteria

**All** make commands are passing and providing the same results as before the changes (see `Makefile`).
Link in the .md files work.

**Comment by oskarth** [comment]
> Jenkinsfile              * -> _assets/ci/
> Jenkinsfile-manual       * -> _assets/ci/

This isn't 100% open since it requires changes on Jenkins (priv ack)

**Comment by mandrigin** [comment]
@oskarth agree, but I'll take the responsibility for coordination of this change internally.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 900.00
Contract address: [0xfdb8a80c6b4ea6e5ec63bfed8d41464f71ddf725](https://etherscan.io/address/0xfdb8a80c6b4ea6e5ec63bfed8d41464f71ddf725)
Network: Mainnet
Paid to: canercidam
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by canercidam** [comment]
I want to work on this today. Will get a PR ready.
