### ISSUE TITLE
Enable gometalinter for test files

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#631]
# Problem

Currently, we do not lint Go test files (`*_test.go`) but we should. Test files, just like the normal ones, should be reliable and bug-free.

# Implementation

Add `"Test": true` property to `.gometalinter.json`. It also requires fixing all lint errors and warning that will be found.

# Acceptance Criteria

1. Go test files are linted,
1. `make lint` passes.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 480.00
Contract address: [0xbb4e3691298f353e34da43c434fe9c5f82849a1d](https://etherscan.io/address/0xbb4e3691298f353e34da43c434fe9c5f82849a1d)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
