### ISSUE TITLE
Measure the energy consumption of `status-go` on a device

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#633]
# Problem

The whole app consumes quite a lot of energy at the moment. Let's figure out how much `status-go` part actually consumes.

# Implementation

Create a minimalistic native wrapper for `status-go` for iOS (and maybe Android) that listens to messages in `#status` and a special ping channel. Also, it should send messages 3-4 times a minute.
Run this under a profiling tool on a physical device and measure battery impact.

Part of: https://github.com/status-im/ideas/issues/83

**Comment by azer** [comment]
Could measuring `statusd` be useful in this case ? 

If yes, a script based on [powertop](https://wiki.archlinux.org/index.php/powertop) can also measure it and be integrated into the CI step to keep track of the consumption as the codebase grows. Out of curiosity, I checked the results and got following result after measuring statusd with powertop for 20 seconds;

```
Usage: 176.9 us/s
Wakeups: 6.6
```

P.S I ran statusd without generating any activity.

**Comment by mandrigin** [comment]
@azer that is a good idea. though, I want to try to measure the consumption as close to the actual hardware we'll run it on. So we can see how the battery is affected by CPU going to hi-perf/lo-perf mode, wifi/3g antenna's activity, etc. And also it is easy to simulate "real-life" activity there, like active public chats.
That's why the mobile app.

**Comment by mandrigin** [comment]
The mobile app: https://github.com/mandrigin/status-go-n-wrapper

<blockquote><img src="https://avatars1.githubusercontent.com/u/466427?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/mandrigin/status-go-n-wrapper">mandrigin/status-go-n-wrapper</a></strong></div><div>status-go-n-wrapper - Native simple wrapper for status-go for iOS and Android.</div></blockquote>

**Comment by mandrigin** [comment]
the test apps are in this repo: https://github.com/status-im/energy-efficient-bok

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/energy-efficient-bok">status-im/energy-efficient-bok</a></strong></div><div>energy-efficient-bok - Body of Knowledge of testing for energy efficiency</div></blockquote>
