### ISSUE TITLE
WhisperV6 as a Geth patch

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#636]
# Problem

We need first implementation of whisperV6 to make it possible to implement Status patcher to it and start to use it.
Our current version of whisperV6 is a just clone of whisperV5. We need to get updates from upstream.

# Implementation

Move whisperV6's code into our Geth version. Make it as a temporary patch.

# Acceptance Criteria

Status-go compiles successfully, tests in whisperV6 packages are passed.

# Notes

That should be temparary patch until we rebase to Geth 1.8+

Part of #634

**Comment by feuGeneA** [comment]
Part of #634
