### ISSUE TITLE
Apply notifications patch to whisperV6

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#637]
# Problem

We need notifications and few changes in whisper servise that present in notifications patch.

# Implementation

Apply patch `geth-patches/0004-whisper-notifications.patch` to whisperV6. Make new patch for whisperV6 (not temporary).

# Acceptance Criteria

Status-go tests are passed.

Part of #634

**Comment by pedropombeiro** [comment]
@JekaMas do we want to include `0009-whisper-envelopes-tracing.patch` in this GHI (it's easy)?

**Comment by JekaMas** [comment]
@PombeirP This is great if you could done all patches in single issue!

**Comment by feuGeneA** [comment]
Part of #634
