### ISSUE TITLE
Investigate how status-go works after changing a network connection

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#639]
# Problem

The mobile Status.im app seems to have a problem with receiving messages after changing the network from Wifi to 3g or another way around. On a desktop (in an iOS simulator) I can reproduce it by switching from Wifi to Ethernet or switching wifi on/off.

We need to:
- reproduce the issue in an isolated environment, make it repeatable;
- figure out if restarting the node will help;
- figure out if that is a status-go or go-ethereum issue;
- figure out if there is a way of handling that w/o restarting the node.

# Acceptance Criteria

1. Test script or test app + reproduction steps to repeat the issue. It should reproduce on the `develop` branch.
2. Fix for the issue. After it is applied, (1) doesn't reproduce anymore.
3. If the issue is in the upstream go-ethereum:
3.1. Check if that is fixed in the latest master there.
3.2. If not — create an issue in the upstream repo.
3.3. Submit a fix to upstream + a patch that fixes (workarounds) this issue in status-go.

**Comment by flexsurfer** [comment]
related with https://github.com/status-im/status-react/issues/3116

**Comment by mandrigin** [comment]
Discovered as a part of: https://github.com/status-im/ideas/issues/75#issuecomment-364123369

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2400.00
Contract address: [0x00b3ea4b9e28d2914f376cb0463c0f473c2e6179](https://etherscan.io/address/0x00b3ea4b9e28d2914f376cb0463c0f473c2e6179)
Network: Mainnet
Status: Pending maintainer confirmation
Winner: andytudhope
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by dshulyak** [comment]
I will write an automation to continuously validate that initial blockchain sync, les and whisper can tolerate different network conditions (loss of connectivity, partial loss of packages, unpredictable latency). If someone wants to have a fast look what is this concrete problem about please go ahead.

**Comment by dshulyak** [comment]
https://github.com/status-im/status-go/pull/646

**Comment by divan** [comment]
As far I as I know, all mobile platforms have mobile connection state/reachability API, and send events when net is switched off, disconnected from network or poor signal quality is detected.

We definitely need to leverage this, but seems like we only can get this information from `status-react` and notify `status-go` via new library/API calls.

**Comment by mandrigin** [comment]
New information (wrote that in #646)

I managed to reproduce it like that (iPhone 8+):

1. Open an app that listens to `#humans-need-not-apply`
2. Receive 2-3 messages
3. Minimize the app
4. Let the phone go to sleep,
5. Let it sleep for 3-5 minutes
6. Unlock the phone, open the app
7. Observe no more messages.
(when the app is restarted, it receives messages again)

Note that the app shouldn't be killed in between (5) and (6).

**Comment by mandrigin** [comment]
@dshulyak @divan that is the error message
`{"jsonrpc":"2.0","id":2968,"error":{"code":-32000,"message":"filter not found"}}`

**Comment by dshulyak** [comment]
@mandrigin Oh, that was really helpful))  Filter can be uninstalled if it wasn't used for 300 seconds.
Regarding https://github.com/status-im/status-react/issues/3271 , i am 99% sure that it is caused by time skew and I know a place where we can reliably hack it to speed up recovery)

**Comment by dshulyak** [comment]
so, application needs to handle such error and recreate a filter

**Comment by mandrigin** [comment]
@andytudhope closing this one because we figured it by ourselves together with @dshulyak (and help from @PombeirP).

**Comment by dshulyak** [comment]
Looks like should be closed long time ago
