### ISSUE TITLE
Make sure Ropsten testnet is available on LES cluster

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#64]
- Morden is reset, now we have Ropsten testnet
- we need to make sure that our LES test cluster is in sync with Ropsten
- https://github.com/ethereum/go-ethereum/pull/3315

**Comment by obscuren** [comment]
I have a node serving LES at `enode://b70fb61a041c3f6cbe73ebdddb2816e04c4297aa4c5a5881cf3ebd24c0bd1bdb5d3c2d3e124ebab4af1144acbba4d9881bce767c6dbdbe31583aadb7da9c03f8@94.242.229.4:30303` and also using discovery v5.

**Comment by jarradh** [comment]
thanks @obscuren ! It seems v5 whisper isn't 100% stable for us so we're using v2 to try get alpha out - also we'd be very happy to help work on Whisper since Status depends on it
