### ISSUE TITLE
Switch Status cluster and mail server node to WhisperV6

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#640]
# Problem

We need to switch our bootnodes cluster to whisperV6 support. Also we need mail server with whisperV6 support.

# Implementation

Check is there any changes in https://github.com/status-im/status-cluster needed.
e.g. https://github.com/status-im/status-cluster/pull/12
Doc https://github.com/status-im/status-cluster/wiki/MailServer-nodes

# Acceptance Criteria

Status-go tests are passed on all networks.

# Notes

It could be that mail server can works only with one whisper protocol. In this case we need two active whisperV6 nodes for some time.
Also it should be checked that updated cluster can works with whisperV5 and whisperv6 at the same time.

Part of #634

**Comment by pedropombeiro** [comment]
@JekaMas maybe it's better to make "Also it should be checked that updated cluster can works with whisperV5 and whisperv6 at the same time." a separate issue, and this one would just be to create a new cluster?

**Comment by feuGeneA** [comment]
Work in progress to get new v6 cluster up and running is visible at https://github.com/status-im/status-cluster/tree/whisper-v6-status-go-%23640 .
