### ISSUE TITLE
Move envelopes tracing patch to whisperV6

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#641]
# Problem

We need backward capability in Status-go code after switching to whisperV6: envelops tracing in whisper servise.
We already have the patch `geth-patches/0009-whisper-envelopes-tracing.patch` from PR https://github.com/status-im/status-go/pull/558 for whisperV5. Nowdays we want the same functionality for whisperV6

Part of #634 

# Implementation

Apply patch `geth-patches/0009-whisper-envelopes-tracing.patch` to whisperV6. Make new patch for whisperV6 (not temporary).

# Acceptance Criteria

Status-go tests are passed.

**Comment by divan** [comment]
We're usually introducing patches and applying them in a single commit.
Also, this issue lacks explanation what's exactly is "envelops tracing" and why do we need it.

**Comment by JekaMas** [comment]
This issue is about applying our whisperV5 patch to whisperV6. It's just saving our current status functionality.

**Comment by divan** [comment]
Ah, I see now, it's not clear from the description. Please try to describe the problem in the issues as clear as possible, so developers with no prior knowledge understand the problem and have enough context to work on it.

**Comment by pedropombeiro** [comment]
@JekaMas as we discussed in https://github.com/status-im/status-go/issues/637#issuecomment-364399660, this work has been done in that issue. I think we can close this as a duplicate.

**Comment by pedropombeiro** [comment]
@feuGeneA you could probably take https://github.com/status-im/status-go/issues/640 instead. Sorry about that, I only realized now that this patch was the one you had taken, it was pretty close to the one handled in #637 so I just took care of it there.

**Comment by JekaMas** [comment]
Done in https://github.com/status-im/status-go/issues/637
