### ISSUE TITLE
LevelDB error when running e2e tests on the public network

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#652]
# Problem

When we run e2e tests on a public network (`make test-e2e networkid=4`), they often fail.

The error is
```
CRIT [02-12|10:57:59] Failed to store last header's hash       err="leveldb: closed"
```
(see https://travis-ci.org/status-im/status-go/jobs/340419267#L721) for an example.

# Implementation

Steps to reproduce: https://github.com/status-im/status-go/issues/652#issuecomment-364924136

# Acceptance Criteria

1. Steps to reproduce are found and provided provided
2. The issue is fixed
3. 10 tests in the row pass on public network pass w/o this error.

# Notes

If a bug is in `go-ethereum` implementation, an upstream patch should be provided

**Comment by canercidam** [comment]
@mandrigin Two remarks from what I noticed:
1) Looks like it especially fails on whisper tests: https://travis-ci.org/status-im/status-go/jobs/340439798
2) I remember that error relating to ungraceful exits (e.g. timeout) from #612. This one is surely not about a timeout but maybe an unexpected exit somewhere in the code.

**Comment by mandrigin** [comment]
Yeah, seems like something gets closed or killed too quickly...

**Comment by mandrigin** [comment]
https://github.com/status-im/status-go/pull/645 — a PR

**Comment by feuGeneA** [comment]
I also experienced this error.  I produced a whisper benchmark that I wanted to run for 10 minutes, but this error precluded me from being able to run it for that long.  The benchmark can be used to easily reproduce the error, but annoyingly you'll have to run it for several minutes to make that happen.  See more details in [this comment](https://github.com/status-im/status-go/issues/579#issuecomment-364384292) on #579 .

**Comment by adambabik** [comment]
Thanks @feuGeneA! I will try to reproduce this bug using your perf test as currently, I haven't managed to reproduce it locally even once.

**Comment by adambabik** [comment]
It's not fixed yet. #645 only improved reporting errors.

**Comment by themue** [comment]
Ah, yes, pushed *close* too early when merging your test improvements.

**Comment by canercidam** [comment]
I'm interested in solving this problem today.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0x04203b0936a620cbcf6cce9fba015d82390d89c0](https://etherscan.io/address/0x04203b0936a620cbcf6cce9fba015d82390d89c0)
Network: Mainnet
Paid to: mandrigin
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
