### ISSUE TITLE
Apply geth patches on the fly.

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#653]
# Problem

Currently, we use a custom fork of `go-ethereum` to apply our patches on.
That makes the process of adding new patches cumbersome (first make a PR to the fork, get it approved, create a patch, update the version, etc).

We want to apply patches "on-the-fly" when updating the dependency or changing any of the patches.

We already have a patches script in `_assets/patches/patcher`

# Acceptance Criteria

1. `make vendor-check` passes
1.1. If any file is added/changed in `patches/geth` and the changes weren't applied, `make vendor-check` should fail.
2. `go-ethereum` dependency is pointed to `github.com/ethereum/go-ethereum`
3. `make dep-ensure` target is created, that runs `dep ensure` and then applies all the patches from `_assets/patches/geth`.
3.1. `make dep-ensure --update <dependency>` syntax is supported.
4. Custom fork of `go-ethereum` isn't used anywhere.
5. README.md and DEPENDENCIES.md are updated with the new process.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 1000.00
Contract address: [0xb459b2dccdd03c9b1f01e7772a8db82bd2892d74](https://etherscan.io/address/0xb459b2dccdd03c9b1f01e7772a8db82bd2892d74)
Network: Mainnet
Paid to: canercidam
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by canercidam** [comment]
Nice! I'll get ready for this.

**Comment by mandrigin** [comment]
We probably want https://github.com/status-im/status-go/pull/647 merged first.

**Comment by adambabik** [comment]
`make dep-ensure --update <dependency>` -- may be tricky. However, why do we need this in the first place? If we want to update `go-ethereum`, couldn't it be a two steps operation: (1) call `dep ensure --update go-ethereum` (2) Follow the normal flow and call `make dep-ensure` which will run `dep ensure` and apply patches?

**Comment by canercidam** [comment]
> `make dep-ensure --update <dependency>` -- may be tricky.

Yes, I don't think this syntax is possible with `make`. But `--update=<dependency>` should be possible as in `test-e2e` target.

**Comment by adambabik** [comment]
Correct, but the question is do we actually need it.

**Comment by mandrigin** [comment]
I don't think it is critical. We can make it a two steps operation, as @adambabik suggested. If the docs are updated, it is fine.

**Comment by canercidam** [comment]
It sounds fine to me either way.

**Comment by canercidam** [comment]
Work still in progress.
1) Looks like the solution to this issue is blocked by #655. Switching to `master` for `go-ethereum` in `Gopkg.toml` results in:
```
master: Could not introduce github.com/ethereum/go-ethereum@master, as its subpackage github.com/ethereum/go-ethereum/whisper/notifications is missing. (Package is required by (root).)
```
and similary with any other version. Can you think of any workaround to this?

2) Supposing there's WIP on branch `my-branch`, would it make sense to compare `my-branch` with `develop` to check for recently added but possibly unapplied patches?

With the changes I'm planning to submit, it's going to be possible to use:
```Makefile
vendor-check:
	@dep ensure
	./_assets/ci/validate-vendor.sh
	./_assets/patches/patcher -c

dep-ensure:
	@dep ensure
	./_assets/patches/patcher
```

**Comment by mandrigin** [comment]
(2) it totally makes sense. We need to catch these things on our CI for sure.

**Comment by mandrigin** [comment]
(1) can you try to demove dependency on on `github.com/ethereum/go-ethereum/whisper/notifications` from status-go? That should help.

**Comment by canercidam** [comment]
It doesn't help since `dep` looks for imports. `whisper/notifications` is used in `geth/node/node.go` so I need to change status-go code as well.

**Comment by mandrigin** [comment]
ah, I meant, check if it is possible to get rid of this dependency in `geth/node/node.go` :)

**Comment by canercidam** [comment]
Oh, sorry. :)

**Comment by canercidam** [comment]
PR #660 - I'm experiencing a lot of problems. `dep ensure -update github.com/ethereum/go-ethereum` + `make dep-ensure` doesn't help. Patches fail:
```
Previously applied:
===================
/home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0011-geth-17-whisperv6-70fbc87.patch
===================

Applying new: /home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0000-accounts-hd-keys.patch

Applying new: /home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0002-les-api-status.patch

Applying new: /home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0003-dockerfiles-wnode-swarm.patch

Applying new: /home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0004-whisper-notifications.patch

Applying new: /home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0006-latest-cht.patch

Failed and reverting: /home/mo/gopath/src/github.com/status-im/status-go/_assets/patches/geth/0006-latest-cht.patch
```

**Comment by canercidam** [comment]
Thanks @andytudhope! :)
