### ISSUE TITLE
Remove or move notification package from go-ethereum fork to status-go

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#655]
# Problem

According to some comments ([here](https://github.com/status-im/status-go/pull/648#issuecomment-364937779) and [here](https://github.com/status-im/status-go/pull/648#issuecomment-364776526)), regarding a package which deals with notifications in https://github.com/status-im/go-ethereum/tree/develop/whisper/notifications, it is not clear if this code is required, but at the very least, it is not necessary for this code to live there and it implies patches (https://github.com/status-im/status-go/blob/develop/_assets/patches/geth/0004-whisper-notifications.patch, https://github.com/status-im/status-go/blob/develop/_assets/patches/geth/0013-whisperv6-notifications.patch). Should the code still be needed, it should be moved to the status-go repo.

# Implementation

Investigate whether code is needed. Remove it if not, move it to status-go if yes.

# Acceptance Criteria

- After removal push notifications work properly.
- Chat performance and functionality is not deteriorated.

# Notes

Code that initializes notifications: https://github.com/status-im/status-go/blob/develop/geth/node/node.go#L186-L192

**Comment by JekaMas** [comment]
The other issue is that the patch contains some useful modifications to whisper service. So it couldn't been removed all at once.
So additional criteria: chats are working fine with the same speed.

**Comment by adambabik** [comment]
@PombeirP @JekaMas what do you think about splitting `0013-whisperv6-notifications.patch` into two patches so that one encapsulates only `whisper/notifications/` code and another one Whisper V6 changes? Even if `whisper/notifications/` is needed, this issue would not require changing `0013-whisperv6-notifications.patch`.

**Comment by JekaMas** [comment]
That'd be great. It should be in the issue.

**Comment by adambabik** [comment]
One thing: watch out for not making circular imports. In `whisper/whisperv5/whisper.go` there is `notificationServer NotificationServer` attribute. So, we will end up with status-go importing go-ethereum and go-ethereum (after patching) will import status-go to get `NotificationServer` declaration.
