### ISSUE TITLE
Investigate/perform upgrade to Geth 1.8.1

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#665]
# Problem

Geth 1.8.1 was [released today](https://blog.ethereum.org/2018/02/14/geth-1-8-iceberg%C2%B9/). It contains many improvements that are important for us, and by upgrading to 1.8.1 we render some patches redundant (namely `0011-geth-17-whisperv6-70fbc87.patch` which ported Whisper v6 to our fork), making future maintenance easier.

# Implementation

Investigate breaking changes in 1.8.1 to determine what work must be done as part of the upgrade. Perform upgrade.

## Breaking changes checklist
- [x] Discovery v4 and v5 have been merged to use the same UDP port (30303 by default). If you are doing manual peer management and using the light client, you may need to ensure your v1.8.0 clients are pointed to port 30303 and not 30304 as previously.
- [x] Trie pruning is enabled on all `--syncmode` variations (including `--syncmode=full`). If you are running an archive node where you would like to retain all historical data, you should disable pruning via `--gcmode=archive`.
- [x] Only the latest 128 tries are kept in memory, most tries are garbage collected. If you are running a block explorer or other service relying on transaction tracing without an archive node (`--gcmode=archive`), you need to trace within this window! Alternatively, specify the `reexec: 12345` tracer option to allow regenerating historical state; and ideally switch to chain tracing which amortizes overhead across all traced blocks.
- [x] Native events rely on modifications to internal go-ethereum types within generated code. If you are using wrappers generated prior to v1.8.0, you will need to regenerate them to be compatible with the new code base.
- [x] The HTTP/WS RPC endpoint was extended with [DNS rebind protection](https://github.com/ethereum/go-ethereum/pull/15962). If you are running an RPC endpoint **addressed by name rather than IP**, run with `--rpcvhost=your.domain` to continue accepting remote requests.

# Acceptance Criteria

- [ ] The different `make` targets work as expected (e.g. `make ci`, `make statusgo-android`, etc)
- TBD

# Notes

This GHI only makes sense to start once https://github.com/status-im/status-go/pull/660 is merged.

TDB

# Future Steps

- Upgrade bootnodes and mailserver cluster with new version.
- TBD

**Comment by dshulyak** [comment]
> The GasLimit and GasUsed fields of blocks and transactions have type uint64 instead of *big.Int. This is a breaking API change. (#15466)

this should require changes in tx manager code and fake backend for tests

**Comment by pedropombeiro** [comment]
Random notes as I'm going through the migration:
- Using localhost in the URL causes [DNS rebinding protection to kick in](https://github.com/ethereum/go-ethereum/pull/15962) and fail the HTTP request. Solution is to either use IP or add localhost as an exception in the node config.
- go-ethereum duktape [patch](https://github.com/ethereum/go-ethereum/pull/16129) might be accepted upstream (mentioned in https://gitter.im/olebedev/go-duktape)
- E2E tests seem flaky (passed locally but failed on Travis CI):
```
go test -timeout 20m ./t/e2e/whisper/... -network=
--- FAIL: TestWhisperMailboxTestSuite (23.35s)
    --- FAIL: TestWhisperMailboxTestSuite/TestRequestMessagesInGroupChat (15.29s)
	Error Trace:	whisper_mailbox_test.go:250
	Error:      	Not equal: 
	            	expected: 1
	            	actual: 0
```

**Comment by PombeirP** [comment]
Comparing the [Android nightly build](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-834ae3.apk) which uses Whisper v5 (left) with a local build with Whisper v6 (right) and leaving the apps running for 10 minutes produces this usage pattern, looking at it with an Android packet sniffer app (TestFairy is disabled for both builds):

![image](https://user-images.githubusercontent.com/138074/36607511-20d67b64-18c7-11e8-9229-7d027d4d94be.png)

Whisper v6 app is built from the `feature/geth-1.8.1` branch in `status-react`, and connected to 2 Whisper v6-enabled bootnodes and with 4 contacts.

**Comment by PombeirP** [comment]
Comparing the [Android nightly build](http://artifacts.status.im:8081/artifactory/nightlies-local/im.status.ethereum-834ae3.apk) which uses Whisper v5 (left) with a local build with Whisper v6 (right) and leaving the apps running for 10 minutes produces this usage pattern, looking at it with an Android packet sniffer app (TestFairy is disabled for both builds):

![image](https://user-images.githubusercontent.com/138074/36607511-20d67b64-18c7-11e8-9229-7d027d4d94be.png)

Whisper v6 app is built from the `feature/geth-1.8.1` branch in `status-react`, and connected to 2 Whisper v6-enabled bootnodes and with 4 contacts.
