### ISSUE TITLE
Set whisper minimum pow with config object

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#671]
# Problem

We have a patch that changes `DefaultMinimumPoW` https://github.com/status-im/status-go/blob/develop/_assets/patches/geth/0004-whisper-notifications.patch#L968-L969 . 

This is really unnecessary and can be done by using whisper config object https://github.com/status-im/status-go/blob/develop/vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/whisper.go#L104

# Acceptance Criteria

1. Minimum PoW is set with config and the changes to default Whisper config are removed from the patch.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 250.00
Contract address: [0x03124ccd9c2c06db11ca74cc85a1f8279fcbb029](https://etherscan.io/address/0x03124ccd9c2c06db11ca74cc85a1f8279fcbb029)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by adambabik** [comment]
The config should be passed in this place: https://github.com/status-im/status-go/blob/develop/geth/node/node.go#L165. Currently, we pass `nil`.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>
