### ISSUE TITLE
Create a bot that constantly pings a channel `#humans-need-not-apply`

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#686]
# Problem

Not enough messages in the test network (Ropsten).
1. For energy consumption tests we need a channel that always has messages.
2. For checking if the messages actually work we need a channel that always has messages.

# Implementation

Make a simple bot on top of `status-go` that sends a timestamp to `#humans-need-not-apply` channel.

Why this repo?
Basically, our patching of Geth makes it impossible to use `status-go` as a normal `dep` dependency.
Either (1) the whole process of patching should be repeated in the second (bot) repo or (2) we will add status-bot to this repo.
(1) seems like a simpler solution for me, so I'd rather go with that.

# Acceptance Criteria

1. The bot is implemented and deployed.

Part of: https://github.com/status-im/ideas/issues/83

**Comment by dshulyak** [comment]
there are no obstacles for writing a bot with upstream go-ethereum

**Comment by mandrigin** [comment]
yeah, you are right, I'll investigate that. it doesn't use jails or notifications or other features of Status

**Comment by mandrigin** [comment]
@dshulyak I took a glance at vanilla Geth. We might need some patches to be fully compatible to status-go messaging. So it is simpler to keep it here right now.
Maybe, we need a better readme for this repo explaining what is where.

**Comment by mandrigin** [comment]
Got blocked by https://github.com/status-im/status-go/issues/655, will fix it first...

**Comment by mandrigin** [comment]
https://github.com/mandrigin/status-go-bots — that's the repo

**Comment by mandrigin** [comment]
That was done in https://github.com/mandrigin/status-go-bots
