### ISSUE TITLE
Reduce mail server traffic

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#690]
# Problem

We have a significant network overhead from offline mailboxing. We want to reduce it as much as possible.

# Implementation

We want to send to a user only messages he or she didn't receive yet. We probably should extend Mail Server API.
The details should be discussed with @yenda .

# Acceptance Criteria

Offline mailboxing works stable, react side has an API to request only messages that haven't been received before.

# Future Steps

Use new API on RN side.

**Comment by dshulyak** [comment]
Would be good to have a more concrete description:
- how was it measured that offline mailboxing leads to a significant overhead? any numbers?
- any concrete ideas/direction for changing API, because at the moment it supports `from` and `to` fields

**Comment by dshulyak** [comment]
API is already available, all changes can be done on status-react side. I am closing this one, please open if there is a suggestion what we can do on mailserver/status-go side

**Comment by yenda** [comment]
I am waiting for the mailserver logs because it seems that the mailserver is dropping the peer when using the  from field in requestMessage

**Comment by dshulyak** [comment]
We always set defaults for from and to fields, now - 1 day and now

**Comment by dshulyak** [comment]
https://github.com/status-im/status-go/blob/develop/services/shhext/api.go#L57-L59

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>
