### ISSUE TITLE
Refactor JailCell interface so that Get returns a thread-safe value

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#691]
# Problem

Otto is not thread-safe by design. Therefore we've built a thrad-safe wrapper layer on top of it (https://github.com/status-im/status-go/blob/develop/geth/jail/internal/vm/vm.go). However, this layer isn't complete, as values retrieved by `JailCell.Get` will return an unsafe value that might call back into Otto, and cause race conditions (seen e.g. in https://github.com/status-im/status-go/blob/feature/geth-1.8.0/t/e2e/whisper/whisper_jail_test.go#L326, which prompted a quick hack, adding `GetObjectValue` in https://github.com/status-im/status-go/pull/689).

# Implementation

There are a few possible improvements that can be done to this code:
1. Make `JailCell.Get` return a wrapper value that is thread-safe.
1. According to https://github.com/status-im/status-go/pull/689#discussion_r169572131:
    1. remove `Get` methods from `common/types#JailCell`, and make tests use `*Cell`, where all our production code will use `JailCell`.
   1. alternatively, just make `*vm.VM` a private field instead of a part of the composition to hide all unwanted methods.

# Acceptance Criteria

- `GetObjectValue` is not present in the `JailCell` interface
- The access to the functionality provided by `GetObjectValue` is still thread-safe
- Tests pass when run with `-race` flag

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 560.00
Contract address: [0xfc4bfe077a30bb9400ab7e4ccf841a7b8471bad3](https://etherscan.io/address/0xfc4bfe077a30bb9400ab7e4ccf841a7b8471bad3)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
