### ISSUE TITLE
 Create generate-check makefile target

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#694]
# Problem

As a developer, I'd like that the CI build fails if I forgot to run `make generate`, in order to avoid inconsistent states being checked in to the repo.

# Implementation

In order to do this, we should implement a `make generate-check` Makefile target which runs similarly to `make vendor-check`, by running `make generate` on a temporary branch and checking if anything other than a timestamp changes, and fail if that's the case.
A new job should be added in `.travis.yml`.

# Acceptance Criteria

- [ ] There is a new documented `generate-check` makefile target.
- [ ] When executed, the new target fails if running `make generate` would create differences compared to the current branch, and succeed if not.
- [ ] Travis runs the new makefile target on each run, and fails the build if `make generate-check` fails

**Comment by canercidam** [comment]
`npm install web3` + `make generate` fails for me:
```
cp ./node_modules/web3/dist/web3.js ./static/scripts/web3.js
cp: cannot stat './node_modules/web3/dist/web3.js': No such file or directory
make: *** [Makefile:111: generate] Error 1
```
[e2e guide](https://github.com/status-im/status-go/blob/develop/t/e2e/README.md) probably needs updating as well.

**Comment by adambabik** [comment]
@canercidam We use a forked version of web3.js. After we moved some directories around, this whole flow broke. I think you should go to `_assets/` and run `npm install` there. Next, in `generate` target it should copy the file from `./_assets/node_modules/web3/dist/web3.js`.

**Comment by pedropombeiro** [comment]
@canercidam updated `develop` to fix the workflow. Thanks for signaling this.

**Comment by alexkohler** [comment]
> checking if anything other than a timestamp changes

@PombeirP What file(s) have potential to only have a timestamp change?

**Comment by pedropombeiro** [comment]
@alexkohler I don't have an answer to that, I'd need to run some experiences to be sure.

**Comment by alexkohler** [comment]
@PombeirP From what I saw in some testing I saw no timestamp only changes, just wanted to make sure I wasn't missing anything obvious - thanks!

**Comment by pedropombeiro** [comment]
Yeah, if there are only timestamp changes, we wouldn't care about that, only if the content of a file changes. Maybe it wasn't clear in my description above, but that's what I meant with it.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb2e33b0e96f09d69dc21fe7c86630346c2bd40d519d7a01cbacf0a4cd5dc5b9c](https://etherscan.io/tx/0xb2e33b0e96f09d69dc21fe7c86630346c2bd40d519d7a01cbacf0a4cd5dc5b9c)

**Comment by andytudhope** [comment]
@alexkohler are you still working on this? Have put up a bounty for you 😉

**Comment by alexkohler** [comment]
@andytudhope how nice! 😉 I have a branch in early stages but i’m currently working on another issue - if anyone else wants to pick this up before I get time to fix that branch up feel free!👍

**Comment by kishansagathiya** [comment]
https://github.com/status-im/status-go/pull/760 was closed because `make generate` was to be removed. Shouldn't this be closed?

**Comment by pedropombeiro** [comment]
Good catch @kishansagathiya, closing.
