### ISSUE TITLE
Whisper v6: Leverage new light mode in geth master

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#705]
# Problem

Currently light nodes forward messages from other nodes. We want to leverage the new `shh.lightclient` `WhisperConfig` flag to enable Whisper light mode to reduce resource consumption.

# Implementation

Upgrade vendored geth to include https://github.com/ethereum/go-ethereum/pull/16172/.
Call `MakeLightClient` if `WhisperConfig.LightClient` is true.

# Acceptance Criteria

TBD

# Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by adambabik** [comment]
@PombeirP is it still relevant?

**Comment by pedropombeiro** [comment]
@adambabik I believe so. I think this is something we'll want to test once we migrate to geth 1.8.3, where this functionality becomes available.

**Comment by sebastiandelgado** [comment]
Where do we get the version of our vendored geth? Is this issue ready to be worked on? Do we want to use whisper light for testing or is the flag meant to be used on statusd in production?

**Comment by pedropombeiro** [comment]
@sebastiandelgado we have a `make update-geth` that normally handles updating geth from the official repo. I think this GHI is not needed and we can close it though (I don't think I understood the changes at the official go-ethereum repo at the time I created this), since if we enable `lightClient` (which we do for the mobile app), `isP2P` will already be true and the messages will not be forwarded.
