### ISSUE TITLE
Rewrite how static peers are handled in params package

### ISSUE THREAD

**Issue by themue** [status-im/status-go#708]
Acceptance criteria:

- [x] Change naming from bootnodes to static peers
- [x] Provide a way to load static peers from a file or embedded file (currently only embedded file is supported)
- [x] Check if `genesisHash` is required in `staticpeers.json`; If not, get rid of it
- [x] It should say `staticpeers` instead of `bootnodes` in `staticpeers.json`
- [x] Check if we can assign static peers to p2p object directly instead of using `addPeer` (`addPeer` is called through `PopulateStaticPeers()` method)

**Comment by dshulyak** [comment]
Last item is done in https://github.com/status-im/status-go/pull/700

**Comment by themue** [comment]
@dshulyak Thx, will check the item when #700 is merged.

**Comment by themue** [comment]
Idea for static peers: maintain and embed them like today unless a flag says to overwrite this static by the content of a file.

**Comment by themue** [comment]
@dshulyak You meant #700 is covering the last topic, but sadly it is blocked. So how can I extract this according part optimally or are there too many dependencies?

**Comment by dshulyak** [comment]
that change is not really dependent on #700 PR, just several lines

1st is to assign our "bootnodes" to p2p static nodes https://github.com/dshulyak/status-go/blob/b407990303906357416a9aa6d506ebc092a919ff/geth/node/node.go#L120

and then remove https://github.com/status-im/status-go/blob/develop/geth/node/manager.go#L101-L106
