### ISSUE TITLE
A data race while closing a node

### ISSUE THREAD

**Issue by JekaMas** [status-im/status-go#709]
# Problem

We have a data race while stopping the node.
[data_race.txt](https://github.com/status-im/status-go/files/1763068/data_race.txt)
The patch with data race https://github.com/status-im/status-go/blob/develop/_assets/patches/geth/0016-fix-leveldb-issue.patch

# Implementation

The cause is in code (`github.com/ethereum/go-ethereum/les/handler.go` after all patches):
```go
for {
        select {
        case event := <-sub.Chan():
            if event == nil {
                return
            }

            switch event.Data.(type) {
            case downloader.StartEvent:
                pm.downloads.Add(1)
            case downloader.DoneEvent, downloader.FailedEvent:
                pm.downloads.Done()
            }
        }
    }
```
We add new tasks into wait group after it has been started. This cause the data race with

```go
pm.downloads.Wait()
```

# Acceptance Criteria

There is no data race in the patch.

@mandrigin

**Comment by mandrigin** [comment]
good catch 👍 
can you also provide steps to reproduce?

**Comment by mandrigin** [comment]
or can you check this branch: https://github.com/status-im/status-go/tree/igorm/sync-terminate?

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by JekaMas** [comment]
@mandrigin A nice fix! For me, it should work fine.
How to reproduce: it got this error once per 5 runs `go test -race -v -timeout 6000s ./t/e2e/whisper/whisper_jail_test.go -network=3`

**Comment by mandrigin** [comment]
@JekaMas when running this code I also see a lot of races like that
```
WARNING: DATA RACE
Read at 0x00c4202fc7b0 by goroutine 32:
  runtime.mapaccess1()
      /usr/local/go/src/runtime/hashmap.go:343 +0x0
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).nextRequest.func2()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:429 +0x157
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*requestDistributor).nextRequest()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/distributor.go:195 +0x30a
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*requestDistributor).loop()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/distributor.go:131 +0x9b

Previous write at 0x00c4202fc7b0 by goroutine 157:
  runtime.mapassign()
      /usr/local/go/src/runtime/hashmap.go:505 +0x0
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*lightFetcher).announce()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/fetcher.go:322 +0x11db
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.(*ProtocolManager).handle()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/handler.go:293 +0xaad
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les.NewProtocolManager.func1()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/les/handler.go:175 +0x325
  github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1()
      /Users/mandrigin/golang/src/github.com/status-im/status-go/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:344 +0x8b
```

Do you see them as well?

**Comment by JekaMas** [comment]
Nope, but according to the code it's a data race. For me, it looks like a deep rabbit hole...

How do you think maybe we need to run our tests with `race` flag at least once per week?
