### ISSUE TITLE
Use `go-ethereum/log` in status-go

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#717]
# Problem

We use our own `log` package in status-go. go-ethereum already has one pretty powerful log package.

# Acceptance Criteria

* `status-go/geth/log` is removed
* `go-ethereum/log` is used everywhere in status-go
* all the log messages are visible
* (potentially) we can configure different outputs and different levels for status-go and go-ethereum.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 700.00
Contract address: [0x00b31e2afec45951f7ddd815ab08b6ab0a83e266](https://etherscan.io/address/0x00b31e2afec45951f7ddd815ab08b6ab0a83e266)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by divan** [comment]
@mandrigin I'm still unsure we really need it. What will be the benefit of it except of having just one log package?

We still cosnidering `go-ethereum` as a dependency, i.e. codebase not fully owned by us. What if on next release, they change `log` package? What if initialization in the `geth` will be implemented in a way incompatible with ours (we pass log configuration trough `StartNode` parameters)?

And the most important question – what problem does it solve? Currently, we have working logging, without any visible problems, no?

Also, some discussions around logging here: https://github.com/status-im/status-go/issues/295

**Comment by mandrigin** [comment]
@divan the typical problem with our logging is on mobile devices which is very inconsistent and have some weird relationship with each other.

Examples: 
1. Some logging goes to a file (geth), some to stdout (status-go) on mobile devices;
2. `SetLogHandler` for status-go log package sets it for geth too, for some reason, but I'm still not sure how that works, because (1).
3. `we pass log configuration trough StartNode parameter`: that I'm not sure. Why then do we set a part of the logging config in our `SetLogHandler`? (see `status-go/geth/log.go:102`, `status-go/geth/node/manager.go:376`)

Less code to maintain, more obvious dependencies, less redundant code in status-go.
If they change the logging package, then that'd be a problem to solve.

**Comment by divan** [comment]
@mandrigin got it, thanks! The first example is actually pretty much a bug, and this definitely should solve it.

**Comment by alexkohler** [comment]
What should the structure of the logging be? Go-ethereum's logging framework supports key/value pairs for logging, would we want per package logging? (e.g. `logger := log.New("package", "geth/jail"`)

**Comment by mandrigin** [comment]
@alexkohler that would be neat! Maybe we can prefix it with `status-go` too, so we can filter that out easily later.

**Comment by alexkohler** [comment]
It seems like go-ethereum follows two paradigms. 
* They initialize their logger on an "as needed" basis. I.e. - loggers are initialized via `log.New` within function calls. 
* They add a `log.Logger` field on the struct, and its methods will log via that struct field.

Alternatively, we could also add a single (unexported) logging instance per package. We may be increasing our memory footprint, but may make per-package logging a little more convenient. What are your thoughts?

**Comment by mandrigin** [comment]
I personally would prefer to follow the per-struct approach that go-ethereum has. I think being consistent helps anyone who is familiar with status-go or go-ethereum to work on each other codebases.
