### ISSUE TITLE
Create a native wrapper for Android to measure energy consumption

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#726]
# Problem

Make a native wrapper to measure energy efficiency on an Android device.

# Implementation

The same functionality as https://github.com/mandrigin/status-go-n-wrapper/tree/master/ios/status-go-tester

1. Use status-go bindings
2. Create an account (or restore it if was created before)
3. Login
4. Create a filter to listen to `#humans-need-not-apply` channel on the Ropsten network.
5. Display the latest message on the main activity.

# Acceptance Criteria

That's how the iOS version looks like (pretty unfancy).
![img_1381](https://user-images.githubusercontent.com/466427/37215467-4bf80230-23b8-11e8-95f4-bc3e6456c327.PNG)

Part of https://github.com/status-im/ideas/issues/83

**Comment by dshulyak** [comment]
@mandrigin was it already created and stored in another repo? maybe we can close this one?

**Comment by mandrigin** [comment]
@dshulyak yep, it is in the bok
