### ISSUE TITLE
Events when mailserver disconnects or number of peers drops

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#728]
# Problem

Currently status-react has to rely on polling the `admin_peers` method to fetch the list of peers and check if the mailserver was disconnected or the number of peers dropped to 0.

A better solution would be for status-go to send a signal to the app or allow the app to register a callback function for these events.

# Implementation

There is already a few signals that are handled by status-react and can be checked for inspiration: `transaction.queued, transaction.failed, node.started, node.stopped,  module.initialized,  jail.signal`.

I propose the 2 signals `mailserver.disconnected` `peers.disconnected` unless you have a better name for it.

# Acceptance Criteria

Signals are sent or callbacks are called when the events occur

# Future Steps

Update status-go version in status-react
Ask @yenda to update status-react to use the callbacks

**Comment by dshulyak** [comment]
Do you need this if https://github.com/status-im/status-go/pull/700 will be merged and peers will be handled in status-go? 
I am bothering with that PR because I am reworking handling mail servers at the moment, also https://github.com/status-im/ideas/issues/92 will affect the way we manage mail servers and other peers.

**Comment by yenda** [comment]
@dshulyak yes it is not meant to be used for managing peers but to indicate to user if something went wrong

**Comment by pedropombeiro** [comment]
@yenda maybe if #700 is merged it is more a question of changing to a more descriptive name for the signal, such as `mailserver.unavailable`?

**Comment by dshulyak** [comment]
This issue should be resolved only when 700 PR is merged or when we will rework the way we connect with peers, as a part of https://github.com/status-im/ideas/issues/92 . The reason for it is that any solution that can be done at the moment will conflict with mentioned changes and will address this issue only partially (we can't distinguish mail server peers from regular whisper peers in status-go at the moment).

Feel free to remove blocking label of course if this urgent

**Comment by yenda** [comment]
Is there a signal already for all peers disconnected ? Is it distinguishable from offline node ?
