### ISSUE TITLE
Key persistence

### ISSUE THREAD

**Issue by yenda** [status-im/status-go#729]
# Problem

Currently symetric keys are not persisted on status-go side

# Scenarios

- restarting a node and login to the same account should restore previously existed symmetric keys

# Implementation

TBD.

# Acceptance Criteria

User can reuse a symKey with the symKeyID accross sessions

**Comment by feuGeneA** [comment]
From Slack:

> feuGene [15 days ago]
> first question where/how should it be stored?
> yenda [15 days ago]
> I don't know how the account whisper private key is stored but I would store the symkey id at the same place, assuming thats encrypted and safe

But the thing is, we don't currently store the account whisper private key anywhere.  Rather, we re-create it (seeded by the geth account private key) each time the geth account is selected for use.

A clear/straightforward solution to persisting symkeys from status-go isn't self-evident.

The only current persistence I can see is the geth account keystore, and that doesn't seem to lend itself to storing any additional data such as for these symkeys.  (I looked hard at using "child accounts" as a way to store whisper topics, an approach that @JekaMas had expressed interest in, but I found that child keys are not something you create, they are derivations of the master key of the HD wallet address; I think maybe we could persist a topic or symkey as the private key to seed a child derivation of the master key (and then ignore/don't use the addresse generated therefrom), but that seems awful cumbersome.)

Perhaps we could just persist the symkeys to some file, but I'm wary of that, as there doesn't seem to be a precedent for having status-go store any user-specific data, outside of what a geth wallet account stores.

The geth node doesn't store whisper topics/symkeys, so I'm thinking status-go shouldn't either.  Further, storing symkeys seems to be regarded as a dApp's responsibility (not that of the node or wallet) and I'm thinking that in this case status-react is such a dApp.  What's your take on this @yenda ?

If it really does make more sense to have the status-go side do the symkey persistence, I will need more input on how such storage should be implemented.

**Comment by JekaMas** [comment]
Could we expend `accounts/keystore/key.go` key type to store symmetric keys either?

**Comment by feuGeneA** [comment]
@JekaMas I was hoping to avoid a modification to go-ethereum, but I am open to that, if it is indeed necessary for us to persist keys from `status-go`.

It looks like we could add more data to the `Key struct` in `accounts/keystore/key.go`, just like we added additional data for the child/sub-accounts in our [0000-accounts-hd-keys.patch](https://github.com/status-im/status-go/blob/develop/_assets/patches/geth/0000-accounts-hd-keys.patch).  I would need to investigate how we should hook into it, whether by adding a handler for one or more RPC methods or C API entry points, or whether by modifying geth's `whisper.go` to utilize a persistent keystore rather than the current in-memory `Whisper.symKeys` property, or whatever else.

**Comment by JekaMas** [comment]
@feuGeneA I've talked with @mandrigin about the persistence of keys. At the moment we don't need to think about restoring account data. So we can use any solution we want.

If you want to use hd accounts, you should talk with @pilu. He's working on https://github.com/status-im/ideas/issues/94 and doing an investigation about using hd keys. We can make a call this week.

**Comment by adambabik** [comment]
Can we add some more scenarios to the description? I don't quite get what we mean by `across sessions`. E.g. restarting a node should keep the symmetric keys in Whisper? Logout and login to the same account should restore previously existed symmetric keys?

**Comment by gravityblast** [comment]
@yenda is this still an open issue? if it is, does the new protocol change something?

**Comment by yenda** [comment]
@pilu yes it's still open, the new protocol persist keys in clojure side for now but this would be better
