### ISSUE TITLE
Create status-go API to return a current revision

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#732]
# Problem

As a developer, I want to see the revision of status-go in Status. Currently, the UI part has no way to retrieve it.

# Implementation

See `statusd -version` command implementation

# Acceptance Criteria

* The API is added that returns the current revision as string.
* The API is exported when building via xgo

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 400.00
Contract address: [0x861c56fa0a55833d437596f3b55f0416509211fe](https://etherscan.io/address/0x861c56fa0a55833d437596f3b55f0416509211fe)
Network: Mainnet
Paid to: ovx
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by adambabik** [comment]
@mandrigin by revision you mean a git commit it was built from?

**Comment by mandrigin** [comment]
@adambabik yep

**Comment by adambabik** [comment]
@mandrigin one more thing, do you need it to be a binding or `web3_clientVersion` comamnd result is enough?

**Comment by mandrigin** [comment]
@adambabik if we make `web3_clientVersion` similar to how browsers' user agent strings are made then we can keep it.

**Comment by adambabik** [comment]
So, I have this output now:
```
{"jsonrpc":"2.0","id":1,"result":"StatusIM/v0.9.9-unstable/darwin-amd64/go1.10.1"}
```

which would be a string `StatusIM/v0.9.9-unstable/darwin-amd64/go1.10.1` when calling it directly in Go. Is it enough if we just add a git SHA like this: `StatusIM/v0.9.9-$GIT_SHA/darwin-amd64/go1.10.1`?

**Comment by mandrigin** [comment]
that would work for me and for the QA team, I think
