### ISSUE TITLE
Create an API method to notify status-go when app goes to background/restores from it

### ISSUE THREAD

**Issue by mandrigin** [status-im/status-go#734]
# Problem

We can't use energy-efficient networking when our app is in the foreground because we want messages to be sent/delivered as soon as possible. If we get a notification that the app went to the background state, we can decrease the network frequency or even pause the node (this is outscoped).

The scope of this issue is to implement a method that notifies about the app state changes, export and connect it to status-react.

# Acceptance Criteria

1. The method is implemented
2. There is a PR in status-react that implements the method on the UI part
 
# Notes

Discovered as a part of https://github.com/status-im/ideas/issues/83

**Comment by adambabik** [comment]
@mandrigin is it still in progress?

**Comment by mandrigin** [comment]
@adambabik nope, it is done and integrated and we use it in idea 83 already :)
closing the issue
