### ISSUE TITLE
Ethereum logger should discard messages earlier if level of handler is lower than message level

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#740]
# Problem

Ethereum logger always calls time.Now and gets a stack trace even if the message will be discarded later. It especially hurts if we will use discovery module, that module has a ton of log.Trace calls, which in idle state is about ~25% of cpu time used by a statusd process.

# Implementation

The problem is in this method https://github.com/ethereum/go-ethereum/blob/master/log/logger.go#L129-L142

Any call to ethereum logger should be a no-op if level of the message is higher than handler level.
It can be achieved by moving logic from logger.write to a handler or add some filtering based on handler level to the logger.write.

# Acceptance Criteria

No-op calls to logger shouldn't be expensive in terms of cpu or memory.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x26c11550cd149d8e4bd72091b6aae5d7e0488a60f1ace5a1af7bfa83e986b816](https://etherscan.io/tx/0x26c11550cd149d8e4bd72091b6aae5d7e0488a60f1ace5a1af7bfa83e986b816)

**Comment by dshulyak** [comment]
Just one detail, it is not worth to add a patch for this change. It should be either done in upstream or implemented without patch if possible
