### ISSUE TITLE
Switch to Go 1.10

### ISSUE THREAD

**Issue by divan** [status-im/status-go#746]
# Description

Go 1.10 has been released one month ago and it's a good moment to start using it.
https://golang.org/doc/go1.10

# Implementation

 - Update Ci configs, Dockerfiles and other build pipeline configs (if any) to use 1.10 Go version
 - Run all the tests to make sure there is no surprise

# Acceptance Criteria
 
 - TravisCI, Jenkins, Dockerfiles are updated to use the Go 1.10
 - Tests are passing as before
 - Bonus point would be to measure diffs for numbers: compilation speed, CPU/memory/GC stats, etc
 - Also worth exploring new build cache capabilities in Go 1.10 to speedup CI builds

# Future Steps

- Update Xgo images to use Go 1.10

**Comment by adambabik** [comment]
@divan is it finished?
