### ISSUE TITLE
It's impossible to deploy contract from DAPP

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#752]
# Problem

It's impossible to deploy contract from DAPP

status-go sends transactions signal with next fields
```
"{..,\"args\":{\"from\":\"0xe07..\",..\"input\":\"0x6060..\"},\"message_id\":\"\"}}"
```
 but we expect on status-react side `{... "data": "0x6060.." ...}`

https://status-im.slack.com/archives/C80EZUFLH/p1521709275000259
# Implementation

it should be `data` instead `input`

# Acceptance Criteria

It's possible to deploy contract from DAPP

**Comment by mandrigin** [comment]
@flexsurfer I can take a look at it today.

**Comment by mandrigin** [comment]
@flexsurfer can you, please, test with status-go from `fix/752-deploy-contract` and verify that it fixes your issue?

**Comment by flexsurfer** [comment]
@mandrigin fixed
