### ISSUE TITLE
Configure CodeClimate with a configuration file

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#759]
# Problem

Our current CodeClimate integration is far from being useful. It's too strict for the current code base and it does not have a configuration file that can be easily adjusted.

# Implementation

Explore a possibility to configure CodeClimate with a configuration file as described [here](https://docs.codeclimate.com/docs/advanced-configuration).

# Acceptance Criteria

1. There is a configuration file in the repository like `.codeclimate.yml`,
1. Selected configuration options and their values have comments if necessary. This is required for the core team and future contributors to be at the same page,
1. This configuration is actually used by CodeClimate checks (may require some changes by integration owner; let us know about it and we will do it).

# Notes

As we do not have any configuration file yet, it's ok to start with a [default checks for Go](https://docs.codeclimate.com/docs/advanced-configuration#section-language-specific-default-checks) and slightly modify checks' values.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 550.00
Contract address: [0xdfb2f9e63c0151102d869f30955e0c78c0edc69d](https://etherscan.io/address/0xdfb2f9e63c0151102d869f30955e0c78c0edc69d)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by gravityblast** [comment]
we can also check this as starting point given that it's used in one of the golang core repos:

https://github.com/golang/dep/blob/master/.codeclimate.yml

<blockquote><img src="https://avatars3.githubusercontent.com/u/4314092?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/golang/dep">golang/dep</a></strong></div><div>Go dependency management tool</div></blockquote>

**Comment by alexkohler** [comment]
@pilu One interesting thing about golang's configuration is that they do not appear to use any of the default checks (argument count, etc..) and rather appear to be using CodeClimate as a means to run golint, go vet, and gofmt, which are all already run by our `lint` make target
