### ISSUE TITLE
Improve command line option structure

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#761]
# Problem

The current `statusd` options list is a bit disorganized, and it will only get worse in the future if we don't take steps to improve the usability. One idea is to group options into logical areas, such as (not definitive or even extensive, we're open to suggestions):
- Node options
- Protocols (LES/SHH/Swarm)
- SHH options
- Metrics/profiling/stats
- Debugging

The standard `flag` package is not sufficiently advanced to support grouping, so we'd want to replace it with https://github.com/urfave/cli (and use [Subcommands categories](https://github.com/urfave/cli#subcommands-categories)).

Another problem is that we're using a dot (`.`) to separate the option name from the sub-option name, but we're not consistent everywhere. Take for instance:
```
  -shh
        Enable Whisper protocol
  -shh.firebaseauth string
        FCM Authorization Key used for sending Push Notifications
  -shh.lightclient
        Start with empty bloom filter, and don't forward messages
```
and compare with:
```
  -http
        Enable HTTP RPC endpoint
  -httphost string
        HTTP RPC host of the listening socket (default "127.0.0.1")
  -httpport int
        HTTP RPC server's listening port (default 8545)
```
That should be `-http.host` and `-http.port` for the sake of consistency.

# Implementation

- [ ] Replace `flag` package with https://github.com/urfave/cli.
- [ ] Group options logically
- [ ] Fix inconsistent usage of dot to separate sub-options.
 
What needs further specifying and investigating.

# Acceptance Criteria

- [ ] The `statusd --help` usage screen clearly shows options grouped in to logical groups.
- [ ] Sub-options that configure main groups of functionality have a dot in the name to indicate the hierarchy (e.g. `-pprof` and `-pprof.port`).
- [ ] Options are interpreted in the same way as before.

Bonus points for color usage in the console ;-)

**Comment by dshulyak** [comment]
> The standard flag package is not sufficiently advanced to support grouping, so we'd want to replace it with https://github.com/urfave/cli (and use Subcommands categories).

you mean such grouping?

```
WHISPER (EXPERIMENTAL) OPTIONS:
  --shh                       Enable Whisper
  --shh.maxmessagesize value  Max message size accepted (default: 1048576)
  --shh.pow value             Minimum POW accepted (default: 0.2)
  
DEPRECATED OPTIONS:
  --fast   Enable fast syncing through state downloads
  --light  Enable light client mode```

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x754560f45b750f8405ab940b55886e569f3a3104a339c489e5f47aec27a2e9d8](https://etherscan.io/tx/0x754560f45b750f8405ab940b55886e569f3a3104a339c489e5f47aec27a2e9d8)

**Comment by pedropombeiro** [comment]
@dshulyak Exactly. I know we can achieve the same by e.g. changing the call to `flag.PrintDefaults()` so it might not seem like a sufficient reason to switch libraries, but at the same time, it also depends on which approach will result in the cleanest code and how extensible it will end up being for the future.

**Comment by pedropombeiro** [comment]
Closing as duplicate of an updated https://github.com/status-im/status-go/issues/614
