### ISSUE TITLE
All configuration that is required by tests should be read without go-bindata

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#765]
# Problem

In the current codebase if you want to use different keys (or any other configuration) for tests it is required to place them at a certain path in static folder, bundle them with go-bindata and only then run tests.
This is simply unnecessary and I consider this workflow as a chore.

# Implementation

Instead, we can simply read those keys from files.
Implementation should use simple utils to load a configuration from a specified location without relying on go-bindata or any other binary bundler.

# Acceptance Criteria

It is possible to run tests by specifying a path to a configuration (private keys) without any pre-conditions.
The genesis for status chain can be simply hardcoded for e2e tests.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa88446f4af8af0e1e2369f4fc81061ce2691a0e6eb663eedc2c7f3a482400d03](https://etherscan.io/tx/0xa88446f4af8af0e1e2369f4fc81061ce2691a0e6eb663eedc2c7f3a482400d03)

**Comment by status-open-bounty** [comment]
Balance: 0 ETH
Tokens: SNT: 1100.00
Contract address: [0xd90612db2c3c419fb4e7fffa65a04a0f05790521](https://etherscan.io/address/0xd90612db2c3c419fb4e7fffa65a04a0f05790521)
Network: Mainnet
Paid to: kishansagathiya
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by kishansagathiya** [comment]
I am planning to take up this task. Is this still relevant/required?

**Comment by pedropombeiro** [comment]
@kishansagathiya looks like it is still relevant, judging by the `static/config` folder.

**Comment by kishansagathiya** [comment]
@PombeirP I have attempted a PR(https://github.com/status-im/status-go/pull/1158) for this. Please review whenever free.

**Comment by pablanopete** [comment]
@kishansagathiya Thanks so much for working on this issue! Right now we're handling SOB payments out of band, could you either email me with an appropriate ERC-20 compatible wallet (like status) at chris.hutchinson@status.im or drop it in here at your convenience so I can help handle this payout thanks for your contributions to status!

**Comment by kishansagathiya** [comment]
@pablanopete emailed you

**Comment by pablanopete** [comment]
Payment sent @kishansagathiya
