### ISSUE TITLE
Remove deprecated Parse method in library.go

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#768]
# Problem

Once https://github.com/status-im/status-react/issues/3689 is closed, this method will no longer be used, so should be removed from the codebase.

**Comment by dshulyak** [comment]
Is it only about Parse method of status react is not using jail anymore? I saw some discussion but i may miss context

**Comment by pedropombeiro** [comment]
Hmm, it's been a while, I don't remember the status-react details anymore.

**Comment by divan** [comment]
Closed in https://github.com/status-im/status-go/pull/1106
