### ISSUE TITLE
New contract handler is not called after contract deployment

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#784]
Problem

```
var simplestorageContract = web3.eth.contract([{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]);
var simplestorage = simplestorageContract.new(
   {
     from: web3.eth.accounts[0], 
     data: '0x6060604052341561000f57600080fd5b60d38061001d6000396000f3006060604052600436106049576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806360fe47b114604e5780636d4ce63c14606e575b600080fd5b3415605857600080fd5b606c60048080359060200190919050506094565b005b3415607857600080fd5b607e609e565b6040518082815260200191505060405180910390f35b8060008190555050565b600080549050905600a165627a7a7230582087e84161fdd2e7143a7ef1adc914230c9751de6d8abb28fce70837c6d45694c90029', 
     gas: '100000'
   }, function (e, contract){
    console.log(e, contract);
    if (typeof contract.address !== 'undefined') {
         console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
    }
 })
```

 Implementation

`function (e, contract){` should be called with `contract.address` after contract will be mined

# UPDATE
I found a workaround, how to get transaction receipt, but contract deployed wrong, there is no contractAddress

**Comment by mandrigin** [comment]
yeah, I see that it is being called, but `contract.address` is `undefined`...

**Comment by flexsurfer** [comment]
@mandrigin that's right it should be called twice , once without address and with transaction hash and once with address after contract is mined

**Comment by mandrigin** [comment]
@flexsurfer gotcha! let me try debugging that...

**Comment by flexsurfer** [comment]
@mandrigin looks like it's a known issue in web3 and we need to call `web3.eth.getTransactionReceipt(hashString [, callback])` in the loop

**Comment by flexsurfer** [comment]
Workaround https://github.com/status-im/hackathon/blob/master/submissions/Dr.%20WeTrust/public/bot/bot.js#L581 


<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/hackathon">status-im/hackathon</a></strong></div><div>hackathon - Status API Hackathon</div></blockquote>

**Comment by mandrigin** [comment]
closing because that is a known issue

**Comment by flexsurfer** [comment]
workaround doesn't work https://ethereum.stackexchange.com/a/32117

<blockquote><img src="https://cdn.sstatic.net/Sites/ethereum/img/apple-touch-icon@2.png?v=fcf6615497f4" width="48" align="right"><div><strong><a href="https://ethereum.stackexchange.com/questions/12051/transaction-receipt-has-contractaddress-as-null/32117">Transaction receipt has contractAddress as null</a></strong></div><div>I see that my transaction is mined. I am trying to store some data into a struct. The mining is successful, however, in the transaction receipt i see that the contract address is null. Is that an e...</div></blockquote>

**Comment by flexsurfer** [comment]
```
 {:blockHash 0x3fac40290e111a91080b9f2e0554a832579458c36a470fcb568cd84f745e2c4a, 
:blockNumber 2968141,
 :contractAddress nil, 
:cumulativeGasUsed 4175925,
 :from 0x794fe5d2b1abd423f0e0f12ba2fbb26d3b1799bf,
 :gasUsed 34568,
 :logs #js [], 
:logsBloom 0x0000000000000000000000000000000,
 :transactionHash 0x026ebda9701f8c29d0eae3702c4e09db5db29951390b64cf54d3faf6b965f029, 
:transactionIndex 16} 
````

**:contractAddress is  null**

**Comment by flexsurfer** [comment]
https://ropsten.etherscan.io/tx/0xf03f47f60cdf49744aa5ba60de5914f243830ec18c1bb8d8b448d1035395ec41

as you can see contract deployed wrong `To:` should be contract address but it's 0x0000000000000000000000000000000000000000

i checked in metamask and it deployed correct https://ropsten.etherscan.io/tx/0xaa62941d44fb76df033ddd7f276437a9c96a23251c748f28f427fd716e99b833

**Comment by dshulyak** [comment]
forgot to close it with https://github.com/status-im/status-go/pull/807
