### ISSUE TITLE
Remove evictionLoop from transactions/queue

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#793]
# Problem

This periodical check is unnecessary https://github.com/status-im/status-go/blob/develop/geth/transactions/queue/queue.go#L111-L112.
And also it adds a non-negligible amount of contention (~10% of blocking time is wasted in this ticker).

# Implementation

Transactions should be queued up to a certain limit (50 is enough). After that limit is reached - return an error to a user that previous transactions must be discarded or completed.

# Acceptance Criteria

An implementation described above + unit tests, and removal of evictionLoop from the queue.

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by mandrigin** [comment]
@dshulyak I'd also note that it would be nice to have this limit to come from the caller side together with the node config.
So it is up to a caller (who has access to all the system information, etc) to figure out this limit.
We can have a default of 50 though.

**Comment by dshulyak** [comment]
I will close it cause it was removed in https://github.com/status-im/status-go/pull/805
