### ISSUE TITLE
Simplify node.Manager

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go#797]
# Problem

NodeManager does not manage multiple nodes, change its name to something more appropriate.
Rename methods indicating there is only support for one node: StartNode -> Start, StopNode -> Stop etc.

# Implementation

#### Interface proposal
```go
type StatusNode interface {
	// previously StartNode
	Start(config *params.NodeConfig) error
	// previously StopNode
	Stop() error
	// previously IsNodeRunning
	IsRunning() bool 				
	// previously NodeConfig			
	Config() (*params.NodeConfig, error)
	// previously EnsureSync
	Sync(ctx context.Context) error
	// previously Node
	GethNode() (*node.Node, error)
	// Previously AddPeer
	AddPeer(url string) error
	// Previously PeerCount
	PeerCount() int
        // ResetChainData
        ResetChainData()
}

```

#### Other methods

- `LightEthereumService() (*les.LightEthereum, error)`
	Used   		: For syncing on `node.Manager.EnsureSync` ( which is exported to API) and `t/utils/utils.go::EnsureNodeSync` (they have really similar logic)
	Action 		: **Try merging logic on `node.ensureNodeSync` and `t/utils/utils.go` so LightEthereumService does not need to be exported.**

- `WhisperService() (*whisper.Whisper, error)`
	Used   		: MailService
	Depends on 	: node.GethNode()
	Action 		: **Evaluate if can be moved to the backend**

- `AccountManager() (*accounts.Manager, error)`
	Used   : accounts package + lib/library_test_utils.go
	Depends on 	: node.GethNode()
	Action 		: **Evaluate if can be moved to accounts package**

- `AccountKeyStore() (*keystore.KeyStore, error)`
	Used   : accounts package
	Depends on 	: node.GethNode()
	Action 		: **Evaluate if can be moved to accounts package**

- `RPCClient() *rpc.Client`
	Used   		: jail package / transactions package
	Depends on 	: rpc package + node.GethNode()
	Action 		: **Evaluate if can be moved to the backend**

#### Unused methods / to be removed:

- PopulateStaticPeers
- ReconnectStaticPeers
- removeStaticPeers
- removePeer

# Acceptance Criteria

Rules for the future PR to be accepted.

**Comment by themue** [comment]
Interface proposal looks good so far. Could you describe handling of `LightEthereumService()` a bit more? Where (package) do you want to merge it? IMHO it's also supported to keep symmetry with `WhisperService()`.

**Comment by gravityblast** [comment]
one simple thing following https://golang.org/doc/effective_go.html#Getters, I would use `Node()` instead of `GetNode()`

<blockquote><div><strong><a href="https://golang.org/doc/effective_go.html#Getters">Effective Go - The Go Programming Language</a></strong></div></blockquote>

**Comment by adriacidre** [comment]
@themue Yep, `LightEthereumService` is only used on blockchain synchronization happening on [node.ensureSync](https://github.com/status-im/status-go/blob/develop/geth/node/manager.go#L391) and [t/utils/utils.go](https://github.com/status-im/status-go/blob/develop/t/utils/utils.go). 

The code on both places look really similar, I think I'll be able to merge both inside `node.Manager::Sync` method, so `LightEthereumService` will be only used inside `node.Manager` so it doesn't need to be exposed as a public method.

**Comment by adriacidre** [comment]
@pilu is `GethNode` not `GetNode` :) It will be returning the underlying `geth.Node`, is kinda confusing at the moment as you have `node.Node` and `geth.Node`

**Comment by gravityblast** [comment]
Sorry @adriacidre  fault!  I think I'm tired testing my changes :)
