### ISSUE TITLE
Add real-world transactions tests that are using simulated backend

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#812]
# Problem

Recently, lots of issues were discovered with the way we are handling transactions.
Partly, it happened because we don't have tests that are confirming that funds are transferred, the contract is created or required state transition happened. We are only checking that transaction was sent to the network.

# Implementation

Our tests should wait till the state will be committed on the chain and verify that result of such transition is expected.
The easiest and fastest way to implement it would be to use simulated backend. It provides a testbed without running pow or poa miners.

I suggest to implement following tests:
- regular eth transfer
- contract state transition (for example https://github.com/ethereum/go-ethereum/blob/master/contracts/ens/contract/ENS.sol#L57)

# Acceptance Criteria

New tests are implemented and passing a CI

<blockquote><img src="https://avatars3.githubusercontent.com/u/6250754?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>

**Comment by mandrigin** [comment]
@dshulyak can you remove "contact creation" from this list since you already added it?

**Comment by dshulyak** [comment]
@mandrigin ok, i just added it for "completeness"

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1770dfb920f63b2d5f2d2d95891ec8f22c510d7529cf6f1531b364c15a3134b6](https://etherscan.io/tx/0x1770dfb920f63b2d5f2d2d95891ec8f22c510d7529cf6f1531b364c15a3134b6)

**Comment by sebastiandelgado** [comment]
@dshulyak A couple questions for more context on this:

What do you mean specifically by  'simulated backend'? As I understand it we would be mocking on-chain state so that we can test confirming that the funds are transferred. Would this simulated backend be more than a set of mocked up RPC calls? Maybe I'm missing the point with this question, so let me know if theres something I should be reading to figure this out.

Are there other examples of this in status-go or other external repos so I can get better context?

**Comment by dshulyak** [comment]
There is such thing in go-ethereum codebase as simulated backend. We have one example in transactor tests. Basically it mocks only the consensus part, allowing users to commit block whenever they want.

**Comment by pablanopete** [comment]
@dshulyak is this issue still bounty-able once we start adding new bounties?
