### ISSUE TITLE
make lint not running `megacheck` linter inside travis

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go#817]
# Problem

`gometalinter` is not running `megacheck` linter inside travis.

By running `make lint` locally you can force `megacheck` to break lint command,
```
$ time make lint
lint
geth/transactions/transactor.go:44:1:warning: unused is unused (deadcode)
geth/jail/doc.go:1:1:warning: package comment should be of the form "Package jail ..." (golint)
geth/transactions/transactor.go:44:6:warning: func unused is unused (U1000) (megacheck)
make: *** [lint] Error 1
make lint  88.81s user 34.33s system 310% cpu 39.653 total
```
however, when you run the same command inside travis the result is:
```
$ make lint
lint
geth/transactions/transactor.go:44:1:warning: unused is unused (deadcode)
make: *** [lint] Error 1
```

# Implementation

gometalinter is being installed on [Makefile](https://github.com/status-im/status-go/blob/develop/Makefile#L149) and it's being called from [.travis.yml](https://github.com/status-im/status-go/blob/develop/.travis.yml#L16).

# Acceptance Criteria

A `megacheck` linter error breaks the build on travis-ci

**Comment by adambabik** [comment]
In `.gometalinter.json`, `megacheck` is enabled so it should be run in Travis. Why do you think it is not?

**Comment by adriacidre** [comment]
Forced [a build](https://travis-ci.org/status-im/status-go/jobs/364639468#L526) with an `unused` method on it [like this](https://github.com/status-im/status-go/commit/e29ca3bba4e641b3fd85dbd79bb26a2aa6e71549#diff-29fcb2ce584c110efe9121cf82ec3ea4L43):
```
+func unused() {
+	println("unused")
+}
```


and as it results on:
```
$ make lint
lint
geth/transactions/transactor.go:44:1:warning: unused is unused (deadcode)
make: *** [lint] Error 1
```

whille on a local environment 
```
$ make lint
lint
geth/transactions/transactor.go:44:1:warning: unused is unused (deadcode)
geth/transactions/transactor.go:44:6:warning: func unused is unused (U1000) (megacheck)
make: *** [lint] Error 1
```

**Comment by adambabik** [comment]
Hm, that's pretty interesting. I wonder if we force `lint` target to run `gometalinter` like this: `gometalinter --config=.gometalinter.json ./...` and get the same results.

**Comment by adriacidre** [comment]
Yep, already tried, I can find the build if needed

**Comment by alexkohler** [comment]
I can't reproduce this: https://travis-ci.org/status-im/status-go/jobs/365191922 (I upped the gometalinter deadline on this branch, but that shouldn't make a difference I wouldn't think)

<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/jobs/365191922">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by adriacidre** [comment]
Hey @alexkohler, 

So, on your build the error looks like is:
```
$ make lint
lint
geth/transactions/transactor.go:28:1:warning: unused is unused (deadcode)
make: *** [lint] Error 1
```
this is correct, and the is an error produced by [deadcode linter](https://github.com/tsenart/deadcode). 

However, if you run the same `make lint` command on your local environment you'll see this `deadcode` error plus another one showing up from [megacheck linter](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck):
```
geth/transactions/transactor.go:44:6:warning: func unused is unused (U1000) (megacheck)
```

the problem, is we have some builds passing when `megacheck` should be detecting errors and breaking the build.

**Comment by alexkohler** [comment]
Ahhh, misunderstood the issue - thank you!

**Comment by alexkohler** [comment]
@adriacidre This appears to be a memory issue:

https://travis-ci.org/status-im/status-go/jobs/365635928
```
DEBUG: [Apr 12 14:38:26.093] [megacheck.5]: warning: /home/travis/gopath/bin/megacheck returned signal: killed: 
DEBUG: [Apr 12 14:38:26.094] [megacheck.5]: megacheck hits 0: ^(?P<path>.*?\.go):(?P<line>\d+):(?P<col>\d+):\s*(?P<message>.*)$
DEBUG: [Apr 12 14:38:26.094] [megacheck.5]: megacheck linter took 1m6.966603318s
```


https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error
> This is usually caused by the script or one of the programs it runs exhausting the memory available in the build sandbox, which is currently 3GB. Plus, there are two cores available, bursted.




<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/jobs/365635928">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error">Common Build Problems - Travis CI</a></strong></div></blockquote>

**Comment by adriacidre** [comment]
Good finding @alexkohler, I saw [this suggestion](https://github.com/travis-ci/travis-ci/issues/4192#issuecomment-161800452), I guess we could try increasing the stack size for example:

```
 before_install:
    ulimit -s 1082768
```

**Comment by alexkohler** [comment]
@adriacidre I'll give that a try :+1:

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 450.00
Contract address: [0x030ba2631176e7d0c930e4a2068c9d48a930f019](https://etherscan.io/address/0x030ba2631176e7d0c930e4a2068c9d48a930f019)
Network: Mainnet
Paid to: alexkohler
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
