### ISSUE TITLE
Implement Push Notification server with support for Gorush

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go#847]
# Problem

As part of https://github.com/status-im/status-go/issues/846, we need a program similar to `statusd` which will implement a "PN server mode", which will accept a `--pndispatcher <URL>` flag, where URL is the address of a configured [gorush gRPC endpoint](https://github.com/appleboy/gorush#run-grpc-service).

# Implementation

- [ ] Process flag in command line;
- [ ] Implement a class that makes use of gRPC to send a PN request to gorush.

# Acceptance Criteria

The new functionality is tested to successfully send a PN to a device through gorush.

# Notes

https://github.com/status-im/status-cluster/issues/75 is a prerequisite. Need a configured gorush instance running in the cloud.

# Future Steps

TBD

**Comment by dshulyak** [comment]
What are the pre-requisites for this PN server? Whisper node? Why it has to be built into statusd?
