### ISSUE TITLE
Solve Otto VM Halting Problem

### ISSUE THREAD

**Issue by jarradh** [status-im/status-go#85]
As referenced here status-im/status-react#686 we currently have no solution to 
https://github.com/robertkrimen/otto#halting-problem

**Comment by farazdagi** [comment]
At first I was like "wtf, solving [the Halting Problem](https://en.wikipedia.org/wiki/Halting_problem)"? But fortunately all that is required is to stop executing long running 3rd party scripts. Which is kind of trivial, of course.

**Comment by farazdagi** [comment]
Proposed PR slows as a hell Jail commands on Android (at least). We need to resolve this.

**Comment by farazdagi** [comment]
will be tackled as a separate issue https://github.com/status-im/status-go/issues/98 (since code has already been merged to dev, and new PR is required anyway).
