### ISSUE TITLE
Move Whisper request message method to shhext space

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#850]
# Problem

As `shh_requestMessages` is a non-standard method, it should not be a part of `shh` namespace but rather `shhext` that is already defined.

# Implementation

Move `shh_requestMessages` to `shhext_requestMessages`.

# Acceptance Criteria

1. The current tests work,
2. Offline messaging works.

**Comment by themue** [comment]
Branch https://github.com/status-im/status-go/tree/issue-850/move-whisper-request

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>
