### ISSUE TITLE
Simplify Post() implementation in sshext

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#853]
# Problem

https://github.com/ethereum/go-ethereum/pull/16495 got merged recently and `shh_post` returns a hash of the envelope instead of boolean now. 

# Implementation

Two possible solutions.

### Remove `shhext_post`

Remove `shhext_post` and patch the original `shh_post` with a tracker. This may require patching web3.js as well.

### Simplify `shhext_post`

Keep `shhext_post` but simplify its implementation to call `shh_post` internally. The implementation will just keep the tracker.

# Acceptance Criteria

* messaging works as expected,
* all existing tests related to `shhext_post` pass.

# Notes

Blocked until Geth 1.8.5 is released.

**Comment by dshulyak** [comment]
shh_post should be patched now instead of using our namespace (shhext) for post

**Comment by adambabik** [comment]
What will be changed in the patch? Just addition of events?

**Comment by dshulyak** [comment]
Also tracker will have to be added to original shh_post.

**Comment by dshulyak** [comment]
> Keep shhext_post but simplify its implementation to call shh_post internally. The implementation will just keep the tracker.

didn't notice this part initially.
you are right that we can keep shhext_post instead of adding tracker to shh_post.

**Comment by dshulyak** [comment]
Unblocking as 1.8.5 got released this morning 😄
