### ISSUE TITLE
Get rid of `/geth` folder

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go#856]
# Problem

A big part of the code is located on `/geth` folder. This doesn't make sense anymore and its sub-packages should be moved to `/`.

# Implementation

Move all `/geth` packages to `/`

# Acceptance Criteria

- Geth folder does not exist
- Pull request is accepted
- CI passes

# Notes

Try to use `git mv` so the git history on moved files is preserved.

**Comment by dshulyak** [comment]
It seems that now is the right time to do this move. There is only a few pending PRs.
So I propose to make a git mv after I land update to geth 1.8.4 https://github.com/status-im/status-go/pull/854

**Comment by pedropombeiro** [comment]
@adriacidre we can remove the `blocked` label now, right?

**Comment by adriacidre** [comment]
@PombeirP yep I think so, i'll remove it now
