### ISSUE TITLE
Wallet sync has not started when user switched from Ropsten with RPC to Ropsten / Mainnet

### ISSUE THREAD

**Issue by lukaszfryc** [status-im/status-go#860]
# Problem

Wallet sync has not started when a user switched from Ropsten with RPC to Ropsten or Mainnet. 

Additional info:
- `currentBlock` was 0
- `eth_syncing` false
- `eth_blockNumber` 0

# Acceptance Criteria

- Wallet is synced after switching network

**Comment by dshulyak** [comment]
This is expected. There are no peers with light server in ropsten cluster
config. Also cht are a bit outdated, so better to try it again after
upgrade to 1.8.5

**Comment by asemiankevich** [comment]
@dshulyak i have updated the issue, would you mind to health-check Mainnet too? it is not syncing as well

**Comment by dshulyak** [comment]
With mainnet there is the same problem as with ropsten. All peers that we have in our current config are providing only shh/6 capability.

**Comment by dshulyak** [comment]
One interesting note is it could be that we run out of light servers connections in mainnet:

TRACE[04-26|08:20:08] Failed proto handshake                   id=71bb01b58165e326 addr=51.15.85.243:30303 conn=staticdial err="too many peers"
TRACE[04-26|08:20:08] Setting up connection failed             id=71bb01b58165e326 err="too many peers"

cc @adambabik

**Comment by mandrigin** [comment]
@dshulyak so that is the cluster issue, right?
