### ISSUE TITLE
It should be possible to change gas and gas price for queued transactions

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#881]
# Problem

It's not possible to change gas and gas prise for queued transactions

**Comment by divan** [comment]
Could you provide more information? Why is this needed?

**Comment by flexsurfer** [comment]
As a user, i want to be able to change gas and gas price for any tx ,so i can take control on it, and don't want to use default values

**Comment by dshulyak** [comment]
@flexsurfer are you saying that it is not possible to overwrite default gas and gas price for transactions that are sent to status-go first time or for transactions that are already pending but not yet signed?

if it is the latter - maybe it is possible to remove old one and resubmit new with updated gas and gas price?

**Comment by flexsurfer** [comment]
yes latter, so if a user doesn't change tx we just sign it, if he wants to change we discard pending tx and create and sign a new one?

**Comment by dshulyak** [comment]
sounds good to me, also before tx is signed we could notify the user that gas price changed and if he wants it we will use lower/higher price

the main point is that we probably can do it without additional binding for update

also, if gas or gas price is nil in args that are sent by status react - status-go will use defaults when a transaction is actually signed, but relying on that could be tricky

**Comment by dshulyak** [comment]
@flexsurfer so wdyt? do we need a new binding for an update or it can be done with discard/create?

**Comment by flexsurfer** [comment]
@dshulyak let's try first with discard/create, if it will work fine, i'll close this issue

**Comment by flexsurfer** [comment]
ok we can't discard transaction, because in that case callback with the error will be called on dapp side, so we need changes in interface

**Comment by adriacidre** [comment]
status-go side has been delivered on https://github.com/status-im/status-go/pull/1000.

Closing this issue as `status-react` missing part is been tracked on https://github.com/status-im/status-react/issues/4065
