### ISSUE TITLE
e2e jail tests on public network are failing with timeout

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#891]
see https://travis-ci.org/status-im/status-go/jobs/373933131

<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/jobs/373933131">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by dshulyak** [comment]
https://travis-ci.org/status-im/status-go/jobs/375806808

<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/jobs/375806808">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
hmm, why only jail tests...

**Comment by dshulyak** [comment]
> hmm, why only jail tests...

i think that because they are first in list that are waiting for blockchain to sync

**Comment by pedropombeiro** [comment]
One thing I don't like about Travis CI is that the links you get don't preserve the actual failed build, they get overwritten by any following builds. So now it's impossible to tell what the issue we're trying to fix is (unless we manage to reproduce it again).

**Comment by pedropombeiro** [comment]
Closing as jail code has been removed.
