### ISSUE TITLE
Whitelist of web3 methods

### ISSUE THREAD

**Issue by flexsurfer** [status-im/status-go#912]
# Problem

For example currently we allow dapps to use all `shh_` methods, but the use of some of those methods can be bad. For example dapps can set the min PoW with `web3.shh.setMinPoW(1)` and users no longer receive messages.

**Comment by sebastiandelgado** [comment]
Now that #993 is merged, are we ok to close this issue or are there unfinished parts?

**Comment by adambabik** [comment]
Consider it done :)
