### ISSUE TITLE
Use the same static nodes/bootnodes for ropsten & mainnet

### ISSUE THREAD

**Issue by cammellos** [status-im/status-go#918]
# Problem

At the moment whisper messages are (mostly) isolated by network id. 

The whisper protocol does not guarantee any isolation, so it would be trivial for someone to publish messages/transaction from a different network and those being relayed to mainnet.

# Solution

After a discussion we have then decided to have relay whisper messages from different network and have a single whisper cluster, at least for ropsten and mainnet.

We would like to enable this now so we can better prepare for the beta launch.

We decided to keep rinkeby isolated as we run CI and it would add unnecessary overhead.

After this change some things will have to be addressed on the status-react side, namely transaction, in order to make sure that the user understand whether a request is coming from mainnet or different networks. https://github.com/status-im/status-react/issues/4171

**Comment by oskarth** [comment]
FYI @adambabik @jakubgs (probably discussed already but just to make sure)
