### ISSUE TITLE
Better way to detect flaky peers

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#924]
Impact: Reliability

Effort: Medium

**Comment by oskarth** [comment]
Unclear to me if https://github.com/status-im/status-go/pull/917 completely solves https://github.com/status-im/status-react/issues/4139, or if there's more work needed here. Capturing it in case.

cc @dshulyak

**Comment by pedropombeiro** [comment]
Should this be closed?

**Comment by oskarth** [comment]
Marked as done so yeah probably, don't know why it didn't auto close
