### ISSUE TITLE
Add new in-app metrics

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#925]
Timeline: Basic metrics Before RC, the rest after
Impact: HA, reliability, uptime
Effort: Medium

# Problem

We need an efficient way to collect metrics. `go-ethereum` has a package `metrics` that collects various low-level data already ([more details](https://github.com/ethereum/go-ethereum/wiki/Metrics-and-Monitoring)). 

We need a few more that should be added before RC in order to have an ability to monitor the cluster effectively.

# Solution

The general idea is to use only `metrics` package from `go-ethereum` and export them to Prometheus format using Prometheus exporter run as a separate Docker container. The metrics from `metrics` package can be retrieved using `debug_metrics` RPC call.

1. Clean up `metrics` package in `status-go`:
1.1. Rewrite `metrics/node` to use `metrics` package from `go-ethereum` and expose the number of connected peers and `maxPeers` value,
1.2. Rewrite `metrics/whisper` to use `metrics` package from `go-ethereum` and expose number of envelopes and the envelopes volume.
1. Expose metrics with the table size of Discovery V5 (geth patch needed).

**Comment by oskarth** [comment]
@adambabik @dshulyak What would basic metrics look like? How would this be consumed/used?

**Comment by adambabik** [comment]
1. The number of peers. Each server node should report of `maxPeers` and currently connected peers so that we know the cluster max and free capacity,
2. The number of incoming Whisper messages for spam detection and product usage metrics,
3. Size of the bootnode Discovery table + peer liveness in that table (or something smarter to monitor the health of the bootnodes).

**Comment by adambabik** [comment]
Note: it's important that these metrics are easily collected. It's better to use pull model where each individual node has no idea about where to send metrics but exposes them through a port.

Ethereum code exposes some metrics in its format. We also have some metrics exposes with Prometheus. It may be beneficial to unify them or write some bridge between them.
