### ISSUE TITLE
Jenkins job running status-scale tests

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#927]
Impact: HA, reliability

Effort: Medium

We need a Jenkins job that can run `status-scale` tests periodically (e.g. daily) so that we are confident that nothing got broken along the way.

Please take a look at https://github.com/status-im/status-scale/ for how to run these tests.

**Comment by adriacidre** [comment]
Some use cases for status-scale to be useful for CI:

1. to test behavior when **network is broken** in some way (for instance we can drop not 100% of traffic but 5% on an individual link) and verify that in general messaging is still 100% reliable

2. when **metrics need to be collected**. we can actually simulate real workload and collect p2p traffic and verify that it is below certain threshold 

3. also we briefly discussed **upgrades testing** using status-scale. it is possible to deploy cluster from multiple images and verify that they can interconnect and operate normally
