### ISSUE TITLE
Extensive P2P tests

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#928]
*Timeline*: After RC
*Impact*: HA, reliability
*Effort*: High

The scenarios should be inspired by the real world. The general idea is to run a cluster of `statusd` nodes in an environment where we can alter the network condition. For example, slow down the network bandwidth, increase pings, drop packets, kill individual nodes, simulate half-open sockets etc.

**Comment by dshulyak** [comment]
This is being tracked in https://github.com/status-im/status-scale
I will close issue in status-go

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-scale">status-im/status-scale</a></strong></div><div>Contribute to status-scale development by creating an account on GitHub.</div></blockquote>
