### ISSUE TITLE
consider opportunities to set sync starting block dynamically

### ISSUE THREAD

**Issue by farazdagi** [status-im/status-go#93]
- related to https://github.com/status-im/status-react/issues/725
- setting trusted CHT: https://github.com/ethereum/go-ethereum/blob/master/light/lightchain.go#L107

**Comment by jarradh** [comment]
this is actually a really good idea

**Comment by farazdagi** [comment]
- I was able to set CHT correctly in https://github.com/status-im/status-go/pull/91/commits/ea1b61c32ae13954e45b83264dc16a4e2e0d4896 
- This CHT's root hash passed validation (against Merkle proofs obtained from peers)
- So, setting CHT is not that hard..it is hard to decide what branch to use i.e. which peer's data to use for reference, if we are to set CHT dynamically

**IMPORTANT:** So, important question: how secure is it to set CHT dynamically?? Geth team will definitely address CHT updating (by relying on consensus, and have voiced their plans to improve trusted point setting), so it might be wiser to just update CHT root *manually* **for now** (this is exactly what Felfoldi does it, but while Geth team updates CHT infrequently, we can do it on a weekly basis - so sync is fast). 

@jarradh Thoughts? Is hard-coded **but regularly updated** trusted CHT a good enough solution? Or should we invest our time into something that almost certainly will be implemented by Geth team down the road?

**Comment by jarradh** [comment]
it's an acceptable for now but is abit opinionated for us, I posed the question in the light-client gitter, let's see what they say

**Comment by farazdagi** [comment]
Closing this ticket for now: agreed upon solution is to do weekly updates to CHT (and thus have weekly releases), up until Geth team makes a more user-friendly validation:
![image](https://cloud.githubusercontent.com/assets/188194/22238211/4e5b7324-e221-11e6-874b-a69f78a6d72b.png)
