### ISSUE TITLE
Move mail server implementation to status-go repo

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#936]
# Problem

The current implementation of the mail server is in go-ethereum repo which does not give us any control over it (except for making patches).

# Implementation

Move the implementation of the mail server to status-go repo.

# Acceptance Criteria

1. Mail server implementation belongs to status-go repo,
2. `statusd` uses it to register the mail server capability.

# Notes

We will introduce more changes to the mail server implementation, mainly security improvements.

**Comment by oskarth** [comment]
Is this critical for beta or is this more of a clean up task we can do later?

**Comment by adambabik** [comment]
This is a blocker for #937 which is critical. It will be harder to change the implementation on the server side if necessary.
