### ISSUE TITLE
Fix mail server vulnerabilities

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#937]
# Problem

1. No restriction on the volume of stored messages,
1. ~~Return at most N messages per request~~ Accept only 24-hour time range in the request ([more info](https://github.com/status-im/status-go/issues/937#issuecomment-388287319)),
1. No rate limiting,
1. Better validation of params. E.g. is it allowed to `To` be lower than `From`?

# Implementation

This issue is blocked by https://github.com/status-im/status-go/issues/936. After the mail server implementation is moved to status-go repo, adjust it accordingly to meet the acceptance criteria.

# Acceptance Criteria

1. Provide a way to restrict the data volume and remove old messages (#948)
1. Limit the number of returned messages to N (TBD). It's on the client side to figure out the most recent message timestamp, adjust it by allowed clock skew and send another request (#946)
1. Implement rate limiting so that a given peer can fetch messages at most N times per second (TBD). (#947 )

# Notes

These are the basic security measures we must implement before going beta.

**Comment by oskarth** [comment]
@adambabik if we tweak mailserver implementation but keep interface compatible, can we guarantee the enode stays the same? Not clear on how this is generated. I.e. we can do some of this work in the _during_ phase.

**Comment by adambabik** [comment]
@oskarth from these four problems, only (2) may require some changes in the client. Moreover, I am not sure if it will be possible to resolve this as the whole flow is async and not a typical request-response. What happens now is that method `shhext_requestMessages` is called, then an RLP-encoded message (`p2pRequestCode`) is sent and here the flow ends. MailServer receives the RLP-encoded message and starts sending envelopes matching the criteria. From the client side, these are regular Whisper messages, not distinguishable, without a complex logic, from regular Whisper messages. Finally, it will be very hard from the client perspective to figure out how to request for the rest of the messages.

An alternative solution, but not a bit less secure, is to limit `From - To` duration, for example, to 12 or 24 hours. It's much simpler and does not need changes in the client (but some would be nice to let the caller of `shhext_requestMessages` know that the duration is too large).

**Comment by adriacidre** [comment]
Closing this issue as all its related sub-tasks have been completed
