### ISSUE TITLE
check disk space before syncing

### ISSUE THREAD

**Issue by jarradh** [status-im/status-go#94]
It seems people with low diskspace end up having overheating phones while geth is syncing. 
Perhaps we can try to have a minimum disk space and pre-allocate it?

**Comment by farazdagi** [comment]
@jarradh tbh, I am not sure what "pre-allocate disk space" means in this context. I can definitely check space left on device, then..well, what should we do then?

**Comment by tiabc** [comment]
jarradh:
> Well there's things like 
> http://man7.org/linux/man-pages/man1/fallocate.1.html
> but the idea is we should allocate a place to write in, so as we're syncing, we won't lose the ability to do so,
> at least preallocate disk space from the last CHT

**Comment by sla-shi** [comment]
Per discussion with @jarradh and @tiabc - when there's not enough space switch to the RPC delegated network.

**Comment by tiabc** [comment]
Setting `low-priority` here as we now use a delegated node by default.

**Comment by tiabc** [comment]
Closing due to https://github.com/status-im/status-go/pull/300#issuecomment-336989052
