### ISSUE TITLE
TestWhisperExtensionSuite/TestSentSignal is flaky 

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#940]
# Problem

```
--- FAIL: TestWhisperExtensionSuite (14.60s)
    --- FAIL: TestWhisperExtensionSuite/TestSentSignal (8.44s)
	Error Trace:	whisper_ext_test.go:82
	Error:      	timed out while waiting for confirmation
```

# Implementation

Almost sure that the test doesn't wait long enough on CI, because it always completes on my local machine

# Acceptance Criteria

Should pass always, on any environment

**Comment by sebastiandelgado** [comment]
This does pass most of the time on travis is that right? Any other tips on how to replicate this failure other than running travis repeatedly? Is there a guide somewhere on how to run travis-ci locally? Maybe I should write one...

**Comment by adriacidre** [comment]
@sebastiandelgado even @adambabik reworked most of those tests, not sure if this one is still broken. 
When I was debugging, running tests locally with `-cpu=1 ` option, allowed me to reproduce this failure quite reliably.

**Comment by adambabik** [comment]
I haven't seen this error for a while. I did not work on it. @adriacidre great tip with `-cpu=1` 👍

**Comment by adriacidre** [comment]
Guys, I've been keeping an eye on broken builds for a while now, and wasn't able to see this problem anymore. 
I'm closing this issue now, but, feel free to re-open if you find the same problem.
