### ISSUE TITLE
Mail server query period limits

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go#946]
# Problem

Current approach of mail server is returning all messages matching the provided query. This is a problem in terms of network data volume so we may want to limit those results.

# Implementation

Limiting queries to ranges of 24 hours of difference between `From` and `To` parameters

# Acceptance Criteria

- [ ] All queries with a range > 24 hours will fail

# Notes

This issue is part of #937

**Comment by adambabik** [comment]
Closed in #949
