### ISSUE TITLE
Update enodes with new cluster

### ISSUE THREAD

**Issue by oskarth** [status-im/status-go#958]
See https://github.com/status-im/status-cluster/issues/91#issuecomment-389112136

Blocked by: XXX

- [x] Clarify blockers from cluster setup POV
- [x] Ensure enodes are active and work
- [x] Update cluster config
- [x] Issue PR to status-react and ensure it gets merged
- [ ] Prepare a bootnode and other nodes available in Russia

**Comment by oskarth** [comment]
@jakubgs @adambabik What's needed on cluster side https://github.com/status-im/status-cluster/projects/1 before we can get enodes up and running?

<blockquote><div><strong><a href="https://github.com/status-im/status-cluster/projects/1">Page not found · GitHub</a></strong></div></blockquote>

**Comment by jakubgs** [comment]
The `infra-eth-cluster` repo is ready to deploy a set of mail/whisper/boot nodes if that's what we want. There's yet no monitoring and I still have to switch it's inventory to Consul, but it should work.
I could deploy an example cluster for you to check out but we are at the dropplet limit in DigitalOcean and I haven't heard from their support yet.

**Comment by jakubgs** [comment]
DigitalOcean limit is no longer an issue, we got bumped to 100 droplets.
Currently `infra-eth-cluster` setup is almost done. It needs a few improvements I should get done today:
* Store keys and enode addresses of all hosts(boot, whisper, mail), preferably bound to the IP
* Deploy bootnodes on separate hosts before anything else
* Dynamically feed addresses of new bootnodes to newly created whisper and mail nodes
* Pull metrics from `statusd` containers (not critical)

I should be able to get those things done today, and then we can start replacing the old nodes with the new cluster, but I'll need clear step on how to approach that.

**Comment by jakubgs** [comment]
Okay, I've solved the key storing problem here:
https://github.com/status-im/infra-eth-cluster/commit/677e44af549adb8573f977e03020c7348651e14c
I think it's good enough for now, but later on we might want to use the Consul key/value store to do this since we can update that manually more easily.

**Comment by jakubgs** [comment]
I've created the new fleet:
http://consul.status.im/ui/da-ams3/nodes?filter=beta
The `statusd` services can be viewed here:
http://consul.status.im/ui/da-ams3/services/statusd-boot
http://consul.status.im/ui/da-ams3/services/statusd-mail
http://consul.status.im/ui/da-ams3/services/statusd-whisper
And for `enode` info you have to use the API:
http://consul.status.im/v1/catalog/service/statusd-boot
http://consul.status.im/v1/catalog/service/statusd-mail
http://consul.status.im/v1/catalog/service/statusd-whisper
Under `ServiceMeta` > `node_enode`.

<blockquote><div><strong><a href="http://consul.status.im/ui/da-ams3/nodes?filter=beta">Sign In</a></strong></div></blockquote>
<blockquote><div><strong><a href="http://consul.status.im/ui/da-ams3/services/statusd-boot">Sign In</a></strong></div></blockquote>
<blockquote><div><strong><a href="http://consul.status.im/ui/da-ams3/services/statusd-mail">Sign In</a></strong></div></blockquote>
<blockquote><div><strong><a href="http://consul.status.im/ui/da-ams3/services/statusd-whisper">Sign In</a></strong></div></blockquote>
<blockquote><div><strong><a href="http://consul.status.im/v1/catalog/service/statusd-boot">Sign In</a></strong></div></blockquote>
<blockquote><div><strong><a href="http://consul.status.im/v1/catalog/service/statusd-mail">Sign In</a></strong></div></blockquote>
<blockquote><div><strong><a href="http://consul.status.im/v1/catalog/service/statusd-whisper">Sign In</a></strong></div></blockquote>

**Comment by oskarth** [comment]
https://github.com/status-im/status-go/pull/994

**Comment by oskarth** [comment]
This is essentially fixed, but ideally we also have the Google nodes here before closing this

**Comment by adambabik** [comment]
@oskarth do we consider servers working in Russia to be a beta blocker? If so, we should put this issue in https://github.com/status-im/status-react/milestone/21

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by oskarth** [comment]
It's tracked here https://github.com/status-im/status-react/issues/4299
