### ISSUE TITLE
Unable to build Status go library for iOS and Android.

### ISSUE THREAD

**Issue by Dodda** [status-im/status-go#961]
# Problem

Unable to build Status go library for iOS and Android using the make commands in terminal mac os.

# Implementation

make statusgo-android (builds .aar file build/android-16/aar)
make statusgo-ios and make statusgo-ios-simulator (builds iOS related artifacts in build/os-
9.3/framework)
![screen shot 2018-05-15 at 11 46 43 am](https://user-images.githubusercontent.com/5211675/40100308-284640e4-5901-11e8-8151-8889e8544032.png)

**Comment by adambabik** [comment]
cc @divan as I know you were changing xgo image recently.

**Comment by Dodda** [comment]
Yes @adambabik , my gopath was set to default location in mac that is $Home/go and put the status-go code in the gopath location, please find this image for the source path but still i am facing the same error.
![screen shot 2018-05-16 at 3 16 27 pm](https://user-images.githubusercontent.com/5211675/40115464-23ec115e-592e-11e8-83bc-c41961060797.png)

**Comment by bgits** [comment]
@Dodda How did you resolve the issue?

**Comment by Dodda** [comment]
by using this command sudo ln -s ~/.go/bin/xgo /bin/xgo
