### ISSUE TITLE
Pre-cache more peers than max limit during during discovery

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-go#972]
# Problem

Current discovery process on a mobile device will stop itself when max amount of peers is found.
It is still possible that we will get +1-2 than max peers in our cache because we rebalance peers after confirmation that the got connected.
It would be a good optimization to cache more than max amount of peers before stopping discovery, so 
that when we loose connection with an initial set of peers we can set up new connections immediately even without turning on discovery.

# Implementation

TBD

# Acceptance Criteria

Cache more peers than max limit, x2 or +4, can be decided during implementation.
It is also important that we stop discovery eventually.

**Comment by adriacidre** [comment]
@dshulyak limits on discovery are based on `RequireTopics` config values. 

It's not possible to just upgrade the limits defined on the config instead of changing the internals of peers package?

**Comment by dshulyak** [comment]
We still want to keep connection limits reasonably low, and the idea is to run discovery even after max limit was reached. So that our cache will be filled with peers that can be used as a replacement if currently connected peer will be failing.
