### ISSUE TITLE
Missing --rpcapi flag for specifying which modules are available via HTTP RPC

### ISSUE THREAD

**Issue by jakubgs** [status-im/status-go#991]
# Problem

I'm using the HTTP RPC endpoint on `statusd` service as a healthcheck for [Consul](https://www.consul.io/docs/agent/checks.html).

Our HTTP RPC options looke like this:
```
  -http
    	Enable HTTP RPC endpoint
  -httphost string
    	HTTP RPC host of the listening socket (default "127.0.0.1")
  -httpport int
    	HTTP RPC server's listening port (default 8545)
  -httptest.serve string
    	if non-empty, httptest.NewServer serves on this address and blocks
```
But geth has:
```
API AND CONSOLE OPTIONS:
  --rpc                  Enable the HTTP-RPC server
  --rpcaddr value        HTTP-RPC server listening interface (default: "localhost")
  --rpcport value        HTTP-RPC server listening port (default: 8545)
  --rpcapi value         API's offered over the HTTP-RPC interface
```
Where `--rpcapi` allows you to specify which modules(`web3`, `admin`, `eth`, etc.) to expos via the HTTP RPC interface.

Currently the only ones expose the following ones: `web3`, `shh`
For use with Consul I'd like to access `admin_nodeinfo` which means the `admin` module has to be exposed/whitelisted.

# Acceptance Criteria

I can enable use of modules like `eth` and `admin` for the HTTP RPC API.

# Future Steps

This will be used in [infra-eth-cluster](https://github.com/status-im/infra-eth-cluster) as a type of healthcheck for Consul as well as a way to get the statusd `enode` for service metadata.

**Comment by themue** [comment]
Flag is `-httpmodules`, default are the standard modules like before. `statusd -h` shows it.

**Comment by jakubgs** [comment]
Brilliant! Thanks a bunch man. I owe your a beverage of your choice.

**Comment by themue** [comment]
You're welcome. ☺️
